### ISSUE TITLE
FYRTUR Rollo von IKEA landet in SENSORS

### ISSUE THREAD

**Issue by Michaelnorge** [Jey-Cee/ioBroker.deconz#102]
Die Objekte "ON" on " REACHABLE" der FYRTUR-Serie von IKEA landen komischer Weise in den Sensoren, alle anderen in den Lampen.

Bei den Lampen gibt es auch die genannten Objekte, sie tun aber nicht.

**Comment by Jey-Cee** [comment]
Grundsätzlich hat der Adapter nichts mit einzelnen Geräten zu tun, alles wird von deConz verwaltet. Der Adapter setzt nur das um was von deConz kommt, somit werden die Objekte ON und REACHABLE wohl als Sensoren geliefert.

Aber um sicher zu gehen stell das Log Level deiner deconz Adapter instantz auf debug und zeig mir was von deConz kommt.
