### ISSUE TITLE
Neue Boolean-States funktionieren nicht (gehen nicht auf false zurück)

### ISSUE THREAD

**Issue by tigus309** [Jey-Cee/ioBroker.deconz#105]
In Version 1.2.4 gibt es sie ja nun endlich... Die lange erwarteten Boolean-States für Schalter. Macht die Arbeit mit dem Adapter deutlich einfacher... Wenn sie denn funktionieren. Eben das Update gemacht und mal probiert: Die States werden bei erster Nutzung angelegt und auf true gesetzt, springen aber leider nicht mehr auf false zurück. Das sollte doch automatisch direkt wieder sofort passieren?

![deconz](https://user-images.githubusercontent.com/5008845/73307204-0a734500-421e-11ea-92d6-7dffe006a6ab.png)

**Comment by Jey-Cee** [comment]
Die werden halt nur beim Drücken Aktualisiert, dachte wenn sie die Rolle button haben springen sie von selbst auf false zurück.
Ich ändere das mit der nächsten Version so das es auf false zurück springt.

**Comment by tigus309** [comment]
>  Ich ändere das mit der nächsten Version so das es auf false zurück springt.
Super! Vielen Dank! Wann kann man mit dem Update denn ungefähr rechnen?

**Comment by Jey-Cee** [comment]
Die Version 1.2.5 ist auf Github.

**Comment by tigus309** [comment]
> Die Version 1.2.5 ist auf Github.

Die Version hat einen Bug! Im buttonpressed bekomme ich nur noch die xxx2-Meldungen, Bei den buttonevent-Ordnern gibt es nur die release_press-Datenpunkte. Auch im buttonpressed kommen jetzt nicht mehr einzelne oder mehrfache Klicks an!

Getestet mit einer Tradfri Fernbedienung
