### ISSUE TITLE
iobroker.deconz crash on scene recall..

### ISSUE THREAD

**Issue by realwax** [Jey-Cee/ioBroker.deconz#106]
Ich habe gerade in der 1.2.5 entdeckt, dass ein szenen recall den adapter crasht:

Ich habe gerade in der 1.2.5 entdeckt, dass ein szenen recall den adapter crasht:

deconz.0 2020-02-10 14:09:15.213 info (16240) Code 404: Ressource not found get devices: []
deconz.0 2020-02-10 14:09:15.206 debug (16240) Code 200: Request succeded get all groups: {"11":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag"
deconz.0 2020-02-10 14:09:14.946 debug (16240) Code 200: Request succeded get all sensors: {"1":{"config":{"configured":true,"on":true,"sunriseoffset":30,"sunsetoffset":-30},"etag":"164aea2cc7392f5aec9684535f72e544","manufacturername":"Phi
deconz.0 2020-02-10 14:09:14.565 debug (16240) Code 200: Request succeded get all lights: {"1":{"ctmax":454,"ctmin":250,"etag":"83c947395a7054d6fc1e34485bf108a6","hascolor":true,"manufacturername":"IKEA of Sweden","modelid":"TRADFRI bulb E
deconz.0 2020-02-10 14:09:14.509 info (16240) deConz Version: 2.5.72; API version: 1.16.0
deconz.0 2020-02-10 14:09:14.498 debug (16240) Code 200: Request succeded get config: {"UTC":"2020-02-10T13:09:14","apiversion":"1.16.0","backup":{"errorcode":0,"status":"idle"},"bridgeid":"00212EFFFF03B313","datastoreversion":"60","devic
deconz.0 2020-02-10 14:09:14.241 info (16240) starting. Version 1.2.5 in /opt/iobroker/node_modules/iobroker.deconz, node: v10.17.0
deconz.0 2020-02-10 14:08:40.683 info (13477) Terminated (NO_ERROR): Without reason
deconz.0 2020-02-10 14:08:40.681 info (13477) terminating
deconz.0 2020-02-10 14:08:40.672 debug (13477) Websocket connection closed
deconz.0 2020-02-10 14:08:40.667 error (13477) TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type object at write_ (_http_outgoing.js:595:11) at ClientRequest.write (_http_outgo
deconz.0 2020-02-10 14:08:40.666 error (13477) uncaught exception: The first argument must be one of type string or Buffer. Received type object
deconz.0 2020-02-10 14:08:40.613 debug (13477) dp: recall; id:Groups.47.Scene_1
deconz.0 2020-02-10 14:08:40.612 debug (13477) stateChange Groups.47.Scene_1 {"val":true,"ack":false,"ts":1581340147512,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1581162661852}

**Comment by Jey-Cee** [comment]
Fehler war nicht nur auf scene recall beschränkt und sollte mit der 1.2.6 behoben sein.
