### ISSUE TITLE
Group state 'bri' wird nicht updgedatet

### ISSUE THREAD

**Issue by Greiler21** [Jey-Cee/ioBroker.deconz#107]
iobroker adapter version: 1.25
phoscon version: 2.05.71
firmware: 26490700

state 'bri' Wert wird nicht angepasst wenn die Helligkeit der Gruppe von extern ( über Hue Essential App, Phoscon Website usw) geändert wird.

Wert wird auch nach neuladen der Objekte nicht richtig angezeigt. Erst wenn die Gruppe ein/ausgeschaltet wird, wird auch der 'bri'-value wieder richtig angezeigt.

**Comment by Jey-Cee** [comment]
Ja das ist mir auch aufgefallen. Als ich Nachgeschaut hab warum es nicht Aktualisiert wird, musste ich feststellen das da gar nichts von deConz kommt. 
Das hat mich irritiert und ich bin mir nicht sicher ob das immer so war. 

Laut doku kann man einstellen ob alle Daten bei einer Änderung Übertragen werden. Möglich das es deshalb keine Aktualisierung gibt. Allerdings wüsste ich nicht wie oder wo man das Einstellen kann.

Jedenfalls sehe ich keine Möglichkeit ohne die Info einer Änderung den Status ab zu fragen.

Wäre interessant zu wissen mit welcher deConz Version das funktioniert hat oder ob überhaupt.

**Comment by kneisel** [comment]
Ich weiß nicht so recht, ob das damit zusammenhängt. Ich beobachte aber bei meiner Testinstallation (Tradfri-Lampe) unerwartete Zusammenhänge zwischen .bri und .on

- Steht .bri auf einem Wert (>0) so kann man mit dem Setzen von .on=true die Lampe anschalten und mit .on=false ausschalten, wobei beim Einschalten die Helligkeit von .bri  angenommen wird ... soweit ist es erwartet.
- Steht .on auf true, so kann man mit dem Setzen von .bri=Wert die Lampe auf den entsprechenden Wert stellen ... auch soweit ist es erwartet.
- Steht .on auf false, so kann man mit dem Setzen von .bri=Wert die Lampe auf den entsprechenden Wert stellen ... das ist NICHT erwartet, denn .on=false, eigentlich würde ich erwartet, dass damit nur der Wert eingestellt wird, der beim nächsten Einschalten (mit .on=true) angenommen wird.

... durch dieses Verhalten benimmt sich das "light"-Objekt in lovelace möglicherweise auch "merkwürdig". Dort kann man durch Betätigung des icons das Licht zwar ausschalten, aber nur noch über Drehen am "Dimmerkreises" wieder einschalten ...

**Comment by Jey-Cee** [comment]
@kneisel du kannst keinen Wert setzen bevor die Lampe an ist, das wird von deConz mit einem Fehler Quittiert. 

Weitere Gründe warum das so ist kannst du in diesem PR finden: #38

**Comment by Jey-Cee** [comment]
Mittlerweile weiss ich das es früher mal geupdatet wurde, aber da wurde bei jedem Event eine Gesamt abfrage gemacht.

Kann sein das ich die Gesamt abfrage wieder ein baue, wenn ich keine andere Möglichkeit finde.

**Comment by Greiler21** [comment]
Die Phoscon GUI und auch die Hue Essentials App lösen das über ein Polling mit einer Gesamtabfrage im 10 Sekunden Intervall. Eventuell wäre das auch noch eine Möglichkeit.
Während des Dimmens einer Gruppe wird von jeder Lampe der Gruppe ein Event verschickt. Bei einer Gruppe mit 10 Lampen könnte das evtl Performance Schwierigkeiten geben. Ich weiß nicht ob es in JavaScript so etwas wie eine Debounce-Funktion gibt um das zu vermeiden. Trotzdem danke dir, dass du am Ball bleibst.

**Comment by Jey-Cee** [comment]
Wie gesagt früher lief das über Gesamt abfrage, mein Gedanke bzw. auch von anderen wenn es ne Push nachricht gibt braucht man nicht extra nochmal alles ab fragen.
Aber wenn halt nicht alle nötigen Infos dabei rüber kommen bleibt ja gar nichts anderes übrig.

**Comment by Jey-Cee** [comment]
Hab gerade gesehen das ich es schon Zurück gebaut habe. Ist in version 1.3.2 drin.

**Comment by Jey-Cee** [comment]
Man sollte die Objekte der Gruppe als Steuerelemente sehen und nicht als Status anzeige.

Siehe dazu hier: #127 da ist das Verhalten für Szenen Ähnlich.
