### ISSUE TITLE
Philips HUE Outdoor Motion Sensor / Sensitivy

### ISSUE THREAD

**Issue by LJSven** [Jey-Cee/ioBroker.deconz#108]
Kann man den Wert für den BWM einstellen, so daß der nicht so schnell getriggerd wird? Wenn ja, was muss ich da machen?

**Comment by Jey-Cee** [comment]
Es gitb 2 Mögliche Datenpunkte die in frage kommen, je nachdem was du haben willst. 

sensitivity: Gibt die Empfindlichkeit wieder. Einfach einen Zahlenwert eingeben und damit Spielen. Es gibt hier keine Vorgabe des Wertebereichs, das kann von Bewegungsmelder zu Bewegungsmelder Unterschiedlich sein. 

duration: Dauer die gewartet wird bis eine Bewegungserkennung wieder gesendet wird. Wertbereich 0-600, bei den meisten ist aber der Mindestwert 60, angegeben in Sekunden.

**Comment by LJSven** [comment]
@Jey-Cee VIelen Dank für die ausführliche Antwort! Wenn ich die Werte im ioBroker ändere, werden diese dann automatisch in den BWM geschrieben? Der Wert sensitivity stand auf 0 - habe ich jetzt mal auf 2 geändert.  Als sensitivitymax steht bei mir 4.
Oder wie würdest du vor gehen?

![Bildschirmfoto 2020-02-18 um 13 03 01](https://user-images.githubusercontent.com/8560588/74734529-08b20580-524f-11ea-9d0c-818e84f1d2b9.png)

**Comment by Jey-Cee** [comment]
Ja die Daten werden Automatisch übertragen.
Ich würde einfach, wie du einen Wert setzen und beobachten wie sich das ganze verhält.

**Comment by LJSven** [comment]
Was ist mit sensitivitymax? Hat das auch eine Bedeutung? Würdest du bei sensitivity in 1er Schritten nach oben gehen, bis es passt?

**Comment by Jey-Cee** [comment]
Das ist dee maximal möglich Wert. Denke das hat sonst keune weitere Bedeutung.
Ja einfach in 1 er Schritten ändern.

**Comment by LJSven** [comment]
Mein Philips OUTDOOR BWM hat keine Feld mit Duration - gibt es irgendwo eine Liste, wo alle Begriffe erklärst sind? Bei "pending" steht z.B. gar kein Wert bei mir.

**Comment by Jey-Cee** [comment]
[Hier](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices) gibt es eine Liste mit Geräten und auch teilweise Erklärung zu den Datenpunkten. Ich weiss selbst nur teilweise wofür sie sind.

Pending ist im Idealfall nie gesetzt, steht nur was drin wenn ein Gerät gerade beschäftigt ist und den neuen Befehl erst danach Ausführen kann.
