### ISSUE TITLE
Deconz Adapter wird im IoBroker nicht angezeigt

### ISSUE THREAD

**Issue by Reuli61** [Jey-Cee/ioBroker.deconz#109]
Der Adapter ist installiert wird aber nicht unter Instanzen angezeigt.

**Comment by Jey-Cee** [comment]
Wenn du von Github installierst musst du eine Instanz anlegen, das passiert nur von npm Automatisch.

**Comment by Reuli61** [comment]
Wie lege ich eine Instanz an?

**Comment by guergen1** [comment]
![grafik](https://user-images.githubusercontent.com/34395245/75095216-e7c11b80-5592-11ea-8583-7083d78e212b.png)
