### ISSUE TITLE
Trigger für Datenpunkte werden beim Neustart des Adapters aktiviert

### ISSUE THREAD

**Issue by xcruzix** [Jey-Cee/ioBroker.deconz#111]
Beim Neustart des Adapters aktualisieren sich wohl die Datenpunkte und entsprechend reagieren alle Trigger auf eben diese.
Diskutiert im Forum:
https://forum.iobroker.net/topic/30466/deconz-adapter-schaltet-bei-neustart

**Comment by Jey-Cee** [comment]
Wie im Forum schon geschrieben ist das kein Fehler.
