### ISSUE TITLE
Duration role 

### ISSUE THREAD

**Issue by Jey-Cee** [Jey-Cee/ioBroker.deconz#116]
Role is false

**Comment by EduardSarjadjuk** [comment]
Hi there,

I have the following problem (iobroker.deconz 1.2.6):
The duration is set to the standard value (Aqara Motion) of 90 s. If I start the adapter, the sensor changes after 90 s the status. After several hours, the sensor no longer changes status after 90s. This takes several minutes. After restarting the adapter, it works again.
Is that the same problem?

**Comment by Jey-Cee** [comment]
@EduardSarjadjuk no this issue has nothing to do with your problem. 
That what you describe is a problem with the connection to deConz. Update deConz to version .74, if this problem is still there i cant do anything.

**Comment by Jey-Cee** [comment]
d42f2bd49eaa08dc0a664d063b970b3b5e685335
