### ISSUE TITLE
Cant delete devices from Instance

### ISSUE THREAD

**Issue by bendigbjoern** [Jey-Cee/ioBroker.deconz#117]
1.2.6 
I cant delete devices out of the instance. When i delete devices directly in phoscon app the adapter dont refresh the instance.

**Comment by Jey-Cee** [comment]
Known behaivior, not a bug. You can delete the objects in ioBroker manual.

**Comment by Jey-Cee** [comment]
#8

**Comment by Jey-Cee** [comment]
Please check v1.3.2
