### ISSUE TITLE
Adapter verbindet sich nur wenn in der deconz Gui angemeldet

### ISSUE THREAD

**Issue by terfurt** [Jey-Cee/ioBroker.deconz#118]
Habe deconz unter Xubuntu in einer VM in Proxmox installiert. Da läuft auch ein Container unter Debian 10 mit iobroker. Die Verbindung zwischen deconz und iobroker funktioniert nur wenn ich in der Xubuntu VM die deconz Oberfläche aufrufe. Wenn ich diese schließe wird der Adapter direkt wieder gelb und die Kommunikation zu den Devices funktioniert nicht mehr. Gibt es da ein workaround?

**Comment by guergen1** [comment]
Entweder muss die deconz-Oberfläche offen sein, oder du musst deconz headless starten:
https://github.com/dresden-elektronik/deconz-rest-plugin#headless-support-for-linux

**Comment by terfurt** [comment]
Hm, auf meinem alten System hatte ich auf einem Raspberry 3 Rasbian mit Desktop installiert und da ging es auch ohne das deconz im Gui gesartet war! Was hat sich geändert?

**Comment by guergen1** [comment]
Dann lief die Gui im Hintergrund?

**Comment by terfurt** [comment]
Nicht das ich wüsste...war ein Rasp3 mit Fhem und darauf deconz.

**Comment by guergen1** [comment]
Es kann sein, dass bei der Raspi-Installation im Hintergrund automatisch das „im Hintergrund“ laufende Programm mitinstalliert wurde.
Führe doch einfach die im Beitrag erwähnten Befehle aus, dann läuft es !
