### ISSUE TITLE
Websocket connection not established in 1.2.6

### ISSUE THREAD

**Issue by holomekc** [Jey-Cee/ioBroker.deconz#119]
Hi after updating to version 1.2.6 the websocket connection is not established. 
In my case I only have sensors connected.

I changed the logging level to silly and could only see that it stopped with:
Code 404: Ressource not found get devices: []

I checked the code and add some logging and could see that the getAutoUpdates function was never called. Therefore, I added it at the end of the getConfig function and then it worked fine.

I am not 100% sure how the actual workflow should look like. I could only see that getAutoUpdates is called in startAdapter -> on stateChange conditionally. But it was not called either.

I am not sure what I could have done differently. I could see that the native content of Gateway_info was align with my deconz configuration.

**Comment by Jey-Cee** [comment]
Have you created a new API key? 
Is deConz running in an container or do you use VLAN?

**Comment by holomekc** [comment]
Deconz is running on raspberry pi with port 8086 and ws port 8087. 
adapter is configured with 127.0.0.1 and port 8086.

Yes i created a new api key. I also reinstalled the adapter.

Installed update on pi of my sister with the same behavior. 

The communication is working fine in general. I see that config request is fine and all data extracted from endpoint is also correct. E.g. ws port is set in native to 8087 as well. Establishing ws connection manually in chrome browser also is working fine. But without the extra getAutoUpdate call the adapter did not even try to establish the websocket connection for some reason.

**Comment by Jey-Cee** [comment]
Websocket connection is depending on upnp broadcast messages from deconz. If this broadcast messages are blocked in youtr network by some reason the websocket connection wont be established.

I will change this behaivior. But keep in mind if the websocket is opened without getting the upnp broadcast it is unmonitored and the adapter does not know if the connection is broken.

**Comment by Jey-Cee** [comment]
d6db4162c645bf48892c25500cfac60c060c4720

**Comment by Jey-Cee** [comment]
96ad6f656bd1b25837cf69277f26fbb88116961d

**Comment by holomekc** [comment]
Hi now i understand your workflow. I have disabled upnp for deconz via upnp=0 property. (Port already in use)

But why does the websocket connection rely on ssdp which is normally just for the discovery? I mean in configuration Ip and port is already specified and config endpoint is called in any case.

I also could see that the websocket connection is killed each minute and reestablished. Isn‘t the onClose callback relyable? Wouldn‘t a delayed reconnect onClose be sufficient?

Edit: https://github.com/websockets/ws#how-to-detect-and-close-broken-connections

**Comment by Jey-Cee** [comment]
Thanks for the link, i already know this and that doesnt help in this case.

There is no onClose event and normal you can use ping/pong on websockets but this method isnt implemented on deConz side, also there is no answer if there was send data to it.
Thats why i am using upnp alive messges to check if deConz is reachable. If not the adapter can show this and re-establish when it is reachable again.

As it was not possible to check if the websocket connection is OK the only way is to re-establish it.

EDIT: Here is the issue on deConz side for missing ping/pong https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2236

**Comment by holomekc** [comment]
Ah I see. Well that is sad.

In past I had the issue that the states did not get updated suddenly after some time. Then this was most likely the websocket connection which "died".

I am still thinking about whether there is a better approach, but I think you are right. Seems like the only way.

**Comment by r2ixuz** [comment]
Even with the latest adapter version 1.3.0 I got still the same error. I use marthoc docker container without UPNP and host network mode. It worked all fine with the old plugin version... :(

**Comment by holomekc** [comment]
Which error and which old plugin version? 1.2.6 or older?

**Comment by r2ixuz** [comment]
old version which works: 1.1.2
new version which don't work: 1.2.6 and 1.3.0 (both produces error: "Code 404: Ressource not found get devices: []")

**Comment by holomekc** [comment]
I have the message as well but it doesn't prevent the adapter from working for me. My issue was only the websocket connection which was not initiated. Maybe you can turn on debug log level. Then you should see more.

**Comment by r2ixuz** [comment]
I use this ioBroker plugin mainly to receive data points from my sensors (e.g. temperature) which doesn't work with the new versions.

Communication seems to be working somehow, as I can request and get a new API key and activate permit join on the deconz server. But receiving data points stops working.

Apperently I am not the only one with this issue: https://forum.iobroker.net/topic/31040/deconz-funktioniert-nach-update-nicht-mehr

Besides I do NOT get the new error message which is introduced in the 1.2.6 code if deconz discovery via upnp fails.

**Comment by holomekc** [comment]
Maybe you can try the workaround i wrote to quick fix the issue. I did not test 1.3.0 though.

edit /opt/iobroker/node_modules/iobroker.deconz/main.js

search for getConfig() function and add getAutoUpdates(); at the end

```JavaScript
  ...
  getAllLights();
  getAllSensors();
  getAllGroups();
  getDevices();
  getAutoUpdates();
}
...
```
Then just restart the adapter

Edit: still did not test 1.3.0 but for people who are not comfortable with editing the file:
https://github.com/holomekc/ioBroker.deconz/blob/master/main.js

**Comment by r2ixuz** [comment]
I tried your workaround. I added getAutoUpdates(); to that line. It worked as you said. Even the yellow adapter light went green after this change.

So I guess the commit 96ad6f6 from 1.3.0 does not get triggert somehow.

**Comment by r2ixuz** [comment]
The new version 1.3.1 fixed the problem for me. Even the light is now green again. ;-)

Thanks for the quick fix.
