### ISSUE TITLE
Could not connect to Websocket fast täglich 1.3.1

### ISSUE THREAD

**Issue by guergen1** [Jey-Cee/ioBroker.deconz#120]
Beinahe täglich verliert der Adapter die Verbindung zum Websocket und kann nur mittels Adapterneustart wieder verbunden werden:

`

deconz.0 | 2020-03-25 15:19:22.566 | debug | (5911) Websocket connection closed
-- | -- | -- | --
deconz.0 | 2020-03-25 15:19:22.565 | warn | (5911) Could not connect to websocket instance of deConz/Phoscon. Error: connect ECONNREFUSED 192.168.1.202:443
deconz.0 | 2020-03-25 15:19:03.253 | debug | (5911) Websocket connection closed
deconz.0 | 2020-03-25 15:19:03.252 | debug | (5911) Websocket connection closed
deconz.0 | 2020-03-25 15:18:22.562 | debug | (5911) Subscribed to updates...
deconz.0 | 2020-03-25 15:18:22.560 | debug | (5911) Websocket connection closed
deconz.0 | 2020-03-25 15:17:22.559 | debug | (5911) Subscribed to updates...
deconz.0 | 2020-03-25 15:17:22.557 | debug | (5911) Websocket connection closed
deconz.0 | 2020-03-25 15:16:22.556 | debug | (5911) Subscribed to updates...
deconz.0 | 2020-03-25 15:16:22.553 | debug | (5911) Websocket connection closed
deconz.0 | 2020-03-25 15:15:22.551 | debug | (5911) Subscribed to updates...
deconz.0 | 2020-03-25 15:15:22.550 | debug | (5911) Websocket connection closed
deconz.0 | 2020-03-25 15:14:22.548 | debug | (5911) Subscribed to updates...
deconz.0 | 2020-03-25 15:14:22.546 | debug | (5911) Websocket connection closed
deconz.0 | 2020-03-25 15:13:22.544 | debug | (5911) Websocket message:  {"e":"changed","id":"4","r":"sensors","state":{"humidity":4962,"lastupdated":"2020-03-25T14:13:22"},"t":"event","uniqueid":"00:15:8d:00:03:cb:7d:35-01-0405"}
deconz.0 | 2020-03-25 15:13:22.543 | debug | (5911) Websocket message:  {"e":"changed","id":"4","r":"sensors","state":{"humidity":4962,"lastupdated":"2020-03-25T14:13:22"},"t":"event","uniqueid":"00:15:8d:00:03:cb:7d:35-01-0405"}
deconz.0 | 2020-03-25 15:13:22.542 | debug | (5911) Websocket message:  {"config":{"battery":91,"offset":0,"on":true,"reachable":true},"e":"changed","id":"4","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:cb:7d:35-01-0405"}
deconz.0 | 2020-03-25 15:13:22.542 | debug | (5911) Websocket message:  {"config":{"battery":91,"offset":0,"on":true,"reachable":true},"e":"changed","id":"4","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:cb:7d:35-01-0405"}
deconz.0 | 2020-03-25 15:13:22.540 | debug | (5911) Websocket message:  {"e":"changed","id":"3","r":"sensors","state":{"lastupdated":"2020-03-25T14:13:22","temperature":1644},"t":"event","uniqueid":"00:15:8d:00:03:cb:7d:35-01-0402"}
deconz.0 | 2020-03-25 15:13:22.539 | debug | (5911) Websocket message:  {"e":"changed","id":"3","r":"sensors","state":{"lastupdated":"2020-03-25T14:13:22","temperature":1644},"t":"event","uniqueid":"00:15:8d:00:03:cb:7d:35-01-0402"}
deconz.0 | 2020-03-25 15:13:22.539 | debug | (5911) Websocket message:  {"config":{"battery":91,"offset":0,"on":true,"reachable":true},"e":"changed","id":"3","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:cb:7d:35-01-0402"}
deconz.0 | 2020-03-25 15:13:22.538 | debug | (5911) Websocket message:  {"config":{"battery":91,"offset":0,"on":true,"reachable":true},"e":"changed","id":"3","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:cb:7d:35-01-0402"}
deconz.0 | 2020-03-25 15:12:56.939 | debug | (5911) Subscribed to updates...
deconz.0 | 2020-03-25 15:12:56.937 | debug | (5911) Websocket connection closed
deconz.0 | 2020-03-25 15:11:56.936 | debug | (5911) Subscribed to updates...
deconz.0 | 2020-03-25 15:11:56.934 | debug | (5911) Websocket connection closed
deconz.0 | 2020-03-25 15:10:56.932 | debug | (5911) Subscribed to updates...
deconz.0 | 2020-03-25 15:10:56.930 | debug | (5911) Websocket connection closed
deconz.0 | 2020-03-25 15:09:56.929 | debug | (5911) Websocket message:  {"config":{"alert":"none","battery":74,"group":"38994","on":true,"reachable":true},"e":"changed","id":"14","r":"sensors","t":"event","uniqueid":"cc:cc:cc:ff:fe:6b:47:48-01-1
deconz.0 | 2020-03-25 15:09:56.928 | debug | (5911) Websocket message:  {"config":{"alert":"none","battery":74,"group":"38994","on":true,"reachable":true},"e":"changed","id":"14","r":"sensors","t":"event","uniqueid":"cc:cc:cc:ff:fe:6b:47:48-01-1
deconz.0 | 2020-03-25 15:09:01.681 | debug | (5911) Websocket message:  {"e":"changed","id":"8","r":"sensors","state":{"humidity":4608,"lastupdated":"2020-03-25T14:09:01"},"t":"event","uniqueid":"00:15:8d:00:03:cf:08:fd-01-0405"}
deconz.0 | 2020-03-25 15:09:01.680 | debug | (5911) Websocket message:  {"e":"changed","id":"8","r":"sensors","state":{"humidity":4608,"lastupdated":"2020-03-25T14:09:01"},"t":"event","uniqueid":"00:15:8d:00:03:cf:08:fd-01-0405"}
deconz.0 | 2020-03-25 15:09:01.679 | debug | (5911) Websocket message:  {"config":{"battery":88,"offset":0,"on":true,"reachable":true},"e":"changed","id":"8","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:cf:08:fd-01-0405"}
deconz.0 | 2020-03-25 15:09:01.679 | debug | (5911) Websocket message:  {"config":{"battery":88,"offset":0,"on":true,"reachable":true},"e":"changed","id":"8","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:cf:08:fd-01-0405"}
deconz.0 | 2020-03-25 15:09:01.677 | debug | (5911) Websocket message:  {"e":"changed","id":"7","r":"sensors","state":{"lastupdated":"2020-03-25T14:09:01","temperature":1768},"t":"event","uniqueid":"00:15:8d:00:03:cf:08:fd-01-0402"}
deconz.0 | 2020-03-25 15:09:01.676 | debug | (5911) Websocket message:  {"e":"changed","id":"7","r":"sensors","state":{"lastupdated":"2020-03-25T14:09:01","temperature":1768},"t":"event","uniqueid":"00:15:8d:00:03:cf:08:fd-01-0402"}
deconz.0 | 2020-03-25 15:09:01.675 | debug | (5911) Websocket message:  {"config":{"battery":88,"offset":0,"on":true,"reachable":true},"e":"changed","id":"7","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:cf:08:fd-01-0402"}
deconz.0 | 2020-03-25 15:09:01.675 | debug | (5911) Websocket message:  {"config":{"battery":88,"offset":0,"on":true,"reachable":true},"e":"changed","id":"7","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:cf:08:fd-01-0402"}
deconz.0 | 2020-03-25 15:08:56.799 | debug | (5911) Subscribed to updates...
deconz.0 | 2020-03-25 15:08:56.797 | debug | (5911) Websocket connection closed
deconz.0 | 2020-03-25 15:07:56.794 | debug | (5911) Subscribed to updates...
deconz.0 | 2020-03-25 15:07:56.792 | debug | (5911) Websocket connection closed

`

Danach kommen noch folgende Log-Meldungen: 
`

deconz.0 | 2020-03-25 16:50:53.464 | debug | (5911) Code 200: Request succeded set light state 2: [{"success":{"/lights/2/state/on":false}}]
-- | -- | -- | --
deconz.0 | 2020-03-25 16:50:53.416 | debug | (5911) Code 200: Request succeded set light state 1: [{"success":{"/lights/1/state/on":false}}]
deconz.0 | 2020-03-25 16:50:53.410 | debug | (5911) dp: on; id:Lights.2 tmp: deconz,0,Lights,2
deconz.0 | 2020-03-25 16:50:53.410 | debug | (5911) stateChange Lights.2  {"val":false,"ack":false,"ts":1585151453408,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":1584838218617}
deconz.0 | 2020-03-25 16:50:53.410 | debug | (5911) dp: on; id:Lights.1 tmp: deconz,0,Lights,1
deconz.0 | 2020-03-25 16:50:53.409 | debug | (5911) stateChange Lights.1  {"val":false,"ack":false,"ts":1585151453408,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":1584838218617}

deconz.0 | 2020-03-25 17:24:52.833 | debug | (5911) system.adapter.admin.0: logging true
-- | -- | -- | --
deconz.0 | 2020-03-25 17:24:35.127 | debug | (5911) system.adapter.admin.0: logging false
deconz.0 | 2020-03-25 17:22:25.205 | debug | (5911) system.adapter.admin.0: logging true

`

Die Phosconapp ist erreichbar. 
Deconz-Version 1.3.1
Phoscon: 2.05.74/25.02.2020

**Comment by Jey-Cee** [comment]
Im Forum gibt es eine Meldung mit dem selben problem aber version 1.2.6. 
Wahrscheinlich wird die Verbindungsanfrage aufgrund der Häufigkeit irgendwann abgelehnt, die frage ist nur ob von deConz oder einer Firewall.

https://forum.iobroker.net/topic/31947/deconz-verbindung-verloren/6

**Comment by RockoRocknase** [comment]
Hallo zusammen,

seit einigen Tagen ist mir aufgefallen, dass ich diese Warnung auch in meinem Log habe. Sie taucht mehrfach täglich auf.

`2020-07-26 12:24:01.929 - warn: deconz.0 (2428) Could not connect to websocket instance of deConz/Phoscon. Error: WebSocket was closed before the connection was established`

Meine deConz-Adapter-Version ist 1.3.10.

Gibt es dazu inzwischen eine Lösung, bzw. eine Information, woher diese Warnung kommt?

Vielen Dank und viele Grüße!

**Comment by Signum** [comment]
Version 1.3.11 – gleiches Problem.

**Comment by Jey-Cee** [comment]
@Signum ganz schön wenig informationen, also gibt es nur einen Link: https://forum.iobroker.net/topic/39625/diverse-probleme-mit-deconz-2-05-84

**Comment by DominikReber** [comment]
Ich habe 3 Deconz-Sticks. 2 an einem Rapsberry Pi und einer über Docker auf einer Synology NAS.

Die 2 Raspberry-Varianten laufen Problemlos, nur bei der Synology/Docker-Variante kommt auch der Fehler:

`Could not connect to websocket instance of deConz/Phoscon. Error: Unexpected server response: 400`

Und zwar alle 30 Sekunden. Aber: Ansonsten läuft alles ohne Probleme. Wäre die Warnung nicht im Log, könnte ich nicht sagen, dass etwas irgendwie nicht gehen würde. Also insofern hab ich kein Problem mit der Warnung, frage mich nur wieso sie auftritt. 

Und zwar tritt es auf, seitdem ich nicht das marthoc-docker-image (die nicht mehr weiter aktualisiert wird) sondern das deconz-community/deconz-docker verwende.

Aber wie gesagt - alles läuft sonst korrekt.

**Comment by cola32** [comment]
Das gleiche Problem habe ich auch
Außerdem funktionieren ALL meine Batterie betriebenen Zigbee Geräte nicht mehr.
Mit dem marthoc funktioniert alles
