### ISSUE TITLE
Ikea Rollos - Code 400: Bad request set light state

### ISSUE THREAD

**Issue by duffbeer2000** [Jey-Cee/ioBroker.deconz#121]
Aktuell eingesetzte Adapterversion 1.2.6
Aktuell eingesetzte Deconz ´Version V2_05_75

Ich habe seit ein paar Tage ein Problem mit meinen Ikea Rollos, wenn ich sie herunterfahren möchte ( Herunterfahren tu ich sie z.B. mit dem Wert deconz.0.Lights.11.bri auf den Wert 255.) kommt folgende Meldung im Log:

deconz.0 | 2020-03-30 13:42:08.732 | warn | (5610)  Code 400: Bad request set light state 12:  [{"error":{"address":"/lights/12/state/transitiontime","description":"parameter,  transitiontime, not available","type":6}}]
-- | -- | -- | --
deconz.0 | 2020-03-30 13:42:08.690 | warn | (5610)  Code 400: Bad request set light state 11:  [{"error":{"address":"/lights/11/state/transitiontime","description":"parameter,  transitiontime, not available","type":6}}]
deconz.0 | 2020-03-30 13:42:08.685 | debug | (5610) dp: bri; id:Lights.12
deconz.0 | 2020-03-30 13:42:08.684 | debug | (5610)  stateChange Lights.12  {"val":254.99999999999997,"ack":false,"ts":1585568528682,"q":0,"from":"system.adapter.iot.0","user":"system.user.admin","lc":1585568528682}
deconz.0 | 2020-03-30 13:42:08.664 | warn | (5610)  Code 400: Bad request set light state 9:  [{"error":{"address":"/lights/9/state/transitiontime","description":"parameter,  transitiontime, not available","type":6}}]
deconz.0 | 2020-03-30 13:42:08.651 | debug | (5610) dp: bri; id:Lights.11
deconz.0 | 2020-03-30 13:42:08.650 | debug | (5610)  stateChange Lights.11  {"val":254.99999999999997,"ack":false,"ts":1585568528645,"q":0,"from":"system.adapter.iot.0","user":"system.user.admin","lc":1585568528645}
deconz.0 | 2020-03-30 13:42:08.647 | debug | (5610) dp: bri; id:Lights.9
deconz.0 | 2020-03-30 13:42:08.646 | debug | (5610)  stateChange Lights.9  {"val":254.99999999999997,"ack":false,"ts":1585568528644,"q":0,"from":"system.adapter.iot.0","user":"system.user.admin","lc":15855685

Setze ich sie auf 0 dann fahren sie sauber nach oben.

deconz.0 | 2020-03-30 13:44:05.550 | debug | (5610) Code 200: Request succeded set light state 11: [{"success":{"/lights/11/state/bri":0}}]
-- | -- | -- | --
deconz.0 | 2020-03-30 13:44:05.543 | debug | (5610) dp: bri; id:Lights.11
deconz.0 | 2020-03-30 13:44:05.543 | debug | (5610)  stateChange Lights.11  {"val":0,"ack":false,"ts":1585568645538,"q":0,"from":"system.adapter.iot.0","user":"system.user.admin","lc":1585568645538}
deconz.0 | 2020-03-30 13:44:05.476 | debug | (5610) Code 200: Request succeded set light state 12: [{"success":{"/lights/12/state/bri":0}}]
deconz.0 | 2020-03-30 13:44:05.461 | debug | (5610) dp: bri; id:Lights.12
deconz.0 | 2020-03-30 13:44:05.461 | debug | (5610)  stateChange Lights.12  {"val":0,"ack":false,"ts":1585568645460,"q":0,"from":"system.adapter.iot.0","user":"system.user.admin","lc":1585568645460}
deconz.0 | 2020-03-30 13:44:05.458 | debug | (5610) Code 200: Request succeded set light state 9: [{"success":{"/lights/9/state/bri":0}}]
deconz.0 | 2020-03-30 13:44:05.432 | debug | (5610) dp: bri; id:Lights.9
deconz.0 | 2020-03-30 13:44:05.431 | debug | (5610)  stateChange Lights.9  {"val":0,"ack":false,"ts":1585568645428,"q":0,"from":"system.adapter.iot.0","user":"system.user.admin","lc":1585568645428}

**Comment by Jey-Cee** [comment]
Liegt vermutlich daran das 254 der maximal wert ist.

**Comment by duffbeer2000** [comment]
Die gleich Meldung kommt bei allen Werten größer 0. Ob 10; 50; 100; 200 immer das gleiche.


deconz.0 | 2020-03-30 13:55:31.250 | warn | (5610) Code 400: Bad request set light state 9:  [{"error":{"address":"/lights/9/state/transitiontime","description":"parameter,  transitiontime, not available","type":6}}]
-- | -- | -- | --
deconz.0 | 2020-03-30 13:55:31.246 | debug | (5610) dp: bri; id:Lights.9
deconz.0 | 2020-03-30 13:55:31.245 | debug | (5610) stateChange Lights.9  {"val":50,"ack":false,"ts":1585569331243,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1585569331243}

**Comment by Jey-Cee** [comment]
Ich sehe gerade das er die Transitiontime mit übergibt, das mag er aber für den Rollo nicht. Steht in dem Datenpunkt was drin?
Wenn ja mal leer machen.

**Comment by duffbeer2000** [comment]
Ok, das war ein guter Hinweis. Ich glaube ich hab den Fehler gefunden:
Wenn ich das Objekt "transitiontime" lösche funktioniert alles wie gewollt. Sobald ich den Adapter aber neu starte legt er das Objekt "transitiontime" wieder an und es funktioniert nicht mehr bis ich es wieder lösche.

**Comment by Jey-Cee** [comment]
Ha das ist ein bug. So lange da nicht drin steht sollte das ignoriert werden. Issue offen lassen, ich kümmere mich darum. 
Dauert aber.

**Comment by duffbeer2000** [comment]
Perfekt! Vielen Dank. Hatte schon seit Tagen die die Alias verdächtigt ;) Ich nehme an due gehst das mit der 1.3.x Testversion an, da ich sowieso darauf updaten wollte schreibst einfach im Forum wenn ich testen soll, ich verfolge den Thread. Vielen Dank im Vorraus!

**Comment by Jey-Cee** [comment]
Bitte die v1.3.2 testen

**Comment by duffbeer2000** [comment]
Funktioniert. Hab gleich die Version 1.3.3 getestet. Alles andere scheint auch weiterhin zu funktionieren.
