### ISSUE TITLE
New Zigbee device not recognized (Xiaomi Aqara sensor)

### ISSUE THREAD

**Issue by jensb** [Jey-Cee/ioBroker.deconz#122]
Hello,

I have a ConBee II stick running on Raspberry Pi 4 with the Phoscon web app and ioBroker.
I also have a bag full of Xiaomi sensors which I want to distribute around the house. The house is equipped with two Innr SP120 smart plugs to act as Zigbee repeaters.

The Innr smart plugs were detected by the Phoscon app and ioBroker without any problem.

The Xiaomi Aqara sensors are detected fine by the Phoscon app, and messages are being sent to ioBroker, but the UI does not show there is another device. I tried opening the Zigbee Network from within ioBroker (does not work) and from within the Phoscon app (works fine). The debug log of the plugin says:

    Websocket message: {"e":"changed","id":"11","r":"sensors","state":{"humidity":5037,"lastupdated":"2020-03-30T19:46:42"},"t":"event","uniqueid":"00:15:8d:00:03:fb:4d:00-01-0405"}
    Websocket message: {"e":"changed","id":"10","r":"sensors","state":{"lastupdated":"2020-03-30T19:46:42","temperature":2604},"t":"event","uniqueid":"00:15:8d:00:03:fb:4 ...

So the messages are definitely sent to ioBroker, but for some reason it does not accept and show them in the web UI.

Any idea what may be going wrong here?

**Comment by Jey-Cee** [comment]
> I tried opening the Zigbee Network from within ioBroker (does not work)
Ok should be fixed with next version.

> Any idea what may be going wrong here?
Nope, but this was reported by by other users also. I have no idea whats going on here.

**Comment by Jey-Cee** [comment]
Related #157
