### ISSUE TITLE
Group states werden nach löschen einer scene nicht mehr aktualisiert

### ISSUE THREAD

**Issue by 123dabei** [Jey-Cee/ioBroker.deconz#127]
Hallo, die Group states innerhalb einer Lichtgruppe werden in 1.3.2 nicht mehr aktualisiert, nachdem eine Szene über den Adapter gelöscht wird. Ein restart des Adapters bzw. Neuanlage der Datenstruktur bringt leider auch keine Änderung. Log hat keine Fehlermeldung.

**Comment by Jey-Cee** [comment]
Das kann ich nicht Nachvollziehen, bei mir funktioniert es wie erwartet.
Welche Admin Version hast du? 
Funktioniert das steuern über die Datenpunkte?

**Comment by 123dabei** [comment]
Admin ist 4.0.7
Steuern über die Datenpunkte funktioniert. Allerdings wird immer nur das jeweilige Attribut im Adapter aktualisiert. Sprich es werden im Hintergrund zwar die Daten übertragen aber eine Rückmeldung/Aktualisierung weiterer betroffener Attribute scheint nicht zu erfolgen. Erst wenn ich über den .on state die Gruppe ein mal aus und wieder ein schalte synchronisieren sich auch wieder alle Attribute. beim nächsten aktivieren einer Szene sind dann aber wieder einige Attribute nicht aktuell bzw. stimmen nicht mit dem tatsächlichen Schaltzustand überein.

**Comment by Jey-Cee** [comment]
Ich hab mir das mal angeschaut, soweit ich das jetzt heraus gefunden hab kann es daran liegen das jede Lampe in der Gruppe unterschiedliche Werte haben kann.
Man sollte die Objekte der Gruppe als Steuerelemente sehen und nicht als Status anzeige.

**Comment by 123dabei** [comment]
Danke für die Rückmeldung. Irgendwie passt das aber nicht zu meinem Adapter-Verhalten.
Folgendes steht bei mir im Widerspruch: 
- Nach der Erklärung, dass die Attribute auf Grund mehrerer Lichter in einer Lichtgruppe als Steuerungselement statt als Status zu sehen sind, müssten zumindest die in der Gruppe enthaltenen Einzelleuchten ihren Staus aktualisieren. Dies passiert bei mir zum Beispiel mit der Farbtemperatur (ct) oder der Helligkeit (bri) aber nicht mit dem level. Letzteres wird zwar auch aktualisiert (leuchtet kurz grün) bleibt aber auf dem alten Wert. 
- Das Attribut scene in der jeweiligen Lichtgruppe kann zwar angepasst werden, eine entsprechende Änderung der Szene findet aber nicht statt (die Änderung bleibt unbestätigt) 

Kurze Ergänzung: Aktuell habe ich zum Test lediglich eine Lichtgruppe, welche auch lediglich eine Leuchte enthält

**Comment by Jey-Cee** [comment]
Level ist ein berechneter Wert der ist noch nicht lange im Adapter. Kann sein das es hier noch irgendwo hackt.

> Das Attribut scene in der jeweiligen Lichtgruppe kann zwar angepasst werden, eine entsprechende Änderung der Szene findet aber nicht statt (die Änderung bleibt unbestätigt)

Was genau und wie Änderst du?
Eine Scene kann angelegt, aufgerufen und angepasst werden. Beim anpassen muss mit save bestätigt werden.

**Comment by 123dabei** [comment]
Hi, in der jeweiligen Lichtgruppe gibt es neben den einzelnen Szenen-Ordnern auch das Attribut .scene. 
Hier wird soweit ich es richtig verstehe die aktuell aktive Szene (die jeweilige Szenennummer) übermittelt. Diese kann auch bearbeitet werden, so dass man vermutlich die entsprechende Szenennummer eingeben kann. Allerdings funktioniert das Attribut bei mir weder als Status noch als Steuerungselement (wie oben beschrieben ist zwar eine Eingabe möglich, diese bleibt aber unbestätigt). Wird die Lampengruppe aus- und wieder eingeschaltet aktualisiert sich der Wert einmalig auf die real eingestellte Szene.
