### ISSUE TITLE
Fehlermeldungen bei Adapterinstallation/Problem Create API Key

### ISSUE THREAD

**Issue by FabianHM** [Jey-Cee/ioBroker.deconz#134]
Hallo zusammen,
während der Adapterinstallation auf meinem ioBroker erscheint folgende Fehlermeldung die mir leider nicht weiterhilft. Mein System ist wie folgt:
Node.js: v10.20.1
NPM: v6.14.4
JS controller: 3.0.18

> 
npm install iobroker.deconz@1.3.4 --loglevel error --prefix "/opt/iobroker" (System call)
Package pixman-1 was not found in the pkg-config search path.Perhaps you should add the directory containing `pixman-1.pc'to the PKG_CONFIG_PATH environment variableNo package 'pixman-1' foundgyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)gyp 
ERR! stack     at ChildProcess.emit (events.js:198:13)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)gyp ERR! System Linux 4.19.97-v7l+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/iobroker/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"gyp ERR! cwd /opt/iobroker/node_modules/canvasgyp ERR! node -v v10.20.1gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-pre-gyp/lib/util/compile.js:83:29)node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.19.97-v7l+node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"node-pre-gyp ERR! cwd /opt/iobroker/node_modules/canvasnode-pre-gyp ERR! node -v v10.20.1node-pre-gyp ERR! node-pre-gyp -v v0.11.0node-pre-gyp ERR! not ok 
host.raspberrypi4 install adapter deconz

Kann mir jemand helfen. Denn die Erstellung des API-Key bei der weiteren Einrichtung geht somit nämlich auch nicht.....
Danke vorab,
Grüße Fabian

**Comment by Jey-Cee** [comment]
Gype Fehler kann man ignorieren, der Exit code Zählt bzw. Ob der Adapter installiert wurde und startet. 

Was steht den im Log wenn du versuchst den Api Key zu erstellen?

**Comment by FabianHM** [comment]
> 
> 
> Gype Fehler kann man ignorieren, der Exit code Zählt bzw. Ob der Adapter installiert wurde und startet.
> 
> Was steht den im Log wenn du versuchst den Api Key zu erstellen?


deconz.0 | 2020-04-25 19:03:54.306 | info | (15282) Code 403: Forbidden get devices: [{"error":{"address":"/devices","description":"unauthorized user","type":1}}]
-- | -- | -- | --
deconz.0 | 2020-04-25 19:03:54.304 | info | (15282) Code 403: Forbidden get all groups: [{"error":{"address":"/groups","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 19:03:54.302 | info | (15282) Code 403: Forbidden get all sensors: [{"error":{"address":"/sensors","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 19:03:54.300 | info | (15282) Code 403: Forbidden get all lights: [{"error":{"address":"/lights","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 19:03:54.297 | info | (15282) Terminated (NO_ERROR): Without reason
deconz.0 | 2020-04-25 19:03:54.296 | info | (15282) terminating
deconz.0 | 2020-04-25 19:03:54.258 | info | (15282) cleaned everything up...
deconz.0 | 2020-04-25 19:03:54.254 | error | (15282) TypeError [ERR_INVALID_URL]: Invalid URL: ws://192.168.1.40:undefined     at onParseError (internal/url.js:241:17)     at new URL (internal/url.js:319:5)     at initAsClient (/opt/iobroker/nod
deconz.0 | 2020-04-25 19:03:54.245 | error | (15282) uncaught exception: Invalid URL: ws://192.168.1.40:undefined
deconz.0 | 2020-04-25 19:03:54.226 | info | (15282) deConz Version: 2.5.74; API version: 1.16.0
deconz.0 | 2020-04-25 19:03:54.120 | info | (15282) starting. Version 1.3.4 in /opt/iobroker/node_modules/iobroker.deconz, node: v10.20.1, js-controller: 3.0.18

DE
![grafik](https://user-images.githubusercontent.com/26110738/80285815-ca8e0200-8727-11ea-9c57-c91b6be75f4f.png)

![grafik](https://user-images.githubusercontent.com/26110738/80285819-d7125a80-8727-11ea-9932-7aef331ac82c.png)

**Comment by Jey-Cee** [comment]
Hast du mal die andere Variante probiert um den Api Key zu erzeugen. Im Log sieht es jedenfalls nicht so aus als wurde ein Api key angefragt, deshalb gibt es die zweite Methode.

**Comment by FabianHM** [comment]
Welche andere Methode gibt es denn? Wo ist dise erläutert?
Hab überall nur von diesem Weg über den Button gelesen bzw. Videos gesehen.... Hatte auch den Port mal geändert auf den des Web Adapters, also 8082 und parallel natürlich in der Phoscon App jeweils nach Button Klick den App Zugriff erlaubt (Wobei es den Button "Unlock Gateway" dort so gar nicht gibt

**Comment by Jey-Cee** [comment]
Ich sehe das Problem nicht und die Logs geben auch nichts her. Stell das Log Level der Adapter Instanz mal auf debug versuch nochmal einen Key zu erstellen und zeig das Log her.

**Comment by FabianHM** [comment]
Nebenbei schon mal vielen Dank für Deine Mühe. Das Thema hat mir heute den ganzen Samstag geraubt...
> 

deconz.0 | 2020-04-25 20:11:51.814 | info | (26914) Code 403: Forbidden get all groups: [{"error":{"address":"/groups","description":"unauthorized user","type":1}}]
-- | -- | -- | --
deconz.0 | 2020-04-25 20:11:51.812 | info | (26914) Code 403: Forbidden get all sensors: [{"error":{"address":"/sensors","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 20:11:51.806 | info | (26914) Code 403: Forbidden get all lights: [{"error":{"address":"/lights","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 20:11:51.777 | info | (26914) Terminated (NO_ERROR): Without reason
deconz.0 | 2020-04-25 20:11:51.777 | debug | (26914) Plugin sentry destroyed
deconz.0 | 2020-04-25 20:11:51.775 | info | (26914) terminating
deconz.0 | 2020-04-25 20:11:51.767 | info | (26914) deConz Version: 2.5.74; API version: 1.16.0
deconz.0 | 2020-04-25 20:11:51.765 | debug | (26914)  Code 200: Request succeded  get config:  {"apiversion":"1.16.0","bridgeid":"00212EFFFF05B1FF","datastoreversion":"60","devicename":"ConBee  II","factorynew":false,"mac":"dc:a6:32:21:d5:c5","mode
deconz.0 | 2020-04-25 20:11:51.717 | info | (26914) cleaned everything up...
deconz.0 | 2020-04-25 20:11:51.713 | error | (26914) TypeError [ERR_INVALID_URL]: Invalid URL: ws://192.168.1.40:undefined     at onParseError (internal/url.js:241:17)     at new URL (internal/url.js:319:5)     at initAsClient (/opt/iobroker/nod
deconz.0 | 2020-04-25 20:11:51.704 | error | (26914) uncaught exception: Invalid URL: ws://192.168.1.40:undefined
deconz.0 | 2020-04-25 20:11:51.625 | info | (26914) starting. Version 1.3.4 in /opt/iobroker/node_modules/iobroker.deconz, node: v10.20.1, js-controller: 3.0.18
deconz.0 | 2020-04-25 20:11:51.475 | debug | (26914) Plugin sentry Initialize Plugin (enabled=true)
host.raspberrypi4 | 2020-04-25 20:11:48.915 | info | instance system.adapter.deconz.0 started with pid 26914
host.raspberrypi4 | 2020-04-25 20:11:18.882 | info | Restart adapter system.adapter.deconz.0 because enabled
host.raspberrypi4 | 2020-04-25 20:11:18.882 | info | instance system.adapter.deconz.0 terminated with code 0 (NO_ERROR)
host.raspberrypi4 | 2020-04-25 20:11:18.882 | error | Caught by controller[1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
host.raspberrypi4 | 2020-04-25 20:11:18.882 | error | Caught by controller[1]:     at getAutoUpdates (/opt/iobroker/node_modules/iobroker.deconz/main.js:678:14)
host.raspberrypi4 | 2020-04-25 20:11:18.882 | error | Caught by controller[1]:     at new WebSocket (/opt/iobroker/node_modules/ws/lib/websocket.js:72:7)
host.raspberrypi4 | 2020-04-25 20:11:18.881 | error | Caught by controller[1]:     at initAsClient (/opt/iobroker/node_modules/ws/lib/websocket.js:478:17)
host.raspberrypi4 | 2020-04-25 20:11:18.881 | error | Caught by controller[1]:     at new URL (internal/url.js:319:5)
host.raspberrypi4 | 2020-04-25 20:11:18.881 | error | Caught by controller[1]:     at onParseError (internal/url.js:241:17)
host.raspberrypi4 | 2020-04-25 20:11:18.881 | error | Caught by controller[1]: TypeError [ERR_INVALID_URL]: Invalid URL: ws://192.168.1.40:undefined
host.raspberrypi4 | 2020-04-25 20:11:18.880 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected
deconz.0 | 2020-04-25 20:11:18.418 | info | (26535) Code 403: Forbidden get devices: [{"error":{"address":"/devices","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 20:11:18.416 | info | (26535) Code 403: Forbidden get all groups: [{"error":{"address":"/groups","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 20:11:18.414 | info | (26535) Code 403: Forbidden get all sensors: [{"error":{"address":"/sensors","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 20:11:18.408 | info | (26535) Code 403: Forbidden get all lights: [{"error":{"address":"/lights","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 20:11:18.369 | info | (26535) deConz Version: 2.5.74; API version: 1.16.0
deconz.0 | 2020-04-25 20:11:18.368 | debug | (26535)  Code 200: Request succeded  get config:  {"apiversion":"1.16.0","bridgeid":"00212EFFFF05B1FF","datastoreversion":"60","devicename":"ConBee  II","factorynew":false,"mac":"dc:a6:32:21:d5:c5","mode
deconz.0 | 2020-04-25 20:11:18.358 | info | (26535) Terminated (NO_ERROR): Without reason
deconz.0 | 2020-04-25 20:11:18.357 | debug | (26535) Plugin sentry destroyed
deconz.0 | 2020-04-25 20:11:18.356 | info | (26535) terminating
deconz.0 | 2020-04-25 20:11:18.313 | info | (26535) cleaned everything up...
deconz.0 | 2020-04-25 20:11:18.310 | error | (26535) TypeError [ERR_INVALID_URL]: Invalid URL: ws://192.168.1.40:undefined     at onParseError (internal/url.js:241:17)     at new URL (internal/url.js:319:5)     at initAsClient (/opt/iobroker/nod
deconz.0 | 2020-04-25 20:11:18.298 | error | (26535) uncaught exception: Invalid URL: ws://192.168.1.40:undefined
deconz.0 | 2020-04-25 20:11:18.215 | info | (26535) starting. Version 1.3.4 in /opt/iobroker/node_modules/iobroker.deconz, node: v10.20.1, js-controller: 3.0.18
deconz.0 | 2020-04-25 20:11:18.066 | debug | (26535) Plugin sentry Initialize Plugin (enabled=true)
host.raspberrypi4 | 2020-04-25 20:11:15.369 | info | instance system.adapter.deconz.0 started with pid 26535
host.raspberrypi4 | 2020-04-25 20:10:45.355 | info | Restart adapter system.adapter.deconz.0 because enabled
host.raspberrypi4 | 2020-04-25 20:10:45.355 | info | instance system.adapter.deconz.0 terminated with code 0 (NO_ERROR)
host.raspberrypi4 | 2020-04-25 20:10:45.355 | error | Caught by controller[1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
host.raspberrypi4 | 2020-04-25 20:10:45.355 | error | Caught by controller[1]:     at getAutoUpdates (/opt/iobroker/node_modules/iobroker.deconz/main.js:678:14)
host.raspberrypi4 | 2020-04-25 20:10:45.355 | error | Caught by controller[1]:     at new WebSocket (/opt/iobroker/node_modules/ws/lib/websocket.js:72:7)
host.raspberrypi4 | 2020-04-25 20:10:45.354 | error | Caught by controller[1]:     at initAsClient (/opt/iobroker/node_modules/ws/lib/websocket.js:478:17)
host.raspberrypi4 | 2020-04-25 20:10:45.354 | error | Caught by controller[1]:     at new URL (internal/url.js:319:5)
host.raspberrypi4 | 2020-04-25 20:10:45.354 | error | Caught by controller[1]:     at onParseError (internal/url.js:241:17)
host.raspberrypi4 | 2020-04-25 20:10:45.354 | error | Caught by controller[1]: TypeError [ERR_INVALID_URL]: Invalid URL: ws://192.168.1.40:undefined
host.raspberrypi4 | 2020-04-25 20:10:45.353 | error | Caught by controller[0]: This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch(). The promise rejecte
deconz.0 | 2020-04-25 20:10:44.877 | info | (26223) Code 403: Forbidden get devices: [{"error":{"address":"/devices","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 20:10:44.875 | info | (26223) Code 403: Forbidden get all groups: [{"error":{"address":"/groups","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 20:10:44.873 | info | (26223) Code 403: Forbidden get all sensors: [{"error":{"address":"/sensors","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 20:10:44.867 | info | (26223) Code 403: Forbidden get all lights: [{"error":{"address":"/lights","description":"unauthorized user","type":1}}]
deconz.0 | 2020-04-25 20:10:44.834 | info | (26223) Terminated (NO_ERROR): Without reason
deconz.0 | 2020-04-25 20:10:44.833 | debug | (26223) Plugin sentry destroyed
deconz.0 | 2020-04-25 20:10:44.832 | info | (26223) terminating
deconz.0 | 2020-04-25 20:10:44.820 | info | (26223) deConz Version: 2.5.74; API version: 1.16.0
deconz.0 | 2020-04-25 20:10:44.819 | debug | (26223) Code 200: Request succeded  get config:  {"apiversion":"1.16.0","bridgeid":"00212EFFFF05B1FF","datastoreversion":"60","devicename":"ConBee  II","factorynew":false,"mac":"dc:a6:32:21:d5:c5","mod
deconz.0 | 2020-04-25 20:10:44.780 | info | (26223) cleaned everything up...
deconz.0 | 2020-04-25 20:10:44.776 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
deconz.0 | 2020-04-25 20:10:44.776 | error | at getAutoUpdates (/opt/iobroker/node_modules/iobroker.deconz/main.js:678:14)
deconz.0 | 2020-04-25 20:10:44.776 | error | at new WebSocket (/opt/iobroker/node_modules/ws/lib/websocket.js:72:7)
deconz.0 | 2020-04-25 20:10:44.776 | error | at initAsClient (/opt/iobroker/node_modules/ws/lib/websocket.js:478:17)
deconz.0 | 2020-04-25 20:10:44.776 | error | at new URL (internal/url.js:319:5)
deconz.0 | 2020-04-25 20:10:44.776 | error | at onParseError (internal/url.js:241:17)
deconz.0 | 2020-04-25 20:10:44.776 | error | (26223) TypeError [ERR_INVALID_URL]: Invalid URL: ws://192.168.1.40:undefined
deconz.0 | 2020-04-25 20:10:44.766 | error | (26223) uncaught exception: Invalid URL: ws://192.168.1.40:undefined
deconz.0 | 2020-04-25 20:10:44.610 | info | (26223) starting. Version 1.3.4 in /opt/iobroker/node_modules/iobroker.deconz, node: v10.20.1, js-controller: 3.0.18
deconz.0 | 2020-04-25 20:10:44.449 | debug | (26223) Plugin sentry Initialize Plugin (enabled=true)
deconz.0 | 2020-04-25 20:10:43.482 | debug | (26223) statesDB connected
deconz.0 | 2020-04-25 20:10:43.481 | debug | (26223) States connected to redis: 127.0.0.1:9000
deconz.0 | 2020-04-25 20:10:43.468 | debug | (26223) States create System PubSub Client
deconz.0 | 2020-04-25 20:10:43.466 | debug | (26223) States create User PubSub Client
deconz.0 | 2020-04-25 20:10:43.459 | debug | (26223) Redis States: Use Redis connection: 127.0.0.1:9000
deconz.0 | 2020-04-25 20:10:43.456 | debug | (26223) objectDB connected
deconz.0 | 2020-04-25 20:10:43.448 | debug | (26223) Objects connected to redis: 127.0.0.1:9001
deconz.0 | 2020-04-25 20:10:43.432 | debug | (26223) Objects client initialize lua scripts
deconz.0 | 2020-04-25 20:10:43.431 | debug | (26223) Objects create User PubSub Client
deconz.0 | 2020-04-25 20:10:43.430 | debug | (26223) Objects create System PubSub Client
deconz.0 | 2020-04-25 20:10:43.425 | debug | (26223) Objects client ready ... initialize now
deconz.0 | 2020-04-25 20:10:43.387 | debug | (26223) Redis Objects: Use Redis connection: 127.0.0.1:9001

**Comment by Jey-Cee** [comment]
Ich weis nicht warum der Adapter bei dir immer Abstürzt so lange es noch keinen Api Key gibt, aber deswegen kann kein Key erstellt werden.

**Comment by FabianHM** [comment]
Haben evtl die Settings des Web Adapters einen Einfluss, Stichwort Web-Sockets?
![grafik](https://user-images.githubusercontent.com/26110738/80287476-29587900-8732-11ea-98b4-924c77599a7f.png)

**Comment by Jey-Cee** [comment]
Ne ich denke ich hab den Grund gefunden, das liegt einer Änderung die ich vor kurzem gemacht habe. Fice ich sobald ich kann.

Bis dahin gibt es nur die Möglichkeit das du das Objekt Gateway_info öffnest und im Reiter Native bei websocketport 443 einträgst.

**Comment by FabianHM** [comment]
Klingt gut. Okay, ich schaue mir den Lösungsweg gleich direkt an.

Dankeschön 👍

**Comment by FabianHM** [comment]
Dort ist aber kein websocketport:
![grafik](https://user-images.githubusercontent.com/26110738/80287911-8fde9680-8734-11ea-9409-5b9e225bd38a.png)

**Comment by Jey-Cee** [comment]
Scroll mal runter das sind normal ziemlich viele punkte und das ist einer der letzten.

**Comment by FabianHM** [comment]
Ne, leider nicht. Vermutlich werden diese Attribute erst später angelegt..

**Comment by Jey-Cee** [comment]
@FabianHM kannst du bitte mal die Aktuelle Version von Github testen. Sollte damit erledigt sein.

**Comment by FabianHM** [comment]
> 
> 
> @FabianHM kannst du bitte mal die Aktuelle Version von Github testen. Sollte damit erledigt sein.

Der App-Key wurde direkt korrekt erzeugt 👍 Prima.

Frage: Wie gehe ich nun vor, wenn Du ein neues Release 1.3.5 veröffentlichst?
Einfach die Gitub Version deinstallieren und dann die 1.35 wieder von NPM installieren?
Danke und Grüße
Fabian

**Comment by Jey-Cee** [comment]
Wenn ich die Version auf npm Veröffentliche brauchst du nichts machen. Wenn es Änderungen geben sollte gibt es eine neue Version.
