### ISSUE TITLE
CT-Wert wird nicht übernommen

### ISSUE THREAD

**Issue by p0rys** [Jey-Cee/ioBroker.deconz#135]
Moin,

ich habe ein Problem mit meinen IKEA Tradfri Farbtemperaturlampen. Wenn ich den Wert für "CT" unter Objekte im ioBroker oder im VIS ändere, wird die Farbe der Lampe zwar verändert aber der Rückgabewert ist weiterhin der Alte.

Hat jemand ähnliche Probleme?

Gruß,
Porys

**Comment by 123dabei** [comment]
Hi, bei den Lampengruppen habe ich das gleiche Verhalten wie du beschreibst. (siehe #127) Bei den Einzellampen aktualisiert sich bei mir der Wert. Allerdings habe ich das Problem sowohl bei den Einzellampen als auch den Gruppen für das .level Attribut.

**Comment by Jey-Cee** [comment]
CT Wertübernahme bei IKEA Lampen ist seitens deConz fehlerhaft. Das ist schon bekannt. 

@123dabei dein Problem hat damit nichtszu tun.

**Comment by MC-1984** [comment]
@Jey-Cee Gibt es hier inzwischen ein Update? Ich kann bei mir über CT gar nichts mehr ändern. Offenbar sollte das Problem dahingehend gelöst werden, dass man anstatt CT XY verwendet ([https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2798#issuecomment-633107162](url)).

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/58948938/83234660-f53d0180-a190-11ea-9dfa-356287c2d34a.png">
XY gibt es bei mir jedoch leider nicht.

Beim Versuch den Colormode umzuschalten (ist das neu?) gibt es eine Fehlermeldung:
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/58948938/83234763-19004780-a191-11ea-8bd5-8d3bcabaec62.png">

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/58948938/83234811-2a495400-a191-11ea-9f7a-50e1412ab5a6.png">

Bei mir tritt das Problem bei allen Ikea Tradfri auf, die Warmweiß/Kaltweiß können. Diese muss ich mangels XY über CT steuern. Alle anderen Lampen steuere ich über XY.

Ich bin auf deconz 2.5.77 und aktueller Adapterversion.

**Comment by Jey-Cee** [comment]
> Offenbar sollte das Problem dahingehend gelöst werden, dass man anstatt CT XY verwendet

Wenn diese Lampen wirklich nur über xy Steuerbar sind kannst du eigentlich nur versuchen den Action Datenpunkt zu benutzen:

`"xy": "[0.1000, 0.1000]"`

Ich glaube zwar nicht das es Funktioniert, aber den Versuch ist es Wert.


> Bei mir tritt das Problem bei allen Ikea Tradfri auf, die Warmweiß/Kaltweiß können. Diese muss ich mangels XY über CT steuern. Alle anderen Lampen steuere ich über XY.

XY gibt es nur bei Farbigen Leuchten.


> Beim Versuch den Colormode umzuschalten (ist das neu?) gibt es eine Fehlermeldung:

Ist read only und wird von deConz gesetzt bzw. von der Lampe ausgelesen.

**Comment by MC-1984** [comment]
@Jey-Cee Mein Problem lag an einem fehlerhaften CT Wert (max 454). Höhere Werte wurden vor dem letzten API Update automatisch auf den maximalen Wert reduziert. Dies wurde geändert und funktionierte daher nicht mehr. Siehe auch [https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2820](url)

Danke für die Hilfe!
