### ISSUE TITLE
Deconz adapter crash 1.3.4 

### ISSUE THREAD

**Issue by realwax** [Jey-Cee/ioBroker.deconz#136]
host.ioBrokerPIB3 | 2020-04-27 15:04:00.283 | error | Caught by controller[1]: at process._tickCallback (internal/process/next_tick.js:68:7)
-- | -- | -- | --
host.ioBrokerPIB3 | 2020-04-27 15:04:00.283 | error | Caught by controller[1]: at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.deconz/main.js:1247:17)
host.ioBrokerPIB3 | 2020-04-27 15:04:00.283 | error | Caught by controller[1]: at new ackStateVal (/opt/iobroker/node_modules/iobroker.deconz/main.js:1983:17)
host.ioBrokerPIB3 | 2020-04-27 15:04:00.283 | error | Caught by controller[1]: at deconz.getStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1577:16)
host.ioBrokerPIB3 | 2020-04-27 15:04:00.282 | error | Caught by controller[1]: at new Promise (<anonymous>)
host.ioBrokerPIB3 | 2020-04-27 15:04:00.282 | error | Caught by controller[1]: at Promise (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1578:16)
host.ioBrokerPIB3 | 2020-04-27 15:04:00.282 | error | Caught by controller[1]: at deconz.getState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6270:17)
host.ioBrokerPIB3 | 2020-04-27 15:04:00.281 | error | Caught by controller[1]: at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:478:19)
host.ioBrokerPIB3 | 2020-04-27 15:04:00.281 | error | Caught by controller[1]: Error: The id is empty! Please provide a valid id.
host.ioBrokerPIB3 | 2020-04-27 15:04:00.280 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected
deconz.0 | 2020-04-27 15:03:59.045 | info | (13096) Terminated (NO_ERROR): Without reason
deconz.0 | 2020-04-27 15:03:59.041 | info | (13096) terminating
deconz.0 | 2020-04-27 15:03:58.987 | info | (13096) cleaned everything up...
deconz.0 | 2020-04-27 15:03:58.983 | error | (13096) Error: The id is empty! Please provide a valid id. at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:478:19) at deconz.getState (/opt/iobroker/node_module
deconz.0 | 2020-04-27 15:03:58.943 | error | (13096) uncaught exception: The id is empty! Please provide a valid id.

**Comment by realwax** [comment]
Hab länger keine Updates gemacht. Ggf. ist es auch die neue Version. Bin am testen...

**Comment by realwax** [comment]
Mit der 1.3.3. habe ich es nicht, wie es scheint.

**Comment by Jey-Cee** [comment]
Ok schau ich mir an. An der stelle wollte ich eine Änderung Rückgängig machen, die nur aus "Bürokratischen" gründen nötig war.

**Comment by Jey-Cee** [comment]
Kannst du bitte mal die 1.3.5 von Github testen.

**Comment by realwax** [comment]
@Jey-Cee Danke! Installiert, kurz getestet. Kein Fehler bisweilen und ich denke weiterhin...
