### ISSUE TITLE
Colorloopspeed too fast

### ISSUE THREAD

**Issue by unstressable** [Jey-Cee/ioBroker.deconz#138]
Since the last Update the colorloopspeed is too fast.

I set up „255“ as value.
This should be the slowest value, but it is very fast.

Seems that „1“ and „255“ are the same. So it might not work actually.

**Comment by Jey-Cee** [comment]
Which version have you installed?

**Comment by unstressable** [comment]
Latest stable on iobroker

**Comment by Jey-Cee** [comment]
1.2.6 or 1.3.4?

**Comment by unstressable** [comment]
It's 1.2.6 (a newer is not available directly)

Should I try the latest Github version?

**Comment by Jey-Cee** [comment]
You could. Problem is fixed in newer version.
