### ISSUE TITLE
No reconnect after restarting deconz-controller

### ISSUE THREAD

**Issue by kopierschnitte** [Jey-Cee/ioBroker.deconz#139]
Hi!
I've noticed that the deconz-adapter (1.2.6) doesn't try to reconnect if I restart the deconz-controller system (running on a dedicated RPi). If this happens, I need to restart the deconz-adapter manually.

Therefore, I would like to suggest a possible **feature enhancement** that the deconz-adapter should try to reconnect either forever or for a reasonable amount of time/tries.

**Comment by Jey-Cee** [comment]
Thanks, this was known before 1.2.6 and was respected, but not properly handeld. 
Actual the version 1.3.5 is in testing and hopefully would be able to release this in the next days.
