### ISSUE TITLE
switch "temperature" ohne verarbeitung

### ISSUE THREAD

**Issue by aargau90** [Jey-Cee/ioBroker.deconz#14]
In der Funktion getSensor(sensorId) wird im switch unter "temperature" keine Verarbeitung vorgenommen, daher werden in iobroker Temperaturänderungen von Sensoren (bei mir Xiaomi) nicht aktualisiert.
Ein eifnaches Copy / Paste von humidity reicht aus um den Bug zu fixen.

Frage: Wieso werden trotz websocket die ändernungen jeweils über ein neuen request abgefragt und nicht direkt aus dem WS Objekt genommen? Ich habe gesehen, dass im WS Objekt der Name des Sensors nicht vorhanden ist. Könnte man das nicht resourcenschonender gestallten in dem man eine Temporäre Liste irgendwo zwischenspeichert mit ID und Name vom Sensor und somit nur dann ein neuer http request gemacht werden muss wenn der Sensorname unbekannt ist.
Einzige "Gefahr" sehe ich, dass so Namensänderungen ggf. nicht sauber übernommen werden

**Comment by aargau90** [comment]
Hoppla, da scheint es doch noch ein weiterer Punkt zu geben, den ich noch nicht ganz entschlüsselt habe:

-> Du prüfst wohl mittels getForeignObjects welchem Objekt vom Adapter die ID gehört. Die scheint aber zumindest bei mir nicht zu passen.
Der Sensor liefert bei mir drei IDs zurück ( 6 7 8 für Temperatur, Luftdruck und Luftfeuchtigkeit) es gibt jedoch nur ein Objekt namens "Aussen"(ID:8)  welches die drei statis untersich abgelegen hat. Daher wird trifft die IF Bedingung nie zu und der Sensor wird nicht ausgelesen / gespeichert. 

Ist diese Abfrage nicht sowieso "für nichts" wenn du danach den Sensor eh mittels ID vom WS Objekt nochmals ausliest oder ist das ggf. die Vorbereitung für oben genanntes direktes updaten ohne weiteren Request?

**Comment by Jey-Cee** [comment]
Der Hintergrund ist einfach: 
Ich habe den Namen als ID in ioBroker verwendet. Später kammen die Xiaomi Sensoren in deConz dazu, die sich Schlauerweise als mehrere Sensoren melden. 
Dresden Elektronik dachte sich es sei Schlau in Phoscon die Sensoren mittels Template als einen zu verwenden. Dumm nur das die RestAPI diese Sensoren noch immer getrennt behandelt, aber jetzt haben sie alle den gleichen Namen.

Dank deinem Beitrag weiss ich jetzt wie ich das mit dem WS besser Lösen kann und gleichzeitig dem Problem mit dem Namen aus dem Weg geh.
Dadurch ändert sich halt die Objekt ID in ioBroker.
