### ISSUE TITLE
Xiaomi Vibrationssensor kein Batteriestatus

### ISSUE THREAD

**Issue by 7egacy** [Jey-Cee/ioBroker.deconz#140]
Beim Xiaomi Vibrationssensor sehe ich in der Phoscon App den Batteriestand in Prozent, zum Adapter wird er jedoch nicht übertragen. Dort steht 0%. Der Wert wird doch bei jedem auslösen des Sensors mit übertragen oder? Oder erst wenn der Batteriestand sinkt?

**Comment by Jey-Cee** [comment]
Ich bin mir nicht sicher wann der Batteriestand übermittelt wird. Sicher auf jeden Fall beim start des Adapters.
Die Sensoren werden als mehrere angelegt somit ist es gut möglich das der richtige Wert bei einem anderen Gerät angezeigt wird.
Generell würde ich aber nicht so viel auf die Batteriewerte geben, die sind nicht sehr Zuverlässig.

**Comment by 7egacy** [comment]
Batteriestatus ist jetzt nach einem Tag auf einmal doch zu sehen.
