### ISSUE TITLE
Probleme mit Eurotronic Spirit Zigbee

### ISSUE THREAD

**Issue by v8turbo** [Jey-Cee/ioBroker.deconz#141]
Habe zum test ein Eurotronic Spirit gekauft. Der Conbee 2 Stick erkennt das Teil, aber im iobroker taucht es nicht auf. Deconz ist die 1.3.5 und Conbee 2.05.75 also alles aktuell. Was kann ich tun ? Resetet etc habe ich den Device schon x mal.

**Comment by Jey-Cee** [comment]
Ich kann dir nicht viel dazu sagen, nur das bei Sensors die Objekte autauchen sollten.
Bei anderen funktioniert das Einwandfrei.

**Comment by KTMLauni** [comment]
Dafür würde ich mir ebenfalls eine baldige Lösung wünschen, da ich diese Thermostate selbst im Einsatz habe und sie seit dem Wechsel auf den ConBee II nicht mehr ansteuern kann.

**Comment by Jey-Cee** [comment]
Ich wiederhole mich nur ungern, aber es scheint nicht angekommen zu sein. Dafür gibt es keine Lösung weil es funktioniert. 

Aber wie man damit umgehen muss kann ich nicht sagen. Schaut im Forum nach dort gibt es einige gute Beiträge dazu.

Und sollte es wiedwr Erwaten Probleme gibt wäre es gut mehr Informationen zu bekommen, wie Log wenn der Log level der Instanz auf debug steht.

**Comment by v8turbo** [comment]
Sorry ich komme Arbeitsbedingt nicht so oft dazu....

Noch mal zu meiner Konfiguration... Habe mir einen neuen Raspberry geholt, da steckt ein Conbee 2 Stick drin. Ich habe mittlerweile 3x 3A RGBW Dimmer und 4x Temperatur Sensoren von Aquara oder wie die heißen. Alles funktioniert perfekt... Außer dieser dumme Thermostat. Er wird auf dem Rasp / Conbee Stick erkannt und Angezeigt... ABER nicht im ioBroker / Deconz Plugin. Er taucht einfach nicht auf, daher -> es funktioniert ebend nicht. Wenn du mir sagst was ich wie/wo machen soll oder du dir das mal per Remote anschauen magst kannst du das gerne tun. Vielleicht gibt es irgendwo ein Log von dem Deconz Plugin ?! Weil im ioBroker taucht ja nichts auf... Daher auch nichts im Log.

Wäre Dankbar für Hilfe.

**Comment by v8turbo** [comment]
Achso eh die Frage kommt... Das Gerät ist wirklich NICHT in deinem Plugin.

Da stehen nur 3x LXT56-LS27LX1.7, paar mal lumi.weather, der Conbee 2 Stick und der Virtuelle Tageslichtsensor PHDL00.

**Comment by Jey-Cee** [comment]
@v8turbo Wann hast du Zeit für ne Remote Session?

**Comment by Jey-Cee** [comment]
Hier für alle die "Lösung" -> https://forum.iobroker.net/topic/28785/how-to-eurotronic-spirit-zigbee-mit-conbee-ii/2

**Comment by ac1dwalk3r** [comment]
hi! wir hatten 2019 schon mal kontakt.....damals war das problem, dass der thermostat zwar eingebunden werden konnte, aber relevante datenpunkte nicht verändert werden konnten. hatte jetzt ein problem mit meinem setup und musste diverses neu installieren -  das meiste wurde durch das backup gesichert, ausgenommen zigbee zeugs....naja, damals hab ich eine fork von deinem deconz projekt gemacht und es mir irgendwie zusammengepfuscht, weil du keine zeit hattest. jetzt sind 2 jahre vergangen und das Problem scheint immer noch zu existieren? mit ausnahme der Kommastelle hat doch alles funktioniert mit meinem code? funktioniert übrigens immer noch^^. ich würde gern mal updates machen, daher frage ich mich, ob du das mittlerweile implementiert hast.....laut diesem thread vor einem halben jahr eher nicht?
