### ISSUE TITLE
xy Wert von Hue Lampe wird nicht übernommen

### ISSUE THREAD

**Issue by DrSchaefer** [Jey-Cee/ioBroker.deconz#143]
Hallo,
seit gestern nach dem Update wird der xy Wert von meiner Hue Lampe nicht mehr übernommen. Ich habe den Adapter heute noch mal gelöscht und die 1.3.7 installiert, mit dem gleichen Ergebnis.
hue oder sat zB werden aber übernommen.

Ich habe die Lampe auch schon zurück gesetzt (mit dem Dimmer Switch) und gegen eine zweite die noch übrig ist getauscht. Beide verhalten sich gleich.

Hier der log auszug beim Ändern von hue:

`deconz.0 | 2020-05-08 11:26:27.149 | debug | (1158) Code 200: Request succeded set light state 2: [{"success":{"/lights/2/state/hue":10012}}]`
`deconz.0 | 2020-05-08 11:26:27.083 | debug | (1158) dp: hue; id:Lights.2 tmp: deconz,0,Lights,2`
`deconz.0 | 2020-05-08 11:48:24.652 | debug | (1158)  stateChange Lights.2  {"val":55,"ack":false,"ts":1588931304647,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":158893130464`
Und hier bei xy:

`deconz.0 | 2020-05-08 11:38:01.121 | debug | (1158) dp: xy; id:Lights.2 tmp: deconz,0,Lights,2`
`deconz.0 | 2020-05-08 11:38:01.121 | debug | (1158)  stateChange Lights.2 {"val":"0.54394,0.4235","ack":false,"ts":1588930681117,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1`

Der Befehl wird wohl gesendet und kommt nicht an? Wie gesagt, hue, sat, bri, on lässt sich alles steuern. In der Phoscon Weboberfläche lässt sich die Farbe auch einstellen. Wenn zB hue verändert wird, wird auch der xy Wert aktualisiert.
Ich habe gerade keine Idee mehr, wo ich weiter suchen soll. Zurück auf 1.3.5 hat auch nicht geholfen.

**Comment by Jey-Cee** [comment]
Also wenn es bei 1.3.5 ging und nach einem Downgrade nicht kann es auch andere Ursachen haben. 
Was für ne js-controller version ist den Installiert?

**Comment by DrSchaefer** [comment]
Ich verwende den Docker Container buanet/iobroker:latest.

` docker exec iobroker npm ls | grep controller`
`iobroker.js-controller@2.2.9`

**Comment by Robox** [comment]
habe das gleiche beobachtet auch bei mit werden die xy nicht wieder geleitet. Die Werte aber Korrekt  von meinen Script nach Anpassung des Datentyp von String  (1.3.4) zu array (1.3.7)  an denn jeweiligen state übermittle.

Node.js  v12.16.3
NPM  6.14.4 
JS controller 3.0.20
OS: linux (Ubuntu)

**Comment by DrSchaefer** [comment]
Ich war davor nicht auf 1.3.5. sondern auf 1.2.6., das habe ich nach dem einspielen von einem Backup bemerkt.
Wenn ich zurück auf 1.2.6 gehe, funktioniert xy wieder (habs aus versehen zwei mal gemacht, ist bei mir also reproduzierbar).

iobroker und deconz laufen bei mir übrigens im docker auf dem selben Raspberry Pi4b, falls das einen unterschied macht (buanet/iobroker:latest und marthoc/deconz). Beide im host-mode und die Ports von deconz auf 8083 bzw. 8443 umgestellt.

**Comment by Jey-Cee** [comment]
Alles egal @Robox hat schon die Lösung. Es gibt jetzt eine Typprüfung im Adapter der Typ von xy stimmt nicht mit dem Überein was eingegeben wird.

**Comment by Robox** [comment]
@Jey-Cee Trotz Anpassung des Datentyp funktioniert es nicht die werde werden aber korrekt an denn xy State  übermittel  und beststigt, kommen aber nicht  beim deconz hub an.

nach setzen des State wird er kurz grün danach rot

**Comment by Jey-Cee** [comment]
Dann gib die werte so ein [0.1000, 0.1000]

**Comment by Robox** [comment]
das habe ich meine array hat den index  0 und 1 einziger unterschiedet habe denn array mit der class array initialisiert aber wie ein array aufgebaut wird ist Geschmackssache.

**Comment by ghost** [comment]
@Robox Hat die Eingabe mit eckigen Klammern funktioniert? Also, wenn z.B. [0.1000, 0.1000] direkt über das xy-State eingegeben wird.
Danke

**Comment by Robox** [comment]
@davincino ich bin zwar nicht der Profi in Javascpt  aber soviel weis ich  ein  array ist array ob ich ihn so 
var array = [0.1000, 0.1000]; 
oder mit 
var array = new Array(0.1000, 0.1000);
initialisiere das macht kein unterschiedet  in beiden fallen bekommt man eine numerischen Array.
deswegen habe ich es gar nicht erst probiert.
habe es für mich aber gelöst und denn xy state wieder denn Datentyp String zugewiesen habe.
was wohl auch in der nächsten versonnen so gefixt wird wenn ich denn Code richtig interpretiere.

**Comment by Fred-Er1c** [comment]
@Robox: Ich habe genau das gleiche Problem und bleibe daher bei Version 1.2.6. Dort funktioniert das setzen von xy für meine Tint Lampen.
Wie hast du das Problem unter Version 1.3.7 genau gelöst? An welcher Stelle hast du den Datentyp String zugewiesen?

**Comment by ghost** [comment]
> @Robox: Ich habe genau das gleiche Problem und bleibe daher bei Version 1.2.6. Dort funktioniert das setzen von xy für meine Tint Lampen.
> Wie hast du das Problem unter Version 1.3.7 genau gelöst? An welcher Stelle hast du den Datentyp String zugewiesen?

Einfach dem xy state den Typ string zuweisen. Dann kannst du wieder so steuern wie bisher. Hat bei mir auch funktioniert.

**Comment by JMagnat** [comment]
Ich habe das gleiche Problem. Ein/Aus und Dimmen klappt wunderbar für die Hue Lampe. Farbwechsel geht gar nicht.
Vollkommen egal, ob ich xy als String oder Array sende.
Alles via Node-Red und ioBroker... Werte kommen im Deconz-Adapter an, aber an der Lampe tut sich gar nichts. :-(

**Comment by bortim** [comment]
Hey @JMagnat ,

bei mir hat es geholfen, wenn ich über die Admin-Oberfläche unter Objekte den Datenpunkt "xy" ganz rechts gelöscht habe.
Nachdem er erneut hinzugefügt wurde, geht es jetzt.
