### ISSUE TITLE
Heiman Siren HS2WD-E

### ISSUE THREAD

**Issue by martinschm** [Jey-Cee/ioBroker.deconz#144]
Hi,
is it possible to fully integrate the above Siren via API ?
It is recognised in the Phoscon App as a light but there is no trigger to turn it on.

On the deconz github (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2754) it was suggested to have it integrated via API.

Would it be possible to do this?

Best
Martin

**Comment by Jey-Cee** [comment]
This isnt the way which this Adapter works. The Adapter will always show any options that are availiable. 
What you are looking for is the datapoint alert. Play with it and see if it works, if not i cant do any thing.

**Comment by Jey-Cee** [comment]
@martinschm any update on your issue?

**Comment by martinschm** [comment]
Hi @Jey-Cee, for the delay in feedback.

It works via API. I found out that there are data points that can be changed that also trigger the alarm and the light.
