### ISSUE TITLE
Battery states not working with newer IKEA Tradfri remotes

### ISSUE THREAD

**Issue by Wildbill-Z** [Jey-Cee/ioBroker.deconz#147]
Beside of many lights, motions sensors and repeaters, I have some older IKEA remotes (with the larger pairing button) and some of the newer ones (small pairing button). None of the newer remotes shows a correct battery state in iobroker. It stays at 0% for weeks. Everything is working OK, all buttons are recognized. All other battery devices show a battery level between 34% and 100%, but the new ones stay at 0%. Even changing batteries to new ones didn't change a thing.
Is this a problem with this adapter or with the Deconz-api? Is there a way to show the "raw messages" sent from Deconz-api for each device?

Greetings, Jürgen
I just set the adapter in iobroker to debug. This is was I got:
```
deconz.0	2020-05-31 12:11:50.921	debug	(18377) Websocket message: {"e":"changed","id":"26","r":"sensors","state":{"buttonevent":3002,"lastupdated":"2020-05-31T10:11:50"},"t":"event","uniqueid":"14:b4:57:ff:fe:65:16:1a-01-1000"}
deconz.0	2020-05-31 12:11:42.805	debug	(18377) Websocket message: {"e":"changed","id":"26","r":"sensors","state":{"buttonevent":3002,"lastupdated":"2020-05-31T10:11:42"},"t":"event","uniqueid":"14:b4:57:ff:fe:65:16:1a-01-1000"}
deconz.0	2020-05-31 12:11:38.263	debug	(18377) Websocket message: {"e":"changed","id":"26","r":"sensors","state":{"buttonevent":2002,"lastupdated":"2020-05-31T10:11:38"},"t":"event","uniqueid":"14:b4:57:ff:fe:65:16:1a-01-1000"}
**deconz.0	2020-05-31 12:11:38.137	debug	(18377) Websocket message: {"config":{"alert":"none","battery":74,"group":"39139","on":true,"reachable":true},"e":"changed","id":"26","r":"sensors","t":"event","uniqueid":"14:b4:57:ff:fe:65:16:1a-01-1**
deconz.0	2020-05-31 12:11:24.529	debug	(18377) Websocket message: {"e":"changed","id":"33","r":"sensors","state":{"buttonevent":3002,"lastupdated":"2020-05-31T10:11:24"},"t":"event","uniqueid":"14:b4:57:ff:fe:50:54:f7-01-1000"}
deconz.0	2020-05-31 12:11:13.249	debug	(18377) Websocket message: {"e":"changed","id":"33","r":"sensors","state":{"buttonevent":2002,"lastupdated":"2020-05-31T10:11:13"},"t":"event","uniqueid":"14:b4:57:ff:fe:50:54:f7-01-1000"}
```

I pressed two times on a new remote, and then on an older remote which shows battery state. as i can see, there were two messages at first press, the first which I marked with two * with other messages like battery state. so it seems to be a problem in Deconz I think?

EDIT: Just opened a [issue](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2851) at deconz-issues.

**Comment by Wildbill-Z** [comment]
I'll close this issue, as I got a solution at [Deconz-github](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2851#issuecomment-636479514) how to readout the battery value in Deconz-GUI and it imidiately showed value in iobroker also.

**Comment by Jey-Cee** [comment]
Thanks for the link. Good to know.
