### ISSUE TITLE
deconz aktualisert neue Hue Lichter nicht

### ISSUE THREAD

**Issue by moschnetwork** [Jey-Cee/ioBroker.deconz#148]
hallo,

leider werden keine neuen Lichter vom deconz Adapter gefunden. Bin up to date und habe deconz neu gestartet sowie auch den raspberry pi.

Hat jemand noch das Problem?

Danke

**Comment by EduardSarjadjuk** [comment]
Hallo, 
ich habe folgendes Problem.
Nach dem Update auf 1.3.8 kann ich keine Lampen mehr steuern und die Bewegungsmeldern (Aqara Motion) verändern auch nicht mehr ihren Status.
Der Adapter zeigt an das er mit deconz (Status Grün) verbunden ist.
Nach dem Downgrade auf 1.3.7 geht wieder alles.
Deconz 2.5.77

Haben sie das selbe Problem ?

**Comment by Jey-Cee** [comment]
Welcher Port ist in der Konfiguration eingetragen? Keiner dann bitte port 80 eintragen.
Bitte um Rückmeldung ob es dann geht.

**Comment by EduardSarjadjuk** [comment]
Dankeschön, mit dem Port 80 geht es wieder bei mir.

**Comment by moschnetwork** [comment]
> Welcher Port ist in der Konfiguration eingetragen? Keiner dann bitte port 80 eintragen.
> Bitte um Rückmeldung ob es dann geht.

Dankeschööööön  für die sehr schnelle Antwort ;) Das war es mit Port 80

Noch ein Tip für alle die bei dieser Änderung nicht speichern können, einfach den Api Key kopieren und wieder einsetzen.

Ach ja, hätte hier noch eine Frage:
es wurden so merkwürdige Gruppen für die Tadfri sowie Hue Schalter angelegt. Diese habe ich nicht angelegt und verstehe nicht woher diese kommen. Von 10 Schaltern wurden Gruppen angelegt, von meinen andere 20 Schaltern keine ...

**Comment by Jey-Cee** [comment]
Port und ip werden Automatisch gespeichert. 
Adapter muss dann neu gestartet werden.

Die Gruppen kommen von deConz, die werden beim anlernen angelegt. Aber Wofür weis ich nicht.

**Comment by MaJaWe1975** [comment]
keine neuen geräte werden von phoscon in deconz übernommen

**Comment by Jey-Cee** [comment]
> keine neuen geräte werden von phoscon in deconz übernommen

Aha und hast du das [hier](https://github.com/iobroker-community-adapters/ioBroker.deconz/issues/148#issuecomment-637747375) gelesen?

**Comment by mayokleckz** [comment]
Danke für den Hinweis.
Wie hätte man selbst auf den fehlenden Port 80 kommen können? In der Adapterinfo steht, nur wenn der Port geändert wurde, ist eine Angabe nötig.
