### ISSUE TITLE
Müller Licht GU10 white+color Spot - hue Wert kann nicht gesteuert werden

### ISSUE THREAD

**Issue by sarotar2303** [Jey-Cee/ioBroker.deconz#149]
Hallo,

ich hoffe ich bin hier richtig mit meiner Frage. 

Ich habe einen Müller Licht tint GU10 RGB white + color Spot eingebunden in deconz.

Ich kann diesen Spot auch steuern über deconz und über die Phoscon Webapp, ich sehe den Spot auch in iobroker dort habe ich unter der Lampe den Wert hue der wohl den Wert  0° - 360°  einnehmen. 
Diesen Wert kann ich in deconz ansteuern aber über iobroker nicht. Egal was in das Objekt eintrage wird entweder nicht übernommen oder auf 0° zurück gestellt.  

Weiß hier jemand woran das liegen kann?

Danke!

Edit: Als ich heute zufällig im Baumarkt war habe ich noch eine tint Lampe mit white + color gekauft diesmal mit E27 Sockel und die funktioniert einwandfrei, auch die Farbeinstellung via hue Wert. Die beiden Lampen haben verschiedene Firmware Stände. GU10 = v2.2 und E27 = v2.0.

**Comment by Jey-Cee** [comment]
Dazu gibt es schon ein Thema bei [deConz](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1652), Exakt das selbe was du hier beschreibst. 
In dem darin verlinkten Issue wird darauf verwiesen das die Lampe Hue gar nicht unterstützt und man xy verwenden muss.

Solltest du version 1.3.7 verwenden musst du xy über den action Datenpunkt setzen:
`"xy": [0.100,0.100]`

**Comment by sarotar2303** [comment]
Vielen Dank für die schnelle Antwort und danke für die Verlinkung zu dem anderen Thema. SChade dass es tatsächlich so ist dass die Lampe mit G10 Fassung anders gesteuert werden muss als das Modell mit E27 Fassung.
