### ISSUE TITLE
Lastannounced-Updates results in permanent updates

### ISSUE THREAD

**Issue by bortim** [Jey-Cee/ioBroker.deconz#150]
Hello @Jey-Cee ,

I am writing you because of an analysis within an issue of deconz-rest-plugin https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2940.

The Pull Request https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2849 will implements the "lastannounced" and "lastseen" Attribute within r = 'lights' and e = 'changed'.
As this data fields are actualized all the time, the deconz-adapter will request the light all the time and nothing can be changed anymore by the admin-UI (and an own script // on-off works).

The changed "lastseen" and "lastannounced" are in an "attr"-tag and not the "state"-tag of a light.
```
{"attr":{"lastseen":"2020-06-14T11:07:34.954Z","manufacturername":"GLEDOPTO","modelid":"GL-C-008S","name":"GLEDOPTO-Controller","swversion":"1.0.8","type":"Extended color light","uniqueid":"00:12:4b:00:1f:6f:ce:e4-0b"},"e":"changed","id":"1","r":"lights","t":"event","uniqueid":"00:12:4b:00:1f:6f:ce:e4-0b"}
{"attr":{"lastseen":"2020-06-14T11:07:36.059Z","manufacturername":"GLEDOPTO","modelid":"GL-C-008S","name":"GLEDOPTO-Controller","swversion":"1.0.8","type":"Extended color light","uniqueid":"00:12:4b:00:1f:6f:ce:e4-0b"},"e":"changed","id":"1","r":"lights","t":"event","uniqueid":"00:12:4b:00:1f:6f:ce:e4-0b"}
```

Nevertheless the whole state ist called all the time and updates nothing.

**Comment by Jey-Cee** [comment]
[17ad51f
](https://github.com/iobroker-community-adapters/ioBroker.deconz/commit/17ad51fba6c6155c42b72db477e92bdd648b5ca7)
