### ISSUE TITLE
[gelöst] deconz  startet nicht mehr: piHole!

### ISSUE THREAD

**Issue by moschnetwork** [Jey-Cee/ioBroker.deconz#152]
hey liebe community,

leider startet mein deconz.0 nicht mehr ;(
 deConz Version: 2.5.72
API Version: 1.16.0

Hier meine log:
`
host.raspberrypi | 2020-06-29 10:06:00.367 | info | Restart adapter system.adapter.deconz.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2020-06-29 10:06:00.367 | info | instance system.adapter.deconz.0 terminated with code 0 (NO_ERROR)
host.raspberrypi | 2020-06-29 10:06:00.367 | error | Caught by controller[1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
host.raspberrypi | 2020-06-29 10:06:00.367 | error | Caught by controller[1]:     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.deconz/main.js:859:36)
host.raspberrypi | 2020-06-29 10:06:00.367 | error | Caught by controller[1]:     at JSON.parse (<anonymous>)
host.raspberrypi | 2020-06-29 10:06:00.367 | error | Caught by controller[1]: SyntaxError: Unexpected token < in JSON at position 5
host.raspberrypi | 2020-06-29 10:06:00.366 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected
deconz.0 | 2020-06-29 10:05:59.834 | info | (10215) Terminated (NO_ERROR): Without reason
deconz.0 | 2020-06-29 10:05:59.832 | info | (10215) terminating
deconz.0 | 2020-06-29 10:05:59.804 | info | (10215) cleaned everything up...
deconz.0 | 2020-06-29 10:05:59.801 | warn | (10215)  Could not connect to websocket instance of deConz/Phoscon. Error:  WebSocket was closed before the connection was established
deconz.0 | 2020-06-29 10:05:59.799 | error | (10215) SyntaxError: Unexpected token < in JSON at position 5     at JSON.parse (<anonymous>)     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.deconz/main.js:859:36)     at p
deconz.0 | 2020-06-29 10:05:59.789 | error | (10215) unhandled promise rejection: Unexpected token < in JSON at position 5
deconz.0 | 2020-06-29 10:05:59.788 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
deconz.0 | 2020-06-29 10:05:59.665 | info | (10215) starting. Version 1.3.9 in /opt/iobroker/node_modules/iobroker.deconz, node: v10.21.0, js-controller: 3.1.4
host.raspberrypi | 2020-06-29 10:05:56.418 | info | instance system.adapter.deconz.0 started with pid 10215
host.raspberrypi | 2020-06-29 10:05:25.405 | info | Restart adapter system.adapter.deconz.0 because enabled
host.raspberrypi | 2020-06-29 10:05:25.405 | info | instance system.adapter.deconz.0 terminated with code 0 (NO_ERROR)
host.raspberrypi | 2020-06-29 10:05:25.405 | error | Caught by controller[1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
host.raspberrypi | 2020-06-29 10:05:25.404 | error | Caught by controller[1]:     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.deconz/main.js:859:36)
host.raspberrypi | 2020-06-29 10:05:25.404 | error | Caught by controller[1]:     at JSON.parse (<anonymous>)
host.raspberrypi | 2020-06-29 10:05:25.404 | error | Caught by controller[1]: SyntaxError: Unexpected token < in JSON at position 5
host.raspberrypi | 2020-06-29 10:05:25.403 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected
deconz.0 | 2020-06-29 10:05:24.873 | info | (8865) Terminated (NO_ERROR): Without reason
deconz.0 | 2020-06-29 10:05:24.871 | info | (8865) terminating
deconz.0 | 2020-06-29 10:05:24.840 | info | (8865) cleaned everything up...
deconz.0 | 2020-06-29 10:05:24.837 | warn | (8865)  Could not connect to websocket instance of deConz/Phoscon. Error:  WebSocket was closed before the connection was established
deconz.0 | 2020-06-29 10:05:24.834 | error | (8865) SyntaxError: Unexpected token < in JSON at position 5     at JSON.parse (<anonymous>)     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.deconz/main.js:859:36)     at pr
deconz.0 | 2020-06-29 10:05:24.825 | error | (8865) unhandled promise rejection: Unexpected token < in JSON at position 5
deconz.0 | 2020-06-29 10:05:24.825 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
deconz.0 | 2020-06-29 10:05:24.708 | info | (8865) starting. Version 1.3.9 in /opt/iobroker/node_modules/iobroker.deconz, node: v10.21.0, js-controller: 3.1.4
host.raspberrypi | 2020-06-29 10:05:15.713 | info | instance system.adapter.deconz.0 started with pid 8865
host.raspberrypi | 2020-06-29 10:05:09.703 | info | instance system.adapter.dwd.0 terminated with code 0 (NO_ERROR)
dwd.0 | 2020-06-29 10:05:09.190 | info | (8406) Terminated (NO_ERROR): Without reason
dwd.0 | 2020-06-29 10:05:08.209 | info | (8406) starting. Version 2.4.10 in /opt/iobroker/node_modules/iobroker.dwd, node: v10.21.0, js-controller: 3.1.4
host.raspberrypi | 2020-06-29 10:05:04.964 | info | instance system.adapter.dwd.0 started with pid 8406
javascript.0 | 2020-06-29 10:05:00.019 | warn | (2140) missing or unrecognized endTime expression: NaN
pollenflug.0 | 2020-06-29 10:04:50.871 | info | (2255) Next DWD pollen request starts on Mon Jun 29 2020 11:00:00 GMT+0200 (GMT+02:00)
host.raspberrypi | 2020-06-29 10:04:44.813 | info | Restart adapter system.adapter.deconz.0 because enabled
host.raspberrypi | 2020-06-29 10:04:44.813 | info | instance system.adapter.deconz.0 terminated with code 0 (NO_ERROR)
host.raspberrypi | 2020-06-29 10:04:44.813 | error | Caught by controller[1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
host.raspberrypi | 2020-06-29 10:04:44.812 | error | Caught by controller[1]:     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.deconz/main.js:859:36)
host.raspberrypi | 2020-06-29 10:04:44.812 | error | Caught by controller[1]:     at JSON.parse (<anonymous>)
host.raspberrypi | 2020-06-29 10:04:44.812 | error | Caught by controller[1]: SyntaxError: Unexpected token < in JSON at position 5
host.raspberrypi | 2020-06-29 10:04:44.811 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected
deconz.0 | 2020-06-29 10:04:44.281 | info | (7598) Terminated (NO_ERROR): Without reason
deconz.0 | 2020-06-29 10:04:44.280 | info | (7598) terminating
deconz.0 | 2020-06-29 10:04:44.248 | info | (7598) cleaned everything up...

`Hoffe es kann mir jemad helfen!

Danke ;)

**Comment by DirkPaulus** [comment]
Hallo versuch ein mal update zu machen .

**Comment by Jey-Cee** [comment]
Was hast du gemacht bevor es nicht mehr ging? Updates?

**Comment by moschnetwork** [comment]
Ich habe 2 Tage zuvor das pihole  installiert und jetzt geht leider nichts mehr. Habe es auch deaktiviert und auch ein update gemacht sowie "sudo apt-get udpate && upgrade" vor 2 Tagen. 

Bei mir stürtzt deconz immer mal wieder (1x je Woche) im ioBroker ab, und hier muss ich den Raspberry pi den Stecker ziehen, und dannach muss ich mit "sudo reboot" neustartetn.  Phoscon App geht tadellos und funktioniert immer.

Bin echt am verzweifeln und habe mir gestern eine 2 Hue Bridge geholt, da ich hier über 96 Hue Geräte im Haus integriert hatte.  (1. Hue Bridge ca. 50 Geräte und der Rest läuft auf conbee II mit ioBroker).

Vielen Dank für Eure Feedbacks ;)

**Comment by moschnetwork** [comment]
Ich glaube den Fehler gefunden zu haben, da beide den Port 80 benutzen. Jetzt weiß ich aber nicht, ob ich beim deconz oder beim piHole den Port wechseln soll. Hat jemand eine Empfehlung? Danke

**Comment by Jey-Cee** [comment]
Am besten du änderst ist bei deConz.
Auf welchem Pi laufen die sachen? Alles auf einem Pi?

**Comment by moschnetwork** [comment]
jep. Ist ein Raspberry pi 4 mit 4 GB RAM. Hab mich vorher informiert, aber wohl nicht richtig ;(

**Comment by moschnetwork** [comment]
Hätte noch einen RP3 über  ... Wollte Geräte und Strom minimaliseren ;)

**Comment by Jey-Cee** [comment]
Hm also mit nem Pi 4 mit 4GB Ram sollte es keine Probleme geben was die Resourcen angeht. Wobei ich nicht weiss was piHole schluckt. 

Der Fehler vom Eingangspost kommt jedenfalls daher das auf Port 80 was anderes Läuft als erwartet.

> Bei mir stürtzt deconz immer mal wieder (1x je Woche) im ioBroker ab, und hier muss ich den Raspberry pi den Stecker ziehen, und dannach muss ich mit "sudo reboot" neustartetn. Phoscon App geht tadellos und funktioniert immer.

Kannst du mal bitte das Log von so einem Absturz zur Verfügung stellen? Ein Adapter Absturz sollte nie einen System Neustart erforderlich machen oder meinst du die Software deConz?

**Comment by moschnetwork** [comment]
hey,

ich meine den deconz.0 Adapter in ioBroker, da die Phoscon GUI und Funktion tadellos laufen.

Habe jetzt das hier gefunden und hoffe dass es der richtige Weg ist:

Just tried to switch the service port using
 "sudo systemctl edit deconz" 
After a bit of trouble my service seems to be running fine again. 
According to 
"sudo service deconz status..."

Output from sudo systemctl cat deconz:

# /etc/systemd/system/deconz.service.d/override.conf
[Service]
ExecStart=
ExecStart=/usr/bin/deCONZ -platform minimal --http-port=8080 --ws-port=8081 --auto-connect=1 --dbg-error=1

Dann noch das für die Firewall:
sudo ufw allow 8080 && sudo ufw allow 8081

Was meinst du?

**Comment by moschnetwork** [comment]
sehe gerade das 8081 vom ioBroker Admin und 8082 von ioBroker VIS belegt ist. Aber 8083 wäre noch frei ;)

hier der Status von deconz.0
`
● deconz.service - deCONZ: ZigBee gateway -- REST API
   Loaded: loaded (/lib/systemd/system/deconz.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-06-30 09:58:17 CEST; 1h 24min ago
 Main PID: 436 (deCONZ)
    Tasks: 5 (limit: 4915)
   Memory: 35.2M
   CGroup: /system.slice/deconz.service
           └─436 /usr/bin/deCONZ -platform minimal --http-port=80

Jun 30 09:58:17 raspberrypi systemd[1]: Started deCONZ: ZigBee gateway -- REST API.
Jun 30 09:58:22 raspberrypi deCONZ[436]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-pi'
Jun 30 09:58:25 raspberrypi deCONZ[436]: libpng warning: iCCP: known incorrect sRGB profile
Jun 30 09:58:25 raspberrypi deCONZ[436]: This plugin does not support propagateSizeHints()
Jun 30 09:58:25 raspberrypi deCONZ[436]: This plugin does not support propagateSizeHints()
Jun 30 09:58:25 raspberrypi deCONZ[436]: This plugin does not support propagateSizeHints()
...skipping...
`

**Comment by moschnetwork** [comment]
**LÖSUNG**:

OK, habs alleine lösen können und bin so vorgegangen:
1. Putty mit ssh verbunden und folgendes eingegeben:
`sudo systemctl edit deconz`
2. Dann folgendes editiert:
`[Service]
ExecStart=
ExecStart=/usr/bin/deCONZ -platform minimal --http-port=8080 --ws-port=8083 --auto-connect=1 --dbg-error=1`
3. mit strg x gespeichert
4. `sudo reboot`
5. iobroker gestartet und deconz Adapter Einstellungen geöffnet und Port auf 8080 gerändert!
 Wichtig: Es lässt sich nicht speichern, da man die Api-Key erst "ausschneiden" und dann wieder "einsetzen" muss!
6. Dann wieder mit reboot und Adapter neustarten.

Jetzt sieht es so aus:
`sudo service deconz status`:
`pi@raspberrypi:~ $ sudo service deconz status
Warning: The unit file, source configuration file or drop-ins of deconz.service
● deconz.service - deCONZ: ZigBee gateway -- REST API
   Loaded: loaded (/lib/systemd/system/deconz.service; enabled; vendor preset: e
  Drop-In: /etc/systemd/system/deconz.service.d
           └─override.conf
   Active: active (running) since Tue 2020-06-30 11:38:32 CEST; 15min ago
 Main PID: 385 (deCONZ)
    Tasks: 5 (limit: 4915)
   Memory: 35.9M
   CGroup: /system.slice/deconz.service
           └─385 /usr/bin/deCONZ -platform minimal --http-port=8080 --ws-port=80

Jun 30 11:38:32 raspberrypi systemd[1]: Started deCONZ: ZigBee gateway -- REST A
Jun 30 11:38:33 raspberrypi deCONZ[385]: QStandardPaths: XDG_RUNTIME_DIR not set
Jun 30 11:38:34 raspberrypi deCONZ[385]: libpng warning: iCCP: known incorrect s
Jun 30 11:38:35 raspberrypi deCONZ[385]: This plugin does not support propagateS
Jun 30 11:38:35 raspberrypi deCONZ[385]: This plugin does not support propagateS
Jun 30 11:38:35 raspberrypi deCONZ[385]: This plugin does not support propagateS

`

Danke für Eure Hilfe ;)
