### ISSUE TITLE
Deconz - Ikea Remote Control

### ISSUE THREAD

**Issue by AhzurdanGit** [Jey-Cee/ioBroker.deconz#154]
Connected Ikea Remote Control through Phoscon
Press button shows "click" in Phoscon beta GUI
Object in IObroker shows up unde deconz.0/Sensors/"serial starting with 588e8..."
Press button shows no change or connectivity under Objects
![Unbenannt](https://user-images.githubusercontent.com/68050893/87010296-a4c0b700-c1c6-11ea-884f-7def1c61d857.JPG)

**Comment by Jey-Cee** [comment]
Could you provide a log, when running adapter instance at loglevel "debug". 
I need more information.

**Comment by AhzurdanGit** [comment]
![Unbenannt](https://user-images.githubusercontent.com/68050893/87239388-dfb52b80-c40e-11ea-8e1d-e6ec24779401.JPG)

After the 10th attempt or so it actually got partly into Objects properly. Still got some strange errors in the log

**Comment by Jey-Cee** [comment]
Please provide logs as Text and from downloaded log. 
In this short part of the log it seems there is no message from your ikea remote control. 



> Still got some strange errors in the log

Which errors do you mean?

**Comment by Jey-Cee** [comment]
I saw you are still using version 2.0.0, please install 2.0.2 from github.

**Comment by AhzurdanGit** [comment]
Issues are gone now
