### ISSUE TITLE
Aqara Multisensor - only temperature not showing

### ISSUE THREAD

**Issue by NGLocanovic** [Jey-Cee/ioBroker.deconz#157]
Hello,

I just paired the Aqara Multisensor (temperature, humidity, pressure) to my Phoscon Gateway (Raspberry Pi + Raspbee II). Inside the Phoscon Gateway, all three values show up correctly. Unfortunately, the temperature does not show up as an object in ioBroker (see screenshots).

Do you have the same problem?

deconz version: 2.05.79
deconz adapter version: 1.3.10
Raspbee II Firmware: 26610700

![Bildschirmfoto 2020-07-23 um 15 20 20](https://user-images.githubusercontent.com/8858043/88291129-11c06a80-ccf8-11ea-8b88-38a6d429cf80.png)
![Bildschirmfoto 2020-07-23 um 14 57 44](https://user-images.githubusercontent.com/8858043/88291155-18e77880-ccf8-11ea-99c2-424173d6a204.png)

Thanks!
Nico

Edit:

I tried to get the sensors via REST and the temperature sensor seems work fine:
```
  "6": {
     "config": {
       "battery": 100,
       "offset": 0,
       "on": true,
       "reachable": true
     },
     "ep": 1,
     "etag": "670eec79614faec15bb0dddd19c92b4f",
     "lastseen": "2020-07-23T15:35:58.485",
     "manufacturername": "LUMI",
     "modelid": "lumi.weather",
     "name": "Weather sensor",
     "state": {
       "lastupdated": "2020-07-23T15:35:58.435",
       "temperature": 2728
     },
     "swversion": "20191205",
     "type": "ZHATemperature",
     "uniqueid": "00:15:8d:00:04:5b:e6:4e-01-0402"
   },
```

**Comment by Jey-Cee** [comment]
I have noticed that from other users, but can not reproduce this problem. 

Referneces:
https://forum.iobroker.net/post/411496

**Comment by NGLocanovic** [comment]
Danke für deine schnelle Antwort!

Gibt es eine Möglichkeit wie ich beim Debuggen helfen kann?

**Comment by NGLocanovic** [comment]
Ich glaub ich habs!
Die Phoscon-App hatte mal so einen "virtuellen" Sensor "Bewegung Glastür" erstellt. Den hatte ich aber irgendwann gelöscht. Der hatte wohl auch die ID 6. Und der Temperatur-Wert wurde unter diesem Sensor aufgelistet. Habe den Sensor aus ioBroker gelöscht und anschließend die Instanz neugestartet. Jetzt wird er auch als "Multisensor" erkannt.
Danke trotzdem!!!

Edit: auch mit `/fullState` wurde der alte "Bewegung Glastür"-Sensor nicht mehr übertragen. Es muss also ein Rudiment vorheriger Übertragungen gewesen sein

**Comment by Jey-Cee** [comment]
Ah ok das scheint plausibel zu sein. Dann dürfte das Thema mit der V2 des Adapters erledigt sein. Da werden die Geräte anhand der MAC angelegt und nicht mehr der ID nach.

**Comment by canim60** [comment]
@Jey-Cee Hallo, Jey erstmal lob an deine Arbeit!, Hab das selbe problem wie @NGLocanovic . Hab gerade ein Wassersensor angelernt, und leider fand ich den über Iobroker nicht. Ich hatte mal ein Sensor wie obe  @NGLocanovic  beschrieben erstellt gehabt und nicht mehr vorhanden war. Was soll ich sagen, der Sensor ist dort aufgetaucht was eigentlicht nicht seien soll. Gibts da eine Möglichkeit oder Bug Fixes,dass neue Geräte einen neuen ID erhalten?,Bevor man sich ein Wolf sucht.. :D

**Comment by Jey-Cee** [comment]
Danke.
Nein von meiner seite aus gibt es  keine möglichkeit das zu ändern. Die ids vergibt deConz.

**Comment by canim60** [comment]
> 
> 
> Danke.
> Nein von meiner seite aus gibt es keine möglichkeit das zu ändern. Die ids vergibt deConz.

Bevor ich ein Issue öffne, sagt dir diese Fehlermeldung was? "

deconz.0 | 2020-09-08 16:42:20.725 | warn | (28340) Could not connect to websocket instance of deConz/Phoscon.  Error: WebSocket was closed before the connection was established
-- | -- | -- | --


"
