### ISSUE TITLE
warn: deconz.0 (2428) Could not connect to websocket instance of deConz/Phoscon. Error: WebSocket was closed before the connection was established

### ISSUE THREAD

**Issue by RockoRocknase** [Jey-Cee/ioBroker.deconz#158]
Hallo zusammen,

seit einigen Tagen ist mir aufgefallen, dass ich diese Warnung auch in meinem Log habe. Sie taucht mehrfach täglich auf.

`2020-07-26 12:24:01.929 - warn: deconz.0 (2428) Could not connect to websocket instance of deConz/Phoscon. Error: WebSocket was closed before the connection was established`

Meine deConz-Adapter-Version ist 1.3.10.

Es gab dazu auch einen Issue, der aber inzwischen leider geschlossen ist. Gibt es dazu eine Lösung, bzw. eine Information, woher diese Warnung kommt?

Vielen Dank und viele Grüße!

**Comment by Jey-Cee** [comment]
Bei dem Fehler auf den du dich beziehst ging es um ein anderes Problem. Deine Fehlermeldung sagt nur aus das die Verbindung geschlossen wurde bevor sie hergestellt wurde. 
Das ist wohl schlicht ein Timing Problem.

Hast du Probleme das etwas nicht funktioniert dadurch?

**Comment by RockoRocknase** [comment]
> Bei dem Fehler auf den du dich beziehst ging es um ein anderes Problem. Deine Fehlermeldung sagt nur aus das die Verbindung geschlossen wurde bevor sie hergestellt wurde.
> Das ist wohl schlicht ein Timing Problem.
> 
> Hast du Probleme das etwas nicht funktioniert dadurch?

Danke für deine Rückmeldung. Ich habe das Problem, dass einige Temperatur-Sensoren nur sehr unregelmäßig einen aktualisierten Wert „senden“ (evtl. liegt es auch am empfangen).

Kann ich das von Dir genannte Timingproblem umgehen, sodass ich ausschließen kann, dass mein Problem daran liegt?

Danke!

**Comment by Jey-Cee** [comment]
> Ich habe das Problem, dass einige Temperatur-Sensoren nur sehr unregelmäßig einen aktualisierten Wert „senden“ (evtl. liegt es auch am empfangen).

Hier ist jetzt die Frage nur in ioBroker oder auch in Phoscon? 
Im ersten Fall liegt es wohl an der Websocket Verbindung.
Im zweiten Fall liegt es am Sensor, dazu muss man aber wissen das es Sensoren gibt die nur senden wenn sich was ändert oder nach einer maximalen Zeit. Bei Xiaomi sind das ~60 Minuten.



> Kann ich das von Dir genannte Timingproblem umgehen, sodass ich ausschließen kann, dass mein Problem daran liegt?

Nein, das habe ich fest Programmiert weil die Websocket Verbindung häufig einfach weg war, aber es gab keine Möglichkeit das fest zu stellen deswegen lasse ich die jetzt alle 60 Sekunden neu aufbauen. Das ist der Ausgangspunkt für das Timing Problem.

**Comment by RockoRocknase** [comment]
Ich habe gerade keinen Sensor da, mit dem ich das testen kann. Da ich bisher von einem Sensor-Defekt ausgegangen bin und diese zurückgesendet habe.

Ich melde mich wieder mit mehr debugging Informationen, sobald der Fall wieder auftritt.

Vielen Dank!
