### ISSUE TITLE
Aqara Vibrationssensor DJT11LM

### ISSUE THREAD

**Issue by Wildshunter** [Jey-Cee/ioBroker.deconz#159]
Hallo, es gibt hier Herausforderungen mit Aqara DJT111LM:

deconz.0.Sensors.2.orientation: Werte werden nicht aktualisiert
deconz.0.Sensors.2.tiltangle: Werte werden nicht aktualisiert
deconz.0.Sensors.2.sensitivitymax: (Werte nicht einstellbar): 1 (High), 11 (Medium), 23 (Low- default)

Danke!

-------
Stick: ConBee II
Version 2.05.78 / 22.5.2020
Firmware: 26580700

deconZ Version 2.5.78
API Version 1.16.0

IoBroker und Raspi 4:
Plattform: linux
Betriebssystem: linux
Die Architektur: arm
CPUs: 4
Geschwindigkeit: 1500 MHz
Modell: ARMv7 Processor rev 3 (v7l)
RAM: 3.8 GB
Node.js: v10.20.1
NPM: 6.14.4

-- json export von ioBroker:

{
  "deconz.0.Sensors.2": {
    "type": "device",
    "common": {
      "name": "Vibration Terassentuer Hauptw",
      "role": "sensor"
    },
    "native": {
      "ep": 1,
      "etag": "f1b5f78dd729c0c55c155b0811fc5d17",
      "id": "2",
      "manufacturername": "LUMI",
      "modelid": "lumi.vibration.aq1",
      "swversion": "20180130",
      "type": "ZHAVibration",
      "uniqueid": "00:15:8d:00:02:c5:b6:61-01-0101"
    },
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396961,
    "_id": "deconz.0.Sensors.2",
    "acl": {
      "object": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Sensors.2.lastupdated": {
    "type": "state",
    "common": {
      "name": "Vibration Terassentuer Hauptw lastupdated",
      "type": "string",
      "role": "value.datetime",
      "read": true,
      "write": false
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396962,
    "_id": "deconz.0.Sensors.2.lastupdated",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Sensors.2.orientation": {
    "type": "state",
    "common": {
      "name": "Vibration Terassentuer Hauptw orientation",
      "type": "array",
      "role": "state",
      "read": true,
      "write": false,
      "custom": {
        "history.0": {
          "enabled": true,
          "changesOnly": true,
          "debounce": 0,
          "maxLength": "10",
          "retention": "31536000",
          "changesRelogInterval": 0,
          "changesMinDelta": 0,
          "aliasId": ""
        }
      }
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396962,
    "_id": "deconz.0.Sensors.2.orientation",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Sensors.2.tiltangle": {
    "type": "state",
    "common": {
      "name": "Vibration Terassentuer Hauptw tiltangle",
      "type": "number",
      "role": "value.tilt",
      "read": true,
      "write": false,
      "unit": "°",
      "def": 0,
      "custom": {
        "history.0": {
          "enabled": true,
          "changesOnly": true,
          "debounce": "1000",
          "maxLength": "960",
          "retention": "31536000",
          "changesRelogInterval": 0,
          "changesMinDelta": 0,
          "aliasId": ""
        }
      }
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396963,
    "_id": "deconz.0.Sensors.2.tiltangle",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Sensors.2.vibration": {
    "type": "state",
    "common": {
      "name": "Vibration Terassentuer Hauptw vibration",
      "type": "boolean",
      "role": "sensor.vibration",
      "read": true,
      "write": true,
      "custom": {
        "history.0": {
          "enabled": true,
          "changesOnly": true,
          "debounce": 0,
          "maxLength": "10",
          "retention": "31536000",
          "changesRelogInterval": 0,
          "changesMinDelta": 0,
          "aliasId": ""
        }
      }
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396963,
    "_id": "deconz.0.Sensors.2.vibration",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Sensors.2.vibrationstrength": {
    "type": "state",
    "common": {
      "name": "Vibration Terassentuer Hauptw vibrationstrength",
      "type": "number",
      "role": "value",
      "read": true,
      "write": false,
      "def": 0,
      "custom": {
        "history.0": {
          "enabled": true,
          "changesOnly": true,
          "debounce": "1000",
          "maxLength": "960",
          "retention": "31536000",
          "changesRelogInterval": 0,
          "changesMinDelta": 0,
          "aliasId": ""
        }
      }
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396963,
    "_id": "deconz.0.Sensors.2.vibrationstrength",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Sensors.2.battery": {
    "type": "state",
    "common": {
      "name": "Vibration Terassentuer Hauptw battery",
      "type": "number",
      "role": "value.battery",
      "read": true,
      "write": false,
      "unit": "%",
      "min": 0,
      "max": 100,
      "def": 0
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396964,
    "_id": "deconz.0.Sensors.2.battery",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Sensors.2.on": {
    "type": "state",
    "common": {
      "name": "Vibration Terassentuer Hauptw on",
      "type": "boolean",
      "role": "switch",
      "read": true,
      "write": true
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396964,
    "_id": "deconz.0.Sensors.2.on",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Sensors.2.pending": {
    "type": "state",
    "common": {
      "name": "Vibration Terassentuer Hauptw pending",
      "type": "array",
      "role": "state",
      "read": true,
      "write": false
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396965,
    "_id": "deconz.0.Sensors.2.pending",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Sensors.2.reachable": {
    "type": "state",
    "common": {
      "name": "Vibration Terassentuer Hauptw reachable",
      "type": "boolean",
      "role": "indicator.reachable",
      "read": true,
      "write": false
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396972,
    "_id": "deconz.0.Sensors.2.reachable",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Sensors.2.sensitivity": {
    "type": "state",
    "common": {
      "name": "Vibration Terassentuer Hauptw sensitivity",
      "type": "number",
      "role": "state",
      "read": true,
      "write": true,
      "def": 0,
      "custom": {
        "history.0": {
          "enabled": true,
          "changesOnly": true,
          "debounce": "1000",
          "maxLength": "960",
          "retention": "31536000",
          "changesRelogInterval": 0,
          "changesMinDelta": 0,
          "aliasId": ""
        }
      }
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396973,
    "_id": "deconz.0.Sensors.2.sensitivity",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Sensors.2.sensitivitymax": {
    "type": "state",
    "common": {
      "name": "Vibration Terassentuer Hauptw sensitivitymax",
      "type": "number",
      "role": "state",
      "read": true,
      "write": true,
      "def": 0
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396973,
    "_id": "deconz.0.Sensors.2.sensitivitymax",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Sensors.2.temperature": {
    "type": "state",
    "common": {
      "name": "Vibration Terassentuer Hauptw temperature",
      "type": "number",
      "role": "value.temperature",
      "read": true,
      "write": false,
      "unit": "°C",
      "def": 0,
      "custom": {
        "history.0": {
          "enabled": true,
          "changesOnly": true,
          "debounce": "1000",
          "maxLength": "960",
          "retention": "31536000",
          "changesRelogInterval": 0,
          "changesMinDelta": 0,
          "aliasId": ""
        }
      }
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1596646396974,
    "_id": "deconz.0.Sensors.2.temperature",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  }
}

**Comment by Jey-Cee** [comment]
> deconz.0.Sensors.2.sensitivitymax: (Werte nicht einstellbar): 1 (High), 11 (Medium), 23 (Low- default)

Wird mit der V2 gefixt.



> deconz.0.Sensors.2.orientation: Werte werden nicht aktualisiert
> deconz.0.Sensors.2.tiltangle: Werte werden nicht aktualisiert

Leider nützt mir der Export der Objekte überhaupt nichts. Ich brauche das Log wenn der Adapter mit dem Log Level debug läuft und sich die Werte des Vibrationssensor ändern, aber nicht in ioBroker Aktualisiert werden.

**Comment by Wildshunter** [comment]
Hallo, Danke!
Mittlerweile habe ich meinen Aqara Sensor zurückgesendet (wegen Wackelkontakt) und warte gerade auf Ersatz. Danke für V2, melde mich sobald der neue sensor da ist. Grüße!

**Comment by Wildshunter** [comment]
Hallo, mein neuer Sensor ist nun angekommen:

deconz.0.Sensors.2.orientation: Werte werden jetzt aktualisert
deconz.0.Sensors.2.tiltangle: Werte werden jetzt aktualisiert

Meiner Info nach sollte man die Vibrationsempfindlichkeit durch Wert "sensitivity" mit den Werten 1 (High), 11 (Medium) und (21) Low (standard) einstellen koennen.  Werte "sensitivity" können gesetzt werden. Evtl. wären hier die möglichen Einstellungen direkt mit High, Medium , Low auswaehlbar. (Gegenüber meiner ersten Aussage das "sensitivitymax" dafür gesetzt werden muß). 
Generell würden mich noch die Beschreibungen zu "sensitivitymax und vibrationstrength" interessieren.

Ein weiteres Feature Request wäre noch "orientation" der x,y,z, Werte in getrennten Feldern unterzubringen, z.B. orientation x, orientation y und orientation z.

Danke, super Arbeit!

**Comment by Jey-Cee** [comment]
[Hier](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1935#issue-502937054) ist eine Erklärung zum Hintergrund von sensitivity(max) und dem Vibrationssensor. 

Für vibrationstrength konnte ich jetzt keine Erklärung finden. 



> Ein weiteres Feature Request wäre noch "orientation" der x,y,z, Werte in getrennten Feldern unterzubringen, z.B. orientation x, orientation y und orientation z.

Ich behalte das mal im Kopf.
