### ISSUE TITLE
Feature Request: include recalling scenes

### ISSUE THREAD

**Issue by mattti** [Jey-Cee/ioBroker.deconz#16]
Would it be possible to also include recalling scenes from deconz?
I find that setting up scenes for me in Phoscon is easier and more reliable than using the scenes adapter.

**Comment by Jey-Cee** [comment]
Hi mattti,
i am sorry that wasn't a point on my to-do-list for this adapter. And for now i will not implement this feature beacause there are a lot of other open points.
I leave this issue open and add this feature request to my to-do-list, but with low priority. 

If you or another person will implement this feature to the adapter and make a pull request, that would be nice.

**Comment by mattti** [comment]
OK, thanks!

For now I wrote a static script using the deconz API.
I'm pretty new to js and I don't program for a living, but I will give the adapter a try when I have time.

**Comment by halloamt** [comment]
Hi,
I submitted PR #25 for that. It works for me but Travis does not like it with Node.js 4
Greetings from the Black Forest
