### ISSUE TITLE
Verbesserungsvorschlag Offset

### ISSUE THREAD

**Issue by JBSullivan** [Jey-Cee/ioBroker.deconz#160]
Ist eigentlich kein Fehler, sondern vielmehr ein Verbesserungsvorschlag - sofern das überhaupt möglich ist.

Alle Aqara Temperatursensoren können ja via Datenpunkt "Offset" mehr oder weniger kalibriert werden.

Ich würde mir das auch für die anderen Aqara Sensoren (Vibration, Wassermelder , BWM usw.) wünschen, sofern das überhaupt möglich ist.

**Comment by Jey-Cee** [comment]
Also so wie ich das verstanden habe wird der Offset direkt im Gerät gesetzt. Deswegen haben den auch nicht alle.
Sicher könnte man einen Offset einbauen der auf alle Geräte angewendet werden kann, aber ich seh das große Problem der Verwirrung. 
Viele nutzen auch Phoscon und wenn dann in ioBroker die Werte dann plötzlich anders sind als in Phoscon kommen deswegen ständig fragen.

Aus meiner Sicht ist es besser wenn jeder der das braucht bewusst selbst macht. Dann weis man selbst auch warum das so ist. 

Aber ich finde deinen Vorschlag interessant und mich interessiert was du dir beim Wassermelder und Bewegungsmelder vorgestellt hast was man mit dem Offset verändert.

Beim Vibrationssensor kann man ja die Empfindlichkeit in Stufen einstellen, das wäre für mich der offset.

**Comment by JBSullivan** [comment]
Also ich dachte beim Offset immer an die Temperatur die ja nahezu jeder Aqara Sensor mitbringt.

So habe ich z.B. den Wassermelder im Technikraum von meinem Pool. Ich hätte mit diesem einen Sensor gleich auch eine Raum Temperatur. Leider liegt der Temperatur Wert des Wassermelder satte 3,5°C gegenüber einem geeeichten Referenz Thermometer daneben.

Bei Vibrationssensor, den ich als Öffnungüberwachung für das Garagentor verwende, das gleiche. So hätte man gleich die Raumtemperatur der Garage, wenn der Temp. Wert nicht auch hier ~ 5°C daneben liegen würde. Von daher dachte ich, das man mit diesen Sensoren zwei Fliegen mit einer Klappe schlagen kann - die eigentliche Funkton (Wasser, Vibration, BWM, Tür/Fenster, The Cube usw) UND die Temperatur.

Wie gesagt, alles was ich so beobachtet habe, liegen speziell die Temp. Werte dieser Sensoren kräftig daneben. Darum das Offset für die Temp. Werte.

**Comment by Jey-Cee** [comment]
Achso du beziehst dich auf die Temperaturen. Das macht natürlich sinn die auch zu verwenden. 

Ich würde dir Empfehlen das selbst zu realisieren. Wenn du die Zeit und lust hast solltest du mehrere Referenz Messungen machen bei Unterschiedlichen Temperaturen, dann siehst du ob die Abweichung immer gleich ist. 

Der Sinn des Offsets ist eigentlich nicht die Abweichung eines Sensors aus zu gleichen sondern den Ausgegebenen Wert an die Tatsächliche Raum Temperatur. Hintergrund ist das in Deutschland zum Beispiel festgelegt ist das die Raumtemperatur in einer höhe von 1 m in der Raum Mitte gemessen wird. Misst man jetzt aber auf 1,6 m Höhe erhält man einen Höheren Wert.
Und diese Differenz ist der Offset (muss dann also als negativer Wert angegeben werden). Der Basis Wert bewegt sich aber Parallel zum Tatsächlichen Wert.

Hat aber hingegen der Temperatursensor eine Abweichung ist keines falls klar ob die Abweichung immer gleich groß ist und somit muss der Offset Variabel sein.
Beispiel:
| Tempertur | Abweichung |
|----|----|
|20  | 0 | 
|21 | 0,1 |
| 22 | 0,5 |

Ich hoffe das ist so einigermaßen Verständlich erklärt.
