### ISSUE TITLE
Deconz stops recieving status updates regarding Aqara door/window sensors

### ISSUE THREAD

**Issue by thenightfighter** [Jey-Cee/ioBroker.deconz#161]
Hi,
after ~ 1 hour deconz at my ioBroker stops recieving data from phoscon app. This happens only with my aqara door/window sensors.
Got 4 sensors all new and everything is updated to latest stable versions.

More information: [https://forum.iobroker.net/topic/26758/deconz-aktualisiert-nicht-stati-von-phoscon-aqara/65](https://forum.iobroker.net/topic/26758/deconz-aktualisiert-nicht-stati-von-phoscon-aqara/65) (german only)

After an restart of the deconz instance within ioBroker they start recieving data again.

**Comment by Jey-Cee** [comment]
@thenightfighter which deConz version are you running (not adapter version)?
Please change the log level for deConz adapter instance and look if there are websoket messages for your sensors after they stopped updating in ioBroker.

**Comment by thenightfighter** [comment]
Running deconz-2.05.78. There are no websocket messages inside the log :(

**Comment by Jey-Cee** [comment]
> There are no websocket messages inside the log :(

Only for your sensors or they no websocket message at all? If the second applies, then you dont have changed the log level.
In this case got to instance overview, activate expert mode and change the log level for the instance.

**Comment by thenightfighter** [comment]
Got many form others devices but non from my sensors :(

**Comment by Jey-Cee** [comment]
Can you please post the log?

**Comment by Jey-Cee** [comment]
I close this while there is no answer for more than a month.
