### ISSUE TITLE
Provide device name as state

### ISSUE THREAD

**Issue by Zefau** [Jey-Cee/ioBroker.deconz#162]
Currently the device name is only available as the channel description. Please provide a state `name`, which reflects the device name.

**Comment by Jey-Cee** [comment]
I do not see why this is usefull, can you tell me where is the benefit of this state?

**Comment by Zefau** [comment]
I'm working on an adapter for a visualization (https://github.com/Zefau/ioBroker.jarvis). I would like to import devices from the ioBroker `enums` (which are eventually refer to the states of the adapter). 

I need the state / information to name the device.
e.g. given the state / channel in enum `deconz.0.Lights.1` (or `deconz.0.Lights.000d6f0013e9ca78`) I have no clue what it actually is, when looking at the nested states.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/31

**Comment by Jey-Cee** [comment]
Hm i understand, but in my mind the better way to go is to read the name from the device object. 
A state 'name' makes the entire attribute name obsolete.

**Comment by Zefau** [comment]
Indeed possible. Thanks for that.
