### ISSUE TITLE
deCONZ adapter restarting every 30 seconds

### ISSUE THREAD

**Issue by Stefan-83** [Jey-Cee/ioBroker.deconz#163]
Hi,
i just installed the current version of deCONZ adapter (1.3.10) and have the same issue (restarting every 30 seconds).

host.ioBrokerGarage | 2020-09-03 12:05:43.651 | info | Restart adapter system.adapter.deconz.0 because enabled
-- | -- | -- | --
host.ioBrokerGarage | 2020-09-03 12:05:43.649 | error | instance system.adapter.deconz.0 terminated with code 156 (156)
deconz.0 | 2020-09-03 12:05:43.064 | warn | (5815) Got terminate signal. Checking desired PID: 5846 vs own PID 5815
deconz.0 | 2020-09-03 12:05:43.051 | debug | (5815) Websocket connection closed
deconz.0 | 2020-09-03 12:05:43.045 | info | (5815) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
deconz.0 | 2020-09-03 12:05:43.040 | info | (5815) terminating
deconz.0 | 2020-09-03 12:05:43.037 | info | (5815) cleaned everything up...
deconz.0 | 2020-09-03 12:05:43.032 | warn | (5815) Got terminate signal. Checking desired PID: 0 vs own PID 5815
host.ioBrokerGarage | 2020-09-03 12:05:43.022 | info | instance system.adapter.deconz.0 started with pid 5846
`
similar to https://github.com/iobroker-community-adapters/ioBroker.deconz/issues/92

**Comment by Jey-Cee** [comment]
Did you delete the Adapter complete, not only the instance?

**Comment by Stefan-83** [comment]
I never deleted it before... I've installed the adapter the first time and got into this issue?
Should I delete it and re-install it?

**Comment by Jey-Cee** [comment]
What is your js-controller version?
Can you please switch the log level for the instance to debug and post the output.

**Comment by Stefan-83** [comment]
js-controller Installed: 2.2.9

But strange... after I set it to Debug-Level, the problem seems to be solved.
Therefore, I'll close this issue by now and I will monitor this...

thanks :)
