### ISSUE TITLE
Anzeige über zweiten Adapter OpenClose

### ISSUE THREAD

**Issue by tonibert** [Jey-Cee/ioBroker.deconz#164]
Hallo, ich nutze 2 Conbee2 Sticks (1. im OG und  den 2. im Keller) jeweils über einen sep. Raspi.
Da ich nun gerne alle Objekte über einen Deconz Adapter in der Überischt haben wollte und auch für andere Skripte immer alles über Deconz.0 abrufen möchte habe ich alle Aquara Fenstersensoren über das Gateway am Master-Raspi eingebunden.
Alle Adapter die über den Empfang des USB-am Master empfangen werden, bekommen auch den richtigen Namen in den Objekten angezeigt.

Alle Sensoren, die im Empfangsbereich des Slave-Raspis laufen werden als OpenClose angezeigt
Gibt es eine (andere) Lösung für mehrere Sticks im Haus oder könnte das behoben werden?

Grüße

![Upload angezeigt](https://user-images.githubusercontent.com/47660393/92327614-257f2080-f05b-11ea-9e64-180b9667303d.png)

**Comment by Jey-Cee** [comment]
Ich tu mich schwer zu verstehen wie du das Überhaupt in eine Adapter Instanz bekommen hast. Du hast zwei Pis mit je einem Stick, dann läuft doch auch auf jedem davon deConz?
Wie hast du die zwei deConz mit einander verbunden?

**Comment by tonibert** [comment]
Ich hatte es erst über einen Stick probiert. Das reichte nicht für beide Etagen , die Kopplung habe ich immer über die Phosconoberfläche-Neuen Sensor verbinden hergestellt. Daraufhin habe ich einen 2 Stick bestellt und an meinen vorhandenen Raspi im Keller gesteckt.

Anschließend bin ich  erneut über die Adresse die IP-Adresse des Sticks am Master Raspi gegangen und konnte nun die anderen Adapter im Keller verbinden. Leider sehe ich keine Netzwerküberischt - wie z.B. im Zigbee Adapter um zu sehen wer welche Verbindung aufbaut.

deConz habe ich auf dem 2 Raspi im Keller nicht installiert.
Ich habe es zwischendurch mal installiert um zu scchauen ob die Namen sich abgleichen. Ich habe aber auf dem Adapter überhaupt keine Geräte vorhanden. 
Meine gesamten Geräte auf dem deConz, sind im Adapter auf dem Raspi im Obergeschoss zu sehen

So habe ich sie eingebunden und sie übermitteln auf fleißig alle Daten
![2](https://user-images.githubusercontent.com/47660393/92332498-9be14a00-f07e-11ea-8e2a-75916d39702e.png)

**Comment by Jey-Cee** [comment]
Wenn du deine Geräte alle so benannt hast wie du sie haben willst, lösch im Adapter die Objekte und starte den Adapter neu dann sollten sie mit den Richtigen Namen auftauchen.

**Comment by tonibert** [comment]
Da ich nicht genau wusste wie ich die Objekte löschen sollte habe ich den gesamten Adapter gelöscht, neu installiert und verbunden. Danke, case closed :-)

Gibt es eine Möglichkeit eine Netzwerküberischt zu bekommen um zu sehen welcher Adapter wie verbunden ist?
