### ISSUE TITLE
Aqara Smart Wireless Switch WXKG11LM #917 - Adding as button

### ISSUE THREAD

**Issue by Siggi0904** [Jey-Cee/ioBroker.deconz#166]
The Aqara Smart Wireless Switch WXKG11LM #917 Button should be added as "button" not as sensor.
In Phoscon App it is added as button, in IOBroker ist will be shown under sensors, what is wrong.

See: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3253

Thanks.

**Comment by Jey-Cee** [comment]
> what is wrong.

Nothing. Sensors is the Endpoint, so it is shown as a sensor.

**Comment by Siggi0904** [comment]
Okay, then it should be a Feature request to differ for Sensors, buttons and lights.
Would be nice.
