### ISSUE TITLE
Gerätestatus wird nicht aktualiseirt  

### ISSUE THREAD

**Issue by EduardSarjadjuk** [Jey-Cee/ioBroker.deconz#167]
Hallo, 

ich habe gemerkt das bei mir mit der Version 2.0.4 der Gerätestatus nicht aktualisiert wird. 
Das bedeutet wenn ich eine Lampe nicht über den Iobroker anschalte, sondern z.B. über die Phoscon Oberfläche, so wird der Status im Iobroker nicht aktualisiert. 
Ich kann die Geräte allerdings über den Ioborker schalten, wenn es über den Iobroker erfolgt ist auch der richtige Status da.
Mit der version 1.3.7 funktioniert alles einwandfrei (Schaltung über Iobroker und extern).
JS COntroller 3.1.6
Node:12.18.3
NPM6.14.6

LG
E.S

**Comment by Voodoo2man** [comment]
Gleiches Problem bei mir auch. Habe den API Key aktualisiert. Leider brachte das keine Verbesserung.
Instanz steht auf Grün, aber es werden keine Objekte aktualisiert.

Edit: habe den Fehler gefunden.
Es wurde ein neuer Ordner „sensors“ (kleingeschrieben) angelegt in dem die Sensoren mit anderem Namen vorhanden sind und auch aktualisiert werden. Bleibt das so, oder wird es gefixt?
Muss man jetzt alle Scripte anpassen?
![DCEC4750-C49C-4806-B892-3253E08831CD](https://user-images.githubusercontent.com/62031459/93075121-a5257480-f685-11ea-935f-62a1fdbaa6c7.jpeg)

**Comment by Jey-Cee** [comment]
Das ist kein Fehler.
Auszug aus dem Changelog:

* use only lower case for ids (2.0.4)

* changed id naming from id to mac (uniqueid) (2.0.0)

**Comment by EduardSarjadjuk** [comment]
Hallo, 

leider werde ich aus dem Changelog nicht ganz schlau.
Welche ids muss ich anpassen ?
Könnetst du mir ein Tip geben. Muss ich die Geräte im Phoscon umbennnen ?
Vielen Dank im Voraus!

**Comment by EduardSarjadjuk** [comment]
Ok habe es dank dem Kommentar oben verstanden. 
Das bedeutet also zwangsläufig alle Skripte, Szenen usw. anzupassen. 
Oder gibt es eine andere möglichkeit ?

**Comment by Jey-Cee** [comment]
Entweder alles Anpassen oder zurück zu 1.3.10.
