### ISSUE TITLE
Fehlerhafte Daten von Aqara Plug

### ISSUE THREAD

**Issue by basty2** [Jey-Cee/ioBroker.deconz#168]
Hallo, nach dem Update von 1.xx zu 2.xx gestern habe ich das durch das zusammenlegen der Sensorendaten durch die MAC folgendes Problem auftrit: 
Es werden 2 unterschiedliche Infos gesendet: 
- (3445) Websocket message: {"e":"changed","id":"44","r":"sensors","state":{"consumption":144200,"lastupdated":"2020-09-15T11:59:55.427","power":0},"t":"event","uniqueid":"xx:xx..."}
- (3445) Websocket message: {"e":"changed","id":"45","r":"sensors","state":{"current":0,"lastupdated":"2020-09-15T12:01:16.117","power":124,"voltage":0},"t":"event","uniqueid":"xx:xx"}

in V1 waren es 2 seperate Sensoren durch die IDs. Nun überschreibt der Powerwert bei der Übertragung des Verbrauchs (immer 0) den tatsächlichen Powerwert immer mit 0.

**Comment by Jey-Cee** [comment]
Das ist Natürlich Spitze. Keine Ahnung woher der Adapter wissen soll welcher Wert jetzt der Richtige ist. 
Am besten wäre es das Übel an der Wurzel zu entfernen, das wäre deConz selbst.

Was ist das den für ein Gerät?

**Comment by basty2** [comment]
Aqara Smart Plug EU

**Comment by basty2** [comment]
Gleiches Problem bei einer Bitron Steckdose. 
Kein Problem bei Xiaomi Smart Plug (ohne Aqara) 
Kein Problem bei Blitzwolf SHP13

Bei den letzten beiden wird kein Powerwert bei Consumption übertragen.

**Comment by Jey-Cee** [comment]
Kannst du mir noch die Version deiner deConz installation geben, dann kann ich einen Issue bei deConz aufmachen.
Und wenn du mir noch genauere Angaben (Modelnummer/-bezeichnung) zu den Plugs hast wäre gut.

**Comment by basty2** [comment]
klar ist Aqara Plug SP-EUC01
Bitron muss ich noch prüfen. Ist aber immer ein Problem wenn bei Consumption auch ein Wert für Power übertragen wird und der Power Wert extra übertragen wird (als andere ID).

**Comment by Jey-Cee** [comment]
deConz version brauche ich noch

**Comment by basty2** [comment]
2.05.80
Ubuntu Version
Bitron 902010/25 zeigt übrigens doch richtig an. D.h. consumption + Power richtig:
(3445) Websocket message: {"e":"changed","id":"34","r":"sensors","state":{"consumption":1789,"lastupdated":"2020-09-15T19:20:04.868","power":5},"t":"event","uniqueid":"..."
Scheint also "nur" ein Problem des Aqara Plug in zu sein.

**Comment by basty2** [comment]
mit der 2.05.82 leider der gleiche Fehler mit dem Aqara Plug. 
Sonst finde ich die Zusammenlegung der Sensoren und die Eineindeutigkeit mit der MAC sehr gut. Räumt die Sensoren auf.

**Comment by basty2** [comment]
Hi @Jey-Cee, 
brauchst Du noch Infos? Ich könnte auch nachfragen, kenne jedoch Websocket-Ablauf nicht so wirklich.

**Comment by Jey-Cee** [comment]
Ich hatte gehofft dein Prbolem hat sich erledigt weil im Changelog von deConz ein Punkt aufgetaucht ist der vermuten hat lassen das er genau das behebt.
Leider hast du ja schon die Aktuellste Version drauf und noch immer das Problem.

Hab gerade den Issue bei dresden elektronik aufgemacht.

**Comment by Jey-Cee** [comment]
Können wir den Issue schließen?

**Comment by basty2** [comment]
Hier können wir es gern schließen. Leider ist der Fehler immer noch in der v83 vorhanden. Ich warte noch einmal die nächste Version ab...

**Comment by Jey-Cee** [comment]
OK dann ist das hoffentlich in der nächsten drin.
