### ISSUE TITLE
Xiaomi Bewegungsmelder / Update

### ISSUE THREAD

**Issue by LJSven** [Jey-Cee/ioBroker.deconz#169]
Ich habe ein komisches Verhalten bei einem Bewegungsmelder - wenn ich morgens die Küche betrete, soll eigentlich eine Ansage kommen. Die kommt aber nicht - sondern erst nach einer gewissen Zeit. Kann leider nicht erkennen, woran das liegen kann. Habe in bisschen den Eindruck, daß nach dem Update der LUX Wert in Verbindung mit dem PRESENCE steht?! Nach dem Motto, wenn LUX = 0 dann keine Bewegung?! Oder eine Art "Sleep"-Modus? Kann das sein? Verbunden könnte der BWM über einen Philips PLUG Sein - kann das aber nicht genau sagen.

**Comment by Jey-Cee** [comment]
Welche Version hast du installiert und von wo?

**Comment by LJSven** [comment]
Adapter Version ist 2.0.4 aus dem latest. Stick & Phoscon ist vom 14.09.2020

**Comment by Jey-Cee** [comment]
Dann installier mal die Version von Github und schau ob es damit weg ist.

**Comment by LJSven** [comment]
Wurden da zu meinem Thema Änderungen gemacht?

**Comment by Jey-Cee** [comment]
Nein aber ich hatte bei mir das selbe verhalten in der Produktivumgebung beobachtet und darauf hin die Github version installiert. Da hab ich ein paar Änderungen , eigentlich nur kleine Fixes gemacht, einer davon scheint aber dieses Problem behoben zu haben.

**Comment by LJSven** [comment]
Reicht es, wenn ich unter Adapter auf installieren von Guthub gehe, oder muss ich den Link eingeben. Bei meinem Adapter steht noch 2.0.4 obwohl auf Github 2.0.5 steht

**Comment by Jey-Cee** [comment]
Ja reicht von Github installieren. Die 2.0.5 gibt es noch nicht, lediglich das Changelog für die Version, also ändert sich die Angezeigte Version in ioBroker nicht.

**Comment by LJSven** [comment]
Okay, habe es mal installiert. Werde morgen berichten.

**Comment by LJSven** [comment]
Bei mir gab es leider keine Veränderung. Sonst noch eine Idee? Mal neu anlernen?

**Comment by Jey-Cee** [comment]
Wenn es ein Problem mit dem Adapter ist wird neu anlernen nicht helfen.

Versuch doch mal deine etwas schwammigen Angaben präziser zu erfassen. Also History logging der Datenpunkte, log Ausgabe in deinem skript wenn die Ausgabe ausgelöst wird. Dann bekommt man mal einen Überblick wann der BWM ausgelöst hat und ob das Skript hätte auslösen sollen.


> Die kommt aber nicht - sondern erst nach einer gewissen Zeit.

Nach welcher Zeit Minuten, Sekunden oder Stunden?

Ist dein BWM modifiziert (5 sekunden Hack)?

**Comment by LJSven** [comment]
Der BWM ist nicht modifiziert. Ich habe den Eindruck, daß er beim ersten mal Betreten nach einer langen Zeit inaktivität nicht geht - danach funktioniert er. Gefühlt würde ich sagen - er wird aufgewacht, schaltet den Datenpunkt im Adapter nicht auf TRUE, obwohl er TRUE sein müsste, dann schaltet er auf FALSE und beim nächsten mal TRUE wird auch der Adapter durchgeschaltet. Es ist halt schwer zu sagen, wann er das erste mal schaltet. Ich habe ein ganz einfaches Script das mir morgens einfach nur sagt, daß die Rollläden gleich gefahren werden, wenn man die Küche betritt / was er beim 2ten mal auch macht. Ausserdem wird in der VIS der BWM auch nicht auf TRUE geschaltet - also würde ich das Script ausschließen. Zu loggen ist halt schwierig, weil man es ja nicht sieht.

![Bildschirmfoto 2020-09-23 um 10 51 23](https://user-images.githubusercontent.com/8560588/93994001-b0685680-fd8f-11ea-9a92-65af7e1f2105.png)

Ich würde sagen, er hätte hier einmal früher schalten müssen - ca. 90 Sekunden.

**Comment by LJSven** [comment]
Was mir gerade auffählt ist, daß in der Phoscon App 181 LUX angezeigt werden, im Adapter auf 182 LUX - keine Ahnung, ob es da einen Zusammenhang gibt.

**Comment by Jey-Cee** [comment]
Ok also wenn es so ist das er erst die zweite Bewegung erkennt musst du mal ganz gezielt in der Früh den BWM auslösen und parallel dazu beobachtest du den Status in der Phoscon app. Damit wissen wir dann ob die Bewegung überhaupt gemeldet wird.

**Comment by LJSven** [comment]
Okay, ich teste es mal morgen früh... oder hast du eine andere Idee, wie ich es "besser" testen kann? Ich weiß halt nicht, ob es wirklich so ist, daß die zweite Bewegung erkannt wird - ist ein Gefühl von mir.

**Comment by Jey-Cee** [comment]
Das ist die beste Möglichkeit die mir gerade Einfällt um zu sehen ob es ein Problem mit dem Adapter ist oder ein Problem mit deinem Zigbee Netz / BWM.

**Comment by bortim** [comment]
Du könntest auch das Loglevel von Deconz erhöhen.
Meiner Erinnerung nach wird dann sehr viel weggeloggt, sodass das auf Seiten von Deconz nachvollzogen werden kann.

Ebenso könntest du das Loglevel vom Adapter erhöhen und dann die Messages von Deconz an den Adapter sehen.
Oder auf den Websocket einen Listener setzen, damit auch das weggeloggt wird.

Eine weitere Möglichkeit wäre, den Deconz-API-Config Parameter "Notify-All" anzeigen zu lassen.
Dieser Parameter gibt an, ob nur geänderte Attribute oder der ganze Datensatz gesendet wird.
Diesen könntest du auch entgegengesetzt ändern.

**Comment by LJSven** [comment]
Ich habe das Gerät neu angelernt - heute Morgen hat es tadellos funktioniert.

**Comment by Jey-Cee** [comment]
Kann der Issue geschlossen werden?

**Comment by LJSven** [comment]
Ja! Danke EUch!
