### ISSUE TITLE
Aqara motion duration value wird nach Update (2.0.4) nicht mehr geschrieben

### ISSUE THREAD

**Issue by MBeeken73** [Jey-Cee/ioBroker.deconz#170]
Nach dem Update auf 2.0.4 wird beim Aqara motion Sensor der Duration level nicht mehr "runtergeschrieben".
Wenn ich wen Wert z.B. auf 10s ändere wird dieser rot dargestellt.
Die Zeit hat sich auch nicht geändert.
![Duration](https://user-images.githubusercontent.com/48216471/94279823-f0c10380-ff4c-11ea-8bb6-f8569150b097.JPG)

P.S.
deConz Version: 2.5.8

**Comment by Jey-Cee** [comment]
War das vorher möglich? Ich meine mich zu erinnern das diese Zeit einen bestimmten Wert (60s ?) nicht unterschreitet.

**Comment by MBeeken73** [comment]
Ja das war möglich.
Ich habe mehrere BWM wo 10s duration vorher runtergeschrieben wurde. Hier läßt sich der Wert jetzt auch nicht mehr ändern.

**Comment by Jey-Cee** [comment]
Ok ich schau mal wo es klemmt.

**Comment by MBeeken73** [comment]
Danke für deine Hilfe.

PS:
Heute die Version 2.0.5 installiert.
Keine Änderung ..

PPS:
Über die API lässt sich die duration ändern
curl -H 'Content-Type: application/json' -X PUT -d '{"duration": 1}' http://DECONZ_IP/api/API_KEY/sensors/SENSOR_ID/config

**Comment by cracyfloyd** [comment]
@Jey-Cee ..Schon was neues. Das wäre schon ne feine Sache. wenn es wieder klappen würde.

@MBeeken73 ..Mal eine vermutlich dumme Frage. Über welche Eingabemaske hast du denn den "curl" Befehl abgesetzt?

**Comment by MBeeken73** [comment]
Gibt es hierzu etwas neues?

**Comment by Jey-Cee** [comment]
Ich hab das schon lokal gefixt. Kommt irgendwann die Tage auf Github.

**Comment by MBeeken73** [comment]
Super! Vielen Dank!

**Comment by mistergyle** [comment]
habe das selbe problem - wann ist mit einem neuen release zu rechnen?
Vielen Dank!

**Comment by Jey-Cee** [comment]
@mistergyle Kann ich nicht sagen.

**Comment by Jey-Cee** [comment]
Development of verion 2 stopped, this is no longer relevant.
For more information (German) look into: https://forum.iobroker.net/topic/39627/deconz-aadapter-beta-ist-zustand-und-zukunft
