### ISSUE TITLE
Deconz crash with js-controller 3.1.6

### ISSUE THREAD

**Issue by easybeat** [Jey-Cee/ioBroker.deconz#171]
Hi

I've just update ioBroker to latest js-controller version and now deconz adapter is crashing when I active a scene on a group:

![image](https://user-images.githubusercontent.com/37217887/94339620-7ac7a580-fffb-11ea-8892-239898a83e8b.png)

I'm running deconz 2.5.82 and adapter 2.04 on an all updated ioBroker system on RasperryPi.

Kind regards

Beat

**Comment by Jey-Cee** [comment]
Did you installed deConz version 2.0.4 before updateing the js-controller and did it run properly?

**Comment by easybeat** [comment]
Yes I did...should I just reinstall it?

Am 26. September 2020 14:36:34 MESZ schrieb Jey-Cee <notifications@github.com>:

**Comment by easybeat** [comment]
![image](https://user-images.githubusercontent.com/37217887/94342085-d9e2e580-000e-11eb-8267-7816c339598b.png)

Still the same. De-Installed the adapter completely and installed it again. Crashing when activating a scene on a group.

**Comment by easybeat** [comment]
Ok very strange behaviour!! I tried on another group and this was working. So I made some changes on the group which is not working directly in deconz. And now the error does not come up anymore.

![image](https://user-images.githubusercontent.com/37217887/94342404-22030780-0011-11eb-8bac-bf491e365d9d.png)

It only happens with the led stripe which is connected to a dresden led controller!

**Comment by easybeat** [comment]
Did some more testing and it is definately only happening on Lightstrips with Dresden Controller:

![image](https://user-images.githubusercontent.com/37217887/94342866-722f9900-0014-11eb-93cf-f6d52cd78b8a.png)

I have removed them now from the group and no more errors coming up.

Does that help?

Kind regards

Beat

**Comment by easybeat** [comment]
Just realised that the length of the id of these 2 devices are shorter by 2 chars than all other devices.

![image](https://user-images.githubusercontent.com/37217887/94343271-4366f200-0017-11eb-8268-34702cfa96b7.png)

**Comment by easybeat** [comment]
No sorry not short of 2 chars. Same length but different format with all them "ffff" in.

**Comment by easybeat** [comment]
All the other states are standard like in other lights.

**Comment by Jey-Cee** [comment]
Please go to Instance Tab, activate Expert mode, change loglevel to debug and post the log (from file not from Admin panel).

**Comment by easybeat** [comment]
Hi

here is the log:

[ErrorLog_ioBroker-20200927.txt](https://github.com/iobroker-community-adapters/ioBroker.deconz/files/5287887/ErrorLog_ioBroker-20200927.txt)

Could you let me know how to get version 2.05? If I install deconz from github it is installing 2.04 but just realized that in 2.04 no Buttonevents are working and you corrected this in 2.05. Thanks.

Kind regards

Beat

**Comment by easybeat** [comment]
@Jey-Cee : Hi

Is the information ok in the log? Does it help?

Kind regards
Beat

**Comment by Jey-Cee** [comment]
Thanks for the log i didnt have a lot of time for now. I takes some time to study the log, please be patient.

**Comment by realwax** [comment]
Hi, 
I can confirm that issue. I am using fls-pp, too. I wrote my error reports an in German. 
I think it's related to the missing white channel that is representated via a separate bulb in rest api deconz. That bulb is not being created by adapter. Any scene recall or change of lights affecting this missing light(white channel) results in a crash as the adapters gets the change and dies...

See here https://github.com/iobroker-community-adapters/ioBroker.deconz/issues/175
and here https://github.com/iobroker-community-adapters/ioBroker.deconz/issues/174


Thank you!

Kind regard 

W

**Comment by easybeat** [comment]
Hi @Jey-Cee 

Any progress on this? Do you need more information?

Kind regards

Beat

**Comment by Jey-Cee** [comment]
Not on this specific topic, the adapter has to rewritten again. This takes a while.

**Comment by Jey-Cee** [comment]
Development of verion 2 stopped, this is no longer relevant.
For more information (German) look into: https://forum.iobroker.net/topic/39627/deconz-aadapter-beta-ist-zustand-und-zukunft
