### ISSUE TITLE
Friendly Names

### ISSUE THREAD

**Issue by wuast94** [Jey-Cee/ioBroker.deconz#172]
When i try to log deconz devices with influxdb my database creates a lot of tables wich is fine, but the MAC? id´s as Names isnt that nice when trying to Visualize the Data

Is there a way to change this ? 

![image](https://user-images.githubusercontent.com/16965460/94374540-46440e80-010d-11eb-8eab-cfccf6f428d2.png)

**Comment by Jey-Cee** [comment]
Nope, sorry.
