### ISSUE TITLE
Zweiter Kanal vom Inwall-Switch fehlt

### ISSUE THREAD

**Issue by DerMaulwurf** [Jey-Cee/ioBroker.deconz#173]
Hallo zusammen,

ich habe ein zweifaches Relais im Einsatz. Die Bezeichnung ist "Zemismart ZW-EU-02".
Mit der Version 1.3.7 erschienen zwei Geräte unter "Lights" und ließen sich wunderbar schalten.
Wegen anderer Gründe habe ich auf 2.0.4 aktualisiert und und nun erscheint unter "lights" leider nur noch ein Gerät mit einem Kanal.
Der zweite Kanal bleibt unsichtbar.

Unter deCONZ (2.05.81) ist das Gerät sichtbar und beide Kanäle lassen sich von dort aus schalten.
![image](https://user-images.githubusercontent.com/25935707/94545916-74306c80-024d-11eb-925e-e080183402c3.png)

Einen kurzen Steckbrief findet man hier: [https://www.zigbee2mqtt.io/devices/LXN59-2S7LX1.0.html](url)

Kann ich noch andere Infos beisteuern?

Vielen Dank und viele Grüße,
Markus

**Comment by Jey-Cee** [comment]
Die ganzen Zigbee infos helfen mir Überhaupt nicht da der Adapter nur die API auswertet.
Was hilfreich wäre sind die Websocket messages für das Gerät. Die bekommt man in dem man die Adapter Instanz auf debug stellt.

**Comment by DerMaulwurf** [comment]
das sind die Websocket-Messages für das Gerät:

`2020-10-01 00:01:03.174  - [34mdebug[39m: deconz.0 (22991) Websocket message: {"attr":{"lastannounced":"2020-09-29T08:55:02Z","lastseen":"2020-09-30T22:01Z","manufacturername":"3A Smart Home DE","modelid":"LXN59-2S7LX1.0","name":"Buero klein","swversion":null,"type":"On/Off light","uniqueid":"08:6b:d7:ff:fe:5d:96:b1-02"},"e":"changed","id":"14","r":"lights","t":"event","uniqueid":"08:6b:d7:ff:fe:5d:96:b1-02"}
`
und
`2020-10-01 00:01:09.374  - [34mdebug[39m: deconz.0 (22991) Websocket message: {"attr":{"lastannounced":"2020-09-29T08:55:02Z","lastseen":"2020-09-30T22:01Z","manufacturername":"3A Smart Home DE","modelid":"LXN59-2S7LX1.0","name":"Büro gross","swversion":null,"type":"On/Off light","uniqueid":"08:6b:d7:ff:fe:5d:96:b1-01"},"e":"changed","id":"13","r":"lights","t":"event","uniqueid":"08:6b:d7:ff:fe:5d:96:b1-01"}
`

**Comment by KTMLauni** [comment]
Guten Abend,
ich reihe mich hier mal ein - node.js 12.19.0 // npm 6.14.8
Ich habe Doppel-Schalter von Aquara im Einsatz, welche seit dem letzten update (2.0.5) ebenfalls den zweiten Kanal verloren haben. In der Phoscon-App ist alles da und läßt sich auch schalten, jedoch nicht so im ioBroker. Dort ist nur der erste Kanal schaltbar.
Wenn ich über Phoscon den zweiten Kanal schalte stürtz die Deconz-Instanz ab.
Im Anhang ist ein aktueller Log-file mit dem Vorgang  (Absturz/Neutsart)
Ich habe den zweiten Kanal jetzt erst einmal abgestellt damit das System vernünftig läuft hoffe aber auf eine baldige Lösung.
Danke und Gruß Martin

[iobroker.2020-10-08.log.html.zip](https://github.com/iobroker-community-adapters/ioBroker.deconz/files/5351142/iobroker.2020-10-08.log.html.zip)

**Comment by Jey-Cee** [comment]
Development of verion 2 stopped, this is no longer relevant.
For more information (German) look into: https://forum.iobroker.net/topic/39627/deconz-aadapter-beta-ist-zustand-und-zukunft
