### ISSUE TITLE
Weiß-Kanal von fls-pp Controller fehlt in der 2.x Version...

### ISSUE THREAD

**Issue by realwax** [Jey-Cee/ioBroker.deconz#174]
Hi, 

In der 1.x version wurde immer eine 2. Lampe für den Weißkanal angelegt. Sieh screen:

![image](https://user-images.githubusercontent.com/14924590/94844329-65e57a80-041e-11eb-93f8-ac56580cfc5d.png)

Dieser ist jetzt nicht mehr vorhanden und somit auch nicht steuerbar.

![image](https://user-images.githubusercontent.com/14924590/94844413-81e91c00-041e-11eb-85fd-91f149107282.png)

Hier direkt von der rest api: (34 wird angelegt - 35 nicht - ich habe mehrere fls-pp - überall das selbe)
34: {
"colorcapabilities": 31,
"ctmax": 500,
"ctmin": 153,
"etag": "4c4d07e9e2bd1cbfc375fec0fe2fc863",
"hascolor": true,
"lastannounced": null,
"lastseen": "2020-10-01T17:44Z",
"manufacturername": "dresden elektronik",
"modelid": "FLS-PP3",
"name": "LED Küche",
"powerup": 7,
"state": {
"alert": "none",
"bri": 158,
"colormode": "xy",
"ct": 153,
"effect": "none",
"hue": 43519,
"on": false,
"reachable": true,
"sat": 253,
"xy": [
  0.1516,
  0.0626
],
},
"swversion": "0214.201000EB",
"type": "Extended color light",
"uniqueid": "00:21:2e:ff:ff:02:f7:c2-0a"
},
35: {
"etag": "fcb71d42840a13abfba82f6836ca0b88",
"hascolor": false,
"lastannounced": null,
"lastseen": "2020-10-01T17:44Z",
"manufacturername": "dresden elektronik",
"modelid": "FLS-PP3 White",
"name": "Light 35",
"powerup": 7,
"state": {
"alert": "none",
"bri": 10,
"on": true,
"reachable": true
},
"swversion": "0214.201000EB",
"type": "Dimmable light",
"uniqueid": "00:21:2e:ff:ff:02:f7:c2-0b"
},

Ich bitte um einen fix - danke 

LG

Wolfgang

**Comment by realwax** [comment]
deconz.0 | 2020-10-01 19:55:41.522 | debug | (12756) Websocket message: {"attr":{"id":"53","lastannounced":"2020-08-22T11:45:03Z","lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Dimmable l
-- | -- | -- | --
deconz.0 | 2020-10-01 19:55:41.518 | debug | (12756) Websocket message: {"attr":{"id":"53","lastannounced":"2020-08-22T11:45:03Z","lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Dimmable l
deconz.0 | 2020-10-01 19:55:40.304 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"52","lastannounced":"2020-08-22T11:45:03Z","lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektroni
deconz.0 | 2020-10-01 19:55:40.300 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"52","lastannounced":"2020-08-22T11:45:03Z","lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektroni
deconz.0 | 2020-10-01 19:55:35.323 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"id":"7","lastannounced":"2020-09-28T14:09:46Z","lastseen":"2020-10-01T17:55Z","manufacturername":"IKEA of Sweden","m
deconz.0 | 2020-10-01 19:55:35.319 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"id":"7","lastannounced":"2020-09-28T14:09:46Z","lastseen":"2020-10-01T17:55Z","manufacturername":"IKEA of Sweden","m
deconz.0 | 2020-10-01 19:55:33.403 | debug | (12756) Websocket message: {"attr":{"id":"39","lastannounced":"2020-08-11T19:05:27Z","lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Light 39",
deconz.0 | 2020-10-01 19:55:33.399 | debug | (12756) Websocket message: {"attr":{"id":"39","lastannounced":"2020-08-11T19:05:27Z","lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Light 39",
deconz.0 | 2020-10-01 19:55:32.263 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"38","lastannounced":"2020-08-11T19:05:27Z","lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektroni
deconz.0 | 2020-10-01 19:55:32.261 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"38","lastannounced":"2020-08-11T19:05:27Z","lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektroni
deconz.0 | 2020-10-01 19:55:31.130 | debug | (12756) Websocket message: {"attr":{"id":"41","lastannounced":"2020-08-13T12:50:58Z","lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Light 41",
deconz.0 | 2020-10-01 19:55:31.126 | debug | (12756) Websocket message: {"attr":{"id":"41","lastannounced":"2020-08-13T12:50:58Z","lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Light 41",
deconz.0 | 2020-10-01 19:55:29.093 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"id":"6","lastannounced":"2020-09-29T21:21:02Z","lastseen":"2020-10-01T17:55Z","manufacturername":"IKEA of Sweden","m
deconz.0 | 2020-10-01 19:55:29.091 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"id":"6","lastannounced":"2020-09-29T21:21:02Z","lastseen":"2020-10-01T17:55Z","manufacturername":"IKEA of Sweden","m
deconz.0 | 2020-10-01 19:55:28.821 | debug | (12756) Websocket message: {"attr":{"id":"35","lastannounced":null,"lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Light 35","powerup":7,"swver
deconz.0 | 2020-10-01 19:55:28.819 | debug | (12756) Websocket message: {"attr":{"id":"35","lastannounced":null,"lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Light 35","powerup":7,"swver
deconz.0 | 2020-10-01 19:55:01.507 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"40","lastannounced":"2020-08-13T12:50:58Z","lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektroni
deconz.0 | 2020-10-01 19:55:01.504 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"40","lastannounced":"2020-08-13T12:50:58Z","lastseen":"2020-10-01T17:55Z","manufacturername":"dresden elektroni
deconz.0 | 2020-10-01 19:54:54.545 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"id":"4","lastannounced":"2020-09-28T14:09:47Z","lastseen":"2020-10-01T17:54Z","manufacturername":"IKEA of Sweden","m
deconz.0 | 2020-10-01 19:54:54.541 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"id":"4","lastannounced":"2020-09-28T14:09:47Z","lastseen":"2020-10-01T17:54Z","manufacturername":"IKEA of Sweden","m
deconz.0 | 2020-10-01 19:54:47.430 | info | (12756) Adapter is ready
deconz.0 | 2020-10-01 19:54:43.114 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"34","lastannounced":null,"lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektronik","modelid":"FLS-
deconz.0 | 2020-10-01 19:54:43.110 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"34","lastannounced":null,"lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektronik","modelid":"FLS-
deconz.0 | 2020-10-01 19:54:31.456 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"id":"3","lastannounced":"2020-10-01T00:02:59Z","lastseen":"2020-10-01T17:54Z","manufacturername":"IKEA of Sweden","m
deconz.0 | 2020-10-01 19:54:31.452 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"id":"3","lastannounced":"2020-10-01T00:02:59Z","lastseen":"2020-10-01T17:54Z","manufacturername":"IKEA of Sweden","m
deconz.0 | 2020-10-01 19:54:30.095 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"id":"5","lastannounced":"2020-09-28T15:42:50Z","lastseen":"2020-10-01T17:54Z","manufacturername":"IKEA of Sweden","m
deconz.0 | 2020-10-01 19:54:30.090 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"id":"5","lastannounced":"2020-09-28T15:42:50Z","lastseen":"2020-10-01T17:54Z","manufacturername":"IKEA of Sweden","m
deconz.0 | 2020-10-01 19:54:16.998 | debug | (12756) Websocket message: {"attr":{"id":"35","lastannounced":null,"lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Light 35","powerup":7,"swver
deconz.0 | 2020-10-01 19:54:16.995 | debug | (12756) Websocket message: {"attr":{"id":"35","lastannounced":null,"lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Light 35","powerup":7,"swver
deconz.0 | 2020-10-01 19:54:11.313 | debug | (12756) Websocket message: {"attr":{"id":"53","lastannounced":"2020-08-22T11:45:03Z","lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Dimmable l
deconz.0 | 2020-10-01 19:54:11.310 | debug | (12756) Websocket message: {"attr":{"id":"53","lastannounced":"2020-08-22T11:45:03Z","lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Dimmable l
deconz.0 | 2020-10-01 19:54:10.127 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"52","lastannounced":"2020-08-22T11:45:03Z","lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektroni
deconz.0 | 2020-10-01 19:54:10.124 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"52","lastannounced":"2020-08-22T11:45:03Z","lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektroni
deconz.0 | 2020-10-01 19:54:03.309 | debug | (12756) Websocket message: {"attr":{"id":"39","lastannounced":"2020-08-11T19:05:27Z","lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Light 39",
deconz.0 | 2020-10-01 19:54:03.305 | debug | (12756) Websocket message: {"attr":{"id":"39","lastannounced":"2020-08-11T19:05:27Z","lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Light 39",
deconz.0 | 2020-10-01 19:54:02.124 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"38","lastannounced":"2020-08-11T19:05:27Z","lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektroni
deconz.0 | 2020-10-01 19:54:02.121 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"38","lastannounced":"2020-08-11T19:05:27Z","lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektroni
deconz.0 | 2020-10-01 19:54:01.003 | debug | (12756) Websocket message: {"attr":{"id":"41","lastannounced":"2020-08-13T12:50:58Z","lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Light 41",
deconz.0 | 2020-10-01 19:54:01.000 | debug | (12756) Websocket message: {"attr":{"id":"41","lastannounced":"2020-08-13T12:50:58Z","lastseen":"2020-10-01T17:54Z","manufacturername":"dresden elektronik","modelid":"FLS-PP3 White","name":"Light 41",
deconz.0 | 2020-10-01 19:53:48.862 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"id":"2","lastannounced":"2020-09-22T13:53:19Z","lastseen":"2020-10-01T17:53Z","manufacturername":"IKEA of Sweden","m
deconz.0 | 2020-10-01 19:53:48.860 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"id":"2","lastannounced":"2020-09-22T13:53:19Z","lastseen":"2020-10-01T17:53Z","manufacturername":"IKEA of Sweden","m
deconz.0 | 2020-10-01 19:53:47.440 | debug | (12756) Subscribed to updates...
deconz.0 | 2020-10-01 19:53:47.384 | debug | (12756) Code 200: Request succeded get group attributes 57319: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"device
deconz.0 | 2020-10-01 19:53:47.354 | debug | (12756) Code 200: Request succeded get group attributes 38804: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"device
deconz.0 | 2020-10-01 19:53:47.269 | debug | (12756) Code 200: Request succeded get group attributes 34420: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"device
deconz.0 | 2020-10-01 19:53:47.188 | debug | (12756) Code 200: Request succeded get group attributes 33582: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":true,"sat":127,"scene":null,"xy":[0,0]},"devicem
deconz.0 | 2020-10-01 19:53:47.139 | debug | (12756) Code 200: Request succeded get group attributes 8518: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":true,"sat":127,"scene":null,"xy":[0,0]},"deviceme
deconz.0 | 2020-10-01 19:53:47.075 | debug | (12756) Code 200: Request succeded get group attributes 4266: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicem
deconz.0 | 2020-10-01 19:53:46.964 | debug | (12756) Code 200: Request succeded get group attributes 3861: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicem
deconz.0 | 2020-10-01 19:53:46.902 | debug | (12756) Code 200: Request succeded get group attributes 53: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemem
deconz.0 | 2020-10-01 19:53:46.854 | debug | (12756) Code 200: Request succeded get group attributes 49: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemem
deconz.0 | 2020-10-01 19:53:46.783 | debug | (12756) Code 200: Request succeded get group attributes 48: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemem
deconz.0 | 2020-10-01 19:53:46.718 | debug | (12756) Code 200: Request succeded get group attributes 47: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemem
deconz.0 | 2020-10-01 19:53:46.677 | debug | (12756) Code 200: Request succeded get group attributes 46: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemem
deconz.0 | 2020-10-01 19:53:46.642 | debug | (12756) Code 200: Request succeded get group attributes 45: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":"1","xy":[0,0]},"devicememb
deconz.0 | 2020-10-01 19:53:46.572 | debug | (12756) Code 200: Request succeded get group attributes 42: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemem
deconz.0 | 2020-10-01 19:53:46.528 | debug | (12756) Code 200: Request succeded get group attributes 39: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemem
deconz.0 | 2020-10-01 19:53:46.494 | debug | (12756) Code 200: Request succeded get group attributes 35: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemem
deconz.0 | 2020-10-01 19:53:46.456 | debug | (12756) Code 200: Request succeded get group attributes 32: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemem
deconz.0 | 2020-10-01 19:53:46.404 | debug | (12756) Code 200: Request succeded get group attributes 21: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemem
deconz.0 | 2020-10-01 19:53:46.341 | debug | (12756) Code 200: Request succeded get group attributes 14: {"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemem
deconz.0 | 2020-10-01 19:53:46.228 | debug | (12756) Code 200: Request succeded get all groups: {"14":{"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemember
deconz.0 | 2020-10-01 19:53:42.315 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"40","lastannounced":"2020-08-13T12:50:58Z","lastseen":"2020-10-01T17:53Z","manufacturername":"dresden elektroni
deconz.0 | 2020-10-01 19:53:40.819 | debug | (12756) Code 200: Request succeded get all sensors: {"1":{"config":{"configured":true,"on":true,"sunriseoffset":30,"sunsetoffset":-30},"etag":"de13e7e43a00884837fde319a7adb3ba","manufacturername":"Phi
deconz.0 | 2020-10-01 19:53:40.054 | debug | (12756) Websocket message: {"attr":{"colorcapabilities":31,"ctmax":500,"ctmin":153,"id":"34","lastannounced":null,"lastseen":"2020-10-01T17:53Z","manufacturername":"dresden elektronik","modelid":"FLS-
deconz.0 | 2020-10-01 19:53:27.197 | debug | (12756) Subscribed to updates...
deconz.0 | 2020-10-01 19:53:25.409 | debug | (12756) Code 200: Request succeded get all lights: {"1":{"colorcapabilities":16,"ctmax":454,"ctmin":250,"etag":"40d6ba7077001117ce803e5229ee6a8b","hascolor":true,"lastannounced":"2020-09-21T17:39:26Z"
deconz.0 | 2020-10-01 19:53:25.335 | info | (12756) deConz Version: 2.5.83; API version: 1.16.0
deconz.0 | 2020-10-01 19:53:25.330 | debug | (12756) Code 200: Request succeded get config: {"UTC":"2020-10-01T17:53:25","apiversion":"1.16.0","backup":{"errorcode":0,"status":"idle"},"bridgeid":"00212EFFFF03B313","datastoreversion":"93","devic
deconz.0 | 2020-10-01 19:53:25.152 | info | (12756) Please wait while adapter is starting
deconz.0 | 2020-10-01 19:53:25.110 | info | (12756) starting. Version 2.0.5 in /opt/iobroker/node_modules/iobroker.deconz, node: v12.16.3, js-controller: 3.1.6
deconz.0 | 2020-10-01 19:53:24.783 | debug | (12756) Plugin sentry Initialize Plugin (enabled=true)
deconz.0 | 2020-10-01 19:53:13.895 | info | (12278) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
deconz.0 | 2020-10-01 19:53:13.889 | info | (12278) terminating
deconz.0 | 2020-10-01 19:53:13.887 | info | (12278) cleaned everything up...
deconz.0 | 2020-10-01 19:53:13.880 | info | (12278) Got terminate signal TERMINATE_YOURSELF
deconz.0 | 2020-10-01 19:53:08.085 | info | (12278) Adapter is ready
deconz.0 | 2020-10-01 19:51:47.550 | info | (12278) deConz Version: 2.5.83; API version: 1.16.0
deconz.0 | 2020-10-01 19:51:47.370 | info | (12278) Please wait while adapter is starting
deconz.0 | 2020-10-01 19:51:47.329 | info | (12278) starting. Version 2.0.5 in /opt/iobroker/node_modules/iobroker.deconz, node: v12.16.3, js-controller: 3.1.6

**Comment by realwax** [comment]
Konkret geht es hier um die Lichter 35, 39, 41, 53 aus dem Websocket debug. Gesehen werden sie anscheinend lt. log, aber die Objekte fehlen und werden auch nicht angelegt.

Danke Dir!

**Comment by realwax** [comment]
Daher kommt auch der crash.... sobald man einen fls-pp verändert und die fehlenden Weißkanäle rückmelden.
https://github.com/iobroker-community-adapters/ioBroker.deconz/issues/175

**Comment by uha-dev** [comment]
selbes Problem bei Gledopto Controllern. Die zweiten Kanäle für weiß werden nicht angelegt und es kommt ein crash, sobald diese geschaltet werden.
Im Log stehen beide drin, hier ein Beispiel:
{"colorcapabilities":31,"ctmax":65535,"ctmin":0,"etag":"44634bea79fa16e1399a92d690cee4ac","hascolor":true,"lastannounced":"2020-09-02T20:22:32Z","lastseen":"2020-10-06T15:47Z","manufacturername":"GLEDOPTO","modelid":"GL-C-007","name":"LED Wohnzimmer Terasse rgb","state":{"alert":"none","bri":76,"colormode":"hs","ct":421,"effect":"none","hue":52736,"on":false,"reachable":true,"sat":127,"xy":[0.3596,0.2312]},"swversion":"2.0.3","type":"Extended color light","uniqueid":"00:12:4b:00:1f:b5:f1:6f-0b"},"6":{"colorcapabilities":0,"ctmax":500,"ctmin":158,"etag":"d33b3074704a69a2f693091b09aa89d4","hascolor":true,"lastannounced":"2020-09-02T20:22:32Z","lastseen":"2020-10-06T15:46Z","manufacturername":"GLEDOPTO","modelid":"GL-C-006","name":"LED Wohnzimmer Terasse weiß","state":{"alert":"none","bri":76,"colormode":"ct","ct":490,"on":false,"reachable":true},"swversion":"2.0.3","type":"Color temperature light","uniqueid":"00:12:4b:00:1f:b5:f1:6f-0f"},"7":
Falls irgendwas aus den Logs benötigt wird, einfach kurz melden.
LG Ulf

**Comment by KTMLauni** [comment]
Auch beim Aquara Double Switch fehlt im ioBroker der zweite Kanal.
In der Phoscon App ist er vorhanden und läuft.
Gruß Martin

**Comment by realwax** [comment]
> Auch beim Aquara Double Switch fehlt im ioBroker der zweite Kanal.
> In der Phoscon App ist er vorhanden und läuft.
> Gruß Martin

Hallo Martin, @KTMLauni 

Eines kannst du ggf. tun. Hänge den output der rest-api an, speziell das licht, welches fehlt bzw. die beiden devices, farb und weißkanal an. Ich denke mehr output hilft @Jey-Cee beim fixen und erkennen.

LG

Wolfgang

![image](https://user-images.githubusercontent.com/14924590/95442304-7e442080-095b-11eb-991f-690dffe4b774.png)

![image](https://user-images.githubusercontent.com/14924590/95442360-90be5a00-095b-11eb-81f2-333620b3acad.png)

**Comment by realwax** [comment]
@Jey-Cee Hey Christoph, hoffe deine anderen Projekte fressen nicht deine ganze Zeit, gibt es schon News hinsichtlich der fehlenden Objekte? DANKE & LG Wolfgang

**Comment by Jey-Cee** [comment]
Ich konnte Gesundheitlich bedingt nicht so viel machen und meine anderen Projekte fressen gerade auch mehr Zeit als mir lieb ist.
Aber durch das Sammeln von Daten sind einige Geräte Zusammen gekommen. Im nächsten schritt muss ich die Daten bereinigen und sichten. Dann kann ich Anfangen eigene Definitionen an zu legen.
Erfahrungsgemäß nimmt das nochmal einiges an Zeit in Anspruch, also dauert es noch.

**Comment by realwax** [comment]
Wenn ich gesundheitlich bedingt lese,  denke ich einfach nur Alles Gute und gut, dass du auf dich acht gibst! Danke für deine ausführliche Antwort und Arbeit.

**Comment by Jey-Cee** [comment]
Development of verion 2 stopped, this is no longer relevant.
For more information (German) look into: https://forum.iobroker.net/topic/39627/deconz-aadapter-beta-ist-zustand-und-zukunft
