### ISSUE TITLE
Geräte lassen sich nicht löschen

### ISSUE THREAD

**Issue by ipod86** [Jey-Cee/ioBroker.deconz#177]
Ich habe eben über die Phoscon Web-App ein Gerät gelöscht und neu verbunden.
Dort hat auch alles geklappt.

Im iobroker sehe ich im Deconz-Adaper aber immer noch das gelöschte Gerät.
Sowohl im Adapter als auch in den Objekten.
Auch das löschen über das Papierkorbsymbol klappt nicht.

deConz Version: 2.5.81
Adapterversion: 1.3.10

**Comment by Jey-Cee** [comment]
Das ein Gerät das in Phoscon gelöscht wurde nicht im Adapter gelöscht wird ist ganz normal.
Man muss die Objekte von Hand löschen.

**Comment by ipod86** [comment]
Warum gibt es dann den Button zum Löschen?
Sollte man den dann nicht besser entfernen, wenn diese Option nicht verfügbar ist?

**Comment by Jey-Cee** [comment]
Sie ist verfügbar das Gerät wird in deConz gelöscht. Nur die Objekte nicht.
