### ISSUE TITLE
New Sonoff SNZB-03 Motion Sensor

### ISSUE THREAD

**Issue by muehlhalde** [Jey-Cee/ioBroker.deconz#178]
Guten Abend,
im letzten deConz Update wurde der Sonoff SNZB-03 Motion Sensor hinzugefügt. 
Bei Phoscon funktioniert alles einwandfrei, in ioBroker wird er aber nicht aufgelistet.
Gehe mal davon aus, dass dieser in den Adapter noch hinzugefügt werden muss.

Dankeschön :)

**Comment by Jey-Cee** [comment]
Nein was in deConz hinzugefügt wird liest der Adapter auch aus. Einfach mal den Adapter neu starten.

**Comment by muehlhalde** [comment]
Stimmt, bisschen peinlich aber Dankeschön für die schnelle Hilfe :)
