### ISSUE TITLE
Aqara Tür- und Fenstersensoren nach Update auf 2.0.5 ohne Statusänderung

### ISSUE THREAD

**Issue by Stonelink77** [Jey-Cee/ioBroker.deconz#180]
Vorher mit Version 1.3.11 alles bestens und stabil. Nach Update auf 2.0.5 geht nichts mehr obwohl die Instanz mit alle drei Positionen auf grün geht. Es kommen keine Werte von Phoscon im ioBroker Objekt an. Ich öffne ein Fenster und es wird nun weiter als geschlossen angezeigt. Bitte prüfen und fixen

**Comment by Jey-Cee** [comment]
Bitte zurück auf die Version 1.3.11. Momentan wird nichts gefixt, der Adapter muss nochmal umgeschrieben werden.

**Comment by yoobeedoobee** [comment]
Habe keine Probleme damit, Status wird korrekt übernommen. Hatte allerdings im Rahmen der Umstellung auf Mac Adressen auch meine deconz.0 Instanz nochmals entfernt und komplett neu angelegt.

**Comment by Michaelnorge** [comment]
Ich hab das gleiche Problem.
Der Adapter legt die Objekte komplett neu an, die Benennung der Objekte ist kleingeschrieben, die "originalen" hingegen groß und können nicht mehr angesteuert werden.
Der API-Schlüssel ist nach update auch verschwunden.
Der LOG gibt an, das der Adapter "ready" ist, obwohl er auf GELB steht.

Version 1.3.11 ist in der Changelog garnicht mehr vorhanden, ein downgrade direkt also nicht möglich.

**Comment by Jey-Cee** [comment]
@Michaelnorge wechsel mal das Repositorie auf Stable.

**Comment by Jey-Cee** [comment]
Development of verion 2 stopped, this is no longer relevant.
For more information (German) look into: https://forum.iobroker.net/topic/39627/deconz-aadapter-beta-ist-zustand-und-zukunft
