### ISSUE TITLE
Deconz installation

### ISSUE THREAD

**Issue by apla2016** [Jey-Cee/ioBroker.deconz#182]
Not able to install Decons on Linux controller, here is my log:

ap@AP-Tiny:~$ sudo gpasswd -a $USER dialout
Adding user ap to group dialout

ap@AP-Tiny:~$ wget -O - http://phoscon.de/apt/deconz.pub.key | \
>            sudo apt-key add -
--2020-10-26 12:04:58--  http://phoscon.de/apt/deconz.pub.key
Resolving phoscon.de (phoscon.de)... 144.76.96.194
Connecting to phoscon.de (phoscon.de)|144.76.96.194|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1692 (1.7K) [application/octet-stream]
Saving to: ‘STDOUT’

-                    100%[======================>]   1.65K  --.-KB/s    in 0s

2020-10-26 12:04:58 (116 MB/s) - written to stdout [1692/1692]

OK

ap@AP-Tiny:~$ sudo sh -c "echo 'deb http://phoscon.de/apt/deconz \
>             $(lsb_release -cs) main' > \
>             /etc/apt/sources.list.d/deconz.list"

ap@AP-Tiny:~$ sudo apt update
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:2 http://packages.linuxmint.com tessa InRelease
Hit:3 http://packages.linuxmint.com tessa Release
Hit:4 https://deb.nodesource.com/node_12.x bionic InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:6 http://archive.canonical.com/ubuntu bionic InRelease
Ign:7 http://phoscon.de/apt/deconz tessa InRelease
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Err:9 http://phoscon.de/apt/deconz tessa Release
  404  Not Found [IP: 144.76.96.194 80]
Get:11 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Reading package lists... Done
E: _The repository 'http://phoscon.de/apt/deconz tessa Release' does not have a Relea         se file.
N: Updating from such a repository can't be done securely, and is therefore disabled          by default.
N: See apt-secure(8) manpage for repository creation and user configuration details._

ap@AP-Tiny:~$ sudo apt install deconz
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package deconz

Any idea what is going on? Thanks.

**Comment by DutchmanNL** [comment]
Please create an issue for Phoscon, this Is just the integration to ioBroker :) 
https://github.com/dresden-elektronik/phoscon-app-beta
