### ISSUE TITLE
Müller Licht Tint LED Effekte neben COLORLOOP

### ISSUE THREAD

**Issue by BigHub40** [Jey-Cee/ioBroker.deconz#183]
Hi,
super gelungen finde ich, dass man bei den Müller LED RGBs über colorloop und colorspeed diesen Effekt selber steuern kann.

Was natürlich toll wäre, wären die weiteren Effekte, die man über die TINT Fernbedienung auslösen kann. 
Nachtlicht, Romantisch, etc...

Die statischen Effekte kann man ja eigentlich mehr als Szene ansehen, daher kann man sich diese ja theoretisch auch selber als "Befehl" basteln und anwenden. 

Was jedoch nicht so ohne weitere geht sind die dynamischen Effekte, wie eben der Colorloop.
Ich finde zum Beispiel den Feuer Effekt der ein Lagerfeuer oder Kerzenflackern simuliert hilfreich. Ebenso wäre es mag cool wenn man so etwas wie diesen "Romantik" Effekt umsetzen kann, bei dem innerhalb der Rot und Pink Töne langsam "geloopt" wird.

Ideal wäre natürlich wenn man zwei Datenpunkte hätte in denen man jeweils einen Farbwert einträgt und dann bei Effekt z.B "2 Color Loop " anklicken könnte, wobei dann zwischen den beiden Farbwerten hin und her geloopt wird. Im Prinzip genau wie beim Colorloop, nur das nicht durch alle Farben sondern zwischen den beiden vordefinierten hin und her geloopt wird.

Danke und viele Grüße!
:-)

**Comment by Jey-Cee** [comment]
Da muss ich dich leider enttäuschen das liegt weit Außerhalb dessen was der Adapter kann. 
Wenn die Müller Licht lampen tatsächlich diese Effekte bereitstellt, also die Lampe und nicht die Fernbedienung, müsste das in deConz integriert werden. Dann kann das auch der Adapter.

Am besten du machst mal bei deConz ein Issue zum Thema auf.

**Comment by BigHub40** [comment]
Danke für die schnelle Antwort. Ich werds mal bei deconz probieren. Ich hatte einfach mal vermutet, das die Lampen das bereitstellen, da ansonsten die Fernbedienung doch dauernd senden würde, so lange der Effekt läuft.
Melde mich wenn ich eine Antwort von deconz bekommen habe.

**Comment by BigHub40** [comment]
Hi, die Hälfte der Features ist bereits gelöst. In dem github link oben. Könntest Du denn die bereits integrierten Effekte auch in den Dropdown mit aufnehmen?

**Comment by Jey-Cee** [comment]
Kann ich in der nächsten version machen.
