### ISSUE TITLE
deconz 2.05 Fehlermeldung im IOBroker Log "Aqara Bewegungsmelder"

### ISSUE THREAD

**Issue by cracyfloyd** [Jey-Cee/ioBroker.deconz#185]
Kann jemand helfen um irgendwie die Fehlermeldung im Log weg zu bekommen. Heraus finden woran es liegt. Die Fehlermeldung war irgendwann da. Ob es an einem Update liegt kann ich nicht sagen.
Als deconz rest api nutze ich 2.05.84. Ist aber auch mit der aktuellen beta 2.05.86. Die habe ich aber wieder deinstalliert da meine Xiaomi Vibrationssensoren mit dieser Version nicht mehr funktionieren. Ich habe auch schon mal alle Objekte gelöscht und neu einlesen lassen.

Bekomme folgendes Fehlerbild im LOG:
deconz.0 2020-10-28 07:16:36.928 error (2718) TypeError: Cannot read property 'success' of undefined
deconz.0 2020-10-28 07:16:36.912 error (2718) Error: Request failed with status code 400

Ich habe diverse Xiaomi Bewegungsmelder, Fensterkontakte, Vibrationssensoren. Philips und Ikea Lampen. Schalter von Philips, Ikea, Xiaomi im Einsatz

Ich habe herausgefunden das der Fehler kommt wenn ich einen Xiaomi Aqara Bewegungsmelder belege. Habe 2 davon und es sind beide betroffen. Anscheinend sind meine Xiaomi Mi Bewegungsmelder nicht betroffen von dem Fehlerbild.
Bei den Aqara werden zusätzlich wohl auch 2 devices angelegt mit dem Eintrag VPIR und FSM_State neben dem eigentlichen Sensor.
Bis auf dem Fehler im Log scheint der Bewegungsmelder zu funktionieren. Die States arbeiten.

**Comment by rg021927** [comment]
Gleichen issue mit aqara vibrations sensor

**Comment by rg021927** [comment]
Hab gerade auf dem raspi auf 2.5.87 aktualisiert, damit ist der issue gefixt
