### ISSUE TITLE
Adapter 2.0.5 Probleme in Verbindung mit IOT Adapter

### ISSUE THREAD

**Issue by snador1977** [Jey-Cee/ioBroker.deconz#186]
Hi, ich habe mit dem neuen Adapter 2.0.5 Probleme in Verbindung mit dem IOT Adapter. Gewünschte Objekte werden im IOT erkennt und auch in der App (Google Home) angezeigt, wenn ich jedoch das (Osram Plug) schalten möchte kommt im LOG ein 404 Error.

Ich habe versuchsweise mal eine Gruppe anlegt und diese per Automatik als Licht an den IOT Adapter übergeben. Wenn ich diese versuche in der APP zu schalten dann wird die Gruppe gelöscht und zwar so, das die Gruppe komplett weg ist, bis runter zu Phoscon und Conbee Gateway...

![screenshot](https://user-images.githubusercontent.com/45245918/97802884-c991dc00-1c46-11eb-9eb7-e040f89637ed.jpg)

**Comment by snador1977** [comment]
Schalten des Lichtes / Osram Plug - ein paar mal an und aus:

![screenshot_01](https://user-images.githubusercontent.com/45245918/97840234-f34d1080-1ce3-11eb-88db-9986739ceed0.jpg)

Und schalten der Gruppe:

![screenshot_02](https://user-images.githubusercontent.com/45245918/97840246-fb0cb500-1ce3-11eb-86ca-9e798a8ced76.jpg)

**Comment by Jey-Cee** [comment]
@snador1977 keine Ahnung was oder wie der iot Adapter funktioniert, für mich ergibt das keinen Sinn was da im Log steht.
Für mich wäre hilfreich den debug vom deconz adapter zu sehen.
