### ISSUE TITLE
Namenswechsel von ID zu MAC ab Version 2 

### ISSUE THREAD

**Issue by BigHub40** [Jey-Cee/ioBroker.deconz#187]
Hallo an alle,
mit dem Wechsel auf 2.0 haben sich die ID´s geändert. Dort stehen nun die MAC Adressen der Geräte drin. Damit ändern sich auch die Datenpunkt-IDs entsprechend.
Da man IDs nicht umbenennen kann, führt das in meinem Fall zu einem Folgeproblem in System die mit diesen Datenpunkten arbeiten. 
Ich muss also Datenpunkte in diesen Systemen neu einbinden, die alten entfernen und auch Skripte im IOBroker umschreiben, wenn diese die alten Datenpunkte nutzen.
Das ist ein enormer händischer Aufwand.

Daher habe ich dazu zwei Fragen:
1: Wird die ID Vergabe über MAC Adressen zukünftig so bleiben? Damit sich der Änderungsaufwand nicht erneut ergibt?
2: Gibt es im IOBroker eine Möglichkeit eine zweite Instanz eines Adapters auf einem anderen Versionsstand laufen zu lassen?
   Also deconz Instanz 0 auf Version 1.3
           deconz Instanz 1 auf Version 2.0
Wenn ja wie müsste man vorgehen? Vor dem Update auf 2.0 die Instanz 1 anlegen und dann nur eine Instanz updaten? 

Danke und viele Grüße!

**Comment by Jey-Cee** [comment]
Geh zurück auf die version 1.3.11 es gibt noch erhebliche Probleme mit der v2 und die Objektstruktur wird sich noch ändern.

**Comment by BigHub40** [comment]
Sollten keine Fehler auftreten muss ich nicht zurück :-) Denn bislang funktioniert alles so wie bisher. (Nachdem ich die ID Änderungen übernommen hatte)
Würde ich jetzt zurück gehen ging das Ändern von vorne los. 
Probleme wie crash etc hatte ich auch aber nachdem ich den JS controller auf die aktuelle Verison gebracht und auf meiner Synology den Marthoc deconz container auf die aktuellste Verison gebracht habe, lief alles ganz gut.

**Comment by cracyfloyd** [comment]
> Geh zurück auf die version 1.3.11 es gibt noch erhebliche Probleme mit der v2 und die Objektstruktur wird sich noch ändern.

Oh je (Objektstruktur). Bitte nicht noch einmal ändern...

**Comment by Jey-Cee** [comment]
@cracyfloyd das habe ich mir nicht ausgesucht. Aufgrund von fehlenden informationen in der Dokumentation der API wusste ich nicht das nicht nur Sensoren als mehrere Geräte ausgegeben werden. Die Folge daraus ist das die neue Struktur nicht alles Abbildet und viele Probleme mit ihren Lampen haben bzw. diese nicht Vollständig steuern können.
Leider lässt sich das nicht in der Aktuellen Struktur nicht Abbilden, weswegen ich sie ändern muss.

**Comment by thorsten26** [comment]
@Jey-Cee Danke für Deinen Tipp! ab 2.x  gibts so einige Probleme zum Beispiel dass der Hue-Wert und Sat-Wert nicht nach IOT übernommen werden können.

**Comment by cracyfloyd** [comment]
Danke erstmal für die Infos..

**Comment by Jey-Cee** [comment]
Development of verion 2 stopped, this is no longer relevant.
For more information (German) look into: https://forum.iobroker.net/topic/39627/deconz-aadapter-beta-ist-zustand-und-zukunft
