### ISSUE TITLE
Adapter bleibt gelb

### ISSUE THREAD

**Issue by xcruzix** [Jey-Cee/ioBroker.deconz#189]
Wenn ich auf meinem deconz/phoscon system die Firewall mit ssh und port 80 aktiviere, geht der Adapter zwar, aber bleibt gelb.
![image](https://user-images.githubusercontent.com/59866158/98954721-603f8200-24fe-11eb-92fd-0fe388ead88d.png)

![image](https://user-images.githubusercontent.com/59866158/98954751-67ff2680-24fe-11eb-96b8-3fc9b0c5dcf4.png)

Neustart bewirkt auch nichts. 
Sobald ich die firewall deaktivieren und den Adapter neustarte wird er grün.

Oder muss ich einen weitern Port als 80 freigeben? Die Verbindung scheint aber zu gehen.

Edit:
Das Schalten über den Adapter geht, aber er bekommt wohl keine Daten mehr von Deconz..
Wie kann ich das beheben?

**Comment by o0shojo0o** [comment]
Du muss noch den Port für die Websocket Verbindung freigeben!
ich glaube das war der Port 443.

**Comment by xcruzix** [comment]
Danke, werde ich mal versuchen. Hatte jetzt den ganzen Rechner freigegeben

**Comment by Jey-Cee** [comment]
Funktioniert es jetzt?
