### ISSUE TITLE
Question: How does "Backup" work? Where is the file stored?

### ISSUE THREAD

**Issue by MarcelMertens** [Jey-Cee/ioBroker.deconz#190]
Hi,

How does "gateway\backup" work?
I expect that a backup will be created (same as phoscon app -> gateway -> backup), but where will the backup file saved?
(Running on ubuntu).
Nothing in /opt/iobroker/backup...

Kind Regards

**Comment by Jey-Cee** [comment]
The backup is saved on the deconz host.
`~/.local/share/dresden elektronik/deCONZ`

**Comment by MarcelMertens** [comment]
Thank ou
