### ISSUE TITLE
unique-id is not unique

### ISSUE THREAD

**Issue by kneisel** [Jey-Cee/ioBroker.deconz#194]
Hello

with the change from internal numbers to unique-ids there are ambiquities, since there are devices with one mac-address but several channels. For that reason, some objects are not longer constructed and therefore can not be accessed by data-points. 
If there are only two channels, one actor (light) and one sensor there's no problem. But if there are several actors and/or sensors, only the first are considered during the construction-process of the corresponding object-tree .

Example:
Xiaomi offers a device with two switches and two sensors (Power and consumption).
In the deconz-api that looks like that:

`"lights": {
        ...
        "19": {
            "etag": "b0e30b1c47ee454d562ccce4e4e52bcf",
            "hascolor": false,
            "lastseen": "2020-12-02T12:38:44.397",
            "manufacturername": "LUMI",
            "modelid": "lumi.relay.c2acn01",
            "name": "Licht Terrasse",
            "state": {
                "alert": "none",
                "on": false,
                "reachable": true
            },
            "swversion": "09-20-2018",
            "type": "Dimmable light",
            "uniqueid": "00:15:8d:00:04:2a:c0:1f-01"
        },
        ...
        "36": {
            "etag": "90dc71465cc2d9453e789de22bcf08a4",
            "hascolor": false,
            "lastseen": "2020-12-02T12:38:14.305",
            "manufacturername": "Unknown",
            "modelid": "lumi.relay.c2acn01",
            "name": "Kabel Terrasse",
            "state": {
                "alert": "none",
                "on": true,
                "reachable": true
            },
            "swversion": "09-20-2018",
            "type": "Dimmable light",
            "uniqueid": "00:15:8d:00:04:2a:c0:1f-02"
        },
    }

    ...

    "sensors": {

        "77": {
            "config": {
                "battery": 10,
                "on": true,
                "reachable": true,
                "temperature": 1900
            },
            "ep": 1,
            "etag": "eb8c3b5fc60b9867cab8c618fab3a86e",
            "lastseen": "2020-12-02T12:38:44.397",
            "manufacturername": "LUMI",
            "modelid": "lumi.relay.c2acn01",
            "name": "Consumption 77",
            "state": {
                "consumption": 602,
                "lastupdated": "2020-12-02T12:35:04.910"
            },
            "swversion": "09-20-2018",
            "type": "ZHAConsumption",
            "uniqueid": "00:15:8d:00:04:2a:c0:1f-01-000c"
        },
        "79": {
            "config": {
                "battery": 10,
                "on": true,
                "reachable": true,
                "temperature": 1900
            },
            "ep": 1,
            "etag": "de7464043a986dfe6381708b5d9fa402",
            "lastseen": "2020-12-02T12:38:44.397",
            "manufacturername": "LUMI",
            "modelid": "lumi.relay.c2acn01",
            "name": "Power 79",
            "state": {
                "current": 0,
                "lastupdated": "2020-12-02T12:38:24.501",
                "power": -1,
                "voltage": 229
            },
            "swversion": "09-20-2018",
            "type": "ZHAPower",
            "uniqueid": "00:15:8d:00:04:2a:c0:1f-01-0b04"
        },
    }
    ...
}
...
`

The problem is e.g. in the match methode, which only takes the mac-address but not the following expression: _mac = mac.match(/..:..:..:..:..:..:..:../g);_

I could think of two possible solutions:
1. Take the complete expression as uniqueid, which would break the current unique-ids, enforcing users to rework their skipts (once again)
2. Extend the current uniqueid with channels as sub-objects - only if there are more than one channel. That would not break the currect data-points (given that the first channel is represented as it is now)

**Comment by Jey-Cee** [comment]
@kneisel thak you for your explanation, i know this already. Solution 1 is easy but causes the same problem as in version 1, more than one entry in ioBroker for one device. 
I have choosen a solution that is near your second one, but with a significant change to the whole device management in the adapter. In future versions the adapter has its own device definitions and will not longer make use of the definitions from deconz.

**Comment by kneisel** [comment]
@Jey-Cee: thank you! Seems a reasonable approach. 
... you've time till spring - I have four more Xiaomi multi-channel devices waiting to be built into the garden-illumination ;-)
... have a merry christmas time.

**Comment by Jey-Cee** [comment]
Development of verion 2 stopped, this is no longer relevant.
For more information (German) look into: https://forum.iobroker.net/topic/39627/deconz-aadapter-beta-ist-zustand-und-zukunft
