### ISSUE TITLE
new errors with deconz 2.07

### ISSUE THREAD

**Issue by realwax** [Jey-Cee/ioBroker.deconz#195]
deconz.0 | 2020-12-04 18:11:33.753 | error | (28100) Error: Request failed with status code 400
-- | -- | -- | --
deconz.0 | 2020-12-04 18:11:33.715 | error | (28100) TypeError: Cannot read property 'success' of undefined

**Comment by jannnfe** [comment]
Hello,
have errors too.

deconz.0 | 2020-12-05 22:50:14.565 | info | (8049) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
deconz.0 | 2020-12-05 22:50:14.561 | info | (8049) terminating
deconz.0 | 2020-12-05 22:50:14.432 | error | (8049) TypeError: Cannot read property 'id' of undefined at handleWSmessage (/opt/iobroker/node_modules/iobroker.deconz/main.js:2325:54) at runMicrotasks (<anonymous>) at processTicksAndRe
deconz.0 | 2020-12-05 22:50:14.430 | error | (8049) unhandled promise rejection: Cannot read property 'id' of undefined
deconz.0 | 2020-12-05 22:50:14.429 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
deconz.0 | 2020-12-05 22:50:14.372 | info | (8049) cleaned everything up...
deconz.0 | 2020-12-05 22:50:14.369 | error | (8049) TypeError: Cannot read property 'id' of undefined at handleWSmessage (/opt/iobroker/node_modules/iobroker.deconz/main.js:2325:54) at runMicrotasks (<anonymous>) at processTicksAndRe
deconz.0 | 2020-12-05 22:50:14.358 | error | (8049) unhandled promise rejection: Cannot read property 'id' of undefined
deconz.0 | 2020-12-05 22:50:14.357 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
deconz.0 | 2020-12-05 22:49:52.670 | info | (8049) deConz Version: 2.7.0; API version: 1.16.0
deconz.0 | 2020-12-05 22:49:52.480 | info | (8049) Please wait while adapter is starting
deconz.0 | 2020-12-05 22:49:52.429 | info | (8049) starting. Version 2.0.5 in /opt/iobroker/node_modules/iobroker.deconz, node: v14.15.1, js-controller: 3.1.6
deconz.0 | 2020-12-05 22:49:18.938 | info | (7452) Terminated (NO_ERROR): Without reason
deconz.0 | 2020-12-05 22:49:18.935 | info | (7452) terminating
deconz.0 | 2020-12-05 22:49:18.798 | info | (7452) cleaned everything up...
deconz.0 | 2020-12-05 22:49:18.795 | error | at WebSocket.ws.onmessage (/opt/iobroker/node_modules/iobroker.deconz/main.js:614:13)
deconz.0 | 2020-12-05 22:49:18.795 | error | at processTicksAndRejections (internal/process/task_queues.js:93:5)
deconz.0 | 2020-12-05 22:49:18.795 | error | at runMicrotasks (<anonymous>)
deconz.0 | 2020-12-05 22:49:18.795 | error | at handleWSmessage (/opt/iobroker/node_modules/iobroker.deconz/main.js:2325:54)
deconz.0 | 2020-12-05 22:49:18.795 | error | (7452) TypeError: Cannot read property 'id' of undefined
deconz.0 | 2020-12-05 22:49:18.791 | error | (7452) unhandled promise rejection: Cannot read property 'id' of undefined
deconz.0 | 2020-12-05 22:48:58.593 | info | (7452) deConz Version: 2.7.0; API version: 1.16.0
deconz.0 | 2020-12-05 22:48:58.437 | info | (7452) Please wait while adapter is starting
deconz.0 | 2020-12-05 22:48:58.392 | info | (7452) starting. Version 2.0.5 in /opt/iobroker/node_modules/iobroker.deconz, node: v14.15.1, js-controller: 3.1.6

Is there a way to fix this issues?

**Comment by Jey-Cee** [comment]
> deconz.0	2020-12-04 18:11:33.753	error	(28100) Error: Request failed with status code 400
> deconz.0	2020-12-04 18:11:33.715	error	(28100) TypeError: Cannot read property 'success' of undefined

I need more information. Can you provide a log in debug mode?

@jannnfe you can install version 2.0.6 from Github, the issue should be solved with it. But be aware it sends data about your used Zigbee devices to my server. If this is not ok for you do not install it and wait for the next version or go back to 1.3.11.
Actual there is no schedule when the next version will come.

**Comment by jannnfe** [comment]
I installed 2.0.6 but im struggling since 4 hours to figure out what's the problem. My devices connected to deCONZ are working fine (Control over Phoscon) but the devices are not updated in ioBroker and i can't really figure out what's the problem. No error log, nothing. They are not getting updated? I repaired some devices that are not reporting states to iobroker but this did not help. Do you have an idea what's wrong?

**Comment by Jey-Cee** [comment]
Seems to be a problem with deconz version >=2.05.88, it does not send updates. 
The only solution that is known downgrade to lower version.

**Comment by jannnfe** [comment]
Is there a way to validate this on my own system, so i can open a issue on deCONZ?
How to test the updates send from deCONZ? 

Btw i installed homebridge and the home bridge hue plugin and all updates are reported in this setup.

**Comment by Jey-Cee** [comment]
You can change the log level of the adapter instance to debug and see whats coming in. Go to instances, activate expert mode and change the log level.

Could be that homebridge is polling data and does not use pushnotifications.

**Comment by Mimiix** [comment]
@jannnfe @Jey-Cee The fact that Phoscon still works, means the issue is not with deCONZ. 

I'd say some stuff going into iobroker is not working properly. Having logs would be amazing here.

**Comment by PLCHome** [comment]
I had similar problems after updating deconz. I installed the client in a docker. So I can keep my usb devices apart I gave the appliances names like ttyUSB_conbee. However, the latest version of Deconz only supports ttyACM0 and ttyACM1. I have mapped the device to ttyACM0 and everything works again.

**Comment by Mimiix** [comment]
@PLCHome Unfortunately, this issue didn't had to do with your fix. Turns out there was some stuff with iobroker on later versions.
