### ISSUE TITLE
Lidl Melinare Lichterkette Farbansteuerung falsch/ Effekte

### ISSUE THREAD

**Issue by canim60** [Jey-Cee/ioBroker.deconz#196]
Hallo @Jey-Cee , habe diese [https://www.lidl.de/de/melinera-lichterkette-zigbee-smart-home/p360021](url) gekauft, habe auch aktuelle Software sowie Firmware drauf 
![grafik](https://user-images.githubusercontent.com/66805899/101226842-13327400-3696-11eb-8d1e-e462e1709f01.png)

Laut Deconz sind die Effekte sowie die Steuerung der Farben drin, wenn ich über Deconz Gui Website die Farbe ansteuere sind die zum Teils nicht richtig,falsche Farbe bzw zu hell . Effekte sollen wohl auch gehen, leider lässt sich dieses untere den Punkt Effekt nicht auswählen. 

Bist du so nett und kannst mal nach schauen?ggfs hinzufügen?

danke!

**Comment by Jey-Cee** [comment]
In Effelte kann man rein schreiben was man will und wenn die Lampe das kennt führt sie das auch aus. Die vorgegebenen Werte sind Standard und sollten alle Lampen kennen. Schreiben kannst du entweder per Script/Widget oder wenn du im Objekte Tab den Expertenmodus einschaltest und auf den Stift klickst der im Feld wert auftaucht.

Hier findest du die Bechreibung für deConz was mit dem Stripe geht.

Bei den Farben kann ich dir nicht helfen. Hab ein review gesehen wo der Stripe mit einer Hue Bridge verwendet wurde und das selbe Problem hat. Denke das liegt dann irgendwie am Stripe.

**Comment by canim60** [comment]
Kannst du mir sagen wie ich die effekte über deconz nun steuern kann?

[https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/HG06467.md](url)

leider lässt sich nichts über den effekt punkt verändern. Schreibe den Wert hinein, bekomme das als Log zurück

`

econz.0 | 2020-12-07 19:06:30.477 | warn | (3532) {"address":"/lights/11/state","description":"invalid value, rainbow, for parameter, effect","type":7}
-- | -- | -- | --
deconz.0 | 2020-12-07 19:06:06.530 | warn | (3532) {"address":"/lights/11/state","description":"invalid value, snow, for parameter, effect","type":7}

`

**Comment by Jey-Cee** [comment]
Sorry der Link ist irgendwie verloren gegeangen: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3716#issuecomment-735467996

Hier steht welche Werte wie gesetzt werden müssen. Am besten du verwendest den action Datenpunkt zur Steuerung. 
Die geschweiften Klammern am Anfang und Ende müssen weg.

Das was du verlinkt hast hat nichts mit deConz zu tun.

**Comment by canim60** [comment]
Irgendwie bin ich zu doof, verstehe was du meinst, im datenpunkt action " {"effect": "strobe"}" eingeben. Dann sollte der effekt ja kommen, habe das ganze im datenpunkt action sowie effekt ausprobiert, tut nichts..

**Comment by Jey-Cee** [comment]
Ohne die { } eingeben bei action eingeben.

**Comment by canim60** [comment]
vielen Dank für deine bemühung aber!, keine chance..., da passiert leider nichts =/. Hab aus verzweifelung den Weihnachtsbaum neu  hinzugefügt. Bin schon bei Version 2.07.01

![grafik](https://user-images.githubusercontent.com/66805899/102277362-7212ab80-3f28-11eb-98b6-a6e984ce644f.png)

**Comment by Jey-Cee** [comment]
Wenn ich das richtig verstehe ist effect speed und effect colours nicht optional. Die musst du also zusammen mit effect setzen.

**Comment by canim60** [comment]
Ich will eigentlich nur die Effekte über Vis wechseln können, gibts dane andere leichte lösung?`, der Controller ist unterm Tannebaum, mühselig dran zu kommen jedes mal.

**Comment by Jey-Cee** [comment]
Dann musst du dir ein Skript bauen und ein Objekte anlegen das du von vis aus steuern kannst, auf das dein Skript reagiert.

**Comment by canim60** [comment]
Das Visualisieren ist kein Problem, das Problem bei mir liegt immernoch einen Effekt über den Iobroker/Deconz  zu schicken, wie oben erwähnt gebe ich die effekte ein und es passiert nichts =/.
