### ISSUE TITLE
Status-Change: Delay-Time

### ISSUE THREAD

**Issue by allgrinder** [Jey-Cee/ioBroker.deconz#197]
Hey,

ich verwende einen Aqara Bewegungsmelder. Dieser zeigt zuverlässig eine Anwesenheit in der Phoscon-App an.
Wird eine Bewegung erfasst updatet sich der Status auf True im iobroker innerhalb weniger Sekunden. Gleichwohl verändert sich der Status in False erst nach zwei Minuten. In der Phoscon-App passiert das gefühlt nach 15 Sekunden.

Viele Grüße
Allgrinder

**Comment by Jey-Cee** [comment]
Mit diesen Infos kann ich bestenfalls sagen: "Was soll ich jetzt machen?"

Damit ich Helfen kann brauch ich...
- Adapter Version
- deConz Version
- logs (debug)

**Comment by allgrinder** [comment]
Entschuldigung!

Der Bewegungsmelder Garderobe (HUE) steuert eine Lampe Garderobe 1/1 (HUE)

Anbei die gewünschten Informationen:
Adapter: 2.0.5
deConz Version: 2.05.79 / 22.5.2020
deConz Firmware: 26580700


[iobroker.2020-12.log](https://github.com/iobroker-community-adapters/ioBroker.deconz/files/5648711/iobroker.2020-12.log)
Es handelt sich bei dem Log um eine HTML-Datei... wusste nicht wie ich am besten den Log runterlade
Danke!

**Comment by allgrinder** [comment]
Das Problem kann geschlossen werden. Es klappt wieder.. habe das drei resets durchgeführt
