### ISSUE TITLE
Power Strip 10A/16A EU/US/UK/AU/JP/UN not recognized completly in the adapter

### ISSUE THREAD

**Issue by shodan65** [Jey-Cee/ioBroker.deconz#198]
The power strip https://zigbee.blakadder.com/Xenon_SM-SO306.html is not recognized completly by the iobroker adapter.

The power strip is show as a device with 5 entities in the Phoscon App and also in HASS
1 entitie to toggle the USB ports and 4 entities to toggle the plugs. The conbee recognition is fine and also HASS as a reference is 
able to control all 5 entities.

In ioBroker the entities are shown in the groups section as part of a group (lights 12 .. 17). However, in the lights section I can only find a single entity related to power strip controlling the 1st plug. In total I can see 12 entities in the light section

Br Martin

**Comment by Jey-Cee** [comment]
You haven't used the Bug report template while relevant information are missing, next time i close issues without this information.

deConz version: ?
Adapter version: ?

**Comment by shodan65** [comment]
Sorry

deconz:
Commercial Version -  2.06.00
Build with Qt 5.5.1
Node limit 200 (max. 200)
Commit f249dccaaa48918ccb9771b66b3a220814aeea72

Adapter: 2.0.5

ConBee 2 
Version: 2.06.00 / 15.11.2020 
Version Firmware: 26660700

**Comment by shodan65** [comment]
I use the docker container on a synology to run dconz

**Comment by Jey-Cee** [comment]
Development of version 2 stopped, this is no longer relevant.
For more information (German) look into: https://forum.iobroker.net/topic/39627/deconz-aadapter-beta-ist-zustand-und-zukunft
