### ISSUE TITLE
Performance Probleme beim Verwenden von Gruppen/Actions

### ISSUE THREAD

**Issue by japapu** [Jey-Cee/ioBroker.deconz#199]
Hi,

ich nutze seit kurzem den deconz Adapter in Verbindung mit dem Conbee Stick II.

Leider habe ich Probleme beim Verwenden des Adapters:
Ich habe habe 5 Gruppen ausgewählt mit insgesamt 23 Philips Hue Lampen.
Wenn ich nun über ein Script die Datenpunkte Actions jeder Gruppe anpasse, werden die ersten 2-3 Gruppen übernommen, die restlichen Gruppen werden jedoch scheinbar ignoriert.
Wenn ich jede Gruppe mit einem Delay von ca. 1 Sekunde anspreche, klappt alles wunderbar.

Gibt es hier noch Limitierungen? Ich hatte gehofft, dass ich mit dem Stick die Hue Bridge ersetzen kann und performance mäßig etwas gewinne.

Gruß Jan

**Comment by Jey-Cee** [comment]
Hi Jan,

du kannst nicht so viele Befehle auf einmal an deConz schicken, ich hab noch nie Untersucht wo genau der Flaschenhals sitzt. Aber das Problem tritt auch nur auf wenn man innerhalb weniger ms mehrere Befehle gleichzeitig schickt.

Idealerweise machst du eine Gruppe aus all diesen Lampen, dann muss auch der Stick nur einmal einen Befehl senden, was den Funkverkehr reduziert. 
Wenn das nicht geht musst du zwischen den Befehlen ein delay einbauen, 50ms könnten schon ausreichen, aber 250ms sollten das Maximum sein. Außer deConz und ioBroker sind per WLAN verbunden.
