### ISSUE TITLE
How to find deCONZ (on Raspi) in iobroker (on Synology docker)?

### ISSUE THREAD

**Issue by 7wells** [Jey-Cee/ioBroker.deconz#200]
Hello!

I run deCONZ on a Raspberry Pi 2 with phoscon as GUI and all works well. Now I installed iobroker in a Synology docker, but do not know if/how to find deCONZ in iobroker. I understood that there should be a deCONZ adapter, but when I search, nothing is found on my local LAN (despite PC, Raspberry Pi 2, and Synology are on the same subnet). I even unlocked the deCONZ/phoscon gateway "to allow 3rd party apps to register themself to the gateway", but that did not help either.

Am I maybe misunderstanding something completely? Thank you so much for sharing your experience and help.

**Comment by Jey-Cee** [comment]
Please show me your adapter configuration.

**Comment by bortim** [comment]
Hello @7wells ,
you open the configuration-page in iobroker (adapterz -> deconz) and use the IP of your Raspberry Pi 2 and the port of the gateway. In parallel you activate the 3rd party app registration in your phoscon.
Regards

**Comment by 7wells** [comment]
Thanks, guys for replying. Please accept my apologies that I did not provide more information. It is because meanwhile I have given up, i.e. I just use it as before (without iobroker or docker).
