### ISSUE TITLE
Frage: Helligkeitswert & Farbtemperatur einstellen ohne Lampe anzuschalten

### ISSUE THREAD

**Issue by iobFan** [Jey-Cee/ioBroker.deconz#202]
Hallo,
ich habe eher eine Frage anstelle eines Bugs. Ggf. ist es auch ein Feature Request?

Ich habe in ioBroker ein Skript geschrieben, welches jede Stunde einen anderen Wert für die Variable "Helligkeit" und "Farbtemperatur" setzt. 

Jetzt will ich jede Stunde all meine Lampen auf diese Werte einstellen. Die Lampen sollen dabei allerdings nicht nicht automatisch angehen, sondern nur auf diese Werte gesetzt werden. Wenn mein Bewegungsmelder um 10 Uhr reagiert, sollen meine Lampen z.B. mit 40% Helligkeit angehen und um 13 Uhr mit 80% Helligkeit.. 

Sobald das Skript die Helligkeitswerte für die Lampen setzt, gehen diese jedoch direkt an, obwohl ich nicht auf den Wert on=true steuere..

Könnt ihr mir sagen, wie ich den Helligkeitswert und Farbtemperatur einer Lampe umstelle, ohne dass die Lampe angeht?

Vielen lieben Dank vorab.

**Comment by Jey-Cee** [comment]
Die Änderungen werden immer direkt an die Lampe geschickt. Ist die Lampe aus nimmt sie die Änderung nicht an.
Setzt du später on auf true wird der vorherige Wert genommen. 

Du musst also deine Lampe nachdem einschalten mit den von dir Gewünschten Werten steuern.
Aber noch besser ist gleich alles auf einmal per action Datenpunkt zu senden.

**Comment by iobFan** [comment]
Cool, vielen Dank @Jey-Cee :) Das hilft mir enorm weiter! Hast du ggf. noch eine Anleitung/Seite, wo beschrieben wird, wie ich den Action Wert steuern kann?

Ich möchte eigentlich nur Level + CT steuern. 

Danke dir!

**Comment by Jey-Cee** [comment]
https://github.com/iobroker-community-adapters/ioBroker.deconz#mehr-als-einen-befehl-senden

**Comment by iobFan** [comment]
@Jey-Cee : Wenn ich eine Action wie folgt schicke --> "level": 90, "ct": 300  dann verändert sich nur die Color-Temperature. Das Level verändert sich nicht. mache ich etwas falsch?

**Comment by Pittini** [comment]
Speicher doch einfach Deine Helligkeit und Ct in ner Variable zwischen und setz die Werte dann wenn tatsächlich eingeschaltet wird. Hatte das gleiche Problem beim LightControl Skript: https://github.com/Pittini/iobroker-LightControl

**Comment by iobFan** [comment]
Hi @Pittini :-) Das mache ich gerade. Jetzt würde ich nur noch gerne Action verwenden anstatt zweimal einen Steuerungs-Befehl abzusetzen. Nur klappt Action noch nicht so richtig.

**Comment by iobFan** [comment]
@Jey-Cee : Ich bekomme bei level folgendes Warning: 

deconz.0 | 2020-12-21 13:44:29.310 | warn | (11032) {"address":"/lights/6/state","description":"parameter, level, not available","type":6}
-- | -- | -- | --


![image](https://user-images.githubusercontent.com/74504938/102778388-c5568500-4392-11eb-9c30-d3c49e69f2ea.png)

**Comment by iobFan** [comment]
Ok ich habe gerade gesehen, dass ich noch auf Version 1.3.11 bin (stable). Vermutlich funktioniert das erst mit einer höheren Version? Ich würde dann mal auf Latest "2.0.5" gehen.

**Comment by iobFan** [comment]
Ok, kann geschlossen werden. Ich sende nun ein Action Datenpunkt mit: "bri": $wert, "ct": $wert

level gibt es nicht.
