### ISSUE TITLE
Blitzwolf BW-SHP13 Datenpunkt Strommessung

### ISSUE THREAD

**Issue by canim60** [Jey-Cee/ioBroker.deconz#203]
Hallo, hab über deconz Web die Steckdose hinzugefügt, kann den Smart-Plug ein und ausschalten, mich interessiert aber der Datenpunkt Strommessung, leider taucht der nicht auf in Iobroker Deconz adapter,gibts da ne möglichkeit das zu bekommen`?
Oder muss das über was anderes realisiert werden?

![grafik](https://user-images.githubusercontent.com/66805899/102890956-a3760480-445d-11eb-94e7-402d4e08169e.png)

**Comment by Jey-Cee** [comment]
Schau mal unter Sensoren nach, kann aber sein das es mit der V2.x gar nicht geht.

**Comment by canim60** [comment]
Danke fürs feedback, taucht unter sensoren nicht auf , hab auch die V2 installiert,wird da was in Zukunft was geben?

**Comment by Jey-Cee** [comment]
Nein die Entwicklung der v2 habe ich eingestellt. Mit v3 wird es was geben.

**Comment by canim60** [comment]
Super danke! Ich warte dann drauf, gibts aktuell ne andere möglichkeit die Daten zu sniffen?

**Comment by Jey-Cee** [comment]
Mit Node-Red könnte es gehen, aber das hab ich noch nie genutzt.

**Comment by canim60** [comment]
ok, da hab ich keine erfahrung mit =/
