### ISSUE TITLE
Adapter crasht bei Schalten einer Gruppe

### ISSUE THREAD

**Issue by Schmakus** [Jey-Cee/ioBroker.deconz#204]
**Describe the bug**  
Der Adapter Crash und startet neu, immer wenn eine bestimmte Gruppe in Phoscon direkt oder über den Adapter geschaltet wird. (in meinem Beispiel mache ich das über Level 0-100).
Es betrifft nur diese eine Gruppe.

Logfile von ioBroker im Anhang.

Adapter v2.0.4
deconz Version 2.07.01 / 8.12.2020
Firmware 26680700
node.js v12.20.0

[Log_deconz_crash.txt](https://github.com/iobroker-community-adapters/ioBroker.deconz/files/5738968/Log_deconz_crash.txt)
<img width="1375" alt="Bildschirmfoto 2020-12-24 um 10 16 12" src="https://user-images.githubusercontent.com/8231359/103077936-12279f00-45d1-11eb-9529-38d9b69b35de.png">

io

**Comment by Jey-Cee** [comment]
Hallo Schmakus, 
dieses Problem habe ich schon behoben, mehr oder weniger, dazu musst du den Adapter von Github installieren. 
Wichtige Info: die Version von Github überträgt informationen über die von dir verwendeten Geräte an meinen Server.

Eine neue Version wird es soch schnell nicht geben weil ich die Entwicklung der v2 Eingestellt habe. 
Als Alternative kannst du Zurück auf die v1.3.11 gehen.
