### ISSUE TITLE
Fyrtur stops working on reconnect

### ISSUE THREAD

**Issue by mzander** [Jey-Cee/ioBroker.deconz#205]
**Describe the bug**  
Hi all,

I am running 2 fyrtur and it is working good.
But if the connection get lost and fyrtur reconnects (e.g. unplug the repeater to which they are connected) they stop working. The blinds cannot be controlled either in iobroker nor the gui of deconz itself.

Does anybody solve this?

There are 2 things that helps in 100% of the cases.
1. remove the battery, wait 5 seconds and add it again
2. pair them again

**To Reproduce**  
1. bind blinds as usual
2. unplug the device to which the blind is connected

**Expected behavior**  
blinds work as usual

**Versions:**  
 - Adapter version: 1.3.11
- deConz version: 2.08.00
 - JS-Controller version: 3.1.16
 - Node version: v12.20.0
 - Operating system: raspbian

**Comment by duffbeer2000** [comment]
If something don't work in deconz anymore, how should the adapter fix it? That's a bug in deconz so you should close this one and open one in the deconz repo.
