### ISSUE TITLE
Adapter startet bei Statusänderung neu

### ISSUE THREAD

**Issue by kevin1706** [Jey-Cee/ioBroker.deconz#206]
Hallo Zusammen,

aktuell habe ich Phoscon Version 2.5.77 und Deconz Adapter in Version 2.05 installiert. Die Zigbee Geräte sind über Phoscon mit dem Conbee II verbunden. 
Ich habe das Problem das beim Ausschalten einer Gruppe im IOBroker, die in Phoscon angelegt wurde, der Deconz adapter neu startet. Anbei das Log.
Hat jemand eine Idee was das Problem sein kann?

![2020-12-27_20h42_59](https://user-images.githubusercontent.com/76663501/103178678-30b5c080-4885-11eb-90d5-85d689c7211d.png)

**Comment by bortim** [comment]
Zur Analyse könnte es hilfreich sein, die Kommunikation von Phoscon -> Deconz zu kennen.
Könntest du dich mit einem html-javascript-Websocket-Reader direkt auf die Schnittstelle verbinden und das Event, das beim Ausschalten versendet wird, bereitstellen?
