### ISSUE TITLE
Connection datapoint is always false

### ISSUE THREAD

**Issue by MC-1984** [Jey-Cee/ioBroker.deconz#207]
**Describe the bug**  
I am not sure if it is a bug in the deconz adapter but I guess so because everything else works as expected.
I am monitoring the deconz.0.info.connection datapoint to get an info if there is a problem with the adapter. The datapoint is shown as true in objects. I can not reproduce this with any other datapoint.

The output of 
![image](https://user-images.githubusercontent.com/58948938/103369522-a494da80-4aca-11eb-88a5-e355fd876d04.png)
always is false.

**Versions:**  
 - Adapter version: 2.06
- deConz version: 2.5.84
 - JS-Controller version: 3.1.6
 - Node version: 14.15.3
 - Operating system: Raspian

**Comment by bortim** [comment]
Can you add a script-view of your blockly-Script, please?

Can you set the debug level in you deconz?
I found in the main.js, that 'info.connection' is set to "true" if 'Subscribed to updates...' occures in the log.

Log Message | state of 'info.connection'
------------ | -------------
Could not connect to websocket instance of deConz/Phoscon. | false
Subscribed to updates... | true
onUnload (function)| false

Maybe you can find the "subscribed to updates..." entry.
This can be an indicator that the value should have changed to true.

Further I can find some lines, where it is set to false again.
But this looks like a komplex condition for the reset.
```
        if (!id || !state || state.ack) {
            if (dp === 'alive') {
                if (state === null) {
                    this.setState(id, {val: false, ack: true});
                    if (ws !== null) {
                        ws.terminate();
                        this.setState('info.connection', {val: false, ack: true});
                    }
```
