### ISSUE TITLE
Feature request: Configuration option to circumvent restAPI error of not updating hue/sat values correctly

### ISSUE THREAD

**Issue by asgothian** [Jey-Cee/ioBroker.deconz#21]
The restAPI does not seem to work properly when setting hue and sat values. It changes the color of the light, but does not update the hue and saturation datapoints.

It may be an option to generate extra datapoints "convertedHue" and "convertedSat" which are driven by either the ct value, if the light is in "ct" mode, or the xy value, if the light is in "xy" mode. Internally, the idea is to generate a message to the restAPI changing the xy value to one calculated from convertedHue and convertedSat if these datapoints are changed in ioBroker, and in return populate these datapoints with hue/sat values calculated from either the color temperature or the xy coordinates reported by the restAPI.

Generation and use of these datapoints could be configurable in the plugin, and would only apply to lights which report color present.

**Comment by Jey-Cee** [comment]
This is not a solution, the color space xy has 3 datapoints. The third is Y, so the result is a xyY color space, deConz has no Y because it is known as sat.

The other thing is i dont know how to calculate xyY. 
I saw you have opened a issue at deConz rest API, i hope they will fix it.

**Comment by asgothian** [comment]
I have been digging deeper into the color conversion, and might have found one. The xy is actually a xyB model, where B is the brightness, so xy and hs should have a 1:1 conversion function, which unfortunately depends on the color gamut of the attached lamp. That said - i agree, this would not be a solution, just a workaround.
