### ISSUE TITLE
transitiontime in action is not set im seconds, needs to be multiplied with 1000 to work

### ISSUE THREAD

**Issue by manoloxxl** [Jey-Cee/ioBroker.deconz#226]
**Describe the bug**  
When using the datapoint "transitiontime" the value is in seconds.
When using same value in action its needed to multiple the value by 1000 to get the same result

**To Reproduce**  
set a lamp (i use ikea E27 bulb) by using the datapoints to
* transitiontime: 300
* bri: 200
> The Lamp is on bri 200 in 5 Minutes

Try to do it same way with action with:
"on": true, "transitiontime": 300, "bri": 200, 
The lamp is at bri 200 after 30 seconds.

When using "on": true, "transitiontime": **3000**, "bri": 200, 
It's working like wanted.

**Versions:**  
 - Adapter version: 1.3.11
- deConz version: 2.09.03 / 23.12.2020
 - JS-Controller version:  3.2.16
 - Node version:  v12.21.0
 - Operating system: Docker-Image

**Comment by manoloxxl** [comment]
So, this is know issue that is not written somewhere?

**Comment by Jey-Cee** [comment]
This is not an issue, because the action datapoint sends raw data to the API. The API expects ms.

**Comment by manoloxxl** [comment]
Thanks! Just saw the difference and reported it 👍
Maybe something for the documentation.
