### ISSUE TITLE
What to do with this warning: "...bri, is not modifiable"

### ISSUE THREAD

**Issue by MichaelSchaaf999** [Jey-Cee/ioBroker.deconz#227]
The log says:
(17304) {"address":"/lights/43/state","description":"parameter, bri, is not modifiable. Device is set to off.","type":201}

What can I do to please avoid this? 

And by the way: Just read the comment about 2.x.x - my version is:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/53481090/114830911-09034d80-9dcd-11eb-9f0c-c93b4f87baf3.png">

So this is the wrong adapter version?
If so: What must I do to replace it with the correct version, what about my datapoint and scripts and scenes?

**Comment by Jey-Cee** [comment]
The message is not that clear but it says what xou need to know: The devive is off, so can not modify bri. 
Turn it on and than change the bri value.

> So this is the wrong adapter version?
Can not say if it is the false version. In your screenshot i can only see the version of deConz.

**Comment by MichaelSchaaf999** [comment]
Dear,
well, yes: It seems to be as simple as it is...   modification of parameters only possible if the device is on. Not vice versa.
Means: My scene turned the device of and then it set the level.
Fixed now - thanks a lot!
