### ISSUE TITLE
Aqara Motion Sensor - Last Seen is missing

### ISSUE THREAD

**Issue by jkbiz** [Jey-Cee/ioBroker.deconz#228]
![iobroker](https://user-images.githubusercontent.com/82655374/115021683-91145080-9ebc-11eb-8fc0-d75fdcce4431.png)
Hello all,

I'm using the latest deConz Version: 2.10.4 Adapter (API Version: 1.16.0) on ioBroker.admin 4.2.1 with Node.js: v12.22.1 and
NPM: 6.14.12
The deCONZ software is running on v2.10.4

Over the RestApi from the deconz website I get this informations:

{"config":{"battery":100,"duration":90,"on":true,"reachable":true,"temperature":2500},"ep":1,"etag":"67b17b6832fa53f300a0999f22d5e5f8","lastseen":"2021-04-16T10:59Z","manufacturername":"LUMI","modelid":"lumi.sensor_motion.aq2","name":"Bewegungsmelder WZ","state":{"lastupdated":"2021-04-16T10:59:20.912","presence":false},"swversion":"20170627","type":"ZHAPresence","uniqueid":"00:15:8d:00:05:72:86:e7-01-0406"}

{"config":{"battery":100,"on":true,"reachable":true,"temperature":2500,"tholddark":12000,"tholdoffset":7000},"ep":1,"etag":"c16aba69aa7c6fcbdfbd7272d3b78a07","**lastseen":"2021-04-16T11:54Z"**,"manufacturername":"LUMI","modelid":"lumi.sensor_motion.aq2","name":"Bewegungsmelder WZ","state":{"dark":false,"daylight":true,"lastupdated":"2021-04-16T11:54:20.243","lightlevel":23803,"lux":240},"swversion":"20170627","type":"ZHALightLevel","uniqueid":"00:15:8d:00:05:72:86:e7-01-0400"}

I am missing the "lastseen" value in the ioBroker deconz Adapter. The value is set, when a motion is deteced.

**Comment by Jey-Cee** [comment]
Last seen is a newer attribute and not included in the adapter. 
The last seen attribute is only a info when the last message was received from the device. 
What you are looking for ist the lastupdated state.

**Comment by jkbiz** [comment]
What you mean ist the Lastupdated value
