### ISSUE TITLE
TS0121 Blitzwolf Smart Plug (BW-SHP13)

### ISSUE THREAD

**Issue by amnesia106** [Jey-Cee/ioBroker.deconz#229]
Hi, 
ich habe einen Blitzwolf Smart Plug (bekannt als BW-SHP13), welcher in Deconz einwandfrei erkannt und dargestellt wird. (Smartplug mit Leistungsmessung)
Im iobroker wird er als Schalter erkannt und lässt sich auch über den deconz Adapter steuern, jedoch werden die Leistungswerte in dem Ordner "sensors" nicht dargestellt.
![222t](https://user-images.githubusercontent.com/40226796/115877872-35137400-a448-11eb-87fb-29d81f7479c4.JPG)
![333t](https://user-images.githubusercontent.com/40226796/115877879-3644a100-a448-11eb-895a-4592966db02b.JPG)

**Comment by Jey-Cee** [comment]
Sicher wieder das alte Leid, du hast bestimmt Geräte gelöscht?
Neu angelernte Geräte bekommen frei gewordenen IDs zugewiesen aber die API gibt die dann nicht aus.
Da kann Adapterseitig nichts gemacht werden.

**Comment by amnesia106** [comment]
gibts dazu nen Workaround?

**Comment by Jey-Cee** [comment]
Ich kenne keinen.
