### ISSUE TITLE
Fehler nach Update auf JS Controller 3.3.X

### ISSUE THREAD

**Issue by msiemers** [Jey-Cee/ioBroker.deconz#230]
Ich bekomme folgende LOG Einträge nach dem Update auf den JS Controller 3.3.X:

deconz.0 | 2021-05-01 08:02:07.150 | warn | (2377446) Object of state "deconz.0.info.connection" is missing the required property "common.type"
-- | -- | -- | --

Andere Adapter haben auch dieses Problem, was muss hier getan werden, damit die Fehlermeldungen nicht mehr erscheinen?

**Comment by Jey-Cee** [comment]
Du hast schon getan was zu tun ist: Einen Fehler beim Adapter melden.

**Comment by Jey-Cee** [comment]
Aktualisiserte version ist als Beta verfügbar. Bitte Testen.
WICHTIG: Die Objekte müssen neu angelegt werden.

**Comment by msiemers** [comment]
@Jey-Cee 

Das Update funktioniert be mir nicht bzw. Lässt es sich nicht installieren.

**Comment by Jey-Cee** [comment]
@msiemers #234

**Comment by msiemers** [comment]
@Jey-Cee - Funktioniert leider nicht. er macht ein Menge aber das Update wird weiterhin angezeigt.

**Comment by Jey-Cee** [comment]
Ignoriere es einfach.
