### ISSUE TITLE
Update not working?

### ISSUE THREAD

**Issue by MichaelSchaaf999** [Jey-Cee/ioBroker.deconz#232]
Update is running smoothly...
<img width="721" alt="image" src="https://user-images.githubusercontent.com/53481090/116974233-191c9780-acbe-11eb-9b7a-37a3a44f65c7.png">

BUT the result is this:
<img width="284" alt="image" src="https://user-images.githubusercontent.com/53481090/116974300-38b3c000-acbe-11eb-926a-f28bbaea7c84.png">

**Comment by Michaelnorge** [comment]
Same here.

**Comment by Jey-Cee** [comment]
Nur die Versions Anzeige in ioBroker ist nicht korrekt. Sonst passt alles.

**Comment by Brainbug01** [comment]
Gibt's dazu dann ein Update? Damit der Adapter nicht immer als Update angezeigt wird?
