### ISSUE TITLE
No Instance after downgrade vom 2.05 to 1.3.15

### ISSUE THREAD

**Issue by ausbremen** [Jey-Cee/ioBroker.deconz#243]
What I did:
Unfortunately I installed 2.05 beta...it worked quite well for a while, but since yesterday it was stopped after several restarts. I read, that the beta isn't supportet any more, so I decided to go back to 1.3.15.

The adapter was stopped and I deleted the object tree manually. After that I deleted the instance and installed 1.3.15 with expert Modus. The installation went through, I can see the adapter in my installed adapters, but there is no instance. In objects, there is only the deconz directory with the sub directory Admin. 

What can I do? Thanx!

**Comment by Jey-Cee** [comment]
You have to add the Instance manually. Go to Adapter Tab hit the 3 points on the adapter card and then the plus.
