### ISSUE TITLE
NEO-Alarm-Sirene (TUYA): volume and melody are not working

### ISSUE THREAD

**Issue by nukleuz80** [Jey-Cee/ioBroker.deconz#246]
Hi Jey-Cee,

i have some problems with two controllable datapoints in ioBroker with a new device.
When i try the API directly to set the values it works fine but not in ioBroker (datapoints).

![image](https://user-images.githubusercontent.com/43496030/121249498-f07f5300-c8a4-11eb-8f6b-d0300643400a.png)

![image](https://user-images.githubusercontent.com/43496030/121249612-10167b80-c8a5-11eb-9973-bbdc5ae61335.png)

 If i put the values directly to the API only the melody DP is changing not the volume DP.
I can´t set the values over the DP in ioBroker.

Can you please have a look to it?

Thanks

Here the debug-log from ioBroker:

[deconz-debug-log.txt](https://github.com/iobroker-community-adapters/ioBroker.deconz/files/6619351/deconz-debug-log.txt)

**Comment by Jey-Cee** [comment]
Hi @nukleuz80,
you have to set th command via action dp. See here: https://github.com/iobroker-community-adapters/ioBroker.deconz#send-more-than-one-command-at-the-same-time

**Comment by nukleuz80** [comment]
Hi @Jey-Cee,

danke für die Info, aber es will nicht funktionieren, wenn ich den action-DP setze mit volume und melody.

Ich zeige dir mal die Datenpunkte der Sensoren und des Lichts.
Beim Licht habe ich lediglich den Datenpunkt: **action**

![grafik](https://user-images.githubusercontent.com/43496030/121353611-549a2980-c92e-11eb-99e5-35b6712e8093.png)


Gesteuert werden müssten aber die DP´s im Sensor:

![grafik](https://user-images.githubusercontent.com/43496030/121353506-3c2a0f00-c92e-11eb-839a-5c84d4566da8.png)


Damit die Sirene auslöst, muss im Licht der alert-DP auf "**lselect**" gesetzt werden.

Hast du noch nen Tip oder mache ich was falsch?

Danke!

**Comment by nukleuz80** [comment]
Nabend,

wenn ich über die API direkt Werte ändere wie hier zu sehen:
![image](https://user-images.githubusercontent.com/43496030/121432994-addc7a00-c97b-11eb-98c4-0fbb7681ed77.png)

Dann werden mir diese in den Datenpunkten angezeigt - auch das Volume bleibt für 2-3 Sekunden auf 30 - springt dann aber zurück auf 2:
![image](https://user-images.githubusercontent.com/43496030/121433175-ed0acb00-c97b-11eb-86c5-8391da16a8ff.png)

Für Hilfe oder Erklärung wäre ich sehr dankbar :)

PS: Auch die richtige Nutzung des Action-DP bekomme ich nicht hin :(

**Comment by Jey-Cee** [comment]
Der Action DP bezieht sich nur auf die Lampe und hat gar nichts mit dem Sensor Teil zu tun. Deshalb kannst du damit nichts steuern was im Sensor Teil steuerbar ist.



> Dann werden mir diese in den Datenpunkten angezeigt - auch das Volume bleibt für 2-3 Sekunden auf 30 - springt dann aber zurück auf 2:

Löst die Sirene denn Überhaupt aus wenn du sie per API steuerst?
Wenn die Werte in ioBroker angezeigt werden und dann wieder zurück Springen kommt das Wahrscheinlich direkt von deConz, das kannst du in den Logs sehen wenn du das Log level für die Instanz auf debug stellst.

**Comment by nukleuz80** [comment]
Moin,

danke für deine Erklärungen.
Ja, ich kann über das Licht und dem DP alert:lselect den Alarm erfolgreich auslösen.

Habe mir schon gedacht, dass die Einstellungen sich nicht übers Licht steuern lassen.

Gibt es denn eine Möglichkeit die config des Sensor 11 in ioBroker sichtbar zu machen, so dass man die Werte wie im Screenshot API zu sehen sind ändern kann? 

Danke und Grüße 

Edit: Momentan behelfe ich mir mit diesem Curl Aufruf - Klasse wäre es doch in dem Sensor 11 einen weiteren Ordner config zu haben mit den zu setzenden Werten/Datenpunkten:

```
curl "http://192.168.0.80/api/4BD6A5097D/sensors/11/config" \
        -X PUT \
        -H 'Content-Type: application/json; charset=utf-8' \
        -d '{"volume":2,"duration":30,"melody":2}'
```

oder einem Action DP in dem man dann den JSON String eintragen kann... 🤷‍♂️

**Comment by nukleuz80** [comment]
Achso und zu der Volume - dort sind die Werte 0-2 einzugeben wobei 0 die lauteste und 2 die leiseste ist - daher wird bei alles > 2 immer 2 gesetzt 🙃

**Comment by nukleuz80** [comment]
@Jey-Cee 

bleibt mir jetzt nur direkt über die API zu gehen? 

Ich habe mir einen Workaround gebastelt mit eigenen Datenpunkten und nem Put-Request über  Blockly.

Bestes

**Comment by Jey-Cee** [comment]
> @Jey-Cee
> 
> bleibt mir jetzt nur direkt über die API zu gehen?
> 
> Ich habe mir einen Workaround gebastelt mit eigenen Datenpunkten und nem Put-Request über Blockly.
> 
> Bestes

Ja  momentan geht das nur so.

**Comment by nukleuz80** [comment]
Ok, danke für Info…
