### ISSUE TITLE
Future plans...? 1.x vs 2.x structure

### ISSUE THREAD

**Issue by realwax** [Jey-Cee/ioBroker.deconz#247]
Hi,

I am still running the 2.x beta version with the modified object structure. As I am using those objects in various other adapters (iqcontrol, iot, influx,...) it is a lot of work removing the object tree and implementing the "old" one.

What are your plans? Will you bring back the structure from 2.x or have you discarded this endeavor.

I am asking because I don't wanna do the change twice - back and forth.

Thank you for any insight!

Cheers
Wolfgang

**Comment by Jey-Cee** [comment]
The object structure of 2.x is obsolet anyway. There will be a new one in the future, actualy i wait for the next minor release from deconz. There should be a new endpoint in the api which will provide devices instead the zigbee nodes.

**Comment by realwax** [comment]
Thank you. Well, then I will stay with 2.x until you introduce the new structure.
