### ISSUE TITLE
Errors after Updating to 1.3.16

### ISSUE THREAD

**Issue by copperfield74** [Jey-Cee/ioBroker.deconz#248]
I've just did the update and got a lot of errors and my alarm system was trying to arm several times without me doing something. I reverted back to 1.3.15 and all is fine.
Node.js v12.22.1
JS-Controller 3.2.16

![Deconz](https://user-images.githubusercontent.com/62651258/122066349-f7e9b380-cdf2-11eb-9cf6-1ca6348db890.JPG)

**Comment by Jey-Cee** [comment]
Can you check the fix while install the adapter from Beta channel.
