### ISSUE TITLE
another error after update 3.16 

### ISSUE THREAD

**Issue by exico66** [Jey-Cee/ioBroker.deconz#250]
After updating, all color bulps changed datapoint "xy" to the art "Objekt". Not possible to change back to the art "Zeichenkette". No colorchange possible any more.

**Comment by exico66** [comment]
hi,
will you fix it?
Regards

**Comment by BiberM** [comment]
I am not used to JavaScript and ioBroker programming but I think I found the problematic lines (main.js lines 2141 ff.):
`case 'xy':
            objType = 'object';
            objRole = 'color.CIE';
            objDefault = '0.10000, 0.10000';
            value = JSON.stringify(value);
            break;`

I don't know why this is there, but it has been changed on purpose with the following commit:
https://github.com/iobroker-community-adapters/ioBroker.deconz/commit/68fde5afd3e42ae48d4bcdda17d508ab8aeae4f4#diff-58417e0f781b6656949d37258c8b9052ed266e2eb7a5163cad7b0863e6b2916a (fixes for js-controller 3.3)

I hope this does help finding a solution a bit quicker as this affects me, too.

Best regards

**Comment by exico66** [comment]
TY

**Comment by Jey-Cee** [comment]
Please install from Github and test.

**Comment by BiberM** [comment]
I cloned the github repo, copied the main.js to the productive system and restarted the ioBroker.deconz instance. When trying to set a xy-value the warning is still the same. I can't currently check if it would be set anyway as the light is in my sons room and he is already asleep. The light ignores changes when off see screenshot).

![grafik](https://user-images.githubusercontent.com/11739148/123686059-a9ef9980-d84f-11eb-9570-729894318571.png)

**Comment by BiberM** [comment]
EDIT: I tried it this morning with the lights switched on and it works. The warning stays but the functionality is back.

**Comment by exico66** [comment]
@Jey-Cee 
I installed it from Github, but the error is still the same.

**Comment by exico66** [comment]
Such a problem to solve it?

**Comment by Jey-Cee** [comment]
BiberM says it is fixed, my tests tells me also it is fixed. 
So give me more information like a log or something else.

**Comment by JayJay68** [comment]
I still use 1.3.16 and have the problem, that I can change a HUE-Value (datapoint "hue" of lights (not groups)) but the led-stripes do nothing. A view seconds later the value of the datapoint change back to the old value. But changing the CT-Value works (it is strange). Please take a look to my post in the ioBroker-forum with more details (versions, some logs and so on): [Link](https://forum.iobroker.net/topic/46709/deconz-adapter-aktualisiert-einzelne-attribute-nicht?_=1628004762029)

If you need further information, let me know.

Thank you for your help.

**Comment by Schmakus** [comment]
Same Problem with v1.3.19, js-controller 3.3.15
(25662) State value to set for "deconz.0.Lights.29.xy" has to be stringified but received type "object"

**Comment by Jey-Cee** [comment]
When appears this message?

**Comment by Schmakus** [comment]
problem solved. I deleted all datapoints before restart the adapter.

**Comment by Stormbringer11** [comment]
Also bei mir gehen die Fehler leider auch nicht weg, wenn ich die Unterordner Lights und Groups lösche und neu anlegen lasse. Das ganze Log ist bei mir voll mit:

`


deconz.0 | 2021-08-17 11:00:10.513 | warn | Code 400: Bad request set group state 12: [{"error":{"address":"/groups/12/action","description":"body contains invalid JSON","type":2}}]
-- | -- | -- | --
javascript.0 | 2021-08-17 11:00:10.508 | warn | at processTimers (internal/timers.js:497:7)
javascript.0 | 2021-08-17 11:00:10.508 | warn | at listOnTimeout (internal/timers.js:556:17)
javascript.0 | 2021-08-17 11:00:10.508 | warn | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1497:29)
javascript.0 | 2021-08-17 11:00:10.508 | warn | at Object.setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1439:20)
javascript.0 | 2021-08-17 11:00:10.508 | warn | You are assigning a string to the state "deconz.0.Groups.12.xy" which expects a array. Please fix your code to use a array or change the state type to string. This warning might become an error in future versions.

`

Muß aber dazu sagen, dass ich an den alten Skripten nichts geändert habe. Müssen die Datenpunkte jetzt anders angesprochen werden? Mit Eckigen Klammern habe ich es auch schon versucht aber selber Fehler. 

Adapter und JS Controller alles aktuell auf Stable Versionen

**Comment by Jey-Cee** [comment]
Das muss so aussehen:
`setState('deconz.0.Lights.1.xy'/*Heizkörper Licht xy*/, [0.100, 0.100])`

**Comment by Stormbringer11** [comment]
Das hat aber früher der Adapter von selber gemacht oder bzw. sind die Klammern nach wie vor zu sehen im Admin Reiter. Habe das spaßhalber sogar mal probiert mit Klammern zu senden aber da kam der selbe Fehler. Momentan fehlt mir leider die Zeit alle Skripte wieder zu ändern, bin jetzt wieder auf die vorherige Version zurück gegangen jetzt funktioniert wieder alles Einwand frei. Trotzdem danke :o)

**Comment by Stormbringer11** [comment]
@jey-cee
Wie müsste das Kommando bei Blocky jetzt aussehen? Ich habe es nochmal so probiert mit der neuen Version. Umfärben tut er schon aber es kommt dann wieder der Fehler von oben. Denke müsste von String in irgendwas Konvertiert werden oder?
Hauptsächlich spiegle ich die xy DPs vom HUE Adapter auf die Deconz Lampen.
<img width="744" alt="Bildschirmfoto 2021-09-19 um 20 00 36" src="https://user-images.githubusercontent.com/43651672/133938072-2958ec27-6002-430f-bfb5-f22f05396066.png">

**Comment by exico66** [comment]
Es wäre wirklich schön, wenn  der Adapterfehler mal behoben würde nach
dieser langen Zeit.

Diese E-Mail kann vertrauliche und/oder rechtlich geschützte Informationen enthalten..

Wenn Sie nicht der richtige Adressat sind, oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte den Absender und löschen Sie diese Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail und der darin enthaltenen Informationen sind nicht gestattet.

Mit freundlichem Gruß
Dirk Frese

Am 19.09.2021 um 20:07 schrieb Stormbringer11:

**Comment by exico66** [comment]
@Stormbringer11 
Hast Du die 3.19er Version getestet? Ich bin noch auf der 11er, hab keine Lust wieder alle Datenpunkte danach wieder umstellen zu müssen.
@Jey-Cee 
Ist der Fehler mit der 19er Version behoben?
Danke für Deine Arbeit!

**Comment by Stormbringer11** [comment]
Kann ich sehr gut nachvollziehen. So gern ich den ioBroker mag nervt das ständige ändern der DP gewaltig. Da brauchst entweder mini Installationen oder gewaltig viel Zeit. Betrifft ja leider nicht nur einen Adapter.  Ich musste auf die 19er wechseln, weil mit der aktuellen Phoscon/Deconz Version die 11er gar keine Farben mehr ansteuerte. Rückblickend hätte ich mir das lieber gespart 🙈 Farbansteuerung funktioniert jetzt aber auch nur teilweise. Kann aber auch davon kommen, dass das System zugespamt wird mit Fehlermeldungen. Aber seit dem neuen JS Controller gibts da leider eh leider sehr viele, weil er string anstelle von number erwartet usw.  🤷‍♀️ Glaub mach jetzt dann eh keine Updates mehr 😂

**Comment by exico66** [comment]
ich habe auch die neueste Phoscon/Deconz Version. Bei mir wechseln unter 3.11 die Farben einwandfrei.

**Comment by exico66** [comment]
@Jey-Cee 
Hallo, ich würde wirklich gerne updaten auf 3.19 aber der von mir im Eingangspost beschriebene >Fehler ist immer noch vorhanden. Wird da noch an einer Lösung gearbeitet?

**Comment by Jey-Cee** [comment]
> @Jey-Cee Hallo, ich würde wirklich gerne updaten auf 3.19 aber der von mir im Eingangspost beschriebene >Fehler ist immer noch vorhanden. Wird da noch an einer Lösung gearbeitet?

Wenn es dir um den Typ des Objekts geht, dann nein. Das ist kein Fehler.

**Comment by Stormbringer11** [comment]
@Jey-Cee Danke für die Rückmeldung, wie ist dann jetzt die korrekte Ansteuerung via Blockly?

**Comment by exico66** [comment]
Was bedeutet denn "kein Fehler"? Meine Lampen lassen sich nicht mehr in der Farbe steuern, sobald ich das Update drauf habe. Das finde ich schon ein bisschen fehlerhaft ;-)

**Comment by Jey-Cee** [comment]
> Was bedeutet denn "kein Fehler"? Meine Lampen lassen sich nicht mehr in der Farbe steuern, sobald ich das Update drauf habe. Das finde ich schon ein bisschen fehlerhaft ;-)

Stell das Log level der Instanz auf debug und such nach folgendem Eintrag nachdem du den befehl gesendet hast:
`Code 200: Request succeded set light state 1: [{"success":{"/lights/1/state/xy":[0.1133,0.6986]}}]`
Diese Meldung besagt das der Befehl von deConz angenommen wurde und so korrekt ist.
Andernfalls sollte eine Meldung wie diese im Log erscheinen: 
`Code 400: Bad request set light state 1: [{"error":{"address":"/lights/1/state","description":"body contains invalid JSON","type":2}}]`

Und nochmal bei mir funktioniert das Steuern der Farbe, das hab ich jetzt extra nochmal getestet.

@Stormbringer11 
![image](https://user-images.githubusercontent.com/16007760/136652458-80cc7d14-8888-4f68-bbcf-24941662864e.png)

**Comment by Stormbringer11** [comment]
Danke @Jey-Cee. Mein Blockly kommt unterm Strich ja auf das Selbe und die Fehlermeldung kommt trotzdem 🙈 Farbe umschalten tut er meistens aber spät halt LOG zu

**Comment by exico66** [comment]
@Jey-Cee 
Ein letzter Versuch! Bis zur Version 1.3.11 funktionieren meine Blocklys einwandfrei. Sobald ich update werden die Farben nicht mehr gesteuert. Auch der XY-Wert in eckigen Klammern bringt keine Änderung. Muss ich wirklich ewig auf der alten Version bleiben?

**Comment by Schmakus** [comment]
JSON Parse verwenden. 
Mit Blockly den Baustein "JSON nach Objekt" und eckige Klammern

**Comment by Stormbringer11** [comment]
@Schmakus Danke das klappt. Dann ändere ich mal alle Skripte 🤗

**Comment by exico66** [comment]
@Schmakus Bin auch dabei alles umzuschreiben - danke!
