### ISSUE TITLE
Brightness causes warning

### ISSUE THREAD

**Issue by nobl** [Jey-Cee/ioBroker.deconz#252]
Fresh install - so no old states.

When setting brightness to max via phoscon app, adapter produces the following warning:
`State value to set for "deconz.0.Lights.X.bri" has value "255" greater than max "254"`

Same appears to apply to groups (and likely every other "bri" datapoint):
`State value to set for "deconz.0.Groups.X.bri" has value "255" greater than max "254"`

**Comment by Jey-Cee** [comment]
Thanks, i will fix it.

**Comment by Jey-Cee** [comment]
Fixed with version 1.3.19
