### ISSUE TITLE
Datenpunkt "effect" update bringt ein crash des Adapters

### ISSUE THREAD

**Issue by jensdersven** [Jey-Cee/ioBroker.deconz#253]
Hi
Ich habe hier mal gelesen (finde leider den Issue nicht mehr) dass es ein Update gabe, welches für eine bestimmte Marke die "effecte" erweitert.
habe jetzt einfach mal ausprobiert diese an meinen Osram Lampen zu steuern, dabei crasht der Adapter.

`
<html>
<body>

deconz.0 | 2021-07-13 10:14:34.870 | info | (7682) starting. Version 1.3.16 in /opt/iobroker/node_modules/iobroker.deconz, node: v12.22.1, js-controller: 3.3.10
-- | -- | -- | --
host.raspberrypi | 2021-07-13 10:14:32.872 | info | instance system.adapter.deconz.0 started with pid 7682
host.raspberrypi | 2021-07-13 10:14:02.818 | info | Restart adapter system.adapter.deconz.0 because enabled
host.raspberrypi | 2021-07-13 10:14:02.816 | error | instance system.adapter.deconz.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.raspberrypi | 2021-07-13 10:14:02.816 | error | Caught by controller[1]: at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.deconz/main.js:290:129)
host.raspberrypi | 2021-07-13 10:14:02.815 | error | Caught by controller[1]: TypeError: Cannot read property 'val' of null
host.raspberrypi | 2021-07-13 10:14:02.808 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejecte
deconz.0 | 2021-07-13 10:14:02.201 | warn | (2057) Terminated (UNCAUGHT_EXCEPTION): Without reason
deconz.0 | 2021-07-13 10:14:02.199 | info | (2057) terminating
deconz.0 | 2021-07-13 10:14:02.198 | info | (2057) cleaned everything up...
deconz.0 | 2021-07-13 10:14:02.187 | error | (2057) Cannot read property 'val' of null
deconz.0 | 2021-07-13 10:14:02.186 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.deconz/main.js:290:129)
deconz.0 | 2021-07-13 10:14:02.186 | error | (2057) TypeError: Cannot read property 'val' of null
deconz.0 | 2021-07-13 10:14:02.181 | error | (2057) unhandled promise rejection: Cannot read property 'val' of null
deconz.0 | 2021-07-13 10:14:02.180 | error | (2057) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

Vor dem Update gab es "Colorloop", bin mir grad nicht sicher obs da auch noch mehr gab. 
ist es nicht möglich diese Effecte nur für diese Speziellen Lampen frei zu schalten?

**Comment by Jey-Cee** [comment]
Nein Leider ist es nicht möglich die Effekte nur bei den entsprechenden Lampen an zu Zeigen. Dafür wäre eine Liste mit allen Lampen und den dazu gehörigen Effekten erforderlich und die gibt es meines Wissens nach nicht.

**Comment by Jey-Cee** [comment]
Fixed with version 1.3.19
