### ISSUE TITLE
Smart Switches not working anymore with 2.12.02 / 12.7.2021

### ISSUE THREAD

**Issue by Andiweli** [Jey-Cee/ioBroker.deconz#255]
![aqara](https://user-images.githubusercontent.com/11447150/125911694-151e2a5c-4fb6-45c7-a236-7dfd7ce7263e.jpg)

A few days ago I still had objects for the "click" states of my AQARA Smart Switches - single press, double press, long press.
Now this entry points have been vanished.

Reconnecting and syncing my Smart Switches only adds this objects:
![smart-switch](https://user-images.githubusercontent.com/11447150/125911393-6844eede-fd28-40fa-b346-c0fd937498fd.JPG)

In the Log I can see the following warning:

deconz.0 | 2021-07-16 09:41:51.615 | warn | Unknown command: send

I am on Phoscon version 2.12.02 / 12.7.2021

Any idea?
Thanks!

**Comment by Andiweli** [comment]
Ok so I manually flashed the latest firmware.
Now it seems to work,

Shouldn't the APT-GET UPDATE do this?

**Comment by Jey-Cee** [comment]
I don't know. You can ask this on phoscon forum -> https://forum.phoscon.de/
