### ISSUE TITLE
Problem after upgrade deCONZ

### ISSUE THREAD

**Issue by bruesche** [Jey-Cee/ioBroker.deconz#256]
Hi there,

first of all. I know there is no support for beta versions of deCONZ. Nevertheless I will report this "problem", because it seems that this will happen in the next stable version of deCONZ too. 

After I upgraded to deCONZ version 2.12.03 my eurotronic zigbee thermostats didn't work anymore. I set the value for heatsetpoint but nothing happens. In the log of iobroker I found this:

deconz.0 | 2021-07-16 14:16:08.886 | warn | (14412) {"address":"/sensors/17/config/heatsetpoint","description":"invalid value, 600, for parameter heatsetpoint","type":7}
-- | -- | -- | --

Asked in GitHub community "dresden-elektronik/deconz-rest-plugin" for help. I can directly sent values via API to the thermostat - works. But via iobroker the "error" above occurred.

Tried every "new" version of deCONZ. The last stable version 2.11.05 is working fine. 

Could it be that there is a new "check" for datatype in deCONZ so the thermostats can't control properly over iobroker adapter?

Thanks for help.

**Comment by Jey-Cee** [comment]
Thank you for reporting. It is known and fixed but not released in stable.
