### ISSUE TITLE
RAW werte für Fernsteuerung über alexa/iot adapter fehlen

### ISSUE THREAD

**Issue by L0rz** [Jey-Cee/ioBroker.deconz#257]
Wie hier beschrieben:
https://github.com/ioBroker/ioBroker.iot/issues/178
 es fehlen bei den Adapternder RAW wert für native.:

"native": { "read_only": true, "write_only": false }

**Comment by Jey-Cee** [comment]
Hast du die anderen Kommentare in dem verlinkten issue gelesen?
