### ISSUE TITLE
Level is not updated for groups that contains more than 1 bulb

### ISSUE THREAD

**Issue by steffensammet** [Jey-Cee/ioBroker.deconz#258]
Hi,

I have several groups defined; some times with 1 bulb, some other times with more than 1 bulb.

Intrestingly, when having a group with only 1 bulb, the level attribute to this bulb is identical to level of the group.
Now surprisingly, when there is a group with 2 or more bulbs, the level attribute does not get updated.  It stay at 50% while all bulbs within are at 30% for example.

(Group adjusted with Apple Home - Phoscon can see this adjustment for the group - ioBroker not)

**Comment by Jey-Cee** [comment]
I know this is weird, but deConz does not send a websocket message while changing the level of a single light in a group.
If there is only one light in the group the handling is not the same. 

In my mind it makes not really sense to set the level of a group to the value of one light, while other can have a complete different level at the same time. So the level for a group is only a element for controling the whole group.
