### ISSUE TITLE
common.def als String passt nicht zu common.type = "object"

### ISSUE THREAD

**Issue by Matzinger81** [Jey-Cee/ioBroker.deconz#260]
Hallo,

auf meiner IOBroker (Rapsberry 4) Installation bekomme die Fehlermeldung 

`(1720) You are assigning a string to the state "deconz.0.Lights.6.xy" which expects a object. Please fix your code to use a object or change the state type to string. This warning might become an error`

wenn ich in den xy Datenpunkt schreiben will. Früher hat dies mit einem String immer geklappt. 

Der Datentyp ist ein "object":

![image](https://user-images.githubusercontent.com/70326462/127969686-f92324e6-1c96-47f5-9ab0-3817da859635.png)

Wenn ich die Werte als Array übergebe, gibt er die gleiche Fehlermeldung aus (nur mit "You are assigning an array..." natürlich)

Der Datenpunkt xy wird dann immer rot, die Lampe bleibt aus.

Mein Deconz Adapter ist auf 1.3.16. Mein Javaskript Adapter auf 5.1.3

Gruß und Danke vorab
Matthias

**Comment by Jey-Cee** [comment]
Fixed with version 1.3.19
