### ISSUE TITLE
[Bug]: Falsche Adresse auf der Übersicht-Seite des Admin

### ISSUE THREAD

**Issue by Siggi0904** [Jey-Cee/ioBroker.deconz#263]
### What happened?

Seit der Version 1.3.19 und dem Admin 5.1.23 ist der DeConz-Adapter auch auf der Übersicht-Seite dargestellt.
Die Adresse um Aufruf des Adapters ist aber falsch.

Richtig wäre: -ip-adresse-/pwa/login.html

Danke für eine Korrektur in der nächsten Version.

### Adapter Version

1.3.19

### deConz (Phoscon) Version

2.11.5

### JS-Controller Version

3.3.15

### Node JS Version

12.22.4

### NPM Version

6.14.14

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Fixed with [bc53653](https://github.com/iobroker-community-adapters/ioBroker.deconz/commit/bc536538280eaf926034d31f82a403e4697f12c7)
