### ISSUE TITLE
[Bug]: TS0201 _TZ3000_qaaysllp doesn't connect/pair correctly

### ISSUE THREAD

**Issue by Pedder007** [Jey-Cee/ioBroker.deconz#265]
### What happened?

I paired the above mentioned sensor device but only get the value for brightness (lux), resp. lightlevel in the deconz adapter.
When pairing the sensor on my test-system with the Zigbee adapter, it is the other way around. I get temperature, humidity and battery, but not brightness/lightlevel.
I already tried to configure manually a temperature datapoint in the device in the deconz object's list (on basis of the datapoint character in the Zigbee adapter), but that doesn't work.
Pairing the device newly by Phoscon also doesn't help. I tested this a couple of times.
On the test system I also was able to read the lightlevel via the developer mode:
![image](https://user-images.githubusercontent.com/44653371/131576029-2eca3a9f-b38f-4290-aa0e-8750f5d04c25.png)

### Adapter Version

1.3.19

### deConz (Phoscon) Version

2.10.04

### JS-Controller Version

3.3.15

### Node JS Version

12.22.5

### NPM Version

6.14.14

### Operating System

Debian

### Relevant log output

```shell
no
```

### Anything else?

This device: https://de.aliexpress.com/item/1005002432525181.html?spm=a2g0s.9042311.0.0.6d554c4d1rDhpZ
Already found other discussion about the device: https://github.com/zigpy/zha-device-handlers/issues/862

But as I see, one half of the values is detected by pairing via Phoscon / deconz and the other half is detected by the ZigBee adapter. Thus I have the hope, that the respective config might can be combined!?

**Comment by Jey-Cee** [comment]
Do you know that sensors are splitted and have several endpoints in ioBroker? Check if there are other datapoints with the values you are looking for.

**Comment by Pedder007** [comment]
Thanks for your answer!
Yes I know, I have a couple of these sensors/devices with multiple end- or datapoints. But that isn't the case here.

I just tried to re-pair the device again on my test sytem via the Zigbee adapter, but that now doesn't work any longer propperly.
It is detected and the pairing process also displays the potential values (temperature, humidity, battery), but afterwards no data is received any.

After that, I re-paired it again to my prod system via the deconz adapter and there again only the brightness values are available.
Before doing this, I deleted it via the deconz gui and paired it then newly via Phoscon.

This is really a bit astonishing ...

**Comment by Jey-Cee** [comment]
Sounds like the sensor is not ok.

**Comment by Pedder007** [comment]
I fear it is still the complicated pairing of it. See respectively the link I posted above. I have two of these devices and the behavior is the same.
My yesterday's hope to get this solved came along with the succesful pairing via the Zigbee adapter, but that is not working any longer. We may then close this issue here, as it is for now and wait on the developers how are currently fighting to get it correctly paired, at least to the deconz rest api.
