### ISSUE TITLE
[Bug]: CT-Wert wird bei ausgeschalteten Lampen nicht übernommen

### ISSUE THREAD

**Issue by hopedotz** [Jey-Cee/ioBroker.deconz#266]
### What happened?

Hi! Meine IKEA-Tradfri-Lampen hängen alle am Dauerstrom. Wenn der Datenpunkt "on" der Lampe auf "off" steht, kann ich keine CT-Farbwerte ändern. Erst, wenn der Datenpunkt auf "true" gesetzt wurde, kann ich den CT-Wert ändern. Gibt es hierfür eine Lösung?

### Adapter Version

1.3.19

### deConz (Phoscon) Version

2.5.77

### JS-Controller Version

v12.20.0

### Node JS Version

v12.20.0

### NPM Version

6.14.8

### Operating System

Ubuntu

**Comment by Jey-Cee** [comment]
Du kannst den Action Datenpunkt verwenden, dann kannst mehrere Befehle auf einmal Ausführen. Sonst geht das nicht anders.
