### ISSUE TITLE
Thermostat Support

### ISSUE THREAD

**Issue by jpakusch** [Jey-Cee/ioBroker.deconz#267]
Hey Guys,

i use the deconz adapter with Conbee 2 Stick and it generally works quite fine.

What i still did not get working was my Thermostat (Moes Tuya Thermostat BTH-002)
It should be supported by Deconz like you can read here:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3304
But the device is discovered as Lamp and all objects i get is an object where i can switch it on/off and some alarm object.

Do you know some Tutorial i can get along with? 
I am quite new to this topic, but i have the idea that this tutorial could be relevant for me to get it running:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters
But does this wotk with the Deconz Adapter? is there a possibility dto do this for the Adapter and the included deconz instance? (i do not have a dedicated deconz instance running somewhere else, could that help me get the device running?)

Thank you for your Help!

Greetings, Jan

**Comment by Jey-Cee** [comment]
Hi Jan,

look under sensors there should be also objects that are related to your BTH.
