### ISSUE TITLE
[Bug]: Xiaomi vibrationssensor sensitivity

### ISSUE THREAD

**Issue by cracyfloyd** [Jey-Cee/ioBroker.deconz#268]
### What happened?

Raspbian OS (Raspberry Pi400)
i use deconz adapter version: 1.3.19
deconz version 2.12.06 (try 2.13.01)
This problem was solved but its comes again after any upgrade.
Xiaomi vibrationssensor not possible to change the value sensitivity. 
bit this is very important to make an alarmsystem.

### Adapter Version

1.3.19

### deConz (Phoscon) Version

2.12.06

### JS-Controller Version

5.1.25

### Node JS Version

12.22.7

### NPM Version

6.14.15

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Are there any log messages if you try to set the sensitivity?

**Comment by cracyfloyd** [comment]
no iam sorry. there is nothing to see in the log.

**Comment by cracyfloyd** [comment]
folgendes habe ich im log gefunden:
es scheint auch der bewegungsmelder betroffen:

deconz.0 | 2021-11-05 07:57:12.413 | warn | {"address":"/sensors/48/config/duration","description":"invalid value, 5, for parameter duration","type":7}

deconz.0 | 2021-11-05 08:00:54.273 | warn | {"address":"/sensors/51/config/sensitivity","description":"invalid value, 15, for parameter sensitivity","type":7}

deconz.0 | 2021-11-05 08:03:09.555 | debug | Code 200: Request succeded set sensor parameters: [{"error":{"address":"/sensors/51/config/sensitivity","description":"invalid value, 10, for parameter sensitivity","type":7}}

**Comment by cracyfloyd** [comment]
Maybe it will be nice when you solve this problem. the problem is also with the xiaomi aqara motion sensor and the duration time. i try with a docker container and deconz version 2.05.77 and with this one the problem is gone.

**Comment by cracyfloyd** [comment]
I have tested more now. now i can say that it works until stable 2.11.5.The failure begins with stable version 2.12.6.
Is anyone working on it ????????

**Comment by Jey-Cee** [comment]
Nope, i am actually not working on this adapter.

**Comment by Jey-Cee** [comment]
Install from Github and test please.

**Comment by jhubig** [comment]
I know it is maybe not the perfect place in this issue, but I had a similar issue for setting the duration of the Aqara motion sensor.

deconz.1 | 2022-01-10 23:10:06.693 | warn | {"address":"/sensors/18/config/duration","description":"invalid value, 20, for parameter duration","type":7}
-- | -- | -- | --

So as a workaround I have set it via `curl -X PUT -d '{"duration":5}' -s "http://<IP_ADRESS>:<PORT>/api/<API_USERNAME>/sensors/<SENSOR_ID>/config"`

BUT 😀  ....with your latest fix (master branch - 1.3.19) it is working again. Thank you.
