### ISSUE TITLE
[Bug]: Sensors not controllable

### ISSUE THREAD

**Issue by QuerkyD** [Jey-Cee/ioBroker.deconz#269]
### What happened?

Hallo, 
ich kann meine Sensoren (Eurotronic Zigbee und Xiaiomi Aquara) nicht steuern. Wenn ich versuche Werte im ioBroker zu schreiben (z.B. Heatsetpoint oder offset) wird der Wert nach kurzer Zeit rot markiert. Über die Deconz-Rest-Api kann ich dann auch sehen, dass der Wert nicht übernommen wurde. Getestet habe ich mit ioBroker 5.2 und deConz 1.3.19. Habe dann nochmal zu ioBroker 4.2 und deConz 1.3.11 gedowngraded. Hier ist das gleiche Problem, allerdings bekomme ich hier eine Warnmeldung im Log: 

`(671) {"address":"/sensors/12/config/offset","description":"invalid value, 0, for parameter offset","type":7}`

Über die Deconz-Rest-Api kann ich die Werte problemlos schreiben: 
PUT  "address":"/sensors/12/config/offset  {"heatsetpoint" : 1850}

### Adapter Version

1.3.19, 1.3.11

### deConz (Phoscon) Version

2.12.02, 2.12.06

### JS-Controller Version

3.3.16

### Node JS Version

10.21.0

### NPM Version

6.14.4

### Operating System

Debian

**Comment by QuerkyD** [comment]
Update: `heatsetpoint `lässt sich mit Version 1.3.11 wohl doch steuern, aber `offset ` funktioniert nicht

**Comment by OnkelBuTscH** [comment]
Ich hatte vor ein paar Tagen das selbe verhalten festgestellt wie Du!
Ein Downgrade auf die deConz Software Version 2.10.04 hat geholfen und ich konnte die Werte wieder ändern.
Die Version vom deConz Adapter und ioBroker war die Aktuellste, diese zu ändern hat auch nicht geholfen!
Ich kann aber leider keine weitere hilfe diesbezüglich geben da ich nun auf dem Zigbee Adapter gewchselt bin, damit läuft alles wie gewünscht.

**Comment by MegaMatze** [comment]
Gleiches Problem auch bei mir. Nach Update kann ich über den ioBroker zwar die Werte noch sauber auslesen, aber Steuern funktioniert nicht. Auch das Downgrade auf 2.10.04 brachte leider nicht den gewünschten Erfolg....
Was ist da los? Ist ein bisschen problematisch gerade wenn im ganzen Haus keine Lichter und sonstigen Applikationen mehr gehen :/

**Comment by MegaMatze** [comment]
> Gleiches Problem auch bei mir. Nach Update kann ich über den ioBroker zwar die Werte noch sauber auslesen, aber Steuern funktioniert nicht. Auch das Downgrade auf 2.10.04 brachte leider nicht den gewünschten Erfolg.... Was ist da los? Ist ein bisschen problematisch gerade wenn im ganzen Haus keine Lichter und sonstigen Applikationen mehr gehen :/

Kommando zurück. Schande über mein Haupt. Offenbar war mein Port durch das Update verstellt worden. Da stand plötzlich 8080 statt 80. Komischerweise hat ioBroker dadurch zwar auslesen können aber nicht schreiben. Jetzt kann der ioBroker wieder steuern

**Comment by QuerkyD** [comment]
Bei mir läufts nach dem Downgrade auch wieder!

**Comment by ticaki** [comment]
Hab das gleiche Problem, aber schon deutlich länger für delay und jetzt auch für duration. Das Probem müsste Zeile 366

`
parameters = ``{ "${dp}": "${state.val}" }``; // keine Ahnung wie ich ein `` darstelle
`
Wenn ich über Postman den Befehl mit "" für Value sende, gibts nen Fehler ohne geht es.
`
{"duration":30}
`

**Comment by GitHubRaspi** [comment]
Bei mir das selbe für Danfoss Ally. Mit 2.12.06 funktioniert es nicht, nach downgrade auf 2.10.04 funktioniert es mit dem offset. Fehler bleibt aber für den Parameter "locked":

Code 400: Bad request set sensor parameters: [{"error":{"address":"/sensors/4/config/locked","description":"invalid value, false, for parameter locked","type":7}}]

**Comment by Jey-Cee** [comment]
See #268
