### ISSUE TITLE
[Bug]: Fehlerspeicher wird voll geschrieben.

### ISSUE THREAD

**Issue by canim60** [Jey-Cee/ioBroker.deconz#271]
### What happened?

Hallo, immer wieder habe ich den  Fehler im Speicher

### Adapter Version

2.0.5

### deConz (Phoscon) Version

2.12.06

### JS-Controller Version

3.3.18

### Node JS Version

12

### NPM Version

6.14.15

### Operating System

Debian

### Relevant log output

```shell
deconz.0 | 2021-10-30 12:01:09.825 | warn | State value to set for "deconz.0.groups.7.ct" has value "0" less than min "250"
-- | -- | -- | --
```

**Comment by Jey-Cee** [comment]
Colortemperature kann nicht 0 sein, der niedrigste Wert ist 250. Setzt du denn Wert von Hand oder per Script auf diesen Wert?

**Comment by canim60** [comment]
ne eigentlicht nicht =/

**Comment by Jey-Cee** [comment]
Als Workaround ändere im Objekt common -> min auf 0

**Comment by canim60** [comment]
danke hat geklappt :)!
