### ISSUE TITLE
Erlaubnis zum Verbinden von Third Party Apps per Iobroker geben

### ISSUE THREAD

**Issue by flisse** [Jey-Cee/ioBroker.deconz#275]
Da ich nach einem Neustart des Systems immer den Button für die Third Party Apps anklicken muss, würde ich es mir wünschen, wenn das per Direktbefehl aus Iobroker gehen würde. 
Den Button muss ich immer betätigen, da meine Homebridge Umgebung sonst keinen Zugriff auf die Lampen und Sensoren erhält.

**Comment by Jey-Cee** [comment]
Da ist was Faul normal merkt sich Phoscon den API Key und vergibt auch für jede App einen eigenen Key.
Für diese Version des Adapters gibt es keine Feature updates mehr.

Steht aber auf der Liste für die nächste große Version.
