### ISSUE TITLE
[Bug]: deconz crash beim setzen von Effect mittels Skript auf "colorloop" oder "none"

### ISSUE THREAD

**Issue by thogens** [Jey-Cee/ioBroker.deconz#276]
### Contact Details

forspam.thomas@gmail.com

### What happened?

Sobald mein (bislang funktionierendes Skript) den Wert einer Lampengruppe "Effect" auf "colorloop" setzt (per blockly text), dann crasht der Adapter.
Wähle ich hingegen den Wert "colorloop" oder "none" im Objekt aus, funktioniert alles wie gewünscht.

btw. Das Ganze läuft auf Synology im Docker container...

### Adapter Version

1.3.19

### deConz (Phoscon) Version

2.13.01

### JS-Controller Version

3.3.18

### Node JS Version

v12.22.7

### NPM Version

6.14.15

### Operating System

Debian

### Relevant log output

```shell
deconz.0 | 2021-11-04 14:00:31.078 | info | terminating
-- | -- | -- | --
deconz.0 | 2021-11-04 14:00:31.075 | info | cleaned everything up...
deconz.0 | 2021-11-04 14:00:31.058 | error | Cannot read property 'val' of null
deconz.0 | 2021-11-04 14:00:31.057 | error | TypeError: Cannot read property 'val' of null     at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.deconz/main.js:283:39)
deconz.0 | 2021-11-04 14:00:31.052 | error | unhandled promise rejection: Cannot read property 'val' of null
deconz.0 | 2021-11-04 14:00:31.051 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
deconz.0 | 2021-11-04 14:00:31.044 | debug | Code 200: Request succeded set group state 40: [{"success":{"/groups/40/action/effect":"none"}}]
```

### Anything else?

<img width="353" alt="Bildschirmfoto 2021-11-04 um 14 10 02" src="https://user-images.githubusercontent.com/66367539/140319030-78069cbe-0bf3-4d44-8eea-6c201c1aa585.png">

**Comment by Jey-Cee** [comment]
Gibt es das Objekt colorspeed in der Gruppe?

**Comment by thogens** [comment]
Ja, gibt es.
Nur leider habe ich jetzt noch ein viel größeres Problem.
Nachdem die States der ganzen Sensoren nicht mehr geupdated wurden. (Phoscon app ging), habe ich den Deconz Adapter gelöscht, nebst all seiner Objekte.
Soeben neu erstellt und nun sind sämtliche IDs durcheinander, bzw. Geräte werden auch verschiedene IDs aufgeteilt.
Ich hatte das vor ein paar Tagen schon einmal und habe Stunden gebraucht, um ein Backup wieder einzuspielen...
Jetzt bin ich wieder ratlos :-(

**Comment by Jey-Cee** [comment]
Besteht das Problem noch?

**Comment by thogens** [comment]
Nachdem ich alles neu aufgesetzt habe, funktioniert es jetzt wieder. 
Das war wirklich eine unheimlich zeitraubende Arbeit, alle Skripte anzupassen.
Wann wurde denn die Groß-Kleinschreibung der ganzen Deconz Elemente gemacht?
Das hat mir echt das Genick gebrochen. - Ist aber verheilt ;-)

**Comment by Jey-Cee** [comment]
Keine Ahnung das muss ewig her sein, wobei deine Beschreibung ja so klang als hättest du die Version 2 des Adapters installiert gehabt.
