### ISSUE TITLE
[Bug]: Offset-Bereich (min/max) für Xiaomi Mi zu klein

### ISSUE THREAD

**Issue by ohle64** [Jey-Cee/ioBroker.deconz#277]
### What happened?

Hi,
bei dem Adapter ist der Offset-Bereich zu klein gewählt (min -500, max +500) wenn Xiaomi Mi Sensoren verwendet werden. Sensor: Multisensor Xiaomi Mi (Temperatur/Humidity) WSDCGQ01LM an ConBee II (USB)/Phoscon 2.09.01
Die Sensoren können: min -999 und max +999 verarbeiten und benötigen auch den Bereich, speziell die Humidity!
Leider hilft auch kein Anpassen der min/max Werte im ioBroker/Objektbrowser da die Werte vom Adapter wieder geändert werden.
Ich habe in Zeile 2377 ff
objMin = -500; geändert auf -999
objMax = 500; geändert auf 999

Bitte bei der nächsten Version mit anpassen.
Gruß Frank

### Adapter Version

1.3.19

### deConz (Phoscon) Version

2.09.01

### JS-Controller Version

3.3.18

### Node JS Version

12.22.7

### NPM Version

6.14.15

### Operating System

Ubuntu

**Comment by Jey-Cee** [comment]
Comes with next version.
