### ISSUE TITLE
Could not connect to deConz/Phoscon. Error: socket hang up

### ISSUE THREAD

**Issue by JTR2000** [Jey-Cee/ioBroker.deconz#278]
Beim starten des Adapters steht immer folgendes im Log.
"Could not connect to deConz/Phoscon. Error: socket hang up"
Status Änderungen kommen im ioBroker an. Es kann aber kein Befehl gesendet werden.

Node.js: v12.22.7
NPM: 6.14.15

Funktioniert nicht.
09:45:41.308	debug	(18131) dp: level; id:Lights.3 tmp: deconz,0,Lights,3
09:45:41.308	debug	(18131) stateChange Lights.3 {"val":0,"ack":false,"ts":1636620341295,"q":0,"c":"script.js.Rollos.WohnzimmerAlle","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1636620341295}
09:45:41.307	silly	(18131) States user redis pmessage deconz.0.*/deconz.0.Lights.3.level:{"val":0,"ack":false,"ts":1636620341295,"q":0,"c":"script.js.Rollos.WohnzimmerAlle","from":"system.adapter.javascript.0","user":"s
.....
09:43:37.053	silly	(18131) States user redis pmessage deconz.0.*/deconz.0.info.connection:{"val":true,"ack":true,"ts":1636620217047,"q":0,"from":"system.adapter.deconz.0","user":"system.user.admin","lc":1636620217047}
09:43:37.001	debug	(18131) Subscribed to updates...
09:43:36.995	error	(18131) Could not connect to deConz/Phoscon. Error: socket hang up
09:43:36.915	info	(18131) starting. Version 1.3.19 in /opt/iobroker/node_modules/iobroker.deconz, node: v12.22.7, js-controller: 3.3.18

**Comment by Jey-Cee** [comment]
> "Could not connect to deConz/Phoscon. Error: socket hang up"
> Status Änderungen kommen im ioBroker an. Es kann aber kein Befehl gesendet werden.

Ist das noch Aktuell?
Socket hang up heist einfach der Adapter keine Verbindung zum deConz bekommt bzw. die Antwort zu lange dauert.

**Comment by JTR2000** [comment]
> > "Could not connect to deConz/Phoscon. Error: socket hang up"
> > Status Änderungen kommen im ioBroker an. Es kann aber kein Befehl gesendet werden.
> 
> Ist das noch Aktuell? Socket hang up heist einfach der Adapter keine Verbindung zum deConz bekommt bzw. die Antwort zu lange dauert.

Ja, ist noch Aktuell.
Hue Essentials kann sich ohne Probleme verbinden, und auch z.B. die Ikea Rollos steuern.

**Comment by SebastianHanz** [comment]
Falls du den Conbee im Docker-Container laufen hast, geb im iobroker-Adapter die interne IP vom Docker-container an mit dem internen Port 80.
Also vermutlich 172.1x.x.x und Bridge Port 80. Bei mir war das die Lösung.

**Comment by JTR2000** [comment]
> Falls du den Conbee im Docker-Container laufen hast, geb im iobroker-Adapter die interne IP vom Docker-container an mit dem internen Port 80. Also vermutlich 172.1x.x.x und Bridge Port 80. Bei mir war das die Lösung.

Hi, danke für deinen Tip, aber läuft nicht im Docker-Container. Hat sich von alleine erledigt, läuft seit heute morgen wieder.
