### ISSUE TITLE
Paulmann wird nicht als Manufacturer erkannt

### ISSUE THREAD

**Issue by gidhap** [Jey-Cee/ioBroker.deconz#279]
Ich habe heute mit etwas support meine ersten Paulmann Zigbee Velora Leuchten per deconz angebunden. 
Funktioniert soweit alles gut. Nur ein Schönheitsfehler gibt es noch. Im Adapter wird der Hersteller als "Unknown" angezeigt.

![image](https://user-images.githubusercontent.com/28500973/144475312-f59f3f8f-e761-45d1-abd6-8e5922ff4387.png)

**Comment by Jey-Cee** [comment]
Das liegt nicht am Adapter, das kommt aus der API von deConz. 
Der Adapter würde undefined ode null schreiben, aber nicht Unknown.

**Comment by gidhap** [comment]
Danke für die rasche Antwort. Ich bin da ja Laie
