### ISSUE TITLE
Feature request: Search for new devices

### ISSUE THREAD

**Issue by udondan** [Jey-Cee/ioBroker.deconz#284]
I'd like to search for new devices without logging in to the Phoscon app (because it is still not really usable on mobile devices. At least on Firefox on iOS it's a pain in the ass).

Ideally there would be a datapoint I can set to `true`, which activates searching for devices.

**Comment by Jey-Cee** [comment]
Did you search before you opened the issue?

**Comment by udondan** [comment]
Absolutely, yes. Neither for the term "search" nor "suche" any valid results are available.

**Comment by Jey-Cee** [comment]
![deconz_new_devices](https://user-images.githubusercontent.com/16007760/147875327-24d551c8-72f2-48b1-a422-bf93b74a1b1d.png)

**Comment by udondan** [comment]
Then maybe this is not a feature request but a bug report: Changing this value to `true` in ioBroker does not allow new devices to be added.

In fact, before opening this issue I had seen and tested this value, without reading its description. Since it didn't work I assumed it must be something else. Sorry 'bout that.

I looked in the code and found the [PUT request](https://github.com/iobroker-community-adapters/ioBroker.deconz/blob/master/main.js#L373) that should be made for the network_open state change. If I execute this API call myself, it perfectly works.

If I read the code correct, there should be a "modify config" entry be added to the logs, unless there is an error. The log is empty though.
