### ISSUE TITLE
Log-File Overload

### ISSUE THREAD

**Issue by mueller-esch** [Jey-Cee/ioBroker.deconz#288]
### Contact Details

paul@mueller-esch.de

### What happened?

Hallo zusammen. Vielleicht kennt jemand auch das Problem:
Eine Warnmeldung müllt das LogFile zu, weil ein Grenzwert einer Lampe den Wert von 8000 überschreitet. Bei der Lampe handelt es sich um eine Immax Neo RGB Lampe. Der Wert für die Farbtemperatur (ct) ist in den Gerätedaten auf max. 8000 eingestellt. Die Lampe liefert aber nach Umstellung immer wieder einen Wert von 65535. Der Grenzwert lässt sich nicht editieren, da er immer wieder überschrieben wird. DeconzLampemwarnung.png

Würde mich über ein Feedback freuen.
![DeconzLampemwarnung](https://user-images.githubusercontent.com/18531616/151178254-b3d952db-433e-41f1-81b7-78d5ce602c70.png)

### Adapter Version

1.3.19

### deConz (Phoscon) Version

2.13.4

### JS-Controller Version

5.2.3

### Node JS Version

14.18.3

### NPM Version

6.14.15

### Operating System

Ubuntu

**Comment by Jey-Cee** [comment]
Laut der Dokumentation von Dresden Elektronik sollte da nie ein Wert über 8000 geliefert werden, weil es sich um Kelvin handelt.
Da fehlt wohl die Umrechnung seitens deConz.
Bitte wende dich an Dresden Elektronik.
