### ISSUE TITLE
[Warn]: Group Meldung obwohl keine Gruppe vorhanden

### ISSUE THREAD

**Issue by Instanz1** [Jey-Cee/ioBroker.deconz#292]
### What happened?

Ich erhalte seit heute folgende Warn Meldung im Adapter:

deconz.0 | 2022-02-10 16:10:13.970 | warn | Object Groups.65520.xy is invalid: Default value has to be stringified but received type "object"
-- | -- | -- | --
deconz.0 | 2022-02-10 16:10:13.572 | warn | This object will not be created in future versions. Please report this to the developer.

Die erste Meldung kam um 15:15 Uhr heute

Warum weshalb die Meldung kommt keine Ahnung, am System wurde heute nichts geändert.

### Adapter Version

1.3.19

### deConz (Phoscon) Version

2.14.01 / 6.2.2022

### JS-Controller Version

4.0.5

### Node JS Version

14.19.0

### NPM Version

6.14.16

### Operating System

Ubuntu

**Comment by Jey-Cee** [comment]
In der Überschrift schreibst du das die Gruppe nicht vorhanden ist, kannst du mal den Objektbaum zeigen?

**Comment by Kaiman77** [comment]
Das gleiche Problem hier auch, trat nach dem Update auf js-controller 4.x auf.
