### ISSUE TITLE
[Bug]: Default value has to be stringified but received type "object"

### ISSUE THREAD

**Issue by kneisel** [Jey-Cee/ioBroker.deconz#295]
### Contact Details

kneisel@kneisel-online.de

### What happened?

Hello
... I still get the message: Default value has to be stringified but received type "object"
(although that should have been fixed in 1.3.15 ?)
-> see log entry
BR Peter

### Adapter Version

1.3.19

### deConz (Phoscon) Version

2.13.04

### JS-Controller Version

5.2.51

### Node JS Version

14.19.0

### NPM Version

6.14.16

### Operating System

Debian

### Relevant log output

```shell
deconz.0 | 2022-02-17 20:01:14.826 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
deconz.0 | 2022-02-17 20:01:14.825 | warn | Object Groups.21.xy is invalid: Default value has to be stringified but received type "object"
```

**Comment by MichaelSchaaf999** [comment]
Confirmed: I too get these error messages in the log. 
Anything we can do?

**Comment by MSchmitt67** [comment]
Hallo,
JS-Controller Version 4.0.15 (stable) same problem


```
2022-02-26 00:36:33.442 - warn: deconz.0 (12037) Object Groups.3.xy is invalid: Default value has to be stringified but received type "object"
--
2022-02-26 00:36:33.457 - warn: deconz.0 (12037) This object will not be created in future versions. Please report this to the developer.
```

**Comment by Jey-Cee** [comment]
Please install from Beta channel.

**Comment by MichaelSchaaf999** [comment]
ver 1.3.20 cannot be seen in the Beta Channel:
<img width="312" alt="grafik" src="https://user-images.githubusercontent.com/53481090/155892872-81db801f-5ce4-401c-9cc1-9f455bdaac89.png">

**Comment by Jey-Cee** [comment]
Then you have to install it in Expert mode from npm.

**Comment by hsteinme** [comment]
Just a confirmation: The mentioned log entry does not appear anymore in version 1.3.20 installed from GitHub. Many thanks to @Jey-Cee.
