### ISSUE TITLE
[Bug]: Default value has to be stringified but received type "object"

### ISSUE THREAD

**Issue by jensdersven** [Jey-Cee/ioBroker.deconz#297]
### What happened?

Nach dem js-controller update auf 4.0x kommen folgende Warnungen
Die Meldung kommt für jedes Objekt was diesen Datenpunkt hat.

### Adapter Version

1.3.19

### deConz (Phoscon) Version

2.0.0

### JS-Controller Version

4.0.x

### Node JS Version

14.19.0

### NPM Version

6.14.16

### Operating System

Debian

### Relevant log output

```shell
deconz.0
2022-02-28 00:47:14.134	warn	This object will not be created in future versions. Please report this to the developer.
deconz.0
2022-02-28 00:47:14.134	warn	Object Lights.9.xy is invalid: Default value has to be stringified but received type "object"
```

**Comment by Jey-Cee** [comment]
Danke fürs melden, aber das nächste mal schauen ob der Fehler schon gemeldet wurde.
#295

**Comment by hsteinme** [comment]
Problem ist ja mittlerweile gemäß https://github.com/Jey-Cee/ioBroker.deconz/issues/295 behoben. Könnte daher bitte jemand (@jensdersven oder @Jey-Cee) dieses Issue hier schließen? Heißen Dank im Voraus.
