### ISSUE TITLE
Values for hue (and others) get set in two steps :(

### ISSUE THREAD

**Issue by captaindork** [Jey-Cee/ioBroker.deconz#298]
Hi there,

i am using latest beta iobroker with updated packages and (non headless) deconz with conbee2. (However I feel I had this issue ever since i started 5 years ago :) )
I will describe the issue using a Tradfri E27, however I have very similar issues also with other devices like  Osram.

My primary issue is, that when I use the colorpicker on my iPhone (HomeKit Devices emulated via yahka) the selected color is „jumping“. Meaning if I want to change from red to blue, I get all sords of colors and press 10 times blue, till I finally end up with blue… (similar happens with vis colorpicker, iot(alexa), …)

After I thought this might be related to transitiontimes or ACK-Values, I feel it is related to the following:
If I disable all adapters except deconz (to ensure it’s not influenced by something else) and go to the objects. Let’s assume hue is set to 360. I now set it manually to 120. Then I get a value of 12,76 and afterwards it changes to 120,47 (which would be even fine).

Could you help me finding the reason, why this extra step, jumping shortly to 12,76 happens? I am quite sure this is why I end up in jammed colors in yahka, as it is so quick that it takes the 12,76 value and from there it starts a chain reaction :)

Thanks a lot for any investigation/help

**Comment by Jey-Cee** [comment]
Hi @captaindork, which colormode has the lamps? There is a object with this information, hs or xy are possible values for RGB.
If the value is xy you should use the xy object for control.
It might be that the extra is happen while deconz is convert the hue value to xy and reports this back to iobroker.
