### ISSUE TITLE
Object Lights.61.xy is invalid: Default value has to be stringified but received type "object"

### ISSUE THREAD

**Issue by unstressable** [Jey-Cee/ioBroker.deconz#300]
### What happened?

iobroker says the following, example:

Object Lights.61.xy is invalid: Default value has to be stringified but received type "object"

### Adapter Version

1.3.19

### deConz (Phoscon) Version

2.12.06

### JS-Controller Version

4.0.18

### Node JS Version

14.18.2

### NPM Version

6.14.15

### Operating System

Debian

**Comment by Pedder007** [comment]
Hi, same issue here with multiple lights (seems to be all > 15 from multiple vendors).
Recognized after just having updated to js-controller 4.0.19 and node.js 14.19.0. Might be there before, but if, then haven't recognized.

Further config:
NPM Version: 6.14.15
Operating System: Debian Buster
deConz Adapter Version: 1.3.19
deConz (Phoscon) Version: 2.10.04 / 14.3.2021
Firmware: 26660700

**Comment by TepMan** [comment]
Same here:

deconz.0 | 5525 | 2022-03-12 22:12:11.237 | warn | This object will not be created in future versions. Please report this to the developer.
deconz.0 | 5525 | 2022-03-12 22:12:11.236 | warn | Object Groups.3.xy is invalid: Default value has to be stringified but received type "object"

Adapter 1.3.19
JS-Controller 4.0.19
NodeJS v14.18.2

**Comment by DarkApollo212** [comment]
Hi there, 

i thinnk i had the same problem - and for me it's solved. 
Try to use the adapter version 1.3.20 - iobroker repository has the version 1.3.19. 

At mine it was an IKEA Tradfri RGB Bulb. In Phoson i activated the color loop for this lamp and in iobroker i got warnings every second.  The warnings were like yours. But with version 1.3.20 they are gone :)

**Comment by Pedder007** [comment]
Hi @DarkApollo212, thanks for the valuable tip!
Did the adapter-update and the issues seems having gone (since ~24hours) now.
👍

**Comment by Jey-Cee** [comment]
Seems to be fixed so i close this issue.
