### ISSUE TITLE
Log Warning "State *** has no existing object, this might lead to an error in future versions"

### ISSUE THREAD

**Issue by M4dm4ni4c** [Jey-Cee/ioBroker.deconz#301]
Contact Details
No response

What happened?
Following Warning in Logfile:
```
deconz.0 | 2022-03-30 22:31:02.473 | warn | State "deconz.0.Gateway_info.alive" has no existing object, this might lead to an error in future versions
deconz.0 | 2022-03-30 22:31:00.153 | warn | State "deconz.0.info.connection" has no existing object, this might lead to an error in future versions

```

Adapter Version
1.3.20

deConz (Phoscon) Version
2.14.01 / 6.2.2022

JS-Controller Version
4.0.21

Node JS Version
14.19.1

NPM Version
6.14.16

Operating System
Debian

Relevant log output
No response

Anything else?
No response

**Comment by Jey-Cee** [comment]
Is this warning still there?

If yes is the js-controller version still the same?
