### ISSUE TITLE
has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by sansonifabio** [Jey-Cee/ioBroker.deconz#304]
### What happened?

Hallo [Jey-Cee] seit dem Phoscon Update auf 2.15.3 habe ich diese Fehler:

deconz.0.Sensors.131.buttonpressed" has no existing object, this might lead to an error in future versions 
Es betrifft Lichtschalter von https://www.techpunt.nl/de/xiaomi-aqara-smart-wall-switch-h1.html?id=252375885&quantity=1

Herzlich Grüße 
![schalter](https://user-images.githubusercontent.com/88761140/166408291-afc0a905-ce2c-4eff-ab39-9eaed41100ba.jpg)
Fabio 

### Adapter Version

1.3.20

### deConz (Phoscon) Version

2.15.03

### JS-Controller Version

 4.0.23

### Node JS Version

14.19.1

### NPM Version

6.14.16

### Operating System

Debian

### Relevant log output

```shell
State "deconz.0.Sensors.131.buttonpressed" has no existing object, this might lead to an error in future versions
```

**Comment by Jey-Cee** [comment]
Hi Fabio, kommt die Meldung immer wieder? 
Laut deinem Screenshot existiert das Objekt.

**Comment by sansonifabio** [comment]
> Hi Fabio, kommt die Meldung immer wieder? Laut deinem Screenshot existiert das Objekt.

Hallo Christoph,
das ist ja ein Ding, **die Meldungen kommen nicht mehr.** 
Keine Ahnung was da los war.
Bis gestern Abend kamen sie immer wenn ich die Lichtschalter bestätigt habe. 
Dann schließe ich das mal.
Herzliche Grüße
Fabio
