### ISSUE TITLE
[Bug]: deconz startet nicht bei reboot

### ISSUE THREAD

**Issue by iobFan** [Jey-Cee/ioBroker.deconz#310]
### What happened?

Ich erhalte nach einem system reboot folgenden Log-Eintrag und der Adapter startet nicht. Wenn ich in iobroker dann nochmal manuell restarte, kommt der Adapter hoch und wird grün:

<html>
<body>

deconz.0 | 2022-06-18 10:59:00.610 | warn | Could not connect to websocket instance of deConz/Phoscon. Error: WebSocket was closed before the connection was established
-- | -- | -- | --

</body>
</html>

An was kann das liegen?

### Adapter Version

1.3.21

### deConz (Phoscon) Version

2.16.01 

### JS-Controller Version

 4.0.23

### Node JS Version

v16.15.1

### NPM Version

8.12.2

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Läuft deConz auf dem selben Gerät wie ioBroker?

**Comment by iobFan** [comment]
Ja, laufen beide auf demselben RaspberryPi

**Comment by Jey-Cee** [comment]
Dann hat der Start von deConz zu lange gedauert. Der Adapter versucht sich dann erneut zu verbinden. Der Abstand zwischen den Verbindungsversuchen beträgt mehrere Minuten.
Wie lange hast du gewartet?
