### ISSUE TITLE
[Bug]: Xiaomi Smart Plug dosen't report the temperature to ioB anymore

### ISSUE THREAD

**Issue by fidi2000** [Jey-Cee/ioBroker.deconz#311]
### Contact Details

stefan.philipp@mail.com

### What happened?

Xiaomi Smart Plug dosen't report the temperature anymore. I can't tell exactly since when/what changed but it was working previously. 
What I've changed as known:
- iobroker node update to v16.16.0
- iobroker js update to 8.11.0
- Phoscon-GW version 2.17.01 / 7/1/2022 Firmware 26720700

The temperature get shown in deCONZ but not transmitted to ioBroker:
![picture ioB plug object](https://user-images.githubusercontent.com/78237221/181256033-74fbf6c6-9c72-429a-9f08-d16ad37949df.png)

![picture Phoscon](https://user-images.githubusercontent.com/78237221/181256094-076e88de-b620-4e84-a7fb-1dee4e7b5fe5.png)
![picture ioB plug object data](https://user-images.githubusercontent.com/78237221/181256098-a44135be-e541-4e7d-8c41-b7961177c3fa.png)
![picture ioB plug object commen](https://user-images.githubusercontent.com/78237221/181256100-574a41c9-4932-469d-a488-45d856c2dafd.png)
![picture deCONZ - Xiaomi Smart Plug - basic](https://user-images.githubusercontent.com/78237221/181256102-f3dc4a7c-18af-4116-924e-ca23775ce4e3.png)
![picture deCONZ - Xiaomi Smart Plug - temperture](https://user-images.githubusercontent.com/78237221/181256104-c84576ca-ab9a-4291-ae57-c54b97f3a3da.png)

### Adapter Version

1.3.21

### deConz (Phoscon) Version

2.17.01

### JS-Controller Version

n/a

### Node JS Version

16.16.0

### NPM Version

8.11.0

### Operating System

Ubuntu

### Relevant log output

```shell
The os / dvice I use is Raspbian (rpi 4)
```

**Comment by Jey-Cee** [comment]
Is this issue still there?
If yes a log in debug mode will help to figure out whats the problem.

**Comment by Jey-Cee** [comment]
Closing while no response.
