### ISSUE TITLE
[Bug]: einzelne DPs werden nach Änderung über action DP nicht angepasst

### ISSUE THREAD

**Issue by dercaptainbc** [Jey-Cee/ioBroker.deconz#312]
### Contact Details

info@dercaptain.de

### What happened?

Wenn ich mehrer Befehle auf einmal über den Datenpunkt action ausführen lassen, dann wird das akkurat ausgeführt, aber leider werden die einzelnen Datenpunkte nicht aktualisiert im Anschluss. 

Zum Beispiel wenn ich in den action dp : `"on":true,"bri":100` schreibe wird der dp von bri nicht aktualisiert sondern bleibt bei seinem alten Wert stehen. Aufgefallen ist es mir auch bei dem dp von ct. 

Für mich macht das einige meiner Funktionen kaputt, die auf den aktuellen Wert aus dem dp reagieren und daraus etwas berechnen. Zum Beispiel das beim Knopfdruck der aktuelle ct Wert um 100 reduziert werden soll, den Befehl zum schreiben führe ich dann nämlich über den action dp aus da ich noch transitiontime mit übergeben um das ganze etwas geschmeidiger aussehen zulassen. 

Aufgefallen ist mir das jetzt beim umstrukturieren meiner Installation da ich vorher einen anderen Adapter für das Steuern der Lichter genutzt hatte. Jetzt aber gerne nur noch einen Adapter im Betrieb haben möchte, nicht mehr zwei.

### Adapter Version

1.3.21

### deConz (Phoscon) Version

2.17.01

### JS-Controller Version

4.0.23

### Node JS Version

16.16.0

### NPM Version

8.11.0

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Stell bitte das Log level für die Instanz um und schau dann im Log ob direkt nachdem ausführen des Befehls eine Meldung mit Websocket message am anfang zu sehen ist.

**Comment by Jey-Cee** [comment]
Closing while no response.
