### ISSUE TITLE
[Bug]: Xiaomi Mi Smart Plug DP: Aktueller verbrauch (Power) IO Broker ist immer 0 Watt

### ISSUE THREAD

**Issue by Asche1985** [Jey-Cee/ioBroker.deconz#314]
### What happened?

Seit dem 20.09.2022 liefert der DP power meiner Xiaomi Mi Smart Plug keine Information mehr, wieviel Strom aktuell verbraucht wird. Vor dem 20.09.2022 lieferte der DP zuverlässig Werte. 

### Adapter Version

1.3.21

### deConz (Phoscon) Version

2.18.2

### JS-Controller Version

4.0.23

### Node JS Version

16.17.0

### NPM Version

8.15.0

### Operating System

Ubuntu

### Anything else?

Ich weiß, dass DECONZ eine neue Stable Version rausgebracht hat. Kann es damit was zu tun haben?

**Comment by Jey-Cee** [comment]
Ja wird vermutlich an der neuen Version liegen. Es gibt immer wieder Änderungen an der API. 
Kannst du mal das Log Level auf debug stellen und dann hier als Text Datei an zu hängen.

**Comment by Asche1985** [comment]
Hat ein bisschen gedauert aber hier die ersten logs. Wenn du einen längeren Eintrag benötigst, sag bescheid. 
[iobroker.2022-09-29.log](https://github.com/Jey-Cee/ioBroker.deconz/files/9678972/iobroker.2022-09-29.log)
[iobroker.2022-09-29.txt](https://github.com/Jey-Cee/ioBroker.deconz/files/9678973/iobroker.2022-09-29.txt)

**Comment by Asche1985** [comment]
Ich hab mal ein wenig geschaut und es scheint ein Fehler bei Deconz zu sein. 2.18.https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6342

**Comment by Asche1985** [comment]
Ich konnte den Fehler mit einem downgrade auf die Deconz Version 2.17.01 lösen. Scheint also kein Problem vom Adapter gewesen zu sein. Ich schließe das Ticket.

**Comment by Jey-Cee** [comment]
Danke für die Rückmeldung.
