### ISSUE TITLE
[Bug]: IDs

### ISSUE THREAD

**Issue by Mephisto090** [Jey-Cee/ioBroker.deconz#315]
### What happened?

Hallo,

wenn ich das Gerät neu hinzufügen muss werden neue IDs generiert. Lässt es sich so umbauen, dass die selbe ID genommen wird?
Kann das Programm nicht die erste Freie ID nutzen? Ich habe 5 Geräte und bin schon bei Nummer 18 angekommen :)

VG

### Adapter Version

1.3.21

### deConz (Phoscon) Version

2.18.02

### JS-Controller Version

aktuell

### Node JS Version

v16.17.1

### NPM Version

8.15.0

### Operating System

Windows (docker)

**Comment by Jey-Cee** [comment]
Die IDs kommen von deConz, da hat der Adapter keinen Einfluss.

**Comment by Mephisto090** [comment]
Alles klar. Danke
