### ISSUE TITLE
How to add _TZE200_e9ba97vf Thermostat Radiator Valve

### ISSUE THREAD

**Issue by PastCoder** [Jey-Cee/ioBroker.deconz#317]
Hi,
is there a way to use this device in this adapter? I can see it in the deconz GIU (but not in the Conbee web page). But it does not appear anywhere else.
Thanks for your support

**Comment by Jey-Cee** [comment]
I think you have  already read that this device is not integrated in deconz rest api. So the answer is No.

**Comment by PastCoder** [comment]
Does this mean I have to look for some completely different alternative (e.g. Zigbee2mqtt)? Would be a pitty to adjust all existing scripts. But if I understand it right, that's the way I have to go, right?

**Comment by Jey-Cee** [comment]
You can create a DDF file by your own (and you can contribute it to the project).
Here is some explanation of the DDF file: https://dresden-elektronik.github.io/deconz-dev-doc/modules/ddf/
As i know there is a DDF Editor in the deconz GUI.
