### ISSUE TITLE
[Bug]: Xiaomi Light Sensor lumi.sen_ill.mgl01 not working

### ISSUE THREAD

**Issue by copperfield74** [Jey-Cee/ioBroker.deconz#321]
### Contact Details

chestersass@web.de

### What happened?

My XIAOMI Light Sensor lumi.sen_ill.mgl01 used to work in the past. I think with the update to v2.18.2 did destroy the function. Now I've updated to v2.19.1 and it still doesn't work. I can connect the sensor to my ConbeeII stick and it's also listed on the DeconzApp, but it always shows 0LUX. If I look into the adapter I can see that it shows STATUS: NOT REACHABLE
![grafik](https://user-images.githubusercontent.com/62651258/203392139-48f782b9-2b3e-4620-b77a-d568ff2f12d3.png)
![grafik](https://user-images.githubusercontent.com/62651258/203392424-0ba77ed7-5eec-4ebe-814e-5e290337b7a9.png)

### Adapter Version

1.3.21

### deConz (Phoscon) Version

2.19.01

### JS-Controller Version

4.0.23

### Node JS Version

14.21.1

### NPM Version

6.14.17

### Operating System

Debian

**Comment by Jey-Cee** [comment]
This seems to be a problem with deConz itself as phoscon say as well not reachable in your screenshot.

**Comment by Jey-Cee** [comment]
Closing while inactive.
