### ISSUE TITLE
[Bug]:Websocket port not configurable

### ISSUE THREAD

**Issue by Chris-FB** [Jey-Cee/ioBroker.deconz#328]
### What happened?

The prot for the Websocket should be configurable. Since it's possible to run deconz as container, the default port 443/tcp is probably used for a different service.

Is it possible to change the WS Port? 

My deconz container exports port 7443/tcp.

```
deconzcommunity/deconz:stable   "/start.sh"              4 days ago   Up 4 days (healthy)   5900/tcp, 6080/tcp, 0.0.0.0:7080->80/tcp, :::7080->80/tcp, 0.0.0.0:7443->443/tcp, :::7443->443/tcp
 deconz
```

### Adapter Version

1.3.21

### deConz (Phoscon) Version

2.20.1

### JS-Controller Version

4.0.23

### Node JS Version

v14.15.0

### NPM Version

6.14.8

### Operating System

Debian

### Relevant log output

```shell
deconz.0 | 2023-03-15 16:11:48.860 | warn | Could not connect to websocket instance of deConz/Phoscon. Error: connect ECONNREFUSED 192.168.178.5:443
```

**Comment by Jey-Cee** [comment]
Ok i see the problem. Will add this soon.

**Comment by Chris-FB** [comment]
Hi, 
thank you for you work. But it's not working. I can set the websocket port, but in the backgroud port 443 is used. 
<html>
<body>


deconz.0 | 2023-04-02 10:43:48.788 | warn | Could not connect to websocket instance of deConz/Phoscon. Error: connect ECONNREFUSED 192.168.178.5:443
-- | -- | -- | --



</body>
</html>

![image](https://user-images.githubusercontent.com/127969520/229342694-6a693eeb-4f72-4987-9872-077616f5ac2b.png)

If I keep this settings and change the deconz websocket to port 443, the iobroker.deconz plugin is working.

**Comment by Jey-Cee** [comment]
Was the adapter running while you have set the port in the config?

**Comment by Chris-FB** [comment]
Yes, the adapter was running.

**Comment by daneb255** [comment]
Still the old 443 port is used :(
