### ISSUE TITLE
[Bug]: NOUS A1Z Zigbee Steckdosen lassen sich nicht mehr schalten bzw. Änderungen am Schaltzustand werden nicht erkannt

### ISSUE THREAD

**Issue by myssv** [Jey-Cee/ioBroker.deconz#329]
### Contact Details

github@myssv.de

### What happened?

NOUS A1Z Zigbee Steckdosen lassen sich nicht mehr schalten bzw. Änderungen am Schaltzustand werden nicht erkannt:

Der Datenpunkt "on" bleibt immer auf True, selbst wenn ich die Steckdose manuell ausschalte. Andersherum kann ich mit dem Datenpunkt die Steckdosen nicht mehr ausschalten. Es hat schon mal funktioniert, kann aber nicht sagen, seit wann es nicht mehr so ist.

### Adapter Version

1.3.21

### deConz (Phoscon) Version

2.21.02 / 19.9.2022

### JS-Controller Version

6.1.4

### Node JS Version

18.16.0

### NPM Version

9.5.1

### Operating System

Debian

### Relevant log output

```shell
./.
```

**Comment by Jey-Cee** [comment]
Bitte erst mal deConz auf die Aktuellste version bringen.

**Comment by myssv** [comment]
v2.21.2 ist doch die aktuelle Version. Danach gab es nur noch die Beta v2.22.0 

Ich habe gerade das Phoscon Gateway updaten lassen und da kam auch keine neuere deConz Version

Oder was meinst Du?

**Comment by Jey-Cee** [comment]
Ich hatte aufs release Datum geschaut das du angegeben hast, das war letztes Jahr. 

Der Adapter implementiert keine Geräte sondern die Api und behandelt dann entsprechend die Anfragen auf Gerätetypen Ebene. Da hier schon lange nichts geändert wurde und auch niemand anderes Probleme mit Geräten gemeldet hat geh ich davon aus das es an der Implementierung vom Gerät in deConz liegt. 
Wenn du wüsstest mit welcher version es zuletzt funktioniert hat kannst du auf fie zurück gehen um das tu Prüfen.

**Comment by myssv** [comment]
So wird es mir in der Phoscon App angezeigt:

![grafik](https://github.com/Jey-Cee/ioBroker.deconz/assets/65643813/ea6c2b0c-5908-417d-974f-c81c66110a4b)

Ich habe aber beim Testen festgestellt, dass ich mit der Phoscon App die Schalter auch nicht mehr schalten kann und habe auch mal den Dresden Support an geschrieben.

**Comment by Jey-Cee** [comment]
Dann schließe ich hier mal.

**Comment by myssv** [comment]
Ich bin einen Schritt weiter:

Mit den "On" Datenpunkten unter deconz/Sensors/n/consumption bzw.  deconz/Sensors/n/power  funktioniert es nicht mehr.

Mit dem Datenpunkt deconz/Lights/n/on funktioniert es immer noch.

**Comment by Jey-Cee** [comment]
> Mit den "On" Datenpunkten unter deconz/Sensors/n/consumption bzw. deconz/Sensors/n/power funktioniert es nicht mehr.

Damit dürfte es noch nie Funktioniert haben, da die Steuerung immer nur über Lights geht.

**Comment by myssv** [comment]
Ich habe 12 dieser Steckdosen in meiner VIS und alle waren mit dem Datenpunkt "power/on".

Ich könnte schwören, dass ich das seinerzeit auch getestet habe.

Egal, nun geht es wieder. Danke!
