### ISSUE TITLE
[Issue]: deconz.0.Sensors.Id or deconz.0.sensors.MACAdress 

### ISSUE THREAD

**Issue by mayokleckz** [Jey-Cee/ioBroker.deconz#331]
### Contact Details

smilegrins@web.de

### What happened?

Hi,
during last week the path for the object has changed again. Once it was Sensors.Id and became sensors.MacAdress, now it is again Sensors.Id.
Is this correct?

### Adapter Version

1.3.21

### deConz (Phoscon) Version

2.21.02

### JS-Controller Version

5.0.4

### Node JS Version

18.16.0

### NPM Version

9.5.1

### Operating System

Debian

**Comment by Jey-Cee** [comment]
There was no change since a long time. 
I think you updated (downgraded) from 2.x.x to 1.3.21. 
The development of 2.x.x was stopped 2 years ago, as there was a lot of problems.

**Comment by mayokleckz** [comment]
clarified.
