### ISSUE TITLE
[Bug]: Use latest API - Update needed

### ISSUE THREAD

**Issue by Siggi0904** [Jey-Cee/ioBroker.deconz#332]
### What happened?

In refer to latest changes at phoscon rest updates please take a look at actual API.
See https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/#window-covering-parameters

Many devices won't work like Ikea blinds etc.

This was discussed at phoscon form too.
https://forum.phoscon.de/t/cant-control-fyrtur-via-phoscon/3764/11

### Adapter Version

1.3.21

### deConz (Phoscon) Version

2.22.0.2

### JS-Controller Version

4.0.24

### Node JS Version

18.16.1

### NPM Version

9.5.1

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Thank you for this hint. I am on heavy load actually and can not say when i have the time to change this.

**Comment by Siggi0904** [comment]
Okay, bad to hear, hopefully we get an update in next time.

**Comment by Jey-Cee** [comment]
You can use the action object to control the blinds. Use the parameters from the link like open and set action to  "open":"true"

**Comment by Siggi0904** [comment]
Okay, but how with iobroker?
We switched back to old ddf and it works for now.

**Comment by Jey-Cee** [comment]
> Okay, but how with iobroker?

??? ->>> You can use the action object to control the blinds. Use the parameters from the link like open and set action to "open":"true"

**Comment by Siggi0904** [comment]
Hi,
It's not possible to use your way. The DDF from deconz is not read correctly and with that,
I cannot communicate with deconz over iobroker.

If I did not understand your way, please guide me in iobroker.
Thanks.

**Comment by C4mp3r-Grey** [comment]
Have the same problem and found this discussion. I run
- Deconz in Docker on RPi4 2_22_2
- IOBroker 6.3.5 in Docker with Deconz Zigbee 2.0.7 manually installed from GitHub
- IKEA Fyrtur on Fw 24.4.11

**Thanks Jey-Cee for your hint, however it took me some time to understand how to set the "action" string.**

**The following strings entered in the `deconz.0.lights.[hex-adress].action` as string work for me:**
`"lift": 100, "open": false` --> lowers the blind to maximum
`"lift": 50, "open": false`  -->lowers/raises the blind to half
`"lift": 0, "open": true` --> raises the blind to the minimum, its open.

Remark: When I started my trials with `"open": false` or `"open": true`, it
- sometimes worked as expected,
- often results in a stop after 1-2 seconds and proceeding after some more seconds, but also
- occassionally stops after 1-2 seconds and only proceeds when writing the action attribute again.

Cheers
C4mper

**Comment by C4mp3r-Grey** [comment]
Update: is still not reliable - although "action" is updated correctly by a javascript, one of two blinds does not react any more. 

Damn, the WAF is falling quickly...

**Comment by C4mp3r-Grey** [comment]
Update 2: having not change anything, everthing runs finde and quickly since this morming. Maybe the zigbee net was overloaded? Don't now how to check that.

Now it runs as expected by using the `action` string through blocky. Fine for me right now.

The big report however is still valid

Anyway, big thanks for all that freeware and your time spent!

**Comment by Jey-Cee** [comment]
Checkout #339

**Comment by Grizzelbee** [comment]
> Checkout https://github.com/Jey-Cee/ioBroker.deconz/pull/339

Please delete your existing blinds devices in object tree first to avoid confusion since completely new DPs with new names will be created for blinds aka window covers.
