### ISSUE TITLE
[Bug]:  DP Level ändert sich nicht auf 0 %, wenn Licht ausgeschaltet wurde

### ISSUE THREAD

**Issue by Stormbringer11** [Jey-Cee/ioBroker.deconz#334]
### What happened?

Halllo  Jey-Cee,

die Überschrift sagt eigentlich schon alles ;-) Wenn man ein Licht ausschaltet bleibt der DP Level "kleben" und geht nicht auf null, siehe Screenshot:

<img width="1328" alt="Bildschirmfoto 2023-07-09 um 12 12 10" src="https://github.com/Jey-Cee/ioBroker.deconz/assets/43651672/86f8f15b-eb2e-456f-a4d3-92309950b880">

Dadurch funktioniert z. B. die Stormberechnung via Virtual Powermeter nicht. Die anderen Adapter wie z. B. Hue  verhalten sich richtig und setzen das Level, dann auf 0 % wenn das Licht ausgeschaltet wird.

<img width="1297" alt="Bildschirmfoto 2023-07-09 um 12 11 33" src="https://github.com/Jey-Cee/ioBroker.deconz/assets/43651672/f14f9d03-2078-4d1c-9522-3db42ddc78cf">

Siehst du eine Möglichkeit, dass irgendwie und irgendwann zu fixen?

Danke und noch einen schönen Sonntag.

### Adapter Version

1.3.21

### deConz (Phoscon) Version

2.21.2

### JS-Controller Version

4.0.24

### Node JS Version

18.16.1

### NPM Version

9.5.1

### Operating System

Ubuntu

**Comment by Jey-Cee** [comment]
> Die anderen Adapter wie z. B. Hue verhalten sich richtig und setzen das Level, dann auf 0 % wenn das Licht ausgeschaltet wird.

Wer sagt das es das richtige verhalten ist? Der Level ist eine Einstellung und kein Zustand sowie on.
Im Bezug auf Virtual Powermeter wäre es auch sehr viel besser wenn Virtual Powermeter die Möglichkeit bietet den Zustand und nicht nur die Einstellung zu Berücksichtigen.

> Siehst du eine Möglichkeit, dass irgendwie und irgendwann zu fixen?

Für mich ist das kein Bug. 
deConz setzt nicht den Helligkeitswert auf 0 wenn on benutzt wird (so wie das andere vielleicht machen), sondern Schaltet tatsächlich die Lampe einfach ab. 
Das heist der Helligkeitswert bleibt in der Lampe gespeichert so dass sie Unabhängig davon woher der Einschalt befehl kommt wieder die selbe Helligkeit hat.

Für den Adapter würden sich aus solch einer Änderung folgende Situationen ergeben:
- Der Adapter setzt den Wert Nachträglich auf 0, der Wert stimmt dann nicht weil in der Lampe ein anderer Wert steht. Außerdem verursacht das jedesmal eine Warnmeldung weil die API die Änderung nicht annimmt wenn die Lampe Aus ist, was zur Folge hat das es X Meldungen von Benutzern gibt "Ständige Fehlermeldungen vom deConz Adapter".
- Der Adapter setzt den Wert auf 0 und die Lampe wird nur über die Helligkeit abgeschalten, die Lampe kann dann nicht mehr mit dem zuletzt eingestellten Wert eingeschalten werden. Was vermutlich bei einigen Usern zu Irritationen oder sogar Problemen führt wenn sie neben ioBroker auch noch Fernbedienungen oder Apps zum Steuern benutzen.

So eine Änderung will gut Überlegt sein.

**Comment by Stormbringer11** [comment]
Danke für die schnell Rückmeldung. Denke das ist jetzt Ansichtssache welcher Adapter sich richtiger verhält 😉 Habe gerade bei Hue getestet, der zieht sich dann auch wieder das vorherige Level wenn die Lampe wieder eingeschaltet wird. Verstehe aber auch, dass du es nicht einfach ändern kannst bzw. willst weil Deconz halt ned Hue ist 😋 Ich frag mal den Entwickler von Virtualpower Meter. Vielleicht kann der mir weiter helfen. Trotzdem vielen Dank.
