### ISSUE TITLE
Question: old Adapter Version 2.06 => 2.07 Update

### ISSUE THREAD

**Issue by easybeat** [Jey-Cee/ioBroker.deconz#337]
Hi

I'm running a very old version of deconz adapter and got notified to update to 2.07 via Github URL.

I did this on console command "iobroker upgrade deconz + url". But it is still showing version 2.06.

Did the update work and should it show version 2.07?

Thanks for help.

Cheers

Beat

**Comment by Jey-Cee** [comment]
I think you did it wrong:
![grafik](https://github.com/Jey-Cee/ioBroker.deconz/assets/16007760/0c48dc8f-0563-44fc-8e23-5a7da454bc24)

**Comment by easybeat** [comment]
Ja, meine ioBroker Instance will mir diesen Dialog nicht anzeigen. Daher habe ich es über die Konsole versucht. Geht das denn nicht über die Konsole?

**Comment by Jey-Cee** [comment]
Expertenmodus einschalten und auf das Octocat Symbol klicken.
Konsole ist kein Empfohlener weg.

**Comment by easybeat** [comment]
Das funktioniert eben bei dieser ioBroker Version nicht mehr...ist irgendwas verschossen!

Gibt es da keinen Weg über die Konsole?

**Comment by Jey-Cee** [comment]
npm install https://github.com/Jey-Cee/ioBroker.deconz/tree/2.0.6

**Comment by easybeat** [comment]
![image](https://github.com/Jey-Cee/ioBroker.deconz/assets/37217887/c444872a-c19c-41b6-8bbc-70cc7e600e56)

nein da fehlt wohl was

**Comment by Jey-Cee** [comment]
Versuchs mal so https://github.com/Jey-Cee/ioBroker.deconz.git#2.0.6

**Comment by easybeat** [comment]
![image](https://github.com/Jey-Cee/ioBroker.deconz/assets/37217887/46b077b4-9f89-4e0e-84e1-e6886e9cdeb1)
![image](https://github.com/Jey-Cee/ioBroker.deconz/assets/37217887/54e4915e-b017-4890-8fb4-e9df93156a85)
Danke Christoph
nun ist etwas gelaufen aber ich bin mir nicht sicher ob das geklappt hat. Adapter Version zeigt immer noch 2.06 an?

**Comment by Jey-Cee** [comment]
Dann musst du noch ein iob upload deconz hinter herschieben

**Comment by easybeat** [comment]
![image](https://github.com/Jey-Cee/ioBroker.deconz/assets/37217887/80e2dea2-7095-46c7-856b-49e82aecd225)

danach zeigt er aber immer noch 2.06 an

**Comment by Jey-Cee** [comment]
Ok jetzt seh ich das Problem. Ich dachte es wäre klar das du den Befehl npm install in opt/iobroker Ausführen musst.

**Comment by easybeat** [comment]
![image](https://github.com/Jey-Cee/ioBroker.deconz/assets/37217887/2ef37707-26f9-4f6a-a574-978765e4cbd4)

Du bist ein Held!! Vielen vielen Dank!!
