### ISSUE TITLE
Motion Sensor twice

### ISSUE THREAD

**Issue by GodHunter** [Jey-Cee/ioBroker.deconz#34]
Hi,

i had bought some Xiamoi Motion Sensors. After adding them to phoscon it generates 2 Objects in iobroker (e.g. Sensor_2 & Sensor_3). Its not a problem at all, but maybe its a bug ;)

**Comment by Jey-Cee** [comment]
No it isnt a bug, it is completly correct. Phoscon handles it as one device, but under the hood there are more than one device.
The Adapter delivers the "raw" data.
