### ISSUE TITLE
[Bug]: websocket port problem

### ISSUE THREAD

**Issue by 5G7K** [Jey-Cee/ioBroker.deconz#340]
### Contact Details

mail-andreas@gmx.de

### What happened?

Adapter Version 1.3.22
Could not connect to websocket instance of deConz/Phoscon. Error: connect ECONNREFUSED 192.168.3.102:443

Websocket port field was empty after update to 1.3.22
Found in log that port 8088 is the correct one
Inserted Port 8088 and save and restarted. Port 8088 saved.
But in log still Port 443: Could not connect to websocket instance of deConz/Phoscon. Error: connect ECONNREFUSED 192.168.3.102:443

### Adapter Version

1.3.22

### deConz (Phoscon) Version

2.23.02

### JS-Controller Version

5.0.13

### Node JS Version

18.18.2

### NPM Version

9.8.1

### Operating System

Ubuntu

**Comment by Jey-Cee** [comment]
See #327

**Comment by 5G7K** [comment]
ich habe den Port nicht bewusst geändert.
Bin nun zurück auf 1.3.21 und alles funktioniert einwandfrei

mit 1.3.21 folgendes Log wo der Port 8088 drin steht:
`2023-10-20 21:24:59.907 - debug: deconz.0 (5841) Code 200: Request succeded get config: {"UTC":"2023-10-20T19:24:59","apiversion":"1.16.0","backup":{"errorcode":0,"status":"idle"},"bridgeid":"002XXXXXXXXX15F1","datastoreversion":"93","devicename":"ConBee II","dhcp":true,"disablePermitJoinAutoOff":false,"factorynew":false,"fwversion":"0x26780700","gateway":"192.168.3.1","internetservices":{"internet":"connected","remoteaccess":"disconnected","swupdate":"connected","time":"connected"},"ipaddress":"192.168.3.102","lightlastseeninterval":60,"linkbutton":false,"localtime":"2023-10-20T21:24:59","mac":"dc:XXXXXXXXXX:8e","modelid":"deCONZ","name":"Phoscon-GW","netmask":"255.255.255.0","networkopenduration":180,"panid":41984,"portalconnection":"disconnected","portalservices":false,"portalstate":{"communication":"disconnected","incoming":false,"outgoing":false,"signedon":false},"proxyaddress":"none","proxyport":0,"replacesbridgeid":null,"rfconnected":true,"starterkitid":"","swupdate":{"checkforupdate":false,"devicetypes":{"bridge":false,"lights":[],"sensors":[]},"notify":false,"text":"","updatestate":0,"url":""},"swupdate2":{"autoinstall":{"on":false,"updatetime":""},"bridge":{"lastinstall":"2023-10-01T12:32:06","state":"noupdates"},"checkforupdate":false,"lastchange":"","state":"noupdates"},"swversion":"2.23.2","timeformat":"24h","timezone":"Europe/Berlin","uuid":"2dXXXX9-7425-4831-bcd1-7XXXXXXXXX2","websocketnotifyall":true,"websocketport":8088,"whitelist":{"06C01506AB":{"create date":"2020-11-27T18:38:05","last use date":"2020-11-27T20:32:58","name":`

Fehler dann
2023-10-20 20:57:16.264 - warn: deconz.0 (19529) Could not connect to websocket instance of deConz/Phoscon. Error: connect ECONNREFUSED 192.168.3.102:443

**Comment by groovegranate** [comment]
Adapter Version 1.3.23

the instruction "b) Enter port number, standard is 80" at readme.md does not work without set a websocket.

correct: Enter standard Bridge Port: 80 and standard Websocket: 443

**Comment by Jey-Cee** [comment]
Fixed with 1.3.23
