### ISSUE TITLE
[Bug]: Osram Plug is not a light

### ISSUE THREAD

**Issue by GermanSheepDog** [Jey-Cee/ioBroker.deconz#341]
### What happened?

An Osram Lightify Plug is adopted by the Phoscon app not as an adapter plug, but as a light in I-broker. This means that the plug cannot be controlled and is also “not reachable”.

### Adapter Version

1.3.21

### deConz (Phoscon) Version

2.24.1

### Node JS Version

v16.20.2

### NPM Version

8.19.4

### Operating System

Ubuntu

### Relevant log output

In ioBroker I saw: Plug 1 | 2 | OSRAM | Plug 01 | light

**Comment by Jey-Cee** [comment]
Plugs are always represented as a light in deConz API, so they shown in ioBroker as a light and can controlled by the "on" state.
If there is a measurement function there will be also a device under sensors.

**Comment by GermanSheepDog** [comment]
@Jey-Cee : My mistake: I deleted the plug and retrained it and now it works great. THANK YOU
