### ISSUE TITLE
[Bug]: Einige Objekte funktionieren nicht richtig

### ISSUE THREAD

**Issue by mattreim** [Jey-Cee/ioBroker.deconz#348]
### What happened?

Hallo Jey-Cee,

leider lassen sich einige Objekte mit dem Adapter nicht steuern. Lesen scheint aber zu funktionieren. Gerade muss ich zum Schreiben entweder Node-Red oder Tabbed Postman/Rested benutzen. Hier einige, die ich gerne verwenden würde.

1. Preset (string) zum Steuern des Thermostat-Modus (Tuya)

Iobroker:
![Preset-ioBroker](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/f6837458-1281-4357-a5b0-3c40e4f2f45d)

Deconz:
![Preset-Deconz](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/b5450895-8777-4e55-8622-a3f877fe327b)

Rested:
![Preset-Rested](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/aa479495-3d33-437c-810c-3fbad0c702e4)

2. Windowopen_set (boolean) Fensteröffnungserkennung (Tuya)

Iobroker:
![Windowopen_set-ioBroker](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/f6be4826-6142-41fe-a895-84cd7734f11d)

Deconz-DDF:
![Windowopen_set-DDF-Deconz](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/bc4cfc85-9407-4ad5-bebc-007c63bb39a0)

Tabbed Postman:
![Windowopen_set-Postman](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/1ce28127-ef2e-4226-a918-fe7c68c5a46e)

3. Mode (string) zum Steuern des Thermostat-Modus (Bosch)

Iobroker:
![Mode-ioBroker](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/fd74e105-12f2-40fe-840c-fd60ee8444a3)

Deconz-DDF:
![Mode-DDF-Deconz](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/c3d21796-6627-4bb8-8690-595c4698dd57)

4. Externalwindowopen (boolean) Fensteröffnungserkennung (Bosch)

Iobroker:
![Externalwindowopen-ioBroker](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/3355a704-7775-4ea5-b89b-23a9f549b0c0)

Deconz-DDF:
![Externalwindowopen-DDF-Deconz](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/511c9a29-ab14-4d8c-ad66-a1a371a9f7ed)

5. Externalsensortemp (value) Temperaturerkennung über einen anderen Sensor (Bosch)

Iobroker:
![Externalsensortemp-ioBroker](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/db243a6c-542c-43f0-be3c-2177ae8fc967)

Deconz-DDF:
![Externalsensortemp-DDF-Deconz](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/0448dac3-3fa7-48bc-aa99-b7adba27e537)

### Adapter Version

1.3.23

### deConz (Phoscon) Version

2.15.1-beta

### JS-Controller Version

5.0.17

### Node JS Version

18.19.0

### NPM Version

10.2.3

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Wie ich in meinem Kommentar bei deinem Fork schon geschrieben habe müssen zu den jeweiligen Objekten auch entsprechende Funktionen geschrieben werden die die Daten dann richtig an deConz schicken. 

Da ich schon an einer gänzlich neuen Version Arbeite, werde ich das jetzt hier nicht mehr einbauen. Solltest du einen PR mit den entsprechenden Änderungen machen werde ich ihn Prüfen und annehmen.

**Comment by mattreim** [comment]
Danke!
