### ISSUE TITLE
Don't display helper groups

### ISSUE THREAD

**Issue by thewhobox** [Jey-Cee/ioBroker.deconz#35]
Hey,

i just got my conbee and connected iobroker with it.
Its working good with fast updates, but one point is not so good.
In my list i have 8 groups with name like "FLS-PP3 helper1 for group 17".
You should not display them in iobroker and skip them in [Line 711](https://github.com/iobroker-community-adapters/ioBroker.deconz/blob/master/main.js#L711).

Also the states are a bit confusing, maybe you can create channels for lights, groups and sensors?

**Comment by Jey-Cee** [comment]
Can you tell me what the helper groups are for? I havent seen it.

**Comment by thewhobox** [comment]
I think they are just for deconz.
I cant Control anything with them.
![image](https://user-images.githubusercontent.com/45664417/54498483-6257d480-4908-11e9-8cde-25674d23bfe5.png)

I [forked ](https://github.com/thewhobox/ioBroker.deconz)your Adapter and skip every help Group (regex).
It also binds state "bri" with state "on" (on = bri > 0) which is needed if you want to Control it with Alexa.

**Comment by thewhobox** [comment]
Same for Sensors.
I have a lot Sensors with Name "CLIP-Sensor TOGGLE-ON-OFF"
![image](https://user-images.githubusercontent.com/45664417/54498623-02622d80-490a-11e9-9e72-38ec942f3d06.png)

(Maybe you could also make for Sensors, Lights and Groups seperated Channels.

**Comment by thewhobox** [comment]
Hey,
Also it seems to over write All channeles and objects when the Adapter restarts.
If you want to use it with Alexa you have to add the smartname to wach state, but after restart iot Adapter cant find any Devices (cause it was overwritten).
You should only overwrite a view attributes only or extract smartname bevor and write it with the Update attributes.

**Comment by thewhobox** [comment]
Fixed with pull Request https://github.com/iobroker-community-adapters/ioBroker.deconz/pull/38
