### ISSUE TITLE
Paid or Free - what about release 1.4.0 ?

### ISSUE THREAD

**Issue by mcm1957** [Jey-Cee/ioBroker.deconz#354]
PLEASE STATE WHETHER RELEASE 1.4.0 IS STILL FREE or requires already a paid license?

Accoring to you posts at forum.iobroker.net ALL you adapters will be commercial / require a paid license. Theres no such informatuion at release 1.4.0. So please clearify if 1.4.0 is still free - or not-

**Comment by Jey-Cee** [comment]
This is not necessary because it is then very clear that it requires a license. Display in the adapter tile and breaking change message that is displayed before the update.

**Comment by mcm1957** [comment]
Don't understand the answer. Maybe the question was not clear. Waht I want to know is:

Is 1.4.0 still free or does it already require a license?

**Comment by Jey-Cee** [comment]
No as you can see there is no licenseInformation with paid, no message in io-package.json that says from now on you have to get a paid license, no comment about paid in readme and no license field in the configuration.

**Comment by mcm1957** [comment]
> No as you can see there is no licenseInformation with paid, no message in io-package.json that says from now on you have to get a paid license, no comment about paid in readme and no license field in the configuration.

Thanks for clarification.
