### ISSUE TITLE
[Bug]: Settings fields are saving without pressing save!

### ISSUE THREAD

**Issue by unstressable** [Jey-Cee/ioBroker.deconz#358]
### What happened?

When changing some fields e.g. the IP-Adress or Port the save-button is gray ond not clickable.
By exiting without saving (cancel) it will save the changes.

There seem to be some other bugs with the setting-buttons. Please double-check.

### Adapter Version

1.4.0

### deConz (Phoscon) Version

2.26.1

### JS-Controller Version

5.0.19

### Node JS Version

18.17.1

### NPM Version

9.6.7

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Please test version 1.6.1 which is available as beta.

**Comment by unstressable** [comment]
I'm not able to test beta-software in my live-environment.
Maybe anyone else?

**Comment by mattreim** [comment]
The error has been fixed, it is now only saved when the save button is pressed. 

@Jey-Cee This can now be closed.
