### ISSUE TITLE
[Bug]: ct-Value too high. Appeared with the latest version

### ISSUE THREAD

**Issue by unstressable** [Jey-Cee/ioBroker.deconz#359]
### What happened?

Since some weeks I see these errors in my log:
State value to set for "deconz.0.Lights.31.ct" has value "28673" greater than max "8000"

It happened suddenly without any changes except updates of deconz and phoson container (Docker)

I think the number of light-groups that are claiming this is increasing.

### Adapter Version

1.4.0

### deConz (Phoscon) Version

2.26.3

### JS-Controller Version

5.0.19

### Node JS Version

18.20.2

### NPM Version

10.5.2

### Operating System

Ubuntu

### Relevant log output

```shell
deconz.0
2024-04-29 21:12:46.667	warn	State value to set for "deconz.0.Lights.27.ct" has value "27878" greater than max "8000"

deconz.0
2024-04-29 21:12:45.905	warn	State value to set for "deconz.0.Lights.31.ct" has value "28382" greater than max "8000"

deconz.0
2024-04-29 21:12:45.660	warn	State value to set for "deconz.0.Lights.27.ct" has value "28170" greater than max "8000"

deconz.0
2024-04-29 21:12:44.829	warn	State value to set for "deconz.0.Lights.31.ct" has value "28673" greater than max "8000"

deconz.0
2024-04-29 21:12:44.645	warn	State value to set for "deconz.0.Lights.27.ct" has value "28462" greater than max "8000"

deconz.0
2024-04-29 21:12:43.849	warn	State value to set for "deconz.0.Lights.31.ct" has value "28965" greater than max "8000"

deconz.0
2024-04-29 21:12:43.557	warn	State value to set for "deconz.0.Lights.27.ct" has value "28754" greater than max "8000"

deconz.0
2024-04-29 21:12:42.708	warn	State value to set for "deconz.0.Lights.31.ct" has value "29258" greater than max "8000"

deconz.0
2024-04-29 21:12:42.593	warn	State value to set for "deconz.0.Lights.27.ct" has value "29044" greater than max "8000"

deconz.0
2024-04-29 21:12:41.805	warn	State value to set for "deconz.0.Lights.31.ct" has value "29550" greater than max "8000"

deconz.0
2024-04-29 21:12:41.583	warn	State value to set for "deconz.0.Lights.27.ct" has value "29336" greater than max "8000"
```

**Comment by mattreim** [comment]
What kind of devices are these (company/model)? Just out of interest.

**Comment by unstressable** [comment]
Philips Hue Gu10 tuneable white (latest with bluetooth)

**Comment by mattreim** [comment]
think the device is not yet properly supported by deConz. You can use RESTED/[deConz REST-API](https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/) to check whether the correct values ​​are being transferred.

`GET ->  http://<IP>/api/<apikey>/lights/<ID>`

**Comment by unstressable** [comment]
I habe these devices since about 4 years now and I never had problems.

I think it is supported yet.

**Comment by mattreim** [comment]
They are currently converting all devices to DDF and yours must also be included in one.

**Comment by mattreim** [comment]
But it could also be related to this: [deconz-rest-plugin](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7704)

**Comment by unstressable** [comment]
I dont know what ddf is, I dont know why this error happened suddenly without any changes in my setting.
Now I changed the log level to "fault" and I hope its silence now ;)

**Comment by TimoGoerlich** [comment]
I have the same issue with a Hue Lightstrip. Also appeared suddenly after update.

State value to set for "deconz.0.Lights.60.ct" has value "42404" greater than max "8000"

**Comment by mattreim** [comment]
I still think it's a problem form [Fix state of Hue lights not always updated correctly #7704](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7704)

**Comment by mattreim** [comment]
Does adjusting the color temprature(ct) work? With a value of "42404" it would now only be blue.

![color-temperature-scale](https://github.com/Jey-Cee/ioBroker.deconz/assets/80219712/68ea04f0-e802-4866-b40c-8e117fddbd51)

**Comment by unstressable** [comment]
In my case everything works fine. The error happens even without  changing the ct value.

actually my log level is „fault“ this makes it silence.

**Comment by kopierschnitte** [comment]
Interesting problem. I've also noticed that "colormode" always changes back from "ct" to "effect", although "effect" isn't a valid option there.
For me, setting the log level to "fault" also fixes flooding the log.

**Comment by Jey-Cee** [comment]
> I've also noticed that "colormode" always changes back from "ct" to "effect", although "effect" isn't a valid option there.

You are right, effect isnt a valid value and more important: This does not exist as a state value on the object colormode.
If this value is really printed in colormode provide more information on which device this happens and the version of deconz software it is happen.

**Comment by kopierschnitte** [comment]
Yes, that's the case.

It's happening on my "Hue Spot GU10"'s (LCG002) and "Hue White and color ambiance" (bulbs / LCT015). Deconz release is 2.26.3

**Comment by Jey-Cee** [comment]
> Yes, that's the case.
> 
> It's happening on my "Hue Spot GU10"'s (LCG002) and "Hue White and color ambiance" (bulbs / LCT015). Deconz release is 2.26.3

Seems that effect is defined as colormode in deConz for this models.

**Comment by mattreim** [comment]
This issue should be resolved with v2.28.1 stable.

**Comment by Jey-Cee** [comment]
Thanks @mattreim.

**Comment by unstressable** [comment]
still there

`<html>
<body>

deconz.0 | 2024-10-07 16:18:35.727 | warn | State value to set for "deconz.0.Lights.16.ct" has value "25687" greater than max "8000"
-- | -- | -- | --
deconz.0 | 2024-10-07 16:18:35.154 | warn | State value to set for "deconz.0.Lights.15.ct" has value "44823" greater than max "8000"
deconz.0 | 2024-10-07 16:18:29.225 | warn | State value to set for "deconz.0.Lights.15.ct" has value "44823" greater than max "8000"
deconz.0 | 2024-10-07 16:18:29.184 | warn | State value to set for "deconz.0.Lights.16.ct" has value "25687" greater than max "8000"


</body>
</html>`


Phoscon: 2.28.1
Deconz: 1.4.1
