### ISSUE TITLE
[Bug]: Window stopped working (Gateway 2.24.2)

### ISSUE THREAD

**Issue by dotcom84** [Jey-Cee/ioBroker.deconz#360]
### Contact Details

unacum@gmail.com

### What happened?

My window blinds are still shown as a "light" in DeConz while the Phoscon web UI now lists them correctly as window blinds.
When trying to control the values as I used to in the past years, the API throws an error 400 (parameter not available).

<img width="636" alt="Bildschirmfoto 2024-05-01 um 09 18 23" src="https://github.com/Jey-Cee/ioBroker.deconz/assets/477203/426ec132-3714-4287-93c1-2ae43895c54e">
<img width="195" alt="Bildschirmfoto 2024-05-01 um 09 18 56" src="https://github.com/Jey-Cee/ioBroker.deconz/assets/477203/5263cea9-c0e9-4402-a53c-5a89c066a262">
<img width="1323" alt="Bildschirmfoto 2024-05-01 um 09 17 51" src="https://github.com/Jey-Cee/ioBroker.deconz/assets/477203/723a140e-58be-4f0a-9906-6e9eb781ad19">

### Adapter Version

1.4.0

### deConz (Phoscon) Version

2.24.2

### JS-Controller Version

 5.0.17

### Node JS Version

v18.19.0

### NPM Version

10.2.3

### Operating System

Ubuntu

### Relevant log output

```shell
Code 400: Bad request set light state 5: [{"error":{"address":"/lights/5/state","description":"parameter, bri, not available","type":6}},{"error":{"address":"/lights/5/state","description":"parameter, on, not available","type":6}}]
```

**Comment by dotcom84** [comment]
That's the controlled device: https://zigbee.blakadder.com/Aqara_ZNCLDJ11LM.html

**Comment by mattreim** [comment]
Stop using the bri and use the lift to control the device.

**Comment by dotcom84** [comment]
Thanks @mattreim - weird behaviour but it works
