### ISSUE TITLE
Group one Sensor with multiple sensor IDs to one object

### ISSUE THREAD

**Issue by siggi85** [Jey-Cee/ioBroker.deconz#37]
Is it possible to group one sensor to one folder in ioBroker objects? Many values like battery, reachable and so on are holded multiple times for the same sensor. Would be better to handle when they would be grouped in ioBroker even when deconz api split them in multiple devices. You could use the Sensor Name as Identifier. Maybe with an adapter option where u can decide the object behaviour?!
![grafik](https://user-images.githubusercontent.com/45281493/54736015-5ccce980-4ba9-11e9-921a-765ed4dc310b.png)
Don't get me wrong, the adapter is nice and it worked this way too, but with many sensors it is much nicer to handle. In the zigbee Adapter it worked like that for example.

**Comment by Jey-Cee** [comment]
I tried it a couple oft times, each one causes problems that makes the behaivor of the Adapter inconsisten.
So i do not spend more time to this feature. Sorry.

**Comment by siggi85** [comment]
Ok. No problem. Thanks for your quick response! :)
