### ISSUE TITLE
Please check weblate webhook

### ISSUE THREAD

**Issue by mcm1957** [Jey-Cee/ioBroker.deconz#370]
Weblate reported several outstanding commits - commits missing in weblate repo.
This can be caused by some intermidate connection problems or by an missing / incorrect webhook.

Please check webhook in this repository
See https://github.com/ioBrokerTranslator/doc/blob/master/README.md#preparation

**Comment by Jey-Cee** [comment]
The URL in weblate points to https://github.com/iobroker-community-adapters/ioBroker.deconz.
It should be https://github.com/Jey-Cee/ioBroker.deconz.
Can you change it? I don't have the permission.

**Comment by mcm1957** [comment]
Thanks for feedback.
Link has been corrected an weblate resynced.
