### ISSUE TITLE
Dimmen von Gruppen nicht möglich nach Update auf 1.0.1

### ISSUE THREAD

**Issue by mctom** [Jey-Cee/ioBroker.deconz#40]
Ich habe gerade das Update auf die Version 1.0.1 durchgeführt.
Das Dimmen von Gruppen ist nun nicht mehr möglich.
Wenn ich einen ...bri Datenpunkt ändere werden die Lampen nicht gedimmt. Das dimmen der Lampen einzeln über den jeweiligen solo Datenpunkt .bri ist möglich.
Wenn ich die Lampen in der Phoscon APP dimme wird auch nicht der korrekte Wert in ioBroker angezeigt.

**Comment by Jey-Cee** [comment]
erledigt #https://github.com/iobroker-community-adapters/ioBroker.deconz/commit/aeb52d1c25ea2400ac782c6275a395b62a4212d6
