### ISSUE TITLE
keine Verbindung zu deconz seit 1.6.2

### ISSUE THREAD

**Issue by ohle64** [Jey-Cee/ioBroker.deconz#403]
Mein System: ubuntu 22.04.5 LTS, node v20.18.0, npm 10.8.2, js-controller 7.0.0, admin 7.2.2, web 6.3.1, ws 2.6.2

Seit v 1.6.2 - 1.6.4 kann keine Verbindung zum deconz (port 8094) auf Windows-Server hergestellt werden. Im Log steht: 
   Could not connect to websocket instance of deConz/Phoscon. Error: Unexpected server response: 301
In den Settings habe ich bei beiden den Port 8094 eingetragen. Mit Version 1.6.1 läuft das so ohne Probleme.

**Comment by mattreim** [comment]
1. API-Schlüssel sichern -> Er kann immer wieder verwendet werden
2. Die richtigen Ports herausfinden -> Phoscon App - Hilfe - API Informationen - Kein Filter - "port"/"websocketport" suchen und notieren
3. deConz-Adapter mit den notierten Daten neu installieren

**Comment by ohle64** [comment]
Danke, der Hinweis auf die API-Infos haben geholfen. Der Web-Socket-Port war ein anderer.
