### ISSUE TITLE
Update 1.0.1 verändert Struktur; Scripte laufen nicht mehr

### ISSUE THREAD

**Issue by heitec11** [Jey-Cee/ioBroker.deconz#41]
Nach dem Update auf 1.0.1 hat sich die Struktur verändert.
Anstelle von Sensor_2 zum Beispiel auf Sensor/2.
Allerdings werden nicht alle Objekt Attribute mit übernommen.
Es fehlt zum Beispiel der Zeitstempel (Update).
Somit sind meine Scripte nicht mehr lauffähig.

**Comment by heitec11** [comment]
Wie komme ich zurück auf Version 0.4.0 ?

sudo npm install iobroker.deconz@0.4.0 --production

Das normale Kommando funktioniert nicht.
npm ERR! notarget No matching version found for iobroker.deconz@0.4.0

**Comment by Jey-Cee** [comment]
Kannst du das mit den Attributen bitte verdeutlichen? 
Meinst du das Objekt lastchanged?

**Comment by heitec11** [comment]
Nein, sondern Objekt: lastupdated

**Comment by heitec11** [comment]
![grafik](https://user-images.githubusercontent.com/44260876/55384991-6f8dd980-552c-11e9-8088-16eb5233d1a0.png)

**Comment by heitec11** [comment]
Oder kommt es automatisch?
Zwei identische Sensoren und bei einem ist das Objekt vorhanden:
 
![grafik](https://user-images.githubusercontent.com/44260876/55385295-15414880-552d-11e9-875c-b36a1160e827.png)

**Comment by Jey-Cee** [comment]
Das kommt automatisch wenn dafür ein Wert geliefert wird. War schon immer so.

**Comment by heitec11** [comment]
Ok. Danke für die Info. Sorry.
Gibt es trotzdem eine Möglichkeit zurück auf Version 0.4.0 zu kommen?

**Comment by Jey-Cee** [comment]
Nein, hab die nicht auf npm veröffentlicht.
