### ISSUE TITLE
Version 1.0.2 Dimmen von Gruppen

### ISSUE THREAD

**Issue by mctom** [Jey-Cee/ioBroker.deconz#42]
Das Dimmen von Gruppen über den Adapter ist wieder möglich. 
Wenn eine Änderung über die Phoscon APP durchgeführt wird, dann wird diese Änderung nicht nach ioBroker übertragen. Wenn die Lampe aus und wieder ein geschaltet wird stimmt der aktuelle Dimmwert.

**Comment by Jey-Cee** [comment]
deConz sendet keine Änderung für die Gruppe wenn die Helligkeit in Phoscon geändert wird. Da kann ich nichts machen.

**Comment by mctom** [comment]
Danke für Info. Dann gebe ich das mal an die Deconz Entwickler weiter.
