### ISSUE TITLE
New Scene for group not showing in ioBroker Objects

### ISSUE THREAD

**Issue by easybeat** [Jey-Cee/ioBroker.deconz#43]
If I add a new scene in Phoscon App the scene is not displayed under the group. Even a restart of deconz instance doesn't help.

Is this a bug or how to update already added groups to see the new scenes?

Thanks

Beat

**Comment by easybeat** [comment]
Oh...just realised it is even worse! Scenes under Groups have totally gone!!

I deleted the former instance and recreated it and now the whole structure is different and no scenes under groups! Is this how it will be or is it a bug?

Thanks
Beat

**Comment by Jey-Cee** [comment]
HM Bug i think.

**Comment by easybeat** [comment]
OK. Do you think this can be fixed very soon?

Is there a way to install version 0.40 on ioBroker?

Thanks for your help.

Beat

**Comment by Jey-Cee** [comment]
You have to check your scene settings. New scenes will only be created if the lightcount is greater than 0. If the state of your light(s) in the scene is off, the count is 0.

There is no way back to 0.4.0

**Comment by easybeat** [comment]
Thanks for reply. Which deconz beta are you working with?

I've created all my scenes on groups and they all have lights. And in 0.40 it did show all scenes below groups. Was there a change on this?

Thanks

Beat

**Comment by easybeat** [comment]
I managed to go back to 0.30 and there all scenes are showing under groups...

Thanks

**Comment by easybeat** [comment]
> You have to check your scene settings. New scenes will only be created if the lightcount is greater than 0. If the state of your light(s) in the scene is off, the count is 0.
> 
> There is no way back to 0.4.0

Hi

I've checked again my scenes and all of them have lights and the state is not of. Please see screenshot.

Could you please let me know if this should work like that and that I should see all scenes under my groups?

Thanks

Beat

![deconz scene in phoscon](https://user-images.githubusercontent.com/37217887/55503022-161dcb80-564e-11e9-9f94-f1cf97567442.JPG)
