### ISSUE TITLE
Scenes still not showing - my scenes look OK?

### ISSUE THREAD

**Issue by easybeat** [Jey-Cee/ioBroker.deconz#44]
> You have to check your scene settings. New scenes will only be created if the lightcount is greater than 0. If the state of your light(s) in the scene is off, the count is 0.
> 
> There is no way back to 0.4.0

Hi

I've checked again my scenes and all of them have lights and the state is not off. Please see screenshot.

Could you please let me know if this should work like that and that I should see all scenes under my groups?

Thanks

Beat

![deconz scene in phoscon](https://user-images.githubusercontent.com/37217887/55503022-161dcb80-564e-11e9-9f94-f1cf97567442.JPG)

_Originally posted by @easybeat in https://github.com/iobroker-community-adapters/ioBroker.deconz/issues/43#issuecomment-479603717_

**Comment by easybeat** [comment]
Hallo

habe soeben gesehen, dass Du ja auch Deutsch sprichst.

Nun habe ich auf einem 2. ioBroker den Deconz 1.02 nochmal installiert. Und definitiv funktioniert der mit meinem Deconz (Beta 2.05.40) nicht.
1. Die Gruppen haben keine Bezeichnung sondern sind alle "undefined"
2. Die Gruppen haben keine Szenen


![deconz scene in phoscon 2](https://user-images.githubusercontent.com/37217887/55510064-aca5b900-565d-11e9-90b2-bd5d46c549c9.JPG)

Siehe dazu wie es mit Version 0.30 funktioniert. Ich greife mit beiden ioBroker auf die gleiche Deconz zu.
![deconz scene in phoscon 2 mit Version 0 30](https://user-images.githubusercontent.com/37217887/55510086-b9c2a800-565d-11e9-8b88-3b1a871d7a45.JPG)

Ich hoffe das hilft weiter?

Besten Dank und Gruss

Beat

**Comment by CommanderXXL** [comment]
Hallo, ich möchte auch kurz einen Statusbericht geben, nachdem ich auch auf 1.02 upgedatet habe.
Ich nutze Deconz Version 2.05.60.
Bei mir sieht es so aus:
![Deconz](https://user-images.githubusercontent.com/49292478/55591231-4c824600-5735-11e9-94e4-32b2876eb955.png)
DIe Gruppe hatte den Namen der zweiten Szene nach dem Import, sie hieß also "Meer". Ich habe sie dann zu "Bad" umbenannt. Leider kann man auch die Szenen nicht aktivieren, weder per Click in den Objekten noch per Script wenn man der Szene bei "recall" true zuweist. Ich kann auch gerne noch weiter berichten wenn es hilft. Ich hatte vorher Version 0.3.2 des Adapters (ohne die Groups/Sensors/Lights) da hat es funktioniert.

**Comment by Jey-Cee** [comment]
Das mit der Benennung hab ich schon teilweise gefixt, aber ich hab noch einen Fehler gefunden.
Ich hab noch nicht einmal die Szenen benutzt deswegen ist mir das gar nicht aufgefallen, das sie nicht gehen.

**Comment by easybeat** [comment]
Danke. Ich bin jetzt auf 0.30 und dort funktionierts so einigermassen. Schade, dass man nicht auf 0.40 zurück kann. Irgendeine Chance diese Version vorübergehend zur Verfügung zu stellen?

Besten Dank für deine Arbeit!!

Gruss
Beat

**Comment by easybeat** [comment]
@Jey-Cee : Wurde da etwas angepasst? Weil mit Version 1.02 funktioniert es definitiv nicht!

Danke und Gruss
Beat

**Comment by Jey-Cee** [comment]
ja hätte 1.1.0 sein, wurde aber nicht hochgeladen, jetzt ist es 1.1.1

**Comment by easybeat** [comment]
Cool Danke...bin leider übers. Weekend weg und kann nicht testen...Ende nchster Woche werde ich es probieren.

Gruss
