### ISSUE TITLE
Not working with deconz 2.05-60

### ISSUE THREAD

**Issue by kurt4160** [Jey-Cee/ioBroker.deconz#49]
Hi,

I updated the adapter from 0.2.5 to 1.0.2. Now there is a problem with deconz 2.05.60. I can control devices (for example switch wallplug), but I do not get any updates from the devices (state of wallplug, temperature, humidity, ...)
There are no errors in the log.
I switched back to 0.2.5 and all is working again.

**Comment by Jey-Cee** [comment]
Habe you deleted the Adapter before installed the New Version?
There are a lot oft changes in Version 1.x.x

**Comment by kurt4160** [comment]
No I did not. I will try this tomorrow.

**Comment by Hiffi** [comment]
Yeah, I can confirm the problem.

deconz 2.05.57, API 1.16.0 (headless, minimal)

Lights can be controlled and get updates, but sensors dont get any updates.
REST API works as usual.

**Comment by Hiffi** [comment]
UPDATE: Okay, know without any further changes there are some objects getting updates,but know some light states are not getting updates. The behavior is not predictable. The REST API still delivers the correct values.

**Comment by pandel** [comment]
+1
Adapter Version 1.1.2 not working correctly with deconz 2.05.67. Simple switches are ok, sensor values not. Reverted to 0.2.5 and it seems working ok for now.
