### ISSUE TITLE
can't add deconz-devices (osram plug) to cloud-adapter

### ISSUE THREAD

**Issue by Somberland** [Jey-Cee/ioBroker.deconz#5]
i'm not sure if the error is on the cloud adapter or this one, but i'm afraid it's a problem of the deconz-adapert. 

I'm not able to add my Osram Smart+Plug to the cloud-adapter, looks like the "on" is set to *state* instead of *switch*.

<img width="836" alt="bildschirmfoto 2018-01-17 um 19 14 38" src="https://user-images.githubusercontent.com/5808345/35059392-44879080-fbbb-11e7-8df5-22fd2271c47c.png">

**Comment by Somberland** [comment]
Same for my Tradfri lights

**Comment by Jey-Cee** [comment]
I have changed it already. You can install it from github, Version number is the same. 

That has nothing to do with the manufacturer.
