### ISSUE TITLE
sending more than one value will reset the first one

### ISSUE THREAD

**Issue by volkerrichert** [Jey-Cee/ioBroker.deconz#51]
If you send e.g. two new values to a light the first one is reverted.

Assume you;d to switch the color temp and the level inside a script.

`
        setState('deconz.0.Lights.6.bri', bri, false);
        setState('deconz.0.Lights.6.ct', ct, false);
`

The lamp will inc the level for a few millisec an then fall back to the original value. This will also happend if the second setState will be inside the callback.

Volker

**Comment by Jey-Cee** [comment]
There is a object for this purpose, it was implemented by an other developer. I habe to look how it works, i come back soon with Instruktion.

**Comment by Jey-Cee** [comment]
You have to put something like:
`"on": true, "bri": 5`
in the object "action"

**Comment by volkerrichert** [comment]
I tried to set { "on": true, "bur":5 }. All i got is

`You are assigning a object to the state "deconz.0.Lights.6.action" which expects a string. Please fix your code to use a string or change the state type to object. This warning might become an error ...`

**Comment by Jey-Cee** [comment]
You dont have done it as i told you. Dont use {}.

**Comment by volkerrichert** [comment]
ok, i'll try a string

**Comment by volkerrichert** [comment]
a string is the correct format THX. But it doesn't change values

i set action to '"on": true,"bri": 254,"ct": 314', all objects are changed and acknowledged. 

![image](https://user-images.githubusercontent.com/640914/60766588-fc0be300-a0ab-11e9-8299-b9e392900213.png)

But the light is still on "bri": 1. This was the value before it was tuned off

**Comment by volkerrichert** [comment]
BTW, bri seem to be set to 254 but then reset to 1. The Lights dims up for 1 second and then dims down again

**Comment by volkerrichert** [comment]
ok, next update. Calls too deconz seems to be ok


```
deconz.0 | 2019-07-07 11:52:40.128 | info | options: {"url":"http://127.0.0.1:80/api/E2854FE473/lights/2/state","method":"PUT","headers":"Content-Type\" : \"application/json","body":"{ \"bri\": 254,\"ct\": 314 }"}
deconz.0 | 2019-07-07 11:52:40.127 | info | options: {"url":"http://127.0.0.1:80/api/E2854FE473/lights/6/state","method":"PUT","headers":"Content-Type\" : \"application/json","body":"{ \"bri\": 254,\"ct\": 314 }"}
```

**Comment by Jey-Cee** [comment]
I cant check it before august or september because i am moving to a new location.

**Comment by kugelkopf123** [comment]
This Issue still exists. 
 deconz:  2.5.72 api: 1.16.0, Adapterversion:1.2.4
Tried it with a Tradfri e14 Lamp.

The value changed on datapoint "bri" and the lamp Dims up vor a second and then its back on the low level. 
On the other side the same. Set the Lamp manually to 254 and try to dim down by setting up the action datapoint with: 
`"ct":450,"bri":1`
It dims down for a second set the DP: Bri to the right value, but the light is full on. 

For me its no problem, I just want to inform you.
