### ISSUE TITLE
Aqara Vibration Sensor DJT11LM - no status change in ioBroker

### ISSUE THREAD

**Issue by fullcavediver** [Jey-Cee/ioBroker.deconz#53]
Hi,

DJT11LM sends many interesting parameters like state.orientation, state.tiltangle, state.vibration and state.vibrationstrength,

```
{
	"config": {
		"battery": 100,
		"on": true,
		"pending": [
			
		],
		"reachable": true,
		"sensitivity": 11,
		"sensitivitymax": 21,
		"temperature": 2700
	},
	"ep": 1,
	"etag": "0d5f099e494192253bee48d582bb067c",
	"manufacturername": "LUMI",
	"modelid": "lumi.vibration.aq1",
	"name": "Vibrationssensor Mobile",
	"state": {
		"lastupdated": "2019-04-29T16:33:45",
		"orientation": [
			2,
			-1,
			88
		],
		"tiltangle": 360,
		"vibration": false,
		"vibrationstrength": 8
	},
	"swversion": "20180130",
	"type": "ZHAVibration",
	"uniqueid": "00:15:8d:00:02:b9:32:23-01-0101"
}
```

and
```
{
	"config": {
		"battery": 100,
		"on": true,
		"pending": [
			
		],
		"reachable": true,
		"sensitivity": 11,
		"sensitivitymax": 21,
		"temperature": 2700
	},
	"ep": 1,
	"etag": "5a7869a900da7366b0b05f344c3f6993",
	"manufacturername": "LUMI",
	"modelid": "lumi.vibration.aq1",
	"name": "Vibrationssensor Mobile",
	"state": {
		"lastupdated": "2019-04-29T16:42:09",
		"orientation": [
			6,
			-2,
			-83
		],
		"tiltangle": 171,
		"vibration": true,
		"vibrationstrength": 8
	},
	"swversion": "20180130",
	"type": "ZHAVibration",
	"uniqueid": "00:15:8d:00:02:b9:32:23-01-0101"
}
```
but I do not see it in ioBroker :-(
![2019-04-29_190755](https://user-images.githubusercontent.com/49302111/56942302-35f3c280-6b1a-11e9-9830-ab2da161c049.png)

What am I doing wrong? Can I create and link these objects manually?
Help, I do not know enough yet
Thank you.

Software versions:
deCONZ: / 2.05.64 (on Raspbian)
ioBroker.deconz: 1.0.2

**Comment by Jey-Cee** [comment]
Thanks for the information. This datapoints are not implemented in the actual version, because they are New to me.

I will added in near future.

**Comment by fullcavediver** [comment]
Thanks a lot, Jey-Cee! I am looking forward to the next test opportunity and implementation.

**Comment by fullcavediver** [comment]
DJT11LM works perfect now with the version 1.1.1. Thank you Jey-Cee for the fast implementation
