### ISSUE TITLE
Scene recall not working

### ISSUE THREAD

**Issue by CommanderXXL** [Jey-Cee/ioBroker.deconz#56]
I use version 1.1.1 of the adapter but i had this issue already since upgrading from 0.3.2. The recalling of scenes inside a group is not working. Nothing happens when pressing the "button" in the "objects" list or when sending a "true" to the "recall" button from a script.

**Comment by Jey-Cee** [comment]
please test from github

**Comment by CommanderXXL** [comment]
@Jey-Cee : Still not working with newest github release. I tried pressing "recall" inside scene via "Objects" list and i tried to set "recall" to true from script. BTW: the problem with naming of group itself is still present. The group is called like the last scene in the group. See this screenshot:
![Deconz](https://user-images.githubusercontent.com/49292478/57175365-6b1a5080-6e4b-11e9-81cf-1b63bad4d300.png)
The correct name of the group is "Bad" in the Deconz interface. Not "Meer"

**Comment by Jey-Cee** [comment]
On my side recall is working, without further information i can not see whats the problem. Please set log level of the adapter instance to debug and provide the log to me.

**Comment by CommanderXXL** [comment]
Hello @Jey-Cee thanks for your effort:  here i have the relevant part of the log:

deconz.0 | 2019-05-04 11:52:31.869 | info | Set group state with ID: undefined parameter:  Code 404: Ressource not found
-- | -- | -- | --
deconz.0 | 2019-05-04 11:52:31.869 | debug | setGroupState BODY:  [{"error":{"address":"/groups/undefined/scenes/2","description":"resource,  /groups/undefined/scenes/2, not available","type":3}}]
deconz.0 | 2019-05-04 11:52:31.869 | debug | setGroupState STATUS: 404
deconz.0 | 2019-05-04 11:52:31.863 | debug | dp: recall; id:Groups.1.Scene_2

It may have to do with the naming problem i described earlier. It looks like the generated URL for Deconz contains "undefined" which looks not quite right.

**Comment by CommanderXXL** [comment]
Wir können übrigens auch auf Deutsch schreiben wenn du willst. Ich bin selbst Software Entwickler (allerdings für C++) daher gerne auch sehr technisch 😜

**Comment by Jey-Cee** [comment]
Die. Namen ein rein informativ und werden nicht zur Verarbeitung verwendet. 
Der Fehler aus dem Log ist genau der den ich behoben hab. Deshalb denke ich du hast nicht die Aktuellste Version installiert. Am besten den ganzen Adapter deinstallieren und von github neu installieren.

**Comment by CommanderXXL** [comment]
Alles klar ich deinstalliere jetzt und mache es nochmal komplett neu von Github. Stand By 😉

**Comment by CommanderXXL** [comment]
@Jey-Cee du hattest Recht. Wenn ich aus Github neu installiere tut es. Ich habe jetzt aber nochmal auf den 1.1.1er Stand vom normalen (nicht Github) Adapter umgestellt und da ist der Fehler noch vorhanden. Ich bin mir nicht sicher wie das den Versionen hier geht. Weil ein "Tag" mit 1.1.1 hab ich keins gefunden im Repo hier. Vielen Dank auf alle Fälle für deinen Support. Jetzt kann ich endlich beim Baden wieder auf Meereslicht schalten 😊

**Comment by easybeat** [comment]
@Jey-Cee : ich habe das gleiche Problem. Wenn ich mit dem Github Link installiere funktionierts.

Ich habe noch ein anderes Problem bemerkt. Wenn man die Instanz das erste Mal erstellt und dann über Node-Red ein Scene.recall macht dann funktioniert das nicht. Man muss zuerst "manuell" auf dem Objekt ein recall auf der Scene auslösen. Danach funktioniert es. Das muss ich auf jeder Szene machen...kannst Dir vorstellen was das für eine Klickerei ist.

Trotzdem bin ich froh ist das Szene-Problem jetzt gelöst und die Struktur ist jetzt auch "bereinigt".

Besten Dank für Deine Arbeit und einen schönen Abend.

Gruss
Beat
