### ISSUE TITLE
Aqara Vibration Sensor orientation field type

### ISSUE THREAD

**Issue by erichsch** [Jey-Cee/ioBroker.deconz#57]
"type": "string", this field is not a string

look at: https://forum.iobroker.net/topic/22205/gel%C3%B6st-zeichenkette-in-zahl-umwandeln-aqara-deconz-vibrationssensor-winkel/25

thank you

**Comment by Jey-Cee** [comment]
Done, now included in Github version

**Comment by erichsch** [comment]
Thank you.
