### ISSUE TITLE
Adapter läuft bei mir nicht. Fehler im Log:

### ISSUE THREAD

**Issue by SeniorCatweazle** [Jey-Cee/ioBroker.deconz#59]

**Comment by SeniorCatweazle** [comment]
host.raspberrypi | 2019-05-08 22:02:54.017 | info | Restart adapter system.adapter.deconz.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2019-05-08 22:02:54.016 | error | instance system.adapter.deconz.0 terminated with code 1 ()
Caught | 2019-05-08 22:02:54.016 | error | by controller[0]: at Function.Module._load (module.js:445:3)
Caught | 2019-05-08 22:02:54.016 | error | by controller[0]: at tryModuleLoad (module.js:453:12)
Caught | 2019-05-08 22:02:54.015 | error | by controller[0]: at Module.load (module.js:494:32)
Caught | 2019-05-08 22:02:54.014 | error | by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught | 2019-05-08 22:02:54.014 | error | by controller[0]: at Module._compile (module.js:577:32)
Caught | 2019-05-08 22:02:54.014 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.deconz/main.js:3:15)
Caught | 2019-05-08 22:02:54.014 | error | by controller[0]: at require (internal/module.js:20:19)
Caught | 2019-05-08 22:02:54.014 | error | by controller[0]: at Module.require (module.js:504:17)
Caught | 2019-05-08 22:02:54.014 | error | by controller[0]: at Function.Module._load (module.js:424:25)
Caught | 2019-05-08 22:02:54.013 | error | by controller[0]: at Function.Module._resolveFilename (module.js:476:15)
Caught | 2019-05-08 22:02:54.013 | error | by controller[0]: Error: Cannot find module '@iobroker/adapter-core'
Caught | 2019-05-08 22:02:54.013 | error | by controller[0]: ^
Caught | 2019-05-08 22:02:54.013 | error | by controller[0]: throw err;
Caught | 2019-05-08 22:02:54.012 | error | by controller[0]: module.js:478
host.raspberrypi | 2019-05-08 22:02:53.621 | info | instance system.adapter.deconz.0 started with pid 14775

**Comment by SeniorCatweazle** [comment]
Was kann ich machen, um die Fehler zu beseitigen? Ich wäre für eine Lösung dankbar.

**Comment by Jey-Cee** [comment]
Welche version des JS-Controllers und nodejs läuft bei dir?

**Comment by SeniorCatweazle** [comment]
> Welche version des JS-Controllers und nodejs läuft bei dir?
![image](https://user-images.githubusercontent.com/50425156/57457810-884a8700-7270-11e9-9fef-50346f78f31b.png)
und
![image](https://user-images.githubusercontent.com/50425156/57458012-e7a89700-7270-11e9-9755-ff8f2f99b819.png)
Danke schon mal für die Hilfe...

**Comment by SeniorCatweazle** [comment]
Ich habe jetzt die Version von nodejs auf 8.16.0 angehoben und alles funktioniert, bekomme aber dennoch Fehlermeldungen die mit der nodejs version zun tun haben.

host.raspberrypi | 2019-05-09 16:18:50.597 | info | Restart adapter system.adapter.tradfri.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2019-05-09 16:18:50.597 | error | instance system.adapter.tradfri.0 terminated with code 1 ()
host.raspberrypi | 2019-05-09 16:18:50.597 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:664:10)
host.raspberrypi | 2019-05-09 16:18:50.597 | error | Caught by controller[0]: at Module._compile (module.js:653:30)
host.raspberrypi | 2019-05-09 16:18:50.597 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tradfri/node_modules/node-aead-crypto/index.js:1:96)
host.raspberrypi | 2019-05-09 16:18:50.597 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/iobroker.tradfri/node_modules/bindings/bindings.js:112:48)
host.raspberrypi | 2019-05-09 16:18:50.597 | error | Caught by controller[0]: at require (internal/module.js:11:18)
host.raspberrypi | 2019-05-09 16:18:50.597 | error | Caught by controller[0]: at Module.require (module.js:597:17)
host.raspberrypi | 2019-05-09 16:18:50.597 | error | Caught by controller[0]: at Function.Module._load (module.js:498:3)
host.raspberrypi | 2019-05-09 16:18:50.596 | error | Caught by controller[0]: at tryModuleLoad (module.js:506:12)
host.raspberrypi | 2019-05-09 16:18:50.596 | error | Caught by controller[0]: at Module.load (module.js:566:32)
host.raspberrypi | 2019-05-09 16:18:50.596 | error | Caught by controller[0]: at Object.Module._extensions..node (module.js:682:18)
host.raspberrypi | 2019-05-09 16:18:50.596 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.raspberrypi | 2019-05-09 16:18:50.596 | error | Caught by controller[0]: NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
host.raspberrypi | 2019-05-09 16:18:50.596 | error | Caught by controller[0]: NODE_MODULE_VERSION 48. This version of Node.js requires
host.raspberrypi | 2019-05-09 16:18:50.596 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.raspberrypi | 2019-05-09 16:18:50.596 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/iobroker.tradfri/node_modules/node-aead-crypto/build/Release/node-aead-crypto.node'
host.raspberrypi | 2019-05-09 16:18:50.595 | error | Caught by controller[0]: ^
host.raspberrypi | 2019-05-09 16:18:50.595 | error | Caught by controller[0]: throw e;
host.raspberrypi | 2019-05-09 16:18:50.594 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.tradfri/node_modules/bindings/bindings.js:121

**Comment by SeniorCatweazle** [comment]
Hallo, 

ich habe die nodejs upgedatet. Nun läuft alles.

Danke
