### ISSUE TITLE
Mehrere Objekteeinträge je Licht/Sensor - normal?

### ISSUE THREAD

**Issue by Michaelnorge** [Jey-Cee/ioBroker.deconz#61]
Hallo erstmal!
Ich sehe an meinem Vorschreiber daß hier auch deutsche Einträge verstanden werden... macht es um einiges leichter für mich LOL !!

Mir ist aufgefallen, daß ich mehrere Objekteinträge (folder) mit teilweise gleichzeitigen Einträgen in den Objekten habe. 

Bei den Zwischensteckern von IKEA ist es ein Eintrag
Türkontakte Xiaomi: 1 Eintrag
Bewegungsmelder Xiaomi: 2 Einträge
Taster Xiaomi: 2 Einträge
Temperatursensoren Xiaomi: 3 Einträge

Die einzelnen Folder zeigen, wenn sie doppelt vorhanden sind, gleiche Werte an,
Teilweise gibt es bestimmte Werte auch nur jeweils in einem der Folder

Das ist zwar alles etwas verwirrend und unübersichtlich, aber trotzdem komme ich damit klar,

Ich wollte nur mal wissen, ob das hier bei mir ein Bug ist oder es so vorgesehen ist bzw. bei Anderen ebenfalls so angezeigt wird.

Grüße
Michael

**Comment by Jey-Cee** [comment]
Ja das ist normal, liegt an den Xiaomi sensoren die melden  sich als mehrere sensoren.

**Comment by Michaelnorge** [comment]
Ich fasse das hier nochmal auf, 
Normal kann das nicht sein. Ich hatte vorher den CC2531 mit dem Adapter iobroker.zigbee, der jeweils nur EINEN Eintrag in den Objekten geschrieben hat.
Gewechselt habe ich allerdings, weil ich mit dem  CC2531 andere Probleme hatte.

**Comment by Jey-Cee** [comment]
Nur weil im zigbee Adapter das anders behandelt wird heißt das nicht das es Überall so sein muss. 

Wenn du mir nicht glaubst, stell den Adapter log level auf debug und du siehst was an Rohdaten von deconz kommt.
