### ISSUE TITLE
Temperatursensoren Xiaomi Batteriewerte fehlen

### ISSUE THREAD

**Issue by Michaelnorge** [Jey-Cee/ioBroker.deconz#62]
Hallo.
Mir ist aufgefallen, da0 die Temperatursensoren von Xiaomi keine Batteriedaten ausgeben, auch wenn das in den Objekten vorgesehen ist.

Grüße
Michael

**Comment by Jey-Cee** [comment]
Das wurde schon mal diskutiert und scheint ein Bug in deConz zu sein.

#19

**Comment by Jey-Cee** [comment]
#19
