### ISSUE TITLE
lastupdated zeit ist falsch

### ISSUE THREAD

**Issue by thurbo** [Jey-Cee/ioBroker.deconz#63]
Irgendwie wird der Wert meiner Sensoren "lastupdated" immer in UTC (Universal Time) erzeugt.
Die eingestellte Local-Time wäre hier der bessere Wert.

Im Phosconapp ist die Uhrzeit die richtige (local-time).
Andere Trigger von anderen Adaptern laufen auch mit der richtigen Zeit (local-time).

**Comment by Jey-Cee** [comment]
Der Wert wird als UTC string von deConz geliefert. Das wurde im Forum schon diskutiert.

**Comment by thurbo** [comment]
Genau das ist es. Warum ist es so?!

Und wo wurde das diskutiert, gerne mit Linkangabe.

**Comment by Jey-Cee** [comment]
Warum das so ist, keine Ahnung.

Hier der Link: https://forum.iobroker.net/post/254354

**Comment by Jey-Cee** [comment]
#91340d00915640b0b66763528e0af4e7b430ee27

**Comment by Jey-Cee** [comment]
Ist jetzt angepasst.

**Comment by DNC74** [comment]
ich befürchte da passt nach wie vor etwas nicht beim schreiben der Datenpunkte:
![image](https://user-images.githubusercontent.com/72687758/95674386-2ce09f00-0bb0-11eb-9010-994e01166f33.png)
Zu sehen ist, dass die Zeitwerte für UTC und z.Z. GMT+2 identisch sind, statt die 2 Stunden versetzt.

Anbei eine Zeile aus dem deconz-Log im Debug-Mode, hier passt es:
`2020-10-11 10:33:09.085 - debug: deconz.0 (24145) Websocket message: {"attr":{"lastannounced":null,"lastseen":"2020-10-11T08:33Z","manufacturername":"dresden elektronik","modelid":"ConBee","name":"Configuration tool 10","swversion":"0x260b0500","type":"Configuration tool","uniqueid":"00:01:23:34:45:56:67:78-01"},"e":"changed","id":"10","r":"lights","t":"event","uniqueid":"00:01:23:34:45:56:67:78-01"}`

Warum ist es in den Datenpunkten gem. Screenshot falsch?

**Comment by Jey-Cee** [comment]
Es ist schon richtig wie es ist, es soll keinen Zeitversatz mehr geben. Das war der Wunsch von den meisten Benutzern.
Dein log Auszug passt nicht zum Screenshot, da ist kein lastupdated dein.

**Comment by DNC74** [comment]
Mein Problem ist, dass Deconz Localtime liefert während die anderen Adapter wie z.B. HUE die Zeit für "LastUpdated" in UTC ausgeben - was in der IT auch so üblich ist, Wenn man die Zeitstempel von Deconz mit denen anderer Devices abgleichen will, funktioniert das nicht ohne weiteres manuelles "übersetzten" der Deconz-Devices.

**Comment by Jey-Cee** [comment]
Das ist mir schon klar, aber viele Benutzer sind damit nicht Klar gekommen und haben das Ständig als Fehler gemeldet.
