### ISSUE TITLE
Verteilte Datenpunkte bleiben als Leichen erhalten

### ISSUE THREAD

**Issue by snador1977** [Jey-Cee/ioBroker.deconz#64]
Ich habe den Conbee2 getestet. Nachdem ich gehört habe, dass Datenpunkte bei diversen Produkten verteilt in verschiedenen Ordnern landen haben ich diverse Produkte in der Phoscon App angelernt und auch gelöscht und mir dazu immer die Datenpunkte im ioB angeschaut. Beim Xiaomi Lumi Plug wird ein Ordner für den Plug unter Lichter im ioB angelegt sowie ein Ordner unter Sensors wo der Datenpunkt für den Stromverbrauch des Plugs drin ist. Mal davon abgesehen, das diese sehr unübersichtlich ist weil man irgendwann gar nicht mehr weis welche Sensoren zu welchen Gerät gehören bleiben bei mir auch Leichen im Bereich Sensoren übrig wenn ich den Plug in der Phoscon App lösche und den Adapter aktualisiere. Der Plug ist dann im Ordner Lichter weg aber der Datenpunkt für den Stromverbraucht ist im Ordner Sensoren noch da. Auch der Adapter Neustart hat nicht geholfen. Erst wenn ich den Stick komplett über die App  zurücksetzte sind die Leichen weg. So wie alles Andere auch :-)

**Comment by snador1977** [comment]
Ein erneutes Anlernen des Lumi Plugs läßt den Plug im Ordner Lichter wieder auftauchen aber es wird kein neuer Datenpunkt unter Sensoren angelegt. Der alte der noch da ist (Leiche) bekommt aber auch keine Werte mehr.

**Comment by snador1977** [comment]
Jetzt eben hatte ich den Fall, dass beim erneuten Anlernen des Plugs ein alter Sensor Datenpunkt wieder mit Daten versorgt wurde. Eigenartige Verhaltenweise :-)

**Comment by Jey-Cee** [comment]
> bleiben bei mir auch Leichen im Bereich Sensoren übrig wenn ich den Plug in der Phoscon App lösche und den Adapter aktualisiere. Der Plug ist dann im Ordner Lichter weg aber der Datenpunkt für den Stromverbraucht ist im Ordner Sensoren noch da.

Also was du beschreibst kann gar nicht sein. Begründung: Der Adapter löscht zu keiner Zeit auch nur ein einziges Objekt, Objekte müssen von Hand gelöscht werden.

> Mal davon abgesehen, das diese sehr unübersichtlich ist weil man irgendwann gar nicht mehr weis welche Sensoren zu welchen Gerät gehören

Das finde ich auch nicht schön lässt sich aber nicht anders lösen.

> Ein erneutes Anlernen des Lumi Plugs läßt den Plug im Ordner Lichter wieder auftauchen aber es wird kein neuer Datenpunkt unter Sensoren angelegt. Der alte der noch da ist (Leiche) bekommt aber auch keine Werte mehr.

Schwer Nachvollziehbar, bei den Sensoren weis ich zu 100% das bei jedem anlernen eine neue ID vergeben wird, deshalb werden auch sicher neue Objekte angelegt. Es kann nur sein das man den Adapter neu starten muss damit sofort alle angelegt werden, andernfalls legt er nur die Objekte an für die er Daten bekommt. Wie das bei den Lampen ist hab ich nicht getestet, dass ist mit den Tradfri zu Nerven aufreibend.

**Comment by snador1977** [comment]
Also das mit den Leichen werde ich noch einmal mit Screenshots festhalten. Ich werde nochmal alles rausschmeißen und versuchen das Ganze zu wiederholen :-)  Darf ich fragen warum der Adapter die Objekte nicht löscht wenn Sie dich gar nicht mehr da sind?

Mich würde interessieren warum man das mit den geteilten Datenpunkten nicht ändern kann? Wäre es nicht möglich wenigsten beim der ersten Übernahme der Daten im Namen einen Zusatz anhängen der einem Rückschluss auf das Gerät zulässt, so dass man sich in komplexeren Umgebungen besser zurecht findet...

**Comment by Jey-Cee** [comment]
> Darf ich fragen warum der Adapter die Objekte nicht löscht wenn Sie dich gar nicht mehr da sind?
Ein Grund, wenn die Objekte einfach gelöscht werden besteht kein Zugriff mehr auf die History Aufzeichnungen für die Objekte.
Ein anderer Faulheit, das muss auch erstmal gebaut werden und ist nicht so einfach wie man denkt.

> Mich würde interessieren warum man das mit den geteilten Datenpunkten nicht ändern kann? Wäre es nicht möglich wenigsten beim der ersten Übernahme der Daten im Namen einen Zusatz anhängen der einem Rückschluss auf das Gerät zulässt, so dass man sich in komplexeren Umgebungen besser zurecht findet...

Das setzt Voraus das bekannt ist was zusammen gehört. Wenn es nicht geändert wurde gibt die API das aber nicht her.
Ist nicht so das ich nicht versucht hab es so zu Bauen. Kein Ansatz hat so funktioniert das es brauchbar war, deswegen investiere ich da keine Zeit mehr.
