### ISSUE TITLE
Trådfri schaltet bei iobroker-Neustart - Bug?

### ISSUE THREAD

**Issue by Michaelnorge** [Jey-Cee/ioBroker.deconz#65]
Hallo.
Ich habe hier 12 Trådfri-Zwischenstecker im System.
Zwei von denen schalten sich an und eine aus, wenn ich ioBroker neu starte.
Das ist unabhängig davon, ob die Stecker vorher an- oder ausgeschaltet waren.

Es ist definitiv der deconz-Adapter, nicht die Phoscon-App die die Schaltung vornimmt.
Der Schaltvorgang ist beim booten der Raspberry in der log. ersichtlich.

**Comment by Jey-Cee** [comment]
Passiert das auch wenn du nur den Adapter neu startest? 
Sind betreffende Zwischenstecker in Skripte eingebunden die auf Aktualisierung des Objekts reagieren?

**Comment by Michaelnorge** [comment]
@Jey-Cee 
*Facepalm*
Verdammt, das ist es... Es wird bei den betreffenden Steckdosen auf Aktualisierung, nicht auf Änderung gewartet!
Wie dumm von mir!!!

Tausend Dank, also kein Bug, sondern reine Dummheit!

Dann schließe ich das hier jetzt!
