### ISSUE TITLE
Ikea trådfri Bewegungsmelder spinnt?

### ISSUE THREAD

**Issue by Michaelnorge** [Jey-Cee/ioBroker.deconz#68]

**Comment by Jey-Cee** [comment]
Hast du den fehler gefunden oder ist das Problem einfach verschwunden?

**Comment by Michaelnorge** [comment]
Sry, der Fehler liegt wohl an phoscon/deconz. Hatte dies zu spät bemerkt und daher hier den Text gelöscht, weil ich den Eintrag hier nicht weg bekomme.
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1742

**Comment by Jey-Cee** [comment]
Ok dann schließe ich das hier.
