### ISSUE TITLE
fix state-naming for cloud adapter etc

### ISSUE THREAD

**Issue by Somberland** [Jey-Cee/ioBroker.deconz#7]
states should be named "unique" to be used with the cloud-adapter etc.
example: https://github.com/Somberland/ioBroker.deconz/blob/feature/name_fix/main.js

<img width="692" alt="bildschirmfoto 2018-01-22 um 15 53 25" src="https://user-images.githubusercontent.com/5808345/35226710-7244c98c-ff8c-11e7-93b4-f6704ceb2416.png">

<img width="969" alt="bildschirmfoto 2018-01-22 um 15 54 43" src="https://user-images.githubusercontent.com/5808345/35226765-9d27aa48-ff8c-11e7-8534-791043e5b9ca.png">

**Comment by Jey-Cee** [comment]
Will be changed with version 0.1.7. State name's are now including the name of the Device/Group.
