### ISSUE TITLE
Smart Things Presence Sensor

### ISSUE THREAD

**Issue by Olivbus** [Jey-Cee/ioBroker.deconz#70]
Ist es geplant diesen Sensor einzubinden?
Beim Zigbee adapter steht er in der Liste der kompatiblen Geräte.
Ich würde mich sehr freuen.

**Comment by Jey-Cee** [comment]
Dazu kann ich nix sagen, das macht dresden-elektronik bzw. die Entwickler die dort Aktiv sind. https://github.com/dresden-elektronik/deconz-rest-plugin/issues
