### ISSUE TITLE
Adapter keeps restarting

### ISSUE THREAD

**Issue by akr1983** [Jey-Cee/ioBroker.deconz#71]
Hi,

i run iobroker within a docker container. The deconz also runs within a docker container. When i connect the adapter to the deconz container, the devices will get synchronised but then the adapter restarts.

Within the log i can get the following error:
`

host.bc0a38b744a3 | 2019-09-01 21:39:13.997 | error | instance system.adapter.deconz.0 terminated with code 0 (OK)
-- | -- | -- | --
host.bc0a38b744a3 | 2019-09-01 21:39:13.997 | error | Caught by controller[1]: at TCP._handle.close [as _onclose] (net.js:561:12)
host.bc0a38b744a3 | 2019-09-01 21:39:13.997 | error | Caught by controller[1]: at Socket.emit (events.js:211:7)
host.bc0a38b744a3 | 2019-09-01 21:39:13.997 | error | Caught by controller[1]: at emitOne (events.js:116:13)
host.bc0a38b744a3 | 2019-09-01 21:39:13.997 | error | Caught by controller[1]: at Socket.socketCloseListener (_http_client.js:377:9)
host.bc0a38b744a3 | 2019-09-01 21:39:13.997 | error | Caught by controller[1]: at ClientRequest.emit (events.js:211:7)
host.bc0a38b744a3 | 2019-09-01 21:39:13.997 | error | Caught by controller[1]: at emitOne (events.js:116:13)
host.bc0a38b744a3 | 2019-09-01 21:39:13.997 | error | Caught by controller[1]: at ClientRequest.req.on (/opt/iobroker/node_modules/iobroker.deconz/node_modules/ws/lib/websocket.js:550:24)
host.bc0a38b744a3 | 2019-09-01 21:39:13.997 | error | Caught by controller[1]: TypeError: Cannot read property 'aborted' of null
host.bc0a38b744a3 | 2019-09-01 21:39:13.997 | error | Caught by controller[0]: port: 443 }
host.bc0a38b744a3 | 2019-09-01 21:39:13.996 | error | Caught by controller[0]: address: '192.168.2.4',
host.bc0a38b744a3 | 2019-09-01 21:39:13.996 | error | Caught by controller[0]: syscall: 'connect',
host.bc0a38b744a3 | 2019-09-01 21:39:13.996 | error | Caught by controller[0]: code: 'ECONNREFUSED',
host.bc0a38b744a3 | 2019-09-01 21:39:13.996 | error | Caught by controller[0]: errno: 'ECONNREFUSED',
host.bc0a38b744a3 | 2019-09-01 21:39:13.996 | error | Caught by controller[0]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
host.bc0a38b744a3 | 2019-09-01 21:39:13.996 | error | Caught by controller[0]: { Error: connect ECONNREFUSED 192.168.2.4:443
deconz.0 | 2019-09-01 21:39:13.457 | error | TypeError: Cannot read property 'aborted' of null at ClientRequest.req.on (/opt/iobroker/node_modules/iobroker.deconz/node_modules/ws/lib/websocket.js:550:24) at emitOne (events.js:116:13)
deconz.0 | 2019-09-01 21:39:13.457 | error | uncaught exception: Cannot read property 'aborted' of null
deconz.0 | 2019-09-01 21:39:13.457 | error | Error: connect ECONNREFUSED 192.168.2.4:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
deconz.0 | 2019-09-01 21:39:13.456 | error | uncaught exception: connect ECONNREFUSED 192.168.2.4:443

`

The IP Address 192.168.2.4 is the IP of the docker host. IoBroker runs on Port 8081 and deconz on Port 32776. There shouldn't be any requests to 192.168.2.4:443 as far as i can tell. Seems like a bug ?

**Comment by Jey-Cee** [comment]
Nope it isnt a bug. On port 443 runs a websocket instance of deConz for push messages.
There are reports they say its a network problem with container. So look wich ports are open. Or do you have some other service running port 443?

**Comment by akr1983** [comment]
Hi,

I already found a solution. It seems, that the adapter is trying to use https, if possible and then tries to connect to the port specified within deconz for https.  I changed the https (and http) port within deconz to the one, that is mapped to the virtual machine. Now everything works like a charme. Maybe somethin for the wiki?

Thanks for the quick reply! :-)

Best regards, Arne
