### ISSUE TITLE
Dimmer Datenpunkt

### ISSUE THREAD

**Issue by p0rys** [Jey-Cee/ioBroker.deconz#72]
Moin,

ich nutze deConz zusammen mit dem iot-Adapter und der Google Home Integration. Leider setzt Google dort den Helligkeitswert im *.bri-Objekt immer zwischen 0 und 100% anstatt 0 bis 255. Wäre es möglich für Lampen und Gruppen einen Datenpunkt (*.dimmer mit dimmer.level) einzubauen der als Range 0 bis 100% akzeptiert und entsprechend (*2,55) die Brightness setzt?

Danke & Gruß

**Comment by duffbeer2000** [comment]
Hey p0rys übergangsweise könntest du die Alias-Funktion nutzen. Da kannst du die Werte automatisiert umwandeln lassen:
https://www.iobroker.net/#de/documentation/dev/aliases.md

**Comment by p0rys** [comment]
Moin duffbeer2000,

vielen Dank für den TIpp!

Aktuell nutze ich die "Convert"-Funktion vom iot-Adapter für die Umrechnung (die ist auch erst nach dem Erstellen dieses Tickets in den Adapter gekommen...). Ich finde beide Ansetze aber etwas unglücklich, da sie bei mehreren Lampen zu viel Konfigurationsaufwand führen. Im HUE-Adapter z.B. ist ein solcher "Dimmer"-Datenpunkt vorhanden und dadurch werden die Lampen automatisch richtig im iot-Adapter angelegt und konfiguriert.

**Comment by tigus309** [comment]
Wäre auch dafür... Meist arbeitet man ja nur mit Helligkeitswerten von 0 bis 100... Auch wenn 255 Schritte natürlich theoretisch besser ist, macht 100 mehr Sinn, gerade bei Google und Alexa-Nutzung. Die meisten Leuchtmittel dürften auch die feinere Abstufung gar nicht darstellen können. Die in meinen Augen beste Lösung wären zwei Datenpunkte (z.B. brightness (0-255) und dimmer (0-100)), welche unabhängig voneinander genutzt werden können und beide immer gegenseitig den aktuellen Wert annehmen (setze ich dimmer auf 100, springt brightness auf 255)...

Gruss Daniel

**Comment by tigus309** [comment]
Gibt es hier einen Status, ob sowas in der Planung ist? Fände es schön, wenn man das einbauen könnte, da sonst jeder selbst für die Umrechnung sorgen muss... Sonst muss ich das halt mal lokal in Angriff nehmen...

**Comment by AlexanderSch90** [comment]
Bin auch dafür. Sollte doch im Adapter einfach zu implementieren sein.

**Comment by FuLLHDvs480p** [comment]
Wäre sehr Hilfreich 👍

**Comment by Jey-Cee** [comment]
Wird beim nächsten größeren Update berücksichtigt.

**Comment by tigus309** [comment]
> 
> 
> Wird beim nächsten größeren Update berücksichtigt.

Kann man GROB sagen, wann man damit rechnen kann? Klar, dass das dann eine unverbindliche Aussage wäre... Nur um abzuschätzen, ob man abwarten möchte oder doch selbst was baut...?

**Comment by Jey-Cee** [comment]
Frühestens in 6 Wochen.

**Comment by Jey-Cee** [comment]
d6db4162c645bf48892c25500cfac60c060c4720
So war zwar anderst geplannt, aber ich hab das jetzt doch gleich eingebaut.

**Comment by tigus309** [comment]
Funktioniert wunderbar! Vielen Dank für die schnelle Umsetzung!

**Comment by v8turbo** [comment]
Ihr Schreibt es wurde eingebaut und funktioniert wunderbar... Bin ich Blind oder wo soll der Dimmwert 1-100 sein ?! Ich hab keinen im deconz Adapter...

**Comment by v8turbo** [comment]
Ok, man muss den Adapter manuell updaten... Wieso eigentlich ? Aktuell ist 1.2.5 laut ioBroker

**Comment by duffbeer2000** [comment]
Man muss es manuell installieren da es nicht im "stable" ist. Du bist jetzt beim Beta-release somit können hier vermehrt Fehler auftreten oder es funktioniert was überhaupt nicht das ist somit noch nichts für die breite Masse.
