### ISSUE TITLE
new api key after reboot

### ISSUE THREAD

**Issue by ralfm12** [Jey-Cee/ioBroker.deconz#82]
Hi, i use the adapter under iobroker Windows 10.
After i reboot my intel nuc, the deconz adapter needs always a new api key to connect.
the old key is not valid and i get only 403 errors.
After i delete the key and request i new one, all is runing fine again.
i use the default password on the conbee 2 stick.
How can i request an automatic update of the api key, if the adapter is unable to work with the old key?

**Comment by Jey-Cee** [comment]
> How can i request an automatic update of the api key, if the adapter is unable to work with the old key?

There is no feature to do this. Normaly the key is stored on both sides. 
After restarting the adapter is there a message in log with rhe API Key?

**Comment by ralfm12** [comment]
there is a 403 error

**Comment by Jey-Cee** [comment]
Have you solved your problem?
