### ISSUE TITLE
Doppelte Adapter (deCONZ?) Instanzen

### ISSUE THREAD

**Issue by JBSullivan** [Jey-Cee/ioBroker.deconz#84]
Hallo ich nutze den ConBee2 Stick mit der deCONZ Software unter Win10.
Der Adapter in ioBroker stuckt mir leider immer folgende Meldungen aus

  | host.iobroker(ioBroker)	2019-11-12 20:48:57.421	error	instance system.adapter.deconz.0 terminated with code 7 (Adapter already running)
-- | --
  | host.iobroker(ioBroker)	2019-11-12 20:48:56.556	info	instance system.adapter.deconz.0 started with pid 11156
  | host.iobroker(ioBroker)	2019-11-12 20:48:26.557	info	Restart adapter system.adapter.deconz.0 because enabled

Auch bekomme ich die Lampen die ich in der Phoscom App angelernt habe, nicht angezeigt. Siehe auch Beitrag im ioBroker Forum - https://forum.iobroker.net/topic/25880/stick-statt-hue-bridge/32

**Comment by Jey-Cee** [comment]
Da das kein Problem des Adapters selbst ist schließe ich den issue.
