### ISSUE TITLE
no more data points from deconz server after update

### ISSUE THREAD

**Issue by r2ixuz** [Jey-Cee/ioBroker.deconz#85]
If my deconz server, which is running in a docker container, is getting an update over night, the iobroker deconz adapter stops collectiong data from the deconz server. I need to restart the adapter manually to retrieve data again.

**Comment by Jey-Cee** [comment]
This is a known behavior. Actual without a soulution.

**Comment by Jey-Cee** [comment]
Fixed in version 1.2.2
Delete old version before installing new.
