### ISSUE TITLE
Missing Datapoints Eurotronic Spirit Zigbee

### ISSUE THREAD

**Issue by ac1dwalk3r** [Jey-Cee/ioBroker.deconz#86]
Just connected eurotronic spirit zigbee via deconz with conbee 2. all with latest software and firmware versions. the device also appeared in iobroker, but: there's a parameter missing. heatsetpoint is not available, although deconz sends it in the package (the info in the debug log of iobroker is exactly the same as in this posting: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1098#issuecomment-462139654. ) so it should basically be supported from deconz. offset temp is available and the value is controllable. i've already tried to create the state for heatsetpoint manually, but always when i trigger a value, it turns red. 
any suggestions, workarounds, time and energy for a bugfix maybe?

i really don't want to return the device, if it would work, it would be the perfect solution for my situation.

ps: just recognized that the on parameter is also not controllable, although its visible. boost, locked, off, displayflipped are also not visible.

**Comment by Jey-Cee** [comment]
I know that and is already planned. Its not a bug, its a feature. The datapoints and its handling has to be added manual for propper function. 

 If it is really urgent for you, you can send me money so i can give it a higher priority.

**Comment by ac1dwalk3r** [comment]
I'm glad that it's on your to do list, but honestly, at the moment i can't spend more money. The main reason, why i don't just buy another device with another gateway is a lack of money. So i have to be patient, and wish you good luck....ps: may i'll send you a coffee next month.

Greetings

**Comment by ac1dwalk3r** [comment]
Mhmmmm....doesn't seem to be difficult and timeconsuming to integrate those states...

**Comment by Jey-Cee** [comment]
If you could do this, you are welcome.

**Comment by ac1dwalk3r** [comment]
done, works perfectly.
i've created a fork, but it would be very nice if you copy those few changes back into your project, i don't want to maintain this....

https://github.com/ac1dwalk3r/ioBroker.deconz.git

ps: this was my first time writing a code....ok, i just copied a few parts and changed the datatype^^

**Comment by Jey-Cee** [comment]
Nice, but there is something missing. The values for heatsetpoint is in this format 2100, that is the equivalent to 21.00°C. So this has to be calculated into that form for user interaction. Also the object definition is missing "Unit: °C".

Please create a Pull Request, so it is easy for me only hit a button and your changes will be merged.
![image](https://user-images.githubusercontent.com/16007760/69410432-56c87300-0d0b-11ea-9755-8ab58b2bbfbc.png)

**Comment by ac1dwalk3r** [comment]
yeah, i noticed before....i just copied the datapoint "offset", with all the definitions, it was the only working one, and there you also have to type 30 for 3.0

at least it works, thats important, i'll think about the format later...

**Comment by svwb22** [comment]
@Jey-Cee Can you estimate when the merge will be done?

**Comment by Jey-Cee** [comment]
Yepp never, because  i have rewritten a lot of the adapter code. This means datapoints for eurotronic are included in the next Version.

**Comment by svwb22** [comment]
Nice! Thank you very much.
