### ISSUE TITLE
Ikea trådfri?

### ISSUE THREAD

**Issue by ulgu** [Jey-Cee/ioBroker.deconz#9]
Is the adapter working with Ikea trådefri? 
Hardware: RPI 3 and dresden usb stick (ConBee)
I have setup deconz software and linked three device (light bulb, motion sensor and switch) and i see them in deconz we-gui.
I have the deconz adapter loaded and configured.
There is only one objeckt in instances tab.
![instans](https://user-images.githubusercontent.com/8265863/37713915-937cb57e-2d18-11e8-88f6-5303c1035f25.PNG)
In the script tab I can see all three objects,
![objectbrowser](https://user-images.githubusercontent.com/8265863/37714452-d95dff3e-2d19-11e8-887b-66ac7c91be0c.PNG)
There are five objects because i renamed  two of them in deconz!

I need help!

Its ok to answer in German.(google translate works ok)

**Comment by Jey-Cee** [comment]
Sorry for the late answer.
I think in actual Version of the Adapter all Kind of devices is supported if it is in deConz.
You habe to reload the object tree if new objects where added.
At this time objects have to have to be deleted by Hand.
