### ISSUE TITLE
Bitron Smoke dedektor 902010/24

### ISSUE THREAD

**Issue by Tobik4** [Jey-Cee/ioBroker.deconz#93]
Hello,
i've a question about the Bitron Smoke dedektor 902010/24.
How can i start the siren?
<img width="820" alt="Unbenannt" src="https://user-images.githubusercontent.com/58916708/72210965-31faab80-34c3-11ea-9ec9-d67ea364f5d0.png">
Thank you for help
Tobias

**Comment by Jey-Cee** [comment]
You could try "strobe", "select", "lselect" and "blink" as value on alert.

**Comment by Tobik4** [comment]
Thank you for help,
It works with select.😉
