### ISSUE TITLE
IP in settings gets overwritten

### ISSUE THREAD

**Issue by mobilutz** [Jey-Cee/ioBroker.deconz#94]
I am running the deconz bridge in a docker container, therefore the IP address of it is not the same as the host.

So my host has i.e. the IP 10.0.0.10, and the docker container has something like 172.17.0.1
I set the correct IP in the adapter config page, but when looking at the config again, is is changed to the `172` one.

**Comment by Jey-Cee** [comment]
In my mind the correct ip is the 172... because thats the ip of deconz, but i am not familiar with docker.
Please go to the forum, there are people who know docker and the problems of this constelation.

**Comment by mobilutz** [comment]
No, this is not a problem with docker.

The problem is, that the deconz adapter changes the IP I set in the Admin UI for that adapter.

This should not happen.

**Comment by Jey-Cee** [comment]
You are right it should not be overwritten.
Have you delete the old version before installing the new one?

**Comment by mobilutz** [comment]
I will try again with manually removing everything. But I did remove through the Admin UI.

**Comment by Jey-Cee** [comment]
Did you have delted the adapter or only the instance?

I could not reproduce this issue. If i type in a new ip and hit Save, leave config and go back to it the ip is still there.

**Comment by mobilutz** [comment]
If the IP of the deconz is really the same, so the config return returns the same IP, then of course that does not change.
But as I am running deconz in a docker container, which gets a different IP than the host it is running on, I get the hosts IP replaced by the docker containers IP.

I did try with deleting instance, adapter and the outcome was always the same, the original IP I put into the configuration changed to the one provided by the deconz config json contents one.

**Comment by githtz** [comment]
I've got the same problem here. Running deconz in a docker-container. The IP address in iobroker is replaced by the local IP of the container. Since I run iobroker and deconz on different hosts, the connection does not work properly once the IP was replaced with the internal one of docker.

**Comment by Jey-Cee** [comment]
Is it possible to get a look on your systems over teamviewer or any desk?

**Comment by githtz** [comment]
I probably could create a demo setup to demonstrate the problem. I'll have a look later.
Meanwhile, I think maybe we could find a workaround if it's possible to configure the preferred IP in deconz instead. It's at least possible to specify the IP-addresses deconz is listening on in the config.ini, but that didn't do the trick for me since my setup is a little more complicated atm.

@mobilutz In the configuration of your docker container you could set `network_mode=host` for docker-compose or `--network host` for cli to make sure your container has the same IP as the device. Works only for the default IP though, if you're using multiple interfaces (for example a VPN) and connect with iobroker from there it does not solve the problem.

I've found a temporary solution by commenting out this line.
https://github.com/iobroker-community-adapters/ioBroker.deconz/blob/28d1b8a4bd18be9411a805bff7cabfba3eed8304/main.js#L801

**Comment by mobilutz** [comment]
@Jey-Cee I don't think, that teamviewer really helps here. But I will provide you with some info that might help.

The situation for me with using docker is of course a very special one, and I think that not many people will have this setup. But when they do, they cannot use this adapter.

Using docker for running deconz, is technically very similar to having a deconz server running "behind" another server/proxy, where the proxy is just forwarding the traffic by specific rules.

I am adding the JSON response, that I get from the URL:
`http://10.0.0.41:5080/api/__USER__/config`

```json
{
  "UTC": "2020-01-17T20:15:58",
  "apiversion": "1.16.0",
  "backup": {
    "errorcode": 0,
    "status": "idle"
  },
  "bridgeid": "XXX",
  "datastoreversion": "60",
  "devicename": "ConBee II",
  "dhcp": true,
  "factorynew": false,
  "fwversion": "0x264a0700",
  "gateway": "172.17.0.1",
  "internetservices": {
    "remoteaccess": "disconnected"
  },
  "ipaddress": "172.17.0.3",
  "linkbutton": false,
  "localtime": "2020-01-17T21:15:58",
  "mac": "XXX",
  "modelid": "deCONZ",
  "name": "XXX",
  "netmask": "255.255.0.0",
  "networkopenduration": 60,
  "panid": 7630,
  "portalconnection": "disconnected",
  "portalservices": false,
  "portalstate": {
    "communication": "disconnected",
    "incoming": false,
    "outgoing": false,
    "signedon": false
  },
  "proxyaddress": "none",
  "proxyport": 0,
  "replacesbridgeid": null,
  "rfconnected": true,
  "starterkitid": "",
  "swupdate": {
    "checkforupdate": false,
    "devicetypes": {
      "bridge": false,
      "lights": [],
      "sensors": []
    },
    "notify": false,
    "text": "",
    "updatestate": 0,
    "url": ""
  },
  "swupdate2": {
    "autoinstall": {
      "on": false,
      "updatetime": ""
    },
    "bridge": {
      "lastinstall": "2019-12-12T12:40:44",
      "state": "allreadytoinstall"
    },
    "checkforupdate": false,
    "install": false,
    "lastchange": "",
    "lastinstall": "",
    "state": "allreadytoinstall"
  },
  "swversion": "2.5.72",
  "timeformat": "12h",
  "timezone": "Europe/Berlin",
  "uuid": "XXX",
  "websocketnotifyall": true,
  "websocketport": 443,
  "whitelist": {},
  "zigbeechannel": 25
}
```

As you see, in the JSON response for the IP `10.0.0.41:5080` we see `"ipaddress": "172.17.0.3"`. But that is just the internal IP inside my server, which I cannot access from any other computer.

And as the adapter uses the `"ipaddress"` to overwrite what I put in the adapter config, the next time the adapter makes a request to deconz it of course fails.

I really don't see, why it is necessary for the adapter to change the adapters settings specifically the things a user can change manually by himself.

I hope that helps, please write if there are more questions.

**Comment by Jey-Cee** [comment]
Ok now it is clear what the problem is. I think about a solution for this not really logical situation.
To solve your problem go to the main.js of the adapter and comment out in line 444  getConfig().

**Comment by mobilutz** [comment]
@Jey-Cee I removed the setting of `ipaddress` in getConfig here:
https://github.com/iobroker-community-adapters/ioBroker.deconz/blob/master/main.js#L801

Why don't you just remove this all together?
If the adapter did make the connection to deconz, then the `ipaddress` is correct and it does not need to be changed at all.

**Comment by mobilutz** [comment]
With 1.2.4 and up, it works as expected now.
Using deconz inside docker is solved.

Thanks @Jey-Cee
