### ISSUE TITLE
No connection to deconz (Version 1.2.2)

### ISSUE THREAD

**Issue by Mr-REM-Esq** [Jey-Cee/ioBroker.deconz#95]
deconz.0 | 2020-01-13 21:06:36.969 | info | (4407) Get Config: Code 404: Ressource not found
-- | -- | -- | --
deconz.0 | 2020-01-13 21:06:36.849 | info | (4407) starting. Version 1.2.2 in /opt/iobroker/node_modules/iobroker.deconz, node: v10.18.1

**Comment by guergen1** [comment]
Here the same

**Comment by Jey-Cee** [comment]
Have you deleted the whole Adapter not only the instance? 
IP and port correct? 
Which version of deconz (not Adapter) do you have?

**Comment by guergen1** [comment]
I deinstalled the adapter and installed V1.0.1, then i deinstalled the 1.0.1 and installed the 1.2.2 with Port 8080; now it is all right!
I never changed the Port!
