### ISSUE TITLE
adatper (version 1.2.2) is restarting agian and again

### ISSUE THREAD

**Issue by volkerrichert** [Jey-Cee/ioBroker.deconz#96]
```
deconz.0 | 2020-01-15 09:27:47.887 | info | (18622) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
-- | -- | -- | --
deconz.0 | 2020-01-15 09:27:47.884 | info | (18622) terminating
deconz.0 | 2020-01-15 09:27:47.386 | warn | (18622) Got terminate signal. Checking desired PID: 19007 vs own PID 18622
deconz.0 | 2020-01-15 09:27:47.380 | warn | (18622) Got terminate signal. Checking desired PID: 0 vs own PID 18622
deconz.0 | 2020-01-15 09:27:18.280 | info | (18622) starting. Version 1.2.2 in /opt/iobroker/node_modules/iobroker.deconz, node: v10.17.0
```

I couldn't find anything else in the logs... It doesn't seems to be fixed.

**Comment by guergen1** [comment]
Here the Same

**Comment by Jey-Cee** [comment]
@volkerrichert adapter komplett gelöscht vor dem Update nicht nur die Instanz? Welche version von deConz (nicht adapter) verwendest du?

**Comment by volkerrichert** [comment]
@Jey-Cee nein, nur ein Update der Instanz gemacht.

deconz ist 
```
Version 2.05.64 / 22.4.2019
Firmware 26330500
```

**Comment by Jey-Cee** [comment]
Danke für die Infos.
Du musst ihn Komplett löschen und neu Installieren.

**Comment by volkerrichert** [comment]
@Jey-Cee : Dazu eine Fage: Warum und werden die Objekte wieder genau so erstellt?

Hintergrund: Wenn man im multihost einen adatper löscht, dann wird der Code nicht mit beseitigt.

**Comment by Jey-Cee** [comment]
Ich musste die Komplette Adapter Konfiguration umschreiben und aus einem mir unbekannten Grund wird bei einem Update die alte Adapterkonfiguration nicht richtig überschrieben.
Die Objekte werden wieder so erstellt, die Struktur hat sich nicht verändert. 
Wenn du aber die Namen der Objekte in ioBroker geändert hast geht das verloren.


> Hintergrund: Wenn man im multihost einen adatper löscht, dann wird der Code nicht mit beseitigt.
Was meinst du mit "der Code wird nicht beseitigt"?

**Comment by volkerrichert** [comment]
ok, dann sollte das einfach löschen der Instanz reichen und dann ein update machen. Richtig?

**Comment by Jey-Cee** [comment]
Nein, du musst wirklich den ganzen Adapter löschen. Das geht in der Adapter Übersicht.

**Comment by volkerrichert** [comment]
und die Codereste? Aber ok, ich verscuhe das mal. Jetzt weiß ich ja was passiert

**Comment by Jey-Cee** [comment]
> und die Codereste?

Ich weis leider immer noch nicht was du damit meinst?

**Comment by volkerrichert** [comment]
wenn man einen adatper beim multihost löscht, dann werden die Codes dazu nicht entfernt. Aber zur Not mache ich das von Hand. Also alles ok

**Comment by volkerrichert** [comment]
![image](https://user-images.githubusercontent.com/640914/72433855-8ee3b380-379a-11ea-8427-83d37add6663.png)
Das meine ich... Keine Instanz, aber trotzdem eine installierte Version. Das geht nur von Hand

**Comment by Jey-Cee** [comment]
Ah ok das war mir neu.
