### ISSUE TITLE
Feature Request: display and modify deconz config-values

### ISSUE THREAD

**Issue by githtz** [Jey-Cee/ioBroker.deconz#97]
Hi there, I'm using the iobroker deconz plugin in my home automation installation. Recently I've added some new devices to my zigbee network. The devices look like this when the `sensor` api is called.

![image](https://user-images.githubusercontent.com/15327800/72451808-ce22fc00-37bc-11ea-9602-48c865a4ba17.png)

The new devices are also shown in iobroker, but I was not able to access the information that are returned by the api in the `config` part.
![image](https://user-images.githubusercontent.com/15327800/72451921-f9a5e680-37bc-11ea-8609-764bad06ac7f.png)

Would it be possible to access and modify that data by extending this adapter? If any help is required I'd love to have a look myself, too, so I could create a PR.

This issue originated here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1098

**Comment by Jey-Cee** [comment]
What is the version of the Adapter you have installed?

**Comment by githtz** [comment]
The version I'm currently using is 1.1.2 - I tried the latest version 1.2.2, too but I could not get it to connect to deconz and had to install manually via `npm`-cli.

// EDIT

Sorry, looks like version 1.2.3 fixes the problem.
