### ISSUE TITLE
duplicate state value updates with buttons(sensors)

### ISSUE THREAD

**Issue by realwax** [Jey-Cee/ioBroker.deconz#98]
Since version 1.2.2 (also in 1.2.3) there are duplicate state value updates on pressed button.

A simple debug blockly item on an object trigger shows it. Value get updated twice and timestamp show a difference of 10ms. 

on({id: 'deconz.0.Sensors.2.buttonevent', change: "any"}, function (obj) {
  console.log((new Date().getTime()));
});

one press - did this:

20:11:04.389 | info | javascript.0 (743) script.js.utils.FB_helpers_VZ_SZ: 1579115464389
-- | -- | --
20:11:04.392 | info | javascript.0 (743) script.js.utils.FB_helpers_VZ_SZ: 1579115464392

another one again:

20:11:08.445 | info | javascript.0 (743) script.js.utils.FB_helpers_VZ_SZ: 1579115468445
-- | -- | --
20:11:08.459 | info | javascript.0 (743) script.js.utils.FB_helpers_VZ_SZ: 1579115468459

There should be only one update as it breaks all trigger scripts waiting for update not change!

Thanks for fixxng

kind regards

Wolfgang

PS: npm 6.14 nodejs 10.17 multihost redis/redis

**Comment by Jey-Cee** [comment]
I will have a look at it.

**Comment by realwax** [comment]
@Jey-Cee Thank you! I can provide more logs or whatever you need. Just let me know.

Eigentlich kann ich ja Deutsch mit dir schreiben. Alte Gewohnheit auf Git in engl ;) 
Der workaround den ich habe ich statt buttonevent auf buttonpressed und "wurde geändert zu gehen. Auch wenn noch immer zu oft getriggert wird, ändert sich der wert beim 2. mal nicht. 


Selbiges verhalten bei Türkontakten:
(Ich habe einmal geöffnet und einmal geschlossen. (reihenfolge von u nach oben... timestamp, newval, oldval)

javascript.0 | 2020-01-16 10:51:46.704 | info | (743) script.js.utils.test2: false
-- | -- | -- | --
javascript.0 | 2020-01-16 10:51:46.704 | info | (743) script.js.utils.test2: false
javascript.0 | 2020-01-16 10:51:46.703 | info | (743) script.js.utils.test2: 1579168306703
javascript.0 | 2020-01-16 10:51:46.698 | info | (743) script.js.utils.test2: true
javascript.0 | 2020-01-16 10:51:46.698 | info | (743) script.js.utils.test2: false
javascript.0 | 2020-01-16 10:51:46.698 | info | (743) script.js.utils.test2: 1579168306698
javascript.0 | 2020-01-16 10:51:03.393 | info | (743) script.js.utils.test2: true
javascript.0 | 2020-01-16 10:51:03.393 | info | (743) script.js.utils.test2: true
javascript.0 | 2020-01-16 10:51:03.393 | info | (743) script.js.utils.test2: 1579168263393
javascript.0 | 2020-01-16 10:51:03.389 | info | (743) script.js.utils.test2: false
javascript.0 | 2020-01-16 10:51:03.389 | info | (743) script.js.utils.test2: true
javascript.0 | 2020-01-16 10:51:03.388 | info | (743) script.js.utils.test2: 1579168263388

**Comment by Jey-Cee** [comment]
Ich glaub du vermischt hier was, buttonevent ist was ganz anderes als ein boolean. Die Türkontakte haben doch das Objekt open, auf das du da reagierst?

**Comment by realwax** [comment]
Ich teste alle "sensoren" ja, der BW hat ein boolean open und eine IKEA hat buttonevent und buttonpressed. Beides integer. Ich teste alles. Ein deconz restart hat das Fehlerhafte verhalten beendet. Ich habe es in die deconz rest api gemeldet. Ich denke hier können wir zu machen. Danke für deine rasche Hilfe! Der prozess lief nur einmal.... dennoch :?
